### ISSUE TITLE
🐞 Bug: KolSelect - Property _size wird nicht verarbeitet

### ISSUE THREAD

**Issue by joschakaisr** [public-ui/kolibri#1000]
# Fehlermeldung

## Beschreibung des Fehlers
Size wird beim KolSelect nicht durchgereicht.

## Reproduktion

- Link zu CodeSandbox: [CodeSandbox](https://codesandbox.io/s/determined-cherry-k3mjl9?file=/src/App.tsx)

## Erwartetes Verhalten
5 Options sichtbar, wie in _size Property angegeben.

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows
- Browser Firefox
- Version 102.4.0esr

**Comment by deleonio** [comment]
@joschakaisr Kannst Du bitte einen Fork auf machen und die Stelle selbst bearbeiten. Das ist sehr einfach.

**Comment by deleonio** [comment]
Wird mit Release 1.1.16 ausgeliefert.
