### ISSUE TITLE
🛹 Feature: Number für KolInputRadio

### ISSUE THREAD

**Issue by mantis30179** [public-ui/kolibri#1217]
# Featureanfrage
## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Die KolInputRadio Komponente kann im Gegensatz zu KolSelect als `_value` nicht mit dem Typ `number` umgehen. 

## Beschreiben Sie die gewünschte Lösung
Ich möchte am InputRadio wie im KolSelect auch den flexiblen `Option` Typen verwenden können.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Umwandlung der Backendwerte in Strings und Rückumwandlung in Numbers bei Übertragungen ans/vom Frontend.

## Zusätzlicher Kontext
[Spielwiese](https://codesandbox.io/s/nervous-sun-tqx7zd):

- Schon beim Laden wird der Number Wert nicht ins KolInputRadio geladen (oberer Teil, Dropdown und Radiobutton sollten übereinstimmen)
- Bei Manipulation am Input Radio wird das gleichnamige KolSelect mitgeändert, andersrum aber nicht, wenn der Typ des Values `number` ist.

(Daniel)

**Comment by deleonio** [comment]
Wir haben das Thema analysiert und können mit dem 1.1.15 Release etwas "optimieren".

Die Folge ist jedoch, dass eine Zahl als String in Zukunft als Zahl interpretiert werden wird.

"true" ==> `true`
"false" ==> `false`
"1" ==> `1`
1 ==> `1`
"1.2" ==> `1.2`
1.2 ==> `1.2`
"[]" ==> `[]`
"{}" ==> `{}`
"abc" ==> `"abc"`

**Comment by deleonio** [comment]
@mantis30179 

Please proof the solution 1.1.15-rc.2 ... https://codesandbox.io/s/quizzical-scott-pvszbs?file=/src/App.tsx

**Comment by mantis30179** [comment]
Klappt, vielen Dank. Die Layoutänderungen werdet ihr wieder zurückrollen, nehme ich an?

**Comment by deleonio** [comment]
@mantis30179 , welche Layoutänderungen?

Am Theming sollte sich nichts geändert haben.

**Comment by deleonio** [comment]
Layout ist wieder gefixed mit 1.1.15-rc.4

**Comment by deleonio** [comment]
"1.20000" ==> 1.2
"07.20" ==> 1.2 (MM.YY)

**Comment by deleonio** [comment]
@mantis30179 

Es ist möglich, dass wir den Support nur noch für `string` zulassen, weil eine Web Component nur einen Typ valide unterstützt. Das Mappen bringt in jedem Fall Probleme mit sich.

Wenn ein anderer Typ wie ein `string` gewünscht ist, dann kann dies mittels Formatter-/Parser-Adapter im Projekt gelöst werden.

**Comment by mantis30179** [comment]
Heißt in Zukunft wird `number` auch für KolSelect nicht mehr zur Verfügung stehen, @deleonio?

**Comment by deleonio** [comment]
Das Ziel ist den Typ des Values möglichst offen zu lassen. Das geht aber wegen Stencil leider aktuell nicht. Ich habe dazu dort ein Ticket eingestellt: https://github.com/ionic-team/stencil/issues/3902

Wir werden das Mapping drin lassen - wir haben das Mapping gestern noch einmal optimiert.
