### ISSUE TITLE
Akkordeon Inhalt update nach STATE Änderung

### ISSUE THREAD

**Issue by Arthuron** [public-ui/kolibri#1297]
# Fehlermeldung

## Beschreibung des Fehlers
Akkordeon reagiert nicht auf Änderungen des Inhaltes, nach Hinzufügen neuer Werte.

## Reproduktion
Leider friert mein gesamter Browser ein, wenn ich versuche CodeSandbox über euren Link zu laden, sorry ?!
 ¯\\\_(ツ)_/¯

## Erwartetes Verhalten
Es wird erwartet das der Korrekte und gesamte Inhalt der Liste (Array) innerhalb des Akkordeons angezeigt wird (auch nach STATE Änderung).

## Desktop:
- Betriebssystem: Win10
- Browser Chrome
- Version 100.0.4896.75

## Zusätzlicher Kontext

_@public-ui/react; 1.1.14-rc.0_

Ich möchte innerhalb eines Akkordeons (KolAccordion) 
diverse Informationen aus einem mehrdimensionalen Array anzeigen (hier vereinfacht dargestellt).
```
const [infos, setInfos] = useState(
   [{
      foo: 'foo',
      bar: 'bar'
   }]
);
```

```
<KolAccordion _heading='Infos' >
   <div slot='header'/>
   <div slot='content'>

      //Liste der Infos
      {infos.map((info, index) => (
         <div>{info.foo}, {info.bar}</div>
      ))}


      //Button zum hinzufügen von neuer Info
      <KolButton
         _label='Neue Info'
         _icon='icofont-plus'
         _on={{
         onClick: () => {
               AddNewInfo();
            },
         }}
      />
   </div>
</KolAccordion>
```

```
const AddNewInfo= () => {
   const InfoList = infos;
   InfoList.push(
      {
         foo: 'bar',
         bar: 'foo'
      });
   setInfos(InfoList)
};
```
und mittels einer Schaltfläche (hier KolButton genutzt) neue Infos hinzufügen.

Die neuen Infos werden auch dem **STATE** hinzugefügt (geprüft via console.log), allerdings werden diese nicht im Akkordeon angezeigt (kein update der Komponente?).

**Comment by deleonio** [comment]
Hallo @Arthuron,

ich vermute die Ursache ist folgender Stelle: `infos` ist immer die gleiche Instanz - dadurch wird die React-State-Change nicht getriggert.

```tsx
const AddNewInfo= () => {
   const InfoList = infos;
   InfoList.push(
      {
         foo: 'bar',
         bar: 'foo'
      });
   setInfos(InfoList)
};
```

Prüfen kannst Du das so ...

```
const AddNewInfo= () => {
   infos.push(
      {
         foo: 'bar',
         bar: 'foo'
      });
   setInfos([...infos])
};
```

**Comment by deleonio** [comment]
Aus Sicht von KoliBri - scheint alles i.O. : https://codesandbox.io/s/react-accordion-render-content-changes-lf21l3?file=/src/App.js
