### ISSUE TITLE
📖 Help: freie Gestaltungsmöglichkeit des `header` slots im Modal

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#1460]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**Hilfeanfrage**

Es besteht der Wunsch im Header der Modale mehreren Bestandteile anzuzeigen: Titel, Subtitel und Schließen Button (siehe Screenshot).

Da der Titel übers KolCard attribut `_heading` reinkommt und durch den Slot nicht überschrieben werden kann, lässt sich das ganze derzeit gestalterisch nur sehr schwierig anpassen. Links und Rechts soll auch das padding ein anderes sein. Für die Slots `content` und `footer` lässt sich das noch gut anpassen, für den `header` aber gar nicht. Es sei denn, wir überschreiben global die `KolCard` Styles, was aber nicht gewüscht ist.

Wie können wir das Gewünschte umsetzen?

![Bildschirmfoto 2022-12-14 um 11 49 01](https://user-images.githubusercontent.com/6606913/207575589-22aff192-2a67-4f1c-a267-bb769fe95031.png)

**Comment by deleonio** [comment]
Hier können wir auch das [Expert-Slot-Konzept](https://public-ui.github.io/docs/konzepte/expert-slot) anwenden.

Standard-mäßig einfacher Titel.

Mit `expert-header` dann wird das ersetzt.

**Comment by Chrisdo82** [comment]
Das war auch meine Hoffnung

**Comment by deleonio** [comment]
Hi @Chrisdo82,

spricht etwas aus Deiner Perspektive gegen die Verwendung von zwei einfachen DIVs?

```html
<div style="display: grid">
  <div></div>
  <div></div>
</div>
```

**Comment by Chrisdo82** [comment]
Hi @deleonio, ich kann mir gerade nicht so genau vorstellen worauf du hinaus willst.

**Comment by Chrisdo82** [comment]
Hallo @deleonio,

wenn ich es richtig in Erinnerung habe, hatten wir uns darauf geeinigt, dass ich nicht das KolCard Element innerhalb des Modals nutzen, sondern es einfach ohne umsetzen soll. Das habe ich jetzt gemacht und konnte mich damit der Designvorlage auch annähern.

Nun gibt das Design aber vor, dass der Subheader oben steht und der Header unten. Per CSS Attribut `order` ist das auch kein Problem, ich will das aber nur beim Modal so haben und nicht generell für die `KolHeading` Komponente so festlegen. Wie kann ich das im Designer realisieren?

So habe ich das Modal bei uns derzeit aufgebaut:
```tsx
    <div className='relative grid h-full w-full grid-rows-2 rounded bg-white shadow'>
      <div slot='header' className='border-b-2 border-ice px-8 py-4'>
        <KolHeading _label={title} _level={1} _secondaryHeadline={'2. Überschrift'} />
        <div className='absolute right-4 top-2'>
          <Button _label='Abbrechen' _variant={hideFooter ? 'primary' : 'ghost'} _on={cancelHandler} _icon='fas fa-times' _iconOnly _tooltipAlign='left' />
        </div>
      </div>
      <div slot='content' className='flex flex-col gap-4 p-8'>
        {children}
      </div>
      {!hideFooter && (
        <div slot='footer' className='flex justify-between border-t-2 border-ice px-8 py-4'>
          <Button _label='Abbrechen' _variant='ghost' {...cancelButtonProps} _on={cancelHandler} />
          {!hideSubmitButton && <Button _label='Ändern' _type='submit' _variant='primary' {...submitButtonProps} />}
        </div>
      )}
    </div>
```

**Comment by deleonio** [comment]
Hinweis: Wir planen, alle Header- und Footer-Slots in Version 2 aus folgenden Gründen zu entfernen:
- Wer einen Footer-Slot braucht, kann das auch problemlos über den Content-Slot (zukünftig unnamed-Slot) machen. Ja, ggf. würde im Design System dafür eine Wrapper-Component aufgebaut.
- Mit Header-Slots gab es bisher immer Probleme, weil das eingefügte HTML nicht valide war. Um einen Schließen-Schalter im Modal einzufügen, müsste man aktuell die Card nachbilden. Ich denke, wir sollten sowohl für das Alert und die Card standardmäßig ein Schließen-Schalter anbieten.

Siehe: https://github.com/public-ui/kolibri/issues/3403

**Comment by deleonio** [comment]
Die Reihenfolge der Überschriften innerhalb der KolHeading lassen sich nicht in Abhängigkeit des umgebenden Contrainers anpassen. Die Frage wäre auch, wieso soll eine Überschrift in einem Design-System unterschiedliche Ausprägungen haben?!

KoliBri geht davon aus, dass der Style in der Komponente eindeutig über alle höherwertigen Komponenten/ HTML-Strukturen ist.

**Comment by Chrisdo82** [comment]
Ok, dann löse ich das bei uns in der Lib.
