### ISSUE TITLE
🛹 Feature: Drag & Drop Sortierung für KolTable Spalten

### ISSUE THREAD

**Issue by joschakaisr** [public-ui/kolibri#155]
# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Wir haben in der Egebnismenge von Suchabfragen Tabellen mit sehr vielen Spalten, sodass idR nicht der gesamte Inhalt sichtbar ist und horizontal gescrollt werden muss. Die User haben unterschiedliche Priorisierungen bei der Reihenfolge der Spalten, bzw. würde diese je nach Ergebnismenge gerne umsortieren können. 

## Beschreiben Sie die gewünschte Lösung
Die Spaltenreihenfolge der KolTable Komponente via Drag&Drop sortierbar machen.

**Comment by deleonio** [comment]
Lösungsskizze:
- im Hackathon ist eine Lösung mit Kontext-Menü vorgeschlagen worden
- darin können vielfältige Einstellungsmöglichkeiten (Reihenfolge Spalten, Spaltenbreite) barrierefrei.
- Drag&Drop wäre erst wenn das steht

**Comment by deleonio** [comment]
Mittels des geplanten Menüs soll das Vertauschen von Spalten möglich werden: https://github.com/public-ui/kolibri/issues/1834
