### ISSUE TITLE
🛹 Feature: Hervorheben von "aktiver" Zeile in KolTable

### ISSUE THREAD

**Issue by joschakaisr** [public-ui/kolibri#156]
# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Wir haben in der Egebnismenge von Suchabfragen Tabellen mit sehr vielen Spalten, sodass idR nicht der gesamte Inhalt sichtbar ist und horizontal gescrollt werden muss. 

## Beschreiben Sie die gewünschte Lösung
Sobald in eine Zeile geklickt wird, soll diese als "aktive" Zeile gehighlightet werden. D.h. diese bekommt z.B. eine andere Hintergrundfarbe/Outline/... als die anderen Zeilen.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Zeilen durch Checkbox-Spalte selektierbar machen. Siehe folgendes AntD Beispiel: https://codepen.io/pen?&editors=001&prefill_data_id=2caf7670-4c18-43a8-b837-dd82b57bab32

## Zusätzlicher Kontext
AntD Beispiel:
![grafik](https://user-images.githubusercontent.com/114665693/197519545-8e2af58b-8e43-4567-86f0-cd567683a603.png)

**Comment by deleonio** [comment]
Lösungsskizze:
- nur in Kombination mit Checkbox
- die Hinterlegung ist für den sehenden Nutzer okay - für eingeschränkte Nutzende ist dann die Checkbox die information

**Comment by deleonio** [comment]
Betrachten wir, nachdem wir die Checkboxen in die Table aufgenommen haben.

**Comment by deleonio** [comment]
Wird mit diesem Ticket gelöst: https://github.com/public-ui/kolibri/issues/3295
