### ISSUE TITLE
🐞 Bug: KolNav children toggle

### ISSUE THREAD

**Issue by CherifTeclead** [public-ui/kolibri#1744]
# Fehlermeldung
Bei der KolNav Komponente ist die toggle Funktion Defekt.

## Beschreibung des Fehlers
Beim Klicken auf einem Parent Tab in KolNav werden die "_children"  nicht ein- und ausgeblendet.

## Reproduktion
- Link zu CodeSandbox: https://codesandbox.io/s/heuristic-elbakyan-4urwpq
=> Die _children Tabs "A" und "B" sind eingeblendet obwohl der user noch nicht auf das Parent "Routes.APPLICATION" geklickt hat.

## Erwartetes Verhalten
Die _children Tabs werden ein- und ausgeblendet beim klicken aufm Parent.

**Comment by deleonio** [comment]
![Image](https://user-images.githubusercontent.com/6279703/210214920-4b72e2ba-7fe0-43fd-af09-09fc96fc2df3.png)
