### ISSUE TITLE
🐞 Bug: InputRadio - Überflüssige Abstände

### ISSUE THREAD

**Issue by tim-laue** [public-ui/kolibri#179]
# Fehlermeldung

## Beschreibung des Fehlers.
Die InputRadio-Komponente wird mit überflüssigen Abständen dargestellt. Diese entstehen durch leere `div` Elemente, die zwischen den Radio-Optionen eingefügt werden.

## Reproduktion

Das Problem tritt bei jeder InputRadio-Komponente auf, die wir einsetzen. Diese werden immer aus Listen etc. dynamisch generiert:

![Unbenannt2](https://user-images.githubusercontent.com/116639708/197759541-6559ca7f-913d-475f-8c0a-0ea6de72721a.PNG)

## Erwartetes Verhalten
InputRadio-Komponenten werden mit normalen Abständen dargestellt.

## Screenshots
![Unbenannt](https://user-images.githubusercontent.com/116639708/197759505-baa46952-1d75-4426-a8fe-aec2d0e81f5f.PNG)

![Unbenannt3](https://user-images.githubusercontent.com/116639708/197759516-18f0d04f-bb3e-4fac-bf6b-0060b2a8ab67.PNG)

## Umgebung
- Desktop
- Windows 10
- Chrome Version 100.0.4896.75
- Kolibri und Kolibri-React Version 1.1.6-rc.11

## Weiterer Kontext

Ich habe dieses Problem bereits im Entwickler-Meeting angesprochen, weiß aber nicht, ob schon eine Lösung in Arbeit ist oder in Betracht gezogen wird. Ich wäre auch bereit, selbst einen PR mit einer Lösung zu erstellen.

**Comment by deleonio** [comment]
Bitte prüfen Sie, ob das Update auf 1.1.9 das Problem löst. Im aktuellen Designer sieht man den beschriebenen Fehler nicht.

Gerne können Sie am CSS Optimierungen vornehmen. Gehen Sie einfach dazu auf den Designer und wechseln in das Theme `mapz`.

Stellen Sie den Schieberegler auf Component-Style.

https://public-ui.github.io/designer/

**Comment by deleonio** [comment]
Bitte mit der Version 1.1.10 nach testen und dann hier kommentieren.

**Comment by deleonio** [comment]
related #563

**Comment by deleonio** [comment]
@tim-laue könnt Ihr bitte Feedback geben? Danke.

**Comment by deleonio** [comment]
@hansellkopp / @tim-laue  Bitte um Feedback.

**Comment by deleonio** [comment]
@HansellKopp / @tim-laue Bitte um Feedback.
