### ISSUE TITLE
[Feature] Nav: `aria-current` bei aktuell ausgewähltem Menü-Item setzen

### ISSUE THREAD

**Issue by tim-laue** [public-ui/kolibri#180]
# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
In der Nav-Komponente ist für Screenreader nicht erkennbar, welches der Menüpunkte zur Zeit ausgewählt ist. Für Sehende ist dieser farblich hinterlegt, für Screenreader-NutzerInnen kann hier das [aria-current Attribut](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) gesetzt werden.

![kolibri-menu-aria-current](https://user-images.githubusercontent.com/116639708/197765977-4b7da772-e401-4099-9154-59e4f2004981.png)

## Beschreiben Sie die gewünschte Lösung
Das `aria-current` Attribut wird automatisch korrekt gesetzt, wenn ein Menüpunkt ausgewählt wird.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
- Die Menü-Elemente aus dem DOM fischen und das Attribut selbst setzen

## Zusätzlicher Kontext
Wurde im Zuge eines BitV-Tests bemängelt.

**Comment by deleonio** [comment]
Vielen Dank @tim-laue,

gerne können Sie auch selbst Änderungen am Code vornehmen und diesen als PR bereitstellen.

Mit dem Release 1.1.10 wird das Feature ausgeliefert und ist schon im R 1.1.10-rc.3 enthalten.

https://github.com/public-ui/kolibri/blob/d7dadfc9c8ad17bdb40f7b640e0bcd0229f7008a/packages/library/src/components/nav/component.tsx#L126
