### ISSUE TITLE
💡 Hinweis: A11y Table noch weiter verbessern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#1839]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**A11y Hinweise**

- [ ] Pagination / Border Style fixen
- [ ] Pagination in eine eigne Region packen
- [ ] Anzahl füllstand in auch in die Caption einfügen

**Comment by cyrdam** [comment]
Würde hier auch das visuelle Ausblenden der Caption hier hinein gehören? Z.B.: `_visuallyHiddenCaption={true}`. Das könnte direkt in der Komponente gehandhabt werden als es global in Styles anzusetzen.

Zusätzlich kann man die Caption als `empty string` setzen, und hier gibt es keine Type. Die Punkte würde für mich hier offen sein:

- Prüfen per TypsScript?
- Prüfen per JavaScript und hinweisen oder throw Error in runtime
