### ISSUE TITLE
🐞 Bug: `KolInput...` Komponenten mit `_required` verhalten sich nicht wie normale `input` Elemente mit `required`

### ISSUE THREAD

**Issue by cyrdam** [public-ui/kolibri#1870]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Input Felder gesetzt mit `_required` werden in normalen Formularen ignoriert.

## Reproduktion

- Link zu CodeSandbox: https://codesandbox.io/s/busy-nobel-dtbplc?file=/src/App.tsx

Schritte zum Reproduzieren des Verhaltens:
- Gehe zu: https://codesandbox.io/s/busy-nobel-dtbplc?file=/src/App.tsx
- Im Vorschaufenster: Klicke auf den Button "Submit"
- Browser Hinweis zeigt auf fehlende Eingabe, Fokus wird auf das input Element gesetzt
- Füge einen Wert ein ("John")
- Klicke auf den Button "Submit"
- URL ändert sich zu: https://dtbplc.csb.app/egal.php?vorname=John&test-radio=option-1&test-text=

Schritte mit POST sind ähnlich, nur dass nach dem erfolgtem Submit die Seite nicht geladen werden kann.

Schritte zum Verhalten mit Tastatur:
- Fokusiere das `KolInputText` Feld
- Lasse das Feld leer
- Drücke die `Enter`Taste
- Formular wird versendet

Formular wird abgesendet, falls das normale Input Feld befüllt war, dann wird dieses als Wert mitgesendet.

## Erwartetes Verhalten
Das Feld verhällt sich wie ein normales Form Feld:

- Der Browser weist darauf hin, dass das Feld leer ist, wenn ein submit (Absenden) aktiviert wird
- Der Browser stopt weitere Aktionen (Versenden des Formulars)
- Das fehlerhafte Feld wird automatisch fokusiert

## Desktop:
- Betriebssystem: Windows 10
- Browser Firefox
- Version 102.6

## Zusätzlicher Kontext
Der `experimental-mode` ist aktiviert.

**Comment by deleonio** [comment]
Genau @cyrdam , das Feature ist experimental und wir werden es weiter verbessern. Danke für den Hinweis und das Ausprobieren!!!

**Comment by deleonio** [comment]
![image](https://user-images.githubusercontent.com/6279703/211247678-8b844f28-e7f4-4724-ab91-fd61bccb2b19.png)

- [ ] wir nehmen das Feature auf
- [ ] versuchen das Eingabefeld auf `vality` zu prüfen: https://developer.mozilla.org/en-US/docs/Web/API/ValidityState
- [ ] `_required` könnte auch ein Custom-Text beinhalten mit impliziten Validator (no-null)

**Comment by webbird** [comment]
Ich glaube das ist wohl in Vergessenheit geraten.
