### ISSUE TITLE
🐞 Bug: KoliBri kann nicht wie beschrieben integriert werden (ViteJS)

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#1905]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn ich KoliBri in ein ViteJS Projekt importiere, dann funktioniert es nicht so wie unter [Erste Schritte - Variante B](https://public-ui.github.io/docs/get-started/erste-schritte/#variant-b-react-projekt) beschrieben. Das einzige was geht, ist wenn ich den CDN (so wie unter Variante A beschrieben) benutze, das ist aber nicht gewünscht. 

Könnt ihr helfen? 

## Reproduktion

https://stackblitz.com/edit/vitejs-vite-dsatir?file=src/App.tsx

Schritte zum Reproduzieren des Verhaltens:
- KoliBri wurde in der main.tsx registriert
- öffne die App.tsx
- in Zeile 24 wurde der KolButton implementiert
- der Button wird nicht gerendert
- stattdessen erscheinen Fehlermeldungen in der Browser Console

## Erwartetes Verhalten
Der Button wird gerendert und ich bekomme beim initialisieren von KoliBri keine Fehlermeldungen in der Console.

**Comment by deleonio** [comment]
Danke @Chrisdo82 für den Hinweis. Das müssen wir uns mal lokal anschauen - läuft fehlerfrei - aber Komponents werden nicht laden.

**Comment by deleonio** [comment]
https://github.com/ionic-team/stencil/issues/3961

**Comment by deleonio** [comment]
@Chrisdo82

- Das scheint aber vorher auch noch nicht so gegangen zu sein?!
- Die Einbindung als Asset ist nicht unbedingt falsch.

**Comment by Chrisdo82** [comment]
@deleonio korrekt, das ging noch nie. Bisher hat das auch nicht gestört, jetzt hat sich bei uns aber ein bisschen was geändert und fällt nun auf die Füße.

Bisher hatten wir es in der `index.html` so eingebunden, damit es überhaupt ging (allerdings nur im develop mode): `<script type="module" src="/node_modules/@public-ui/components/dist/kolibri/kolibri.esm.js"></script>`

Das wird vom Bundler aber richtigerweise entfernt. Die einzige Lösung (noch nicht ausprobiert) die ich derzeit sehe, ist alles unter `/node_modules/@public-ui/components/dist/kolibri/` in den `public` ordner zu verschieben und es dann von dort zu importieren. 

Evtl. gibt es ja noch einen besseren/einfacheren Weg?

**Comment by Chrisdo82** [comment]
@deleonio Wenn ich alles importiere, dann funktioniert es. Sollte evtl. noch in der Doku mit aufgenommen werden.

**Comment by deleonio** [comment]
https://github.com/public-ui/kolibri/blob/main/docs/GET_STARTED.md#i-vite--react
