### ISSUE TITLE
💡 Hinweis: _on sollte nicht deprecated werden für Link und LinkButton

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#1906]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**Hilfreicher Hinweis**

Bei der Benutzung von z.B. [ReactRouter](https://reactrouter.com/en/main), sind wir auf die `onClick`-Handler angewiesen um damit routen zu können. Würde ich nur KolLink benutzen, dann würde die komplette Seite (inkl. aller Resourcen) neu geladen werden, statt nur die benötigten Komponenten auszutauschen.

**Comment by deleonio** [comment]
Hallo @Chrisdo82,

wir bieten heute alle Varianten von Button, ButtonLink, Link und LinkButton an. Alle semantischen Links unterstützen nur noch `_href` und alle Buttons nur noch `_on`. Optisch gibt es Button und Links jeweils als Link und Button.

Sollte also weiterhin funktionieren.

Hint: Try `focus()` with 1.1.16

| Merkmal | Link  | LinkButton | Button | ButtonLink | ButtonToggle |
|:---:|:---:|:---:|:---:|:---:|:---:|
| Design | Link | Button | Button | Link | Button | 
| Semantik | `a` | `a` | `button` | `button` | `button` | 
| `_href` | ➕ | ➕ | ➖ | ➖ | ➖ | 
| `_on` | ➖ | ➖ | ➕ | ➕ | ➕ |
| `focus()` | ➕ | ➕ | ➕ | ➕ | ➕ |
| Wert | ➖ | ➖ | ➖ | ➖ | `boolean` |

**Comment by Chrisdo82** [comment]
Hallo @deleonio, funktioniert leider nicht. Der onClick Handler ist bei Verwendung des BrowserRouters von ReactRouter zwingend notwendig. Die andere Alternative die Link-Componente von ReactRouter zu verwenden, fällt ja leider aus. 

Hier ein Beispiel dass das gut verdeutlicht: https://codesandbox.io/s/minimal-kolibri-sample-forked-25rzx2?file=/src/Navigation.tsx

(euer Playground Beispiel in StackBlitz scheint übrigens kaputt zu sein)

**Comment by deleonio** [comment]
@Chrisdo82 hier die Lösungsalternativen: https://codesandbox.io/s/kolibri-sample-react-link-sample-1jgz8v?file=/src/Navigation.tsx

Ja, bei Sandbox haben wir noch ein Problem beim Laden von ESM und einen Variablenkonflikt in GLOBAL. (Vielleicht hängt das hiermit auch zusammen: https://github.com/public-ui/kolibri/issues/1905)

**Comment by Chrisdo82** [comment]
Das wäre semantisch aber nicht richtig. Es sind doch nun einmal Links die irgendwohin navigieren sollen. Stattdessen Buttons zu verwenden die wie Links aussehen, ist m.E. nicht die richtige Lösung. 

Was ist denn überhaupt der Grund dafür, onClicks nicht mehr zu unterstützen?

**Comment by Chrisdo82** [comment]
Darüberhinaus wird der KolLink von vielen weiteren Komponenten verwendet, z.B der KolBreadcrumb oder der KolNav. Da würde der Workaround nicht mal funktionieren. Für uns würde das also bedeuten, das wir alle Komponenten die KolLink verwenden nachbauen müssten, da wir den onClick benötigen.

**Comment by deleonio** [comment]
So machen es andere Projekte - wenn es um die Semantik geht.

```tsx
      <div className="d-flex gap-2">
        <h2>React-Router die die Seite nicht neuladen:</h2>
        <Link to="/">
          <KolLink _href="">Home</KolLink>
        </Link>
        <Link to="/tabs">
          <KolLink _href="">Test</KolLink>
        </Link>
      </div>
```

- [ ] Das Thema bei der KoliBri-internen Wiederverwendung werden wir separat betrachten müssen.

**Comment by Chrisdo82** [comment]
Ok das wäre ein Workaround. 

Mich würde aber dennoch interessieren was der Grund dafür ist, das native `onClick` nicht mehr zu unterstützen.

**Comment by deleonio** [comment]
Ein Punkt der das Thema treibt, ist die klare eindeutige Verwendung der Komponenten. Wenn wir Link-Komponenten anbieten, wo mal `_href` und mal `_on` angeben werden kann oder muss - dann ist das nicht "smart" (DX). Die Ablösung von `_on` bei Link-Komponenten würde `_href` required machen.

BTW - das habe ich auch schon gesehen.
```tsx
<KolLink onClick={} ... />
```

**Comment by deleonio** [comment]
@Chrisdo82  - Update: https://public-ui.github.io/blog/button-und-link-komponenten#l%C3%B6sung

**Comment by Chrisdo82** [comment]
> Ein Punkt der das Thema treibt, ist die klare eindeutige Verwendung der Komponenten. Wenn wir Link-Komponenten anbieten, wo mal `_href` und mal `_on` angeben werden kann oder muss - dann ist das nicht "smart" (DX). Die Ablösung von `_on` bei Link-Komponenten würde `_href` required machen.

Das `_href` required sein sollte, sehe ich genauso. Nur nicht, dass dadurch der `_on`-Callback entfernt wird. Das eine schließt das andere meiner Meinung nach nicht aus. Wenn ich nicht möchte, dass der Default ausgeführt wird, dann kann ich das im Callback mit `preventDefault` unterbinden, habe aber den Vorteil (gegenüber Buttons), das ich sehe wohin navigiert werden würde, wenn ich diesen Link anklicke. Dafür sind Links da, um den Nutzer irgendwohin zu navigieren, ganz egal ob das nun nativ übers href oder über einen onClick-Handler passiert. In meinen Augen verbessert das nicht die DX, im Gegenteil. Aber das ist wohl Ansichtssache ;-)

**Comment by Chrisdo82** [comment]
Ich werde mal probieren ob der Workaround `<KolLink onClick={} ... />` funktioniert. Geht dieser dann auch für Breadcrumb und Co?

**Comment by deleonio** [comment]
Kleines Trainingsbeispiel: https://codesandbox.io/s/minimal-kolibri-sample-forked-62kqj6
