### ISSUE TITLE
🐞 Bug: KolButtonLink - icon kann nicht oberhalb oder unterhalb des Labels platziert werden

### ISSUE THREAD

**Issue by AndreasZimnas** [public-ui/kolibri#1907]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
KolButtonLink ignoriert die Attribute 'top' und 'bottom' für die icons.

## Reproduktion

https://codesandbox.io/s/nostalgic-microservice-6qpdy3

## Erwartetes Verhalten
Die Attribute 'top' und 'bottom' funktionieren wie bei KolButton und KolLinkButton

**Comment by deleonio** [comment]
Vielen Dank @AndreasZimnas, wir ergänzen das fehlende Styling an.

**Comment by deleonio** [comment]
fix with v1.3
