### ISSUE TITLE
🛹 Feature: KolButton sollte für das _on Event auch einen Wert liefern können

### ISSUE THREAD

**Issue by AndreasZimnas** [public-ui/kolibri#1908]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Featureanfrage

Für KolButton und KolButtonLink sollte für das Event '_on' neben den existierenden EventCallbacks auch callbacks die einen Wert mit sich bringen verfügbar sein, wie z.B. bei KolPagination (EventValueCallback) oder KolTabs (CustomEvent)

**Comment by deleonio** [comment]
Hallo @AndreasZimnas,

kannst Du uns bitte ein Beispiel geben, warum ein Schalter eine Wert transportieren sollte?

Das könnte noch interessant sein:

- https://github.com/public-ui/kolibri/issues/1906#issuecomment-1373200761
- https://github.com/public-ui/kolibri/issues/771

**Comment by AndreasZimnas** [comment]
In einen ngFor erstellen wir Dynamische Schaltflächen. Wir wollen beim Betätigen der Schaltfläche eine Funktion ausführen ohne die Seite neu zu Laden (reload). Da die Schaltflächen dynamisch erstellt werden brauchen wir den index des ngFor um zu wissen welche Schaltfläche betätigt wurde. Eventuell sollte Link oder LinkButton mit _on funktionieren, wenn #1906 implementiert wird, wäre das für uns auch in Ordnung.

Generell wäre es aber hilfreich auch einen Wert beim _on Event eines KolButton zu übergeben, insbesonderen wenn die KolButtons dynamisch erstellt werden.

**Comment by deleonio** [comment]
@AndreasZimnas - danke für die Anregung: Es wird einen Value beim Button geben ;-)

https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-value

**Comment by deleonio** [comment]
Wenn Du magst, dann kannst Du dass gerne fix selber rein bauen. Beim Button musst Du die Props und State-Types erweitern (hochnavigieren).

- Prop hinzugefügen
- validateValue
- componentWillLoad ergänzen
- click Callback auf EventValueCallback umstellen

**Comment by deleonio** [comment]
ist in v1.3 enthalten
