### ISSUE TITLE
🛹 Feature: KolButtonLink unterstützung für _underline

### ISSUE THREAD

**Issue by AndreasZimnas** [public-ui/kolibri#1909]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Featureanfrage
KolButtonLink  sollte das Attribut _underline von KolLink auch unterstützen.

**Comment by deleonio** [comment]
Hallo @AndreasZimnas,

das Property `_underline` wollen wir eher abschaffen, da das Styling mittlerweile im hybriden Modus möglich ist.

Wir hatten das damals nur wegen der Nav-Komponente eingebaut.

**Comment by deleonio** [comment]
Property `_underline` und ein paar andere sind jetzt `@deprecated`. Siehe changelog 1.1.16

**Comment by AndreasZimnas** [comment]
@deleonio könntest du mir ein Beispiel geben wie der hybride Modus funktioniert? Oder gibt es so ein Beispiel irgendwo?

**Comment by deleonio** [comment]
@AndreasZimnas kannst Du uns bitte ein Beispiel geben, wo Ihr einen Link braucht - der von vorgegeben Design abweichen soll.

**Comment by AndreasZimnas** [comment]
Ich möchte nur das underline nicht haben. Wir haben ein Timeline in dem wir dynamisch ButtonLinks erstellen, jeder ButtonLink ist ein Zeitpunkt in dem Timeline. Vom design her möchten wir keinen Button, sondern etwas das einen Link ähnlicht. Wir haben ButtonLink benutzt und nicht LinkButton oder Link da das _on in diesen beiden als deprecated gekennzeichnet sind.

**Comment by deleonio** [comment]
Danke Dir für das anschauliche Beispiel.

KoliBri hat eine Timeline-Komponente im Backlog, können wir uns das zusammen vielleicht mal anschauen?

Aus Sicht eines Design System möchte man ein konsistentes Erscheinungsbild. Das heißt ein Link als solcher sicht immer gleich aus.

Wenn eine neue Komponente entworfen wird können, manche KoliBri-Komponenten auch ohne Shadow (hyprid) wiederverwendet und müssen gestylt werden.

Gerne können wir aus diesem Thema ein Tutorial machen.

**Comment by deleonio** [comment]
remove in 1.3
