### ISSUE TITLE
💡 Hinweis: SemVer für die Versionierung verwenden

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#1948]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**Hilfreicher Hinweis**

Ich denke das ist selbsterklärend. https://semver.org/lang/de/

**Comment by deleonio** [comment]
Hallo @Chrisdo82, wir verwenden die [semantische Versionierung](https://public-ui.github.io/docs/willkommen#versionierung). Wo können wir uns verbessern?

**Comment by Chrisdo82** [comment]
Wenn ich mich nicht täusche, gab es seit dem Release auf Github nur Patch Updates, dabei waren einige Punkte mit dabei die mindestens ein Minor- wenn nicht sogar ein Major-Release zur Folge hätten haben müssen.

Z.B. der Punkt aus der Version `1.1.15` "Badge: Der Badge wurde um einen Smart-Button, wie bei den Inputs, erweitert.", hätte lt. Definition ein Minor-Release `1.2.0` zur Folge haben müssen. Stattdessen war es aber ein Patch-Release. 

Daher sieht es für mich derzeit so aus, als hätte es seit dem 1.6.2022 (`v1.1.0`) nur Fixes aber keine neuen Features gegeben, was ja aber eigentlich nicht stimmt.

**Comment by deleonio** [comment]
@Chrisdo82 vielen Dank für die Anregung. Ja Du hast recht. Wir haben relativ häufig neue Features dabei und haben nicht extra den Minor-Level erhöht. Es sollte nichts dagegen sprechen, dies in Zukunft zu tun.

Ich nehme das zum nächsten Core-Meeting mit.
