### ISSUE TITLE
🐞 Bug: 1.1.16  KolNav verliert labels

### ISSUE THREAD

**Issue by eugen-cc** [public-ui/kolibri#1995]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung
Nach Betätigung des "compact" Button der Navigation, gehen die Labels auf "undefined"

## Reproduktion

Siehe KolNav Beispiel in der Offiziellen Kolibri Dokumentation

## Screenshots

![2](https://user-images.githubusercontent.com/14055972/211773354-680f30d1-c0e6-4cfd-be08-31fcb1bd4ac9.PNG)

**Comment by deleonio** [comment]
Should be fixed with v1.1.18 now. Thanks!!!

**Comment by deleonio** [comment]
Siehe https://codesandbox.io/s/kolibri-public-ui-react-samples-forked-zrp5t7
