### ISSUE TITLE
🛹 Feature: Console Output deaktivieren oder konfigurierbar machen

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#2008]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Der folgende Output in der Console (sowohl im Browser als auch bei UnitTests) ist bei der Entwicklung hinderlich und nervig, da die eigentlichen relevanten Ausgaben dadurch untergehen. 

![Bildschirm­foto 2023-01-12 um 12 32 53](https://user-images.githubusercontent.com/6606913/212056104-28c48f40-724d-4359-933a-e4d1d11cb204.png)

## Beschreiben Sie die gewünschte Lösung
Ich würde das gerne per Konfiguration ausschalten können.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Ich könnte die console.info natürlich überschreiben bzw. mit Jest wegmocken, aber diesen Schritt möchte ich gerne vermeiden.

**Comment by deleonio** [comment]
Reicht das im Test?!

**Comment by Chrisdo82** [comment]
Prinzipiell würde mir es reichen wenn ich es für die Tests deaktivieren kann

**Comment by deleonio** [comment]
kommt mit 1.2-rc.0

**Comment by deleonio** [comment]
Die Outline sollte im Test nicht mehr auftreten.

**Comment by Chrisdo82** [comment]
@deleonio es tritt nach wie vor auf. 

Da es aber super störend ist, habe ich es in der `vite.config.ts` folgendermaßen unterdrückt:

```
  {
    test: {
      ...
      onConsoleLog(log) {
        if (log.includes("The theme process is locked")) return false
        if (log.includes("The accessible HTML-Standard")) return false
        if (log.includes("deprecated Das Property _icon-align bzw. _iconAlign ist veraltet")) return false
        if (log.includes("<empty line>")) return false
        return undefined
      },
    },
  }
```

Ist natürlich nur ein Workaround und ich würde lieber keine Lognachrichten unterdrücken, aber ich möchte diese Informationen im Test einfach nicht sehen.
