### ISSUE TITLE
🛹 Feature: Select Option Label auch für andere types ermöglihen (z.B. `number`)

### ISSUE THREAD

**Issue by cyrdam** [public-ui/kolibri#2021]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.

Den Label Type von `Option` nicht nur auf `string` beschränken.

Falls eine Quelle z.B. ein Array nur mit Zahlen enthällt, dann müssten diese umgewandelt werden (performance). Für eine `number` sollte dies aber nicht nötig sein.

## Beschreiben Sie die gewünschte Lösung

`number` Werte wären möglich ohne sie in Strings umzuwandeln. Beispiel:

```typescript
// @public-ui/components/dist/types/types/input/types.d.ts

export declare type Option<T> = {
  disabled?: boolean;
  label: string | number;
  value: T;
};

<KolSelect
  _list={{ label: 5, value: 5 }}
/>

// Oder Werten mit `Array.map()`

const sourceValues = [5, 10, 20];
// ...
return (<KolSelect
  _list={
    sourceValues.map((value) => ({ label: value, value}) )
  }
/>)
```

**Comment by deleonio** [comment]
@cyrdam hört sich plausibel an. Gerne einfach einen PR liefern ;-)
