### ISSUE TITLE
🐞 Bug: aria-current bei Navigations-Menüs ohne Unterpunkte wird nicht gesetzt

### ISSUE THREAD

**Issue by tim-laue** [public-ui/kolibri#2043]
# Fehlermeldung

## Beschreibung des Fehlers
Siehe [voriges Issue zum `aria-current` Attribut](https://github.com/public-ui/kolibri/issues/180). In unserer Appplikation, die nur eine flache Liste von Menüpunkten hat, wird das Attribut nach wie vor nicht gesetzt.

## Reproduktion

Ist in der [Code Sandbox](https://codesandbox.io/s/modest-cray-mkb7tw) direkt sichtbar.

## Erwartetes Verhalten
Dass das Attribut auf `"page"` gesetzt wird.

## Screenshots

![bugnav1](https://user-images.githubusercontent.com/116639708/212637843-23678465-3b59-487f-9b5a-b4af6a0d75ad.PNG)

![bugnav2](https://user-images.githubusercontent.com/116639708/212637786-c49cc8e2-3f2e-460f-a422-80d37d2f0a5b.PNG)

## Desktop:
- Betriebssystem: Windows
- Browser: Firefox und Chrome
- Kolibri-Version 1.1.15

## Zusätzlicher Kontext
Hansell hat hierzu [den Quellcode](https://github.com/public-ui/kolibri/blob/d7dadfc9c8ad17bdb40f7b640e0bcd0229f7008a/packages/library/src/components/nav/component.tsx#L126) schon einmal untersucht. Hier wird, wenn der Menüpunkt keine Children hat, das `aria-current` Attribut explizit nicht gesetzt. Warum ist das so?

**Comment by deleonio** [comment]
@tim-laue - Ihr findet bestimmt schnell die fehlende Stelle. Könnt Ihr bitte forken und einfach einen PR stellen?

https://github.com/public-ui/kolibri/blob/main/packages/library/src/components/nav/component.tsx

**Comment by tim-laue** [comment]
@deleonio - An [der betreffenden Stelle im Code](https://github.com/public-ui/kolibri/blob/3bda09b461e20ae0ac4b2c44f99758274b9dcbfc/packages/library/src/components/nav/component.tsx#L173) steht ein Kommentar der explizit sagt, dass `aria-current` hier nicht gesetzt werden soll. Das können wir uns leider nicht erklären, sodass ich Stand jetzt ohne Weiteres keinen PR dazu erstellen kann.

**Comment by deleonio** [comment]
Hi @tim-laue, schau mal ca. 20 Zeilen weiter oben - dort wir aria-current gesetzt. Es ist quasi genau verkehrt herum.

**Comment by tim-laue** [comment]
@deleonio [PR ist erstellt.](https://github.com/public-ui/kolibri/pull/2092)

**Comment by deleonio** [comment]
removed with v1.3 - ist schon seit längerem nicht mehr im code verknüpft

**Comment by deleonio** [comment]
fix with v1.3

**Comment by tim-laue** [comment]
@deleonio Habt ihr dieses Feature mit der aktuellen Version schon einmal getestet? Bei uns erscheint nach wie vor kein `aria-current`.

**Comment by deleonio** [comment]
https://w5u37c.csb.app/#/nav/aria-current?theme=th
https://codesandbox.io/s/kolibri-public-ui-react-samples-w5u37c?from-embed=&initialpath=%23/nav/aria-current?theme=th&file=/src/samples/nav/aria-current.tsx
