### ISSUE TITLE
🛹 Feature: Zusammenhang zwischen Tabellen-Headern und -Content

### ISSUE THREAD

**Issue by tim-laue** [public-ui/kolibri#2044]
# Featureanfrage

## Problembeschreibung
Wenn eine `KolTable` mehrere Ebenen von Headern hat, ist für Screenreader-User der Zusammenhang zwischen übergeordneten Headern und dem Content nicht verständlich. Im Beispiel unten geht es um den Zusammenhang zwischen dem Header-Eintrag "65.270" und den Werten unter "Anzahl" und "Summe in Tsd. €".

![featuretable1](https://user-images.githubusercontent.com/116639708/212640791-5c6aaf8d-9a6b-43ee-a76a-e813fa0cb36a.PNG)

## Beschreiben Sie die gewünschte Lösung
Eine gute Lösung wird [hier](https://www.w3.org/WAI/WCAG22/Techniques/html/H43) von der W3C umrissen.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Keine

**Comment by deleonio** [comment]
@cbraehmig Bitte zusätzlichen Retest machen.

@laske185 Scopes beachten.
