### ISSUE TITLE
💡 Hinweis: Im BMF Theme Kontrast bei Breadcrumbs verbessern

### ISSUE THREAD

**Issue by tim-laue** [public-ui/kolibri#2047]
Uns wurde mitgeteilt, dass in unserer Applikation das letzte Element in unseren Breadcrumbs zu hell ist, also die Kontrastanforderungen für Barrierefreiheit nicht erfüllt. Das ist durch Styling leicht zu lösen, aber vielleicht wäre es sinnvoll, dass das BMF-Theme schon von Haus aus genügend Kontrast hat.

![tipbreadcrumbs1](https://user-images.githubusercontent.com/116639708/212643087-d964d818-83bc-40c1-894b-61ddab37161b.PNG)

**Comment by deleonio** [comment]
@gretaneumann kannst Du bitte mal Feedback geben?

**Comment by deleonio** [comment]
Im Designer sieht es anders aus ... können wir da mal drüberschauen?

<img width="964" alt="image" src="https://user-images.githubusercontent.com/6279703/212648124-d84eb65f-bd6d-4e9b-a8b8-4822496efd8a.png">

**Comment by deleonio** [comment]
@tim-laue Habt Ihr noch einmal im Projekt geschaut?!

**Comment by tim-laue** [comment]
Mit der aktuellen Version von Kolibri und den Themes scheint alles zu funktionieren, daher kann dieses Issue gern geschlossen werden. Danke!
