### ISSUE TITLE
💡 Hinweis: Text von Tabs wird automatisch in Caps Lock geschrieben

### ISSUE THREAD

**Issue by ElVariablo** [public-ui/kolibri#2078]
> **Note**
> - [ X ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**Hilfreicher Hinweis**

Beim erzeugen von Tabs wird die Tab Beschriftung automatisch in Caps Lock geschrieben. Zwar gibt es keinen BITV Prüfschritt der genau dagegen spricht, jedoch kann das schreiben von Text in Caps Lock zu Barrieren führen. Daher sollte der Text so wie geschrieben dargestellt werden.
![2023-01-17_14h18_44](https://user-images.githubusercontent.com/118798973/212909088-4476d523-780b-4d2b-8a7c-67309725f74a.png)

Herzuleiten ist dies aus den [Accessibility Requirements for People with Low Vision Section 3.3.4](https://w3c.github.io/low-vision-a11y-tf/requirements.html#capitalization) der W3C.

>Text in all capital letters is more difficult to read for most people, with and without disabilities.

Da der Text in Großbuchstaben schwer zu lesen ist, kann dies zu Barrieren für Menschen mit und ohne Beeinträchtigung führen.

**Comment by deleonio** [comment]
@ElVariablo - kannst Du Deinen Hinweis bitte konkretisieren. VD

**Comment by deleonio** [comment]
Ich glaube das ist ein Styling-Thema.

@gretaneumannn, @simonhesse

**Comment by gretaneumannn** [comment]
Hallo @ElVariablo! Vielen Dank für die Anmerkung. Wir haben uns für die Capital Letters in den Tabs entschieden, um eine stärkere Hervorhebung zum restlichen Content zu gewährleisten. In normalen Buchstaben würde das Tab-Design zu sehr in den Hintergrund rücken und die Gefahr bestehen, dass es nicht mehr als klickbare Fläche wahrgenommen werden würde. Denn auch die Butttons sind in Capital Letters geschrieben. 
Ich stimme Ihnen jedoch zu, dass besonders lange Wörter in Cap. Letters zu einer Beeinträchtigung im Leseverhalten führen können. Daher sollten die Tabs auch überwiegend aus kurzen Wörtern und nur aus einem Wort bestehen. Da dies jedoch nicht immer möglich ist, können wir das Thema gerne noch einmal zur Diskussion stellen und ggf. ein Alternativdesign vorschlagen. VG Greta

**Comment by deleonio** [comment]
Wir schließen diese Ticket und übernehmen das Thema in eine Diskussion.
