### ISSUE TITLE
🐞 Bug: [>= 1.1.16] kol-button-wc nimmt nicht die volle Größe ein

### ISSUE THREAD

**Issue by eugen-cc** [public-ui/kolibri#2115]
> **Note**
> - [ x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

## Beschreibung des Fehlers
Wenn man die Breite des KolButtons verändern möchte, bspw. mit CSS width:100% , dann sieht man, dass die kol-button-wc Komponente sich nicht an ihre Parent-Komponente anpasst und der Button die Größe nicht ändert.
Mit der Version 1.1.15 funktioniert es noch.

## Erwartetes Verhalten
KolButton lässt sich in der Größe/Breite verändern.

## Screenshots
- &lt;=1.1.15
![before](https://user-images.githubusercontent.com/14055972/213735748-d8bd123c-5651-43d8-9ecd-eb2e30e17bc0.PNG)

- &gt;=1.1.16
![now](https://user-images.githubusercontent.com/14055972/213735774-105abb51-b906-436c-bc45-43987a4458ce.PNG)

**Comment by deleonio** [comment]
fix with v1.3
