### ISSUE TITLE
🐞 Bug: KolInputRadio gibt falsche Werte onChange zurück

### ISSUE THREAD

**Issue by mello-r** [public-ui/kolibri#2152]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
KolInputRadio gibt falsche Werte bei onChange zurück.

## Reproduktion

- Link zu CodeSandbox: https://codesandbox.io/s/gifted-ellis-2bn6ws?file=/src/App.tsx

Schritte zum Reproduzieren des Verhaltens:
- Wechsel zwischen Eintrag 1 und Eintrag 2
- Der Wert ist '-0' oder '-1'

## Erwartetes Verhalten
Der Wert ist 'entry1' oder 'entry2', so wie es in der Liste als Value definiert wurde.

**Comment by deleonio** [comment]
Hallo @mello-r 

Siehe hier: https://codesandbox.io/s/dreamy-einstein-tc27hs?file=/src/App.tsx:525-770

```tsx
declare type InputTypeOnChange = {
  [Events.onChange]?: EventValueCallback<Event, unknown>;
};

<KolInputRadio
  _id="id"
  _list={[
    { label: "Eintrag 1", value: "entry1" },
    { label: "Eintrag 2", value: "entry2" }
  ]}
  _on={{ onChange: (event, value) => setValue(value) }}
/>
```

**Comment by mello-r** [comment]
Danke das funktioniert. @deleonio meinst du man sollte das in der Dokumentation aufnehmen? Ich hab vorher die Dokumentation durchgesehen und keinen Hinweis darauf gefunden.

**Comment by Chrisdo82** [comment]
Ich stolpere auch gerade über diesen Bug @deleonio, ist dass aus der CodeSandbox nicht eher ein Workaround? Oder was ist der Grund warum die `inputs` den `value` -0 und -1 bekommen? Müsste dort nicht eher entry1 bzw. entry2 drinstehen?

<img width="1281" alt="Bildschirmfoto 2023-03-31 um 14 55 11" src="https://user-images.githubusercontent.com/6606913/229126029-2f195067-bb48-49b2-9bab-12352be6f5a5.png">

**Comment by deleonio** [comment]
Hi @Chrisdo82 , hi @Wolfram-Zell ,

die Values im HTML sind Platzhalter-Values (: string) die es ermöglichen, auf App-Ebene auch komplexe Values (bspw. Objekte) handln zu können.

In Version 2 von KoliBri werden wir auch statische Formulare voll unterstützen und dafür wird hier, wie Du auch erwartest, wieder genau der Wert stehen, den Du reingegeben hast. (Ist für static Forms nötig) Der Komfort für die App-Entwicklung wird wegfallen, kann aber mittels Formatter/Parsern vor Inputs leicht gehandled werden.

**Comment by Wolfram-Zell** [comment]
Ein entsprechender Hinweis ist hinzugefügt und wird mit der nächsten Version der Doku ausgerollt.
