### ISSUE TITLE
🐞 Bug: NVDA Fehler beim Accordion

### ISSUE THREAD

**Issue by ElVariablo** [public-ui/kolibri#2169]
> **Note**
> - [ X ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Beim ersten Tab auf die Accordion Komponente wird der Status des Accordion nicht angesagt (erweitert / reduziert).

## Reproduktion

https://public-ui.github.io/docs/components/accordion#code

## Erwartetes Verhalten
Erwartetes Verhalten wäre die Ansage des momentanen Status auch beim ersten Tab, im Normalfall reduziert.

## Zusätzlicher Kontext
Die HTML5 Komponente details zeigt dieses verhalten.

**Comment by deleonio** [comment]
@ElVariablo Bitte teste das mit der Version 1.3.3 nach.
