### ISSUE TITLE
📖 Help: Viel (überflüssiger?) Text in NVDA bei KolNav und Breadcrumbs

### ISSUE THREAD

**Issue by tim-laue** [public-ui/kolibri#2219]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**Hilfeanfrage**

NVDA liest recht viel Text vor, wenn man mit Tab die Breadcrumbs oder KolNav annavigiert. Das ist im Screenshot (entfernt) zu sehen - hier wurde vom Logo nach rechts durch den Header über die Breadcrumbs zum ersten Punkt im Seitenmenü navigiert (gemeint sind die vielen "Sprungmarken"). Wir haben Feedback bekommen, dass das bei einem BitV-Test vielleicht zu einer Abwertung führen könnte.

Ist das so gewollt oder haben wir hier irgendetwas falsch konfiguriert?

**Comment by deleonio** [comment]
@ElVariablo bitte nachtesten. Danke

**Comment by deleonio** [comment]
![image](https://user-images.githubusercontent.com/6279703/217180843-ea584f6a-8fa8-4954-9dd3-c683aeb2ea65.png)

Die Navigationsbeschriftung wird von den KoliBri-Komponenten schon übernommen und muss nicht außen vorgenommen werden. Dafür ist `_aria-label` Pflicht.

**Comment by deleonio** [comment]
@ElVariablo - wie ist das Stand?

**Comment by AntnSaj** [comment]
Bei dem Nachtesten der Komponenten gab es keine Auffälligkeiten, die sich negativ auf einen BITV-Test auswirken könnten. Die "Sprungmarke" wird einmalig vorgelesen, sobald das Element fokussiert wird. @ElVariablo Ticket kann geschlossen werden, sofern du nichts hast, was dagegen spricht.
