### ISSUE TITLE
🐞 Bug: Abstände in KolNav fehlen

### ISSUE THREAD

**Issue by tim-laue** [public-ui/kolibri#2220]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In unserer KolNav Komponente fehlen die Abstände zwischen den Icons und den Texten.

## Reproduktion

Kann den Fehler in der [CodeSandbox](https://codesandbox.io/s/wizardly-bartik-2fmxd2?file=/src/App.tsx) leider nicht reproduzieren. Könnte das an der älteren Kolibri-Version liegen, die dort läuft?

## Erwartetes Verhalten

Die Icons und der Text sollten wie gewohnt einen Abstand haben.

## Screenshots

![menuabstaende](https://user-images.githubusercontent.com/116639708/215711223-e87fb49b-2a6e-4645-9587-9d30049f1c97.png)

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows
- Browser: Chrome
- Version: Alle Kolibri-Pakete auf 1.1.18

**Comment by deleonio** [comment]
Bitte auf v1.3.1 updaten.

https://w5u37c.csb.app/#/nav/basic

<img width="432" alt="image" src="https://user-images.githubusercontent.com/6279703/215762399-8e1a5866-ec1e-4464-afd5-8138338c39d4.png">
