### ISSUE TITLE
🐞 Bug: Value im KolInputDate kann nicht entfernt werden

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#2257]
# Fehlermeldung

## Beschreibung des Fehlers
Aktuell ist es nicht möglich, im KolInputDate den gesetzten Wert zu entfernen. 

## Reproduktion

https://codesandbox.io/s/funny-clarke-0yjh91?file=/src/App.tsx

## Erwartetes Verhalten
Erwartet wird, dass mit dem Setzen von `undefined` oder `null` der aktuelle Wert gelöscht wird.

## Zusätzlicher Kontext
Problem wurde im wöchentlichen Meeting gemeldet.

**Comment by laske185** [comment]
Lösung: null akzeptieren und über die Referenz den Wert setzen

**Comment by deleonio** [comment]
Hinweis . das geht auch beim nativen Input nicht, sobald der Wert über den Datepicker gesetzt wurde.

**Comment by deleonio** [comment]
Bitte parallel mit prüfen: https://github.com/public-ui/kolibri/issues/2202
