### ISSUE TITLE
Abstand zwischen Label und Input verringern

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#2282]
Aufgrund von Verbesserung der Lesbarkeit und Zugehörigkeit, sollte der Abstand zwischen Label und Inputfeld auf **4px** verringert werden.

**Comment by deleonio** [comment]
@Chrisdo82 bitte via Designer machen.

**Comment by Chrisdo82** [comment]
Hi @deleonio, kann ich übernehmen. Wohin muss ich das erzeugte Theme vom Designer jetzt hinterlegen?

**Comment by deleonio** [comment]
Siehe LinkedIn

**Comment by deleonio** [comment]
// kein KoliBri Core Issue.
