### ISSUE TITLE
🐞 Bug: Tests mit Vitest schlagen fehl nach Upgrade auf Version >= 1.3.0

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#2312]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Unsere Tests mit Vitest schlagen nach einem KoliBri Upgrade von 1.1.18 auf mindestens 1.3.0 fehl. Folgende Fehlermeldung erscheint dabei auf Stackblitz: 

```
TypeError: items is undefined
``` 

Lokal sieht die Fehlermeldung etwas anders aus:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
 ❯ setThemeStyleAfterHydrated node_modules/.pnpm/@public-ui+components@1.3.1/node_modules/@public-ui/components/dist/cjs/index-65050ef8.js:4:8640
 ❯ Timeout.<anonymous> node_modules/.pnpm/@public-ui+components@1.3.1/node_modules/@public-ui/components/dist/cjs/index-65050ef8.js:4:9361
 ❯ listOnTimeout node:internal/timers:559:17
 ❯ processTimers node:internal/timers:502:7
```

## Reproduktion

- Link zu Stackblitz: https://stackblitz.com/edit/github-w9fjy7-xurzxq?file=src%2FApp.tsx,package.json,src%2Ftest%2Fsetup.ts,src%2FApp.test.tsx

Schritte zum Reproduzieren des Verhaltens:
- Rufe Stackblitz auf
- Schaue dir das Ergebnis im Terminal an => fail
- gehe in die package.json und passe die KoliBri Versionen von 1.3.1 auf 1.1.18 an
- führe das Script im Terminal erneut aus
- Schaue dir das Ergebnis im Terminal an => success

## Erwartetes Verhalten
Die Tests laufen weiterhin durch.

## Kontext
KoliBri wird in der setup.ts für die Testsuite initialisiert. Ich vermute auch das hier der Fehler liegt.

**Comment by Chrisdo82** [comment]
@deleonio dieses Issue verhindert bei uns gerade ein Upgrade auf die neuste Version

**Comment by Chrisdo82** [comment]
btw. die console.infos erscheinen immer noch

**Comment by deleonio** [comment]
Du kannst Dir genau das Vite Projekt jetzt über die CLi generieren. `npm init kolibri@next vite-app` hier geht die App der Test schlägt fehl, keine Konsole errors.

**Comment by Chrisdo82** [comment]
> Du kannst Dir genau das Vite Projekt jetzt über die CLi generieren. `npm init kolibri@next vite-app` hier geht die App der Test schlägt fehl, keine Konsole errors.

Die setup.ts in dem init bei euch ist aber falsch, da scheint beim kopieren etwas nicht geklappt zu haben. Dort müsste die Initialisierung von Kolibri enthalten sein. Wenn man die anpasst, dann geht der Test auch. Habt ihr den Bug im letzten rc gefixed? Die `console.info` erscheint übrigens weiterhin.

**Comment by deleonio** [comment]
Hi @Chrisdo82,

mit der neusten Version 1.4-rc.7 sind die Irritationen gefixed.

- https://stackblitz.com/edit/github-w9fjy7-apsixi
- Bitte Changelogs beachten für 1.4

Ich kenne mich mit Vitest noch nicht so gut aus - könntest Du bitte das Setup im Template entsprechend anpassen. Das wäre nett.

**Comment by deleonio** [comment]
Hi @Chrisdo82,

mit der neusten Version 1.4-rc.7 sind die Irritationen gefixed.

- https://stackblitz.com/edit/github-w9fjy7-apsixi
- Bitte Changelogs beachten für 1.4

Ich kenne mich mit Vitest noch nicht so gut aus - könntest Du bitte das Setup im Template entsprechend anpassen. Das wäre nett.

**Comment by Chrisdo82** [comment]
Der Test funktioniert. Ich habe aber leider immer noch das Problem dass nun das Theme nicht mehr geladen wird. Und die console.infos erscheinen immer noch. Wie kann ich die unterdrücken?

**Comment by Chrisdo82** [comment]
> Ich kenne mich mit Vitest noch nicht so gut aus - könntest Du bitte das Setup im Template entsprechend anpassen. Das wäre nett.

Scheint doch jetzt geklappt zu haben? Bei Stackblitz laufen die Tests jetzt erfolgreich durch.

**Comment by Chrisdo82** [comment]
> Bitte Changelogs beachten für 1.4

Bis auf die Anpassung des Pfades für die Schriften kann ich nicht rauslesen was wir bei uns wie anpassen müssen.

**Comment by deleonio** [comment]
> > Ich kenne mich mit Vitest noch nicht so gut aus - könntest Du bitte das Setup im Template entsprechend anpassen. Das wäre nett.
> 
> Scheint doch jetzt geklappt zu haben? Bei Stackblitz laufen die Tests jetzt erfolgreich durch.

Hier ging es mir um das Template in der Create-KoliBri-App . #nice-to-have

**Comment by Chrisdo82** [comment]
@deleonio Hast du hier schon Feedback für mich?

- Wie kann ich das BMF Theme einbinden (wird mit 1.4x nicht initialisiert und in der Changelog lese ich dazu nichts raus was ich wie anpassen muss)
- console.infos unterdrücken (was muss ich anpassen damit ich diese im Test nicht sehe?)

**Comment by Chrisdo82** [comment]
mit v1.4.0 gelöst
