### ISSUE TITLE
🐞 Bug: Designer ist leer

### ISSUE THREAD

**Issue by Wangador** [public-ui/kolibri#2330]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn man den Designer aufruft ist der Code links leer und die Komponenten rechts ungestyled.

## Reproduktion

- Link zum Designer: 'https://public-ui.github.io/designer/'

Schritte zum Reproduzieren des Verhaltens:
- Rufe den Designer auf
- Dort sind sofort das leere Codefeld und die ungestylten Komponenten zu sehen

## Erwartetes Verhalten
Default styling für alle Komponenten

**Comment by deleonio** [comment]
Hallo @Wangador , bitte drücken Sie Strg + F5 bzw. Command + Shift + R.

**Comment by deleonio** [comment]
Hinweis ist in der Seite eingebaut.

**Comment by isthisstackoverflow** [comment]
@deleonio Ich habe das Problem in Firefox 109.0.1 (64-Bit) auch. Hard Refresh hilft nicht. In Firefox habe ich es testweise in einem privaten Fenster aufgerufen, und parallel auch auf meinem Mobiltelefon geschaut, wo ich den Designer noch nicht aufgerufen hatte. Das Verhalten ist jeweils so wie im Startbeitrag beschrieben.
