### ISSUE TITLE
🐞 Bug: Vertikale Überschriften werden nicht mitsortiert

### ISSUE THREAD

**Issue by Zementaa** [public-ui/kolibri#2372]
> **Note**
> - [ x ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn die Zeilensortierung (sort-Attribut) verwendet wird, werden vertikale Überschriften nicht mitsortiert.

## Reproduktion
Bereits im Kolibri-Meeting reproduziert.

Schritte zum Reproduzieren des Verhaltens:
- Tabelle mit Sortierfunktion erstellen
- Spalte sortieren
- Daten-Zeilen werden sortiert, vertikale Überschriften bleiben gleich

## Erwartetes Verhalten
Vertikale Überschriften werden beim sortieren mitsortiert.

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows
- Browser Chrome
- Version -

**Comment by deleonio** [comment]
Wir müssen hierzu eine Analyse zur Machbarkeit machen und geben dann ein erstes Feedback.

**Comment by deleonio** [comment]
Hallo @Zementaa,

die Vertikale sortieren von vertikalen Headern stellt ein komplexes Thema dar. Beispielsweise könnten Header-Gruppen durch das Sortieren auseinandergerissen. Wir würden den Feature-Wunsch offen lassen, sehen aber aktuell keinen guten Lösungsweg, den wir umsetzen würden.

VG Martin

**Comment by deleonio** [comment]
Wir sollten aus logischen Gründen das Sortieren nicht ermöglichen, sobald man sowohl vertikale als auch horizontale Header verwendet.
