### ISSUE TITLE
🐞 Bug: kol-select option value Werte immer negative Integer (war: erlaubt keinen String)

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#2373]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In einem klassischen HTML-Select können option values sowohl numerisch als auch alphanumerisch sein. Beispiel:
`<option value="wert">Was auch immer ich statt dessen anzeigen möchte</option>`

KolSelect macht aus Zeichenketten negative Zahlen, z.B.
`<option value="-1">Was auch immer ich statt dessen anzeigen möchte</option>`

Edit: Korrektur: Ich bekomme *immer* negative Zahlen, egal was ich angebe.

## Reproduktion
https://codesandbox.io/s/festive-leftpad-ok7m5l?file=/src/App.tsx

## Erwartetes Verhalten
Zeichenketten sollten als value funktionieren.

**Comment by deleonio** [comment]
Hallo @webbird,

das Wert-Handling erfolgt auf Controller-Ebene. Wird der Wert über den Callback geholt, dann werden auch die korrekten Formate zurückgegeben.

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/6279703/220079989-e097b822-797b-463f-b652-b4fc936c1a04.png">

Angepasstes Beispiel: https://codesandbox.io/s/wild-sea-001035?file=/src/App.tsx

**Comment by webbird** [comment]
Danke sehr!
