### ISSUE TITLE
🛹 Feature: Tabellenfooter (tfoot)

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#2374]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage
Ich habe Tabellen mit einer "Summary"-Zeile, also eine "Gesamtsumme" als Zusammenfassung. Beim Sortieren wird diese Zeile dann natürlich mit sortiert. Eine Möglichkeit wäre die Zusammenfassung in tfoot. Ist das eingeplant?
Ich habe mir damit beholfen, die Summary statt in der Tabelle in der umliegenden kol-card unterzubringen, aber aus Sicht der Barrierefreiheit ist das vermutlich suboptimal.

## Beschreiben Sie die gewünschte Lösung
Die Unterstützung von tfoot sollte dann auch bei Sortierung u.ä. berücksichtigt werden.

Gibt es eine Alternative zur Verwendung von tfoot für diesen konkreten use case?

**Comment by deleonio** [comment]
Spec-Team: Könnt Ihr bitte mal ein paar Ref-Bespiele heraussuchen, wie wir einen Table-Footer umsetzen könnten.

**Comment by Dottopia** [comment]
Grundsätzlich spricht erstmal nichts gegen die Verwendung von tfoot, da diese gut vom Screenreader vorgelesen wird, visuell immer unten an der Tabelle platziert wird und beim sortieren nicht mit sortiert wird:
Bei folgendem Beispiel kann man mal ein tfoot einbauen und sehen, dass es nicht mit sortiert wird:
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sort_table

Screenreader-Auszug bei einem tfoot:
![2023-02-20_11h53_24](https://user-images.githubusercontent.com/16099573/220564915-ab8e590d-4bae-4870-a9b4-f4bf892fd863.png)

Wie so ein tfoot in KoliBri umgesetzt werden kann ist eine gute Frage. Gäbe es die Möglichkeit ein property zu erstellen ähnlich wie _caption?

**Comment by deleonio** [comment]
Umsetzung-Idee aufsetzen. Lösungvorschläge erarbeiten.

**Comment by Wolfram-Zell** [comment]
1. boolean Option um die unterste Zeile zu markieren.
2. Option die ein Objekt erwartet ähnlich wie _headers
    a) nur unten
    b) unten und rechts

**Comment by deleonio** [comment]
Spezifikation:
- neues Property: `_dataFoot` - gleiches Format wie  `_data`

**Comment by Wolfram-Zell** [comment]
Copy code from tbody (refactor both if aplicable)
