### ISSUE TITLE
🐞 Bug: Nicht interaktive Tabelle enthalten den Fokus.

### ISSUE THREAD

**Issue by HansellKopp** [public-ui/kolibri#2375]
> **Note**
> - [ ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
BitV Fehler: Nicht interaktive Tabelle erhalten den Fokus.

Der <KolTable> Komponente hat kein _disabled Attribute oder andere Weg, um den Fokus setzen zu vermeiden

## Reproduktion

Nutzen Sie die [CodeSandbox](https://codesandbox.io/s/inspiring-firefly-teqjmn), um ein reproduzierbares Beispiel zu erstellen.

- Link zu CodeSandbox: '...'

Schritte zum Reproduzieren des Verhaltens:
- Gehe zu '...'
- Klicke auf '....'
- Scrollen Sie nach unten zu '....'
- Siehe Fehler

## Erwartetes Verhalten
Eine klare und prägnante Beschreibung dessen, was Sie erwartet haben.

## Screenshots
Fügen Sie gegebenenfalls Screenshots hinzu, um Ihr Problem zu erläutern.

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: [z.B. iOS]
- Browser [z.B. Chrom, Safari]
- Version [z.B. 22]

## Smartphone (bitte ergänzen Sie folgende Angaben):
- Gerät: [z.B. iPhone 6]
- Betriebssystem: [z.B. iOS8.1]
- Browser [z.B. Aktienbrowser, Safari]
- Version [z.B. 22]

## Zusätzlicher Kontext
Fügen Sie hier einen beliebigen anderen Kontext zum Problem hinzu.

**Comment by deleonio** [comment]
Das wurde explizit so umgesetzt - weil nur so das Fokussieren der Tabelle zum seitlichen Scollen möglich ist.

@HansellKopp könntest Du näher erläutern, was für dein Anliegen spricht.

**Comment by HansellKopp** [comment]
Bei den BiTV Test haben sie festgestellt, dass nicht-interaktive Elemente den Fokus nicht erhalten sollen. In unseren Anwendungsfälle haben wir einige Tabellen mit wenigen Elementen, die nicht gescrollt werden müssen. Trotzdem bekommen sie Fokus bei den Tastatur Navigation.

**Comment by deleonio** [comment]
@mardot @cbraehmig @ElVariablo Bitte nehmt das mal mit. KoliBri muss die Barrierefreiheit sicherstellen, daher ist das default-mäßig so. Soll das abstellbar werden?!

Ich würde es nicht ermöglichen, da wir nie sicher sein können wie der Zoom den Faktor scrollbare Tabellen erfordert!

**Comment by deleonio** [comment]
Ich möchte noch zu bedenken geben, dass auch ohne interaktive Elemente eine Tabelle unter Umständen fokussierbar sein muss, da nicht klar ist, wie klein bzw. die Tabelle gezoomt wird und das seitliche Scollen erforderlich wird.

**Comment by ElVariablo** [comment]
Prinzipiell gilt, dass der Mehrwert der Scrollbarkeit höher wiegt als der eine zusätzliche Tab schritt. 
Es sollten jedoch folgende Punkte überprüft werden:

- ist es möglich den Tab Fokus erst zu ermöglichen, wenn die Tabelle einen horizontalen Scroll Balken erhält
- ist es bei der momentanen Implementierung überhaupt noch möglich einen horizontalen Scroll Balken zu erhalten? Alle Beispiele die wir sehen sind mit dem Buchstaben Umbruch umgesetzt. Falls es momentan nicht möglich ist, sollte entweder wieder die Alternative gegeben werden oder der Tab schritt entfernt werden. (Eventuell 2 varianten der Tabelle oder über zwei Attribute lösen?)

**Comment by deleonio** [comment]
Der Tabellen Container maximal 100 %.

Es ist möglich, jeder Spalte eine Breite zu geben. Dadurch kann eine Tabelle innerhalb des Containers breiter sein.

Mal schauen, ob wir einen Listener machen können, der feststellt, ob ein Scollbalken aktiv ist. Dann tabindex="0".
