### ISSUE TITLE
📖 Help: Screenreader soll den Inhalt im "header" slot vom Accordion vorlesen

### ISSUE THREAD

**Issue by joschakaisr** [public-ui/kolibri#2379]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

Es besteht der Wunsch, dass im Accordion neben der Überschrift ein Icon dargestellt wird und darunter zusätzliche Informationen. Das lässt sich gut, wie in eurem [Accordions mit header Slot Beispiel](https://public-ui.github.io/docs/components/accordion/#accordions-mit-header-slot) realisieren.

Der Screenreader ließt hierbei aber nicht den Inhalt des header Slot vor. 

Wie schaffe ich es, dass die zusätzlichen Informationen und das aria-label von dem Icon beim Fokus auf das Accordion vorgelesen werden?

**Comment by ElVariablo** [comment]
Hallo,

das Beispiel der der Accordions mit header Slot ist etwas verwirrend und wird angepasst. Der Header-Slot soll im Wesentlichen nicht dazu dienen weitere Informationen bereit zu stellen, sondern Interaktive Elemente mit einzubinden. Dazu unterhalb zwei Bilder um den Einsatz zu verdeutlichen.

![Image](https://user-images.githubusercontent.com/118798973/222365704-aa9f1b87-5384-4b06-b41c-b925d12cd0a5.png)

![Image](https://user-images.githubusercontent.com/118798973/222365718-6215ccbf-74c2-4814-9dc2-05bedcd7eab3.png)

Momentan ist es so, dass der Inhalt des header Slot nicht beim Tab Fokus des Elements mit vorgelesen wird, aber im Linearen Lesemodus. Im Normalfall gehen Screenreader Nutzende die Seite im Lesemodus durch und erreichen somit alle Elemente und so auch die weiteren Informationen im header Slot. 

Es gibt momentan Überlegungen der heading Komponente noch die Option zu geben über oder unter Text zu verwenden. Das würde euer Problem lösen da Ihr die weiteren Informationen in den Untertext schreiben könntet

**Comment by joschakaisr** [comment]
Hallo, 
heißt das, es ist bereits BITV konform, dass die Screenreader Nutzenden die zusätzlichen Informationen im header Slot über den Lesemodus erhalten oder soll die Über-/Untertext Property dann die BITV Lösung werden?
