### ISSUE TITLE
🐞 Bug: Cannot find module './locales/de.json'

### ISSUE THREAD

**Issue by snowcode101** [public-ui/kolibri#2456]
Hallo zusammen,

wir haben bei der aktuellen Version einen Bug:

# Fehlermeldung
`
Error: node_modules/@public-ui/components/dist/types/i18n.d.ts:2:23 - error TS2307: Cannot find module './locales/de.json' or its corresponding type declarations.
`

## Beschreibung des Fehlers
Die in `i18n.d.ts` referenzierte Datei-Import 'de.json' existiert nicht.

## Reproduktion
* `npm init kolibri@latest my-app`
* template: angular-app
* `npm install`
* `npm run build`

## Workaround
Legt man die erwartete Datei `de.json` per Hand an, kann die Anwendung erfolgreich gebaut werden.

**Comment by deleonio** [comment]
@laske185 Bitte alle Texte typisiert mit TypeScript abbilden.

JSON-Config wieder aus tsconfig.json entfernen.
