### ISSUE TITLE
🛹 Feature: Umsetzung eines Loading-Button mittels Expert-Slot

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#2476]
> **Note**
> - [ ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

![image](https://user-images.githubusercontent.com/6279703/221570005-b9ef6efe-8dc1-48f5-8c84-9cd6f6b866f5.png)

**Comment by Chrisdo82** [comment]
ich habe einen LoadingButton gebaut der nach dem Wechsel des Ladezustands, noch für ein paar Sekunden einen Haken anzeigt. Hier zu sehen: https://codesandbox.io/p/sandbox/minimal-kolibri-sample-forked-r3df27?file=%2Fsrc%2FButton.tsx%3A86%2C27 
 
Allerdings funktioniert das Ganze nicht, wenn _iconOnly gesetzt ist, da dann der expert Slot nicht verwendet wird.
 
Hast du eine Idee, wie wir die gleiche Funktionalität auch für _iconOnly gewährleisten können?

**Comment by deleonio** [comment]
Eine Lösungsidee wäre, eine Wrapper-Component umzusetzen und `_hideLabel` nicht an die KoliBri-Komponente weiterzureichen.

Einfach über den Expert-Slot beide Modi umsetzen:

1. Mit Label so wie es jetzt implementiert ist
2. Nur Icon mit Tooltip über Expert-Slot hereinreichen

**Comment by deleonio** [comment]
Duplikat: https://github.com/public-ui/kolibri/issues/4747

**Comment by Chrisdo82** [comment]
@deleonio 
Der Lösungsansatz funktioniert, jedoch komme ich nicht drumherum eine `_customClass` mit `_variant="custom"` zu setzen, damit das CSS auch für IconOnly-Buttons funktioniert. 

Ich hatte erst die Hoffnung, dass ich mit `_customClass="hide-label"` weiterkomme, jedoch gibt es dann weiter unten ein `display:none` welches verhindert, dass der Expert Slot gerendert wird.
Ich wollte dann eine neue `icon-only` Klasse einführen, aber die scheint es schon im CSS von eurem BaseTheme zu geben. Ist das ein Überbleibsel welches mal entfernt werden sollte?
