### ISSUE TITLE
Component: Tree neu umsetzen

### ISSUE THREAD

**Issue by mspecht-adesso** [public-ui/kolibri#2478]
> **Note**
> - [ ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Hierarchisch strukturierte Daten sollen in einer platzsparenden, übersichtlichen und benutzerfreundlichen Art dargestellt werden.

## Beschreiben Sie die gewünschte Lösung
Es wird eine Tree-Component benötigt, die beliebig viele Stufen and Daten in einer Baunstruktur darstellen kann.
Die Tree-Componente sollte ein JSON-File entgegennehmen und entsprechend der unten gezeigten Abbildung strukturiert darstellen. Die einzelnen Ebenen sollten per Klick zu öffnen bzw. zu schließen sein. Das sollte per Maus und auch per Tastatur möglich sein.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Eine klare und prägnante Beschreibung aller alternativen Lösungen oder Funktionen, die Sie in Betracht gezogen haben.

## Zusätzlicher Kontext
![Super-Treeview](https://user-images.githubusercontent.com/122083845/221575095-a51eeb5e-5625-4fe3-a792-143bc1bc28c9.png)

# Spezifikation

Aufteilung in zwei Komponenten:
- tree
  - shadow-Dom
  - tree items in slot akzeptiert
- treeItem
  - ohne shadow-Dom

```html
<kol-tree _label="Überschrift">
    <kol-tree-item _label="Item A" />
    <kol-tree-item _label="Item B" />
    <kol-tree-item _label="Item C with children">
        <kol-tree-item _label="Item CA" />
        <kol-tree-item _label="Item CB" />
    </kol-tree-item>
</kol-tree>
```

### Tree
- `label: string` (muss aria-label werden)

### TreeItem
- `label: string`
- `expanded: boolean`
- slot

## Refresh bei DOM-Änderungen

Tree muss aktualisiert werden, wenn Items geändert werden.

Pro Tree ein `MutationObserver`:

```js
var MutationObserver = window.MutationObserver || window.WebKitMutationObserver;
var observer = new MutationObserver(function(mutations) {
    // updateDom - stencil method (https://stenciljs.com/docs/methods)
    mutations[0].target.updateDom();
    console.log(mutations);
});

var config = { childList: true }
observer.observe(element, config);
```

Jedes TreeItem muss ebenso `observer.observe(element, config)` aufrufen.

`observer.disconnect();` beim Entfernen des Trees.

## Vorgehen

- Baumstruktur umsetzen
- erstmal ohne Checkboxen
- Inhalt der Treeitems als Slots
- Ich würde ernsthaft prüfen, ob wir nicht einfach die `kol-details-wc` einsetzen könnten.
- Konstruktion beachten, s.o.

```tsx
<ul role="tree">
  <li role="none">
    <KolDetails role="treeitem" _summary="Tree">
      <ul role="tree">
        <li role="none">
          <KolDetails role="treeitem" _summary="false">
            <div slot="expert">...</div>
          </KolDetails>
        </li>
        <li role="none">
          <KolDetails role="treeitem" _summary="Tree">
            <ul role="tree">
              <li role="none">
                <KolDetails
                  role="treeitem"
                  _summary="Tree"
                ></KolDetails>
              </li>
              <li role="none">
                <KolDetails
                  role="treeitem"
                  _summary="Tree"
                ></KolDetails>
              </li>
            </ul>
          </KolDetails>
        </li>
      </ul>
    </KolDetails>
  </li>
</ul>
```

- https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/
- https://codesandbox.io/s/kolibri-public-ui-react-tree-draft-xz45sy?file=/src/index.tsx
- 
# Mixed-Ansicht
```tsx
<kol-tree _label="Item A">
  # shadow-root
     <ul role="tree">
        <li role="treeitem">
           <slot name="item-1">
             <kol-tree-item>...</kol-tree-item>
           </slot>
        </li>
        <li role="treeitem">
           <slot name="item-2">
             <kol-tree-item>...</kol-tree-item>
           </slot>
        </li>
        <li role="treeitem">
           <slot name="item-3">
             <kol-tree-item>
             </kol-tree-item>
           </slot>
        </li>
      </ul>



  <li role="none">
    <KolDetails role="treeitem" _summary="Tree">
      <ul role="tree">
        <li role="none">
          <KolDetails role="treeitem" _summary="false">
            <div slot="expert">...</div>
          </KolDetails>
        </li>
        <li role="none">
          <KolDetails role="treeitem" _summary="Tree">
            <ul role="tree">
              <li role="none">
                <KolDetails
                  role="treeitem"
                  _summary="Tree"
                ></KolDetails>
              </li>
              <li role="none">
                <KolDetails
                  role="treeitem"
                  _summary="Tree"
                ></KolDetails>
              </li>
            </ul>
          </KolDetails>
        </li>
      </ul>
    </KolDetails>
  </li>
</ul>
```

**Comment by deleonio** [comment]
@mardot Bitte evaluiert die Komponenten-Anfrage und schaut nach einer Vorlage. Danke

**Comment by ElVariablo** [comment]
Aus Barrierefreiheitssicht spricht nichts gegen die Komponente. Die Einträge und die verschiedenen Ebenen müssen nur als geschachtelte Listen umgesetzt werden. W3C hat umfassende Beispiele auf Ihrer Seite.
Generell zur Komponente: https://www.w3.org/WAI/ARIA/apg/patterns/treeview/
Darstellungsbeispiel von Daten: https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-1b/#top

**Comment by deleonio** [comment]
Hi @mspecht-adesso, schau Dir bitte auch die Vorlagen aus der WCAG an, sie Kommentar oben.

**Comment by mspecht-adesso** [comment]
Moin, mache ich.

**Comment by deleonio** [comment]
Hallo @mardot, wie machen wir hier weiter.

Ich weiß nicht, ob die Implementierung wie von der WCAG empfohlen umgesetzt ist?

FYI: @Chrisdo82

**Comment by laske185** [comment]
Offen: Checkboxen je TreeItem.

TODO: neues Ticket anlegen, dass den aktuellen Piloten um die Checkboxen erweitert.

**Comment by laske185** [comment]
Issue angelegt: https://github.com/public-ui/kolibri/issues/6449
