### ISSUE TITLE
🛹 Feature: Popover

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#2533]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---
Trigger ist automatisch das im HTML vorangehende Element.

**Comment by ElVariablo** [comment]
Auf der Seite ist unter dem Punkt Accessibility aufgelistet worauf im Bezug auf die Barrierefreiheit geachtet werden sollte.

Beispiele können die Implementierung von Bootstrap, servicenow oder paste sein

- https://getbootstrap.com/docs/4.0/components/popovers/
- https://developer.servicenow.com/dev.do#!/reference/next-experience/tokyo/now-components/now-popover/overview
- https://paste.twilio.design/components/popover

**Comment by deleonio** [comment]
Hi @Wolfram-Zell, hier das Ticket zum Popover.

**Comment by deleonio** [comment]
Lösungsskizze:
- Interessante Vorlage: https://headlessui.com/react/popover
- [x] Ausrichtungsalgorithmus vom Tooltip
- [x] Beim Öffnen Fokus auf Popover (tabindex="0" auf Popover Container)
- ~~Öffnen mit Übergabe eines activeElement, welches auch Referenznode für die Positionierung ist~~
- [x] Referenznode ist der Vorgängernode im DOM, wie beim Tooltip
- [x] Schließen bei WCAG nachlesen (ESC?!)
- [x] Fokus nach Schließen auf activeElement
