### ISSUE TITLE
🛹 New Component: Image

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#2535]
W3C, WACG

https://mui.com/joy-ui/react-aspect-ratio/

- src: string / alternativ src-data?
- alt: string ... description?!
- ratio: Type?!
- lazy loading

- see Icon

- [ ] Bitte später noch die `NEW_COMPONENT.md` anreichern.

**Comment by deleonio** [comment]
- [ ] Bitte später noch die `NEW_COMPONENT.md` anreichern.

**Comment by Wolfram-Zell** [comment]
Die .mds sind im Branch 2649-feedback-zum-onboarding-auf-github zu finden.
