### ISSUE TITLE
🐞 Bug: Datumfeld löscht Eingabe

### ISSUE THREAD

**Issue by lnk1812** [public-ui/kolibri#2536]
# Fehlermeldung

## Beschreibung des Fehler
Wenn ein Datumsfeld mit einem Mausklick fokussiert wird und anschließend eine Eingabe erfolgt, wird bei dem Wechsel zur Monatseingabe der Tag gelöscht. Wird das Datumsfeld über den Tabulator fokussiert, tritt dieser Fehler nicht auf.

## Reproduktion
Der Fehler tritt in der Version 1.1.7-rc.5 auf und auch in der aktuellen Version v1.4.2-rc.0
https://public-ui.github.io/docs/components/input-date

Der Fehler lässt sich auf verschiedene Wege reproduzieren
Schritte zum Reproduzieren des Verhaltens:

### Eingabe verschwindet direkt
- Docs Seite aufrufen
- Klicke auf das Datumsfeld
- "1" Eingeben

### Normale Eingabe (Tag verschwindet)
- Docs Seite aufrufen
- Klicke auf das Datumsfeld
- schnell "12121".... Eingeben

### Eingabe spamen (Tag und Monat verschwinden)
- Docs Seite aufrufen
- Klicke auf das Datumsfeld
- Sehr schnell "12121".... Eingeben

## Erwartetes Verhalten
Die eingegebenen Werte bleiben erhalten.

## Desktop:
- Betriebssystem: WIndows 10
- Browser Chrome
- Version 110.0.5481.97

**Comment by laske185** [comment]
Um das Datum löschen zu können, wird der Wert des HTML-inputs mit der Komponente synchronisiert. Dieser Sync geht hier durcheinander. Vermutlich sollte es zeitversetzt synchronisiert werden, damit schnelle Eingaben nicht blockiert werden.
