### ISSUE TITLE
📖 Help: Anpassung eines bestehenden Themes

### ISSUE THREAD

**Issue by BenRichter** [public-ui/kolibri#2537]
**Hilfeanfrage**

Ich möchte eines der bestehenden Themes erweitern bzw. Styling überschreiben und nutze dazu den Export im Designer.
In Angular registriere ich bisher das Theme in der app.modules.ts und wollte dieses über die exportierte JSON wie folgt anpassen:

```ts
import { KoliBriModule } from '@public-ui/angular-v15';
import { defineCustomElements } from '@public-ui/components/dist/loader';
import { KoliBriDevHelper } from '@public-ui/components';
import { register } from '@public-ui/core';
import { BMF } from '@public-ui/themes';
import kolibriTheme from './../sass/kolibri-theme.json';

...

export class AppModule {
  constructor() {
    KoliBriDevHelper.patchTheme('bmf', kolibriTheme);
    register([BMF], defineCustomElements);
  }
}
```

Die Styles werden so aber nicht übernommen. Ich erhalte nur eine Warnung: "_[Theming] The theme process is locked. This means that the theme "bmf" should not be patched."_

Eigentlich möchte ich nur einzelne Elemente geringfügig anpassen, anstatt ein komplett separates Theme zu erstellen.
Dies ist in der Dokumentation leider nur theoretisch Beschrieben. Hier wäre ein einfaches Beispiel sehr hilfreich.

**Comment by deleonio** [comment]
Hallo @BenRichter ,

wir haben den Code-Snippet im Designer dahingegen optimiert. Dann ist es gleich sichtbar.

Du musst immer nach dem Registrieren patchen.

Siehe https://github.com/public-ui/kolibri/blob/20ce4356eb5a9465ff51243b59276f24281e937c/packages/designer/src/components/editor/ts-editor.ts#L21

PS: Mo 13 Uhr Regeltermin / BMF ... bist Du da dabei?
