### ISSUE TITLE
🛹 Feature: 'ref' wird nicht durchgereicht

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#26]
`ref`s werden derzeit nicht forwarded. Das z.B. funktioniert derzeit nicht:

```
<KolButton ref={ref} ... />
```

Erwartetes Verhalten wäre, dass das `ref` an das `button` Element durchgereicht werden würde. Bei Bedarf kann ich noch ein detaillierteres Beispiel liefern

Opened by @Chrisdo82

**Comment by deleonio** [comment]
Created by @Chrisdo82

**Comment by deleonio** [comment]
Hierzu könnte man sich mal folgende Code-Zeile anschauen: https://github.com/public-ui/kolibri/blob/82632e255b0650c6049d6dedf08d77a605838754/packages/library/src/components/form/controller.ts#L59

**Comment by deleonio** [comment]
@Chrisdo82

**Comment by Chrisdo82** [comment]
ja?

**Comment by Chrisdo82** [comment]
Hier kann das Problem nachgestellt werden: https://codesandbox.io/s/focused-paper-z2biwk?file=/src/components/StartseiteComponent.tsx

**Comment by deleonio** [comment]
Ich habe die Idee -> das wir die betreffenden Komponenten um eine `public focus`-Methode einbauen gehen müsste.

**Comment by Chrisdo82** [comment]
Hallo, die focus Methode wäre sicherlich nicht verkehrt, wäre allerdings nur ein workaround. ref würde damit immer noch nicht unterstützt werden.

**Comment by deleonio** [comment]
@Chrisdo82 könnte mit 1.1.16 gelöst sein.

**Comment by Chrisdo82** [comment]
Hat sich bis auf die `focus`-Methode noch was geändert? Solange `ref`'s nicht forwarded werden, ist das Thema m.E. nicht gelöst.

**Comment by deleonio** [comment]
Naja Du nimmst einfach die ref von der Component und die propagiert den focus durch. Probiere es dann aus und wir schauen uns dann an - wo wir stehen.

**Comment by Chrisdo82** [comment]
ok scheint hier geklappt zu haben: https://codesandbox.io/s/unruffled-chatelet-g1msqv?file=/src/components/StartseiteComponent.tsx

ich gucke mal im Projekt ob es noch weitere UseCases gibt.

**Comment by deleonio** [comment]
@Chrisdo82 works ;-) https://codesandbox.io/s/youthful-resonance-uziouk?file=/package.json
