### ISSUE TITLE
Nav: Separate Link and Expanded-Button

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#2600]
Bei den aufklappbaren Menüpunkten sollte der Menülink vom Aufklapp-Button getrennt werden - da es zwei separate Aktionen sind.

![Image](https://user-images.githubusercontent.com/6279703/224244636-526876d2-1bd5-4ce3-b654-14981434d981.png)

**Comment by laske185** [comment]
Wie verhält es sich, wenn ein Eintrag ein Icon haben sollte?

**Comment by Wolfram-Zell** [comment]
1. keine Unterpunkte: das ganze Element soll Link sein.
2. Unterpunkte >0 & Oberpunkt hat Link: Label (unabhängig vom Inhalt) hat Oberpunkt Link, Chevron klappt Untermenü auf
3. Unterpunkte >0 & Oberpunkt hat keinen Link: das ganze Element soll Untermenü aufklappen
