### ISSUE TITLE
Nav: Support two _variant's 'paging' and 'folding'

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#2601]
Aktuell unterstützen wir das "Aufklappen" (folding) - wir können aber auch zusätzlich das "Blättern" (paging) als Variant der Navigation umsetzen.

![Image](https://user-images.githubusercontent.com/6279703/224244825-4172251a-f670-47a9-b76c-ae621c697a9e.png)

https://ec.europa.eu/component-library/ec/components/navigation/menu/code/

**Comment by Wolfram-Zell** [comment]
<s>Bitte Skizze oder Beispiel hinzufügen.</s>
