### ISSUE TITLE
🛹 Feature: Icon Toggle

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#2652]
Es wird ein Toggle in Form eines Icons benötigt.

- Kein Label
- Tooltip hinzufügen
- Aktiver Zustand: Solid Icon
- Inaktiver Zustand: Regular Icon
- width: 24px; height: 24px;

<img width="470" alt="image" src="https://user-images.githubusercontent.com/118734593/225377228-96557510-0cce-4c63-bd57-7e85fa033e4b.png">

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Eine klare und präzise Beschreibung des Problems. Ex. Ich bin immer frustriert, wenn [...]

## Beschreiben Sie die gewünschte Lösung
Eine klare und prägnante Beschreibung dessen, was passieren soll.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Eine klare und prägnante Beschreibung aller alternativen Lösungen oder Funktionen, die Sie in Betracht gezogen haben.

## Zusätzlicher Kontext
Fügen Sie hier beliebigen weiteren Kontext oder Screenshots zur Funktionsanfrage hinzu.

**Comment by deleonio** [comment]
@gretaneumannn, @Chrisdo82 feature in 1.5-rc1 umgesetzt.
