### ISSUE TITLE
🛹 Feature: Capital-Letters entfernen (Badges, Tabs, Buttons)

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#2661]
Die Entscheidung ist nun darauf gefallen Capital-Letters aus der Anwendung zu nehmen, um die Lesbarkeit und Flexibilität zu erhöhen. 

**Badges**
font-family: BundesSans Web;
font-size: 16px;
font-weight: 400;
line-height: 24px;
letter-spacing: 0px;
text-align: left;

**Tabs**
font-family: BundesSans Web;
font-size: 18px;
font-weight: 700;
line-height: 24px;
letter-spacing: 0px;
text-align: left;

**Buttons**
font-family: BundesSans Web;
font-size: 18px;
font-weight: 700;
line-height: 24px;
letter-spacing: 0px;
text-align: center;

**Comment by gretaneumannn** [comment]
@Chrisdo82: Auch für dich zur Info :)

**Comment by deleonio** [comment]
Danke Euch. Achtung im BITV darf Letter Spacing nicht gesetzt werden!

FYI: @gretaneumannn , @Chrisdo82

**Comment by deleonio** [comment]
Hallo @Chrisdo82 und @gretaneumannn ,

wir würden das dann gemeinsam über den Designer umsetzen.

Lasst uns bitte mal einen Call für den Abgleich des Styleguides planen.

**Comment by gretaneumannn** [comment]
Hallo Martin, hallo Christian,

wir haben besprochen, dass ich zunächst die Komponenten abgleiche und eine Liste derer anlege, die angepasst werden müssen. Am besten wir schauen dann gemeinsam nach einem Termin in der nächsten Woche oder vielleicht diesen Freitag?

Lieben Gruß
Greta

**Comment by Chrisdo82** [comment]
@deleonio Ticket kann geschlossen werden
