### ISSUE TITLE
kol-button-wc _iconOnly: click gets registered by <kol-span-wc>, not <button>

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#2771]
If the <button> (inside <kol-button>) is disabled (via "_disabled") Chromium browsers still propagate onClick events from elements inside the <button>.
This triggers onClick events on <kol-button>.
Handler set via _on: { onclick: function } do work as intended.
![Image](https://user-images.githubusercontent.com/117265922/227179649-ab59e392-1eb5-499b-8762-ea34dafdf8a3.png)

**Comment by deleonio** [comment]
@Wolfram-Zell haben wir das nicht gestern mit behoben?

**Comment by Wolfram-Zell** [comment]
> @Wolfram-Zell haben wir das nicht gestern mit behoben?

Exakt.
