### ISSUE TITLE
Dauerthema: Vereinheitlichung aller Attribute/Properties

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#2813]
Wir wollen, dass alle Properties eindeutig über alle Components sind.

Hierzu erfolgt eine Vereinheitlichung semantisch gleicher Properties, deren Typen und Beschreibungen. Properties die dadurch abgelöst werden, werden in Version 1 als `@deprecated` markiert.

Arbeitsschritte
- [ ] Erstellen einer Markdown-Datei (DE, EN) in der Website unter Konzepte "Propteries" (https://github.com/public-ui/public-ui.github.io/tree/main/dev/docs/20-concepts) - https://github.com/public-ui/kolibri/issues/2813
- [ ] Einfügen der vereinheitlichten Properties in den Componenten
- [ ] Sicherstellung der Abwärtskompatibilität durch Weiterleiten auf neue Properties und deren Validatoren

Attribute umbenennen:
- [ ] _list: bei meisten inputs ist das eine Liste von Vorschlägen für die Autovervollständigung, bei Radio und Select eine Liste der Optionen.
- [ ] _value & _checked bei Checkboxen ?

Gerne kannst Du hier verbesserte Beschreibungen einpflegen.
Nutze `node scripts/cheat-sheet.js`

## Current properties

See https://public-ui.github.io/docs/concepts/properties

**Comment by Wolfram-Zell** [comment]
[AttributeName] ist der Typ des Attributs, 
Prop[AttributName] ist ein Typ der das Attribut enthält.
Verwendung:
```ts
type State = Prop[AttributeName1] & {
  attribute2: [AttributeName2];
}
```

**Comment by Wolfram-Zell** [comment]
@deleonio Plan hier mal ne Stunde oder so ein, das sind viele Punkte, die ich nicht (alleine) entscheiden kann.
