### ISSUE TITLE
🐞 Bug: Modale können initial nicht geöffnet werden

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#2817]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Wenn ich dem KolModal ein `_activeElement` mitgebe, erwarte ich, dass dieses initial beim Seitenaufruf geöffnet wird. Dies funktioniert aber nur, wenn ich die Seite schon vorgeladen habe und KoliBri bereits vollständig initialisiert wurde. Wenn ich aber die Seite initial aufrufe, dann wird das Modal nicht geöffnet. Erst wenn ich die Komponente neu render, dann funktioniet es.

Ich denke das Video unter Reproduktion verdeutlicht dieses Verhalten.

## Reproduktion

https://user-images.githubusercontent.com/6606913/228500343-ae9a8893-be1f-4044-8dbf-d27de52cb4ec.mov

- Link zu CodeSandbox: https://codesandbox.io/s/throbbing-forest-dywwch?file=/src/App.tsx

Schritte zum Reproduzieren des Verhaltens:
- Öffne bereitgestellte CodeSandbox
-> Das Modal wird nicht geöffnet
- Bearbeite nun im linken Bereich den Code, passe z.B. den String in Zeile 6 an
-> das Modal wird geöffnet
- per Reload kann das Verhalten jederzeit wieder reproduziert werden

## Erwartetes Verhalten
Das Modal wird geöffnet, wenn `_activeElement` bereitgestellt wird, ganz egal unter welchen Umständen es gerendert wurde.

**Comment by deleonio** [comment]
Hi @Chrisdo82 , Danke für das Finding. Wir schauen es uns an.

**Comment by Wolfram-Zell** [comment]
@Chrisdo82 
Den Bug konnte ich reproduzieren, aber leider _noch_ nicht beheben, hilft dir der Workaround auch _show zu setzen?

**Comment by Chrisdo82** [comment]
Hi @Wolfram-Zell, der Workaround hilft. Danke.

**Comment by Wolfram-Zell** [comment]
Behoben in Version 1.5.0-rc9.
In Versionen davor muss `_show` und `_activeElement` gesetzt werden. (und am besten auch beim Schließen beides zurücksetzen)
Ab Version 1.5.0-rc9 muss beim Schließen `_activeElement` auf `null` gesetzt werden, wer das jetzt schon so macht, für den wird es auch weiterhin funktionieren.
