### ISSUE TITLE
🛹 Feature: Google Material Icon Family mit aufnehmen

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#2873]
Version: Rounded (fill und nicht fill)

- https://github.com/google/material-design-icons
- https://fonts.google.com/icons?icon.style=Rounded
- https://github.com/marella/material-symbols/blob/main/material-symbols/rounded.css

**Comment by gretaneumannn** [comment]
Fontdatei: https://developers.google.com/fonts/docs/material_symbols?hl=de

**Comment by deleonio** [comment]
@gretaneumannn Done . siehe Designer - Code: https://github.com/public-ui/kolibri/tree/main/packages/designer/public/assets
