### ISSUE TITLE
🛹 Feature: Tooltip bei kol-input ohne Label

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#2874]
Bei allen Eingabefeldern und Aktionselementen ohne Label, soll ein Tooltip erstellt werden.
Wenn Pflichtfeld, dann Stern in Tooltip.

**Comment by deleonio** [comment]
![image](https://github.com/public-ui/kolibri/assets/6279703/770f1fc7-9439-476c-bf00-7620fea46b7a)

**Comment by deleonio** [comment]
Siehe https://github.com/public-ui/kolibri/issues/4413
