### ISSUE TITLE
[FEAT] Nav Expanded-Buttons add (aria-controls)

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#2949]
- [ ] expanded regions mit nonce ids versehen (`id`)
- [ ] expanded buttons mit den jeweiligen nonce ids der regions versehen (`aria-controls`)

**Comment by Wolfram-Zell** [comment]
Wie ist hier der Status? Was fehlt, was muss anders? Kann das geschlossen werden?

**Comment by deleonio** [comment]
@ElVariablo kannst du das bitte reviewn: https://github.com/public-ui/kolibri/blob/feature/aria-control-f%C3%BCr-nav-compact-button/packages/components/src/components/nav/component.tsx
