### ISSUE TITLE
🛹 Feature: Cycle und Linear Spinner

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#3003]
Es besteht zu dem Spinner Bedarf an einem Cycle und Linear Spinner. Beide Komponenten sollen mit und ohne Beschreibung zur Verfügung gestellt werden. Die Animation kann an folgende Animation angelehnt werden: https://codepen.io/tamedia/pen/vLzxKW mit dem CSS Code (Kommentar).

**Cycle Spinner:**
![image](https://user-images.githubusercontent.com/118734593/233133232-f3b3a66c-f51c-418c-97f1-57dde1d7d93a.png)
![image](https://user-images.githubusercontent.com/118734593/233133254-298e1d3e-57bf-49e5-85b1-0e620b7b268b.png)

**Linear Spinner:**
![image](https://user-images.githubusercontent.com/118734593/233133300-ff0f1080-2857-4a56-a44f-57bbfd41e3c7.png)

**Comment by gretaneumannn** [comment]
Für die Animation sollte folgender Part des CSS-Codes angepasst werden:

.loader__spinner {
  border: 10px solid #CCE4F0;
  border-left: 10px solid #004B76;
  transform: translateZ(0);
    animation: spinner 1.5s infinite cubic-bezier(0.7, 0.3, 0.4, 0.6);
  border-radius: 50%;
  width: 100px;
  height: 100px;
}

**Comment by deleonio** [comment]
Siehe: https://github.com/public-ui/kolibri/pull/3147

**Comment by deleonio** [comment]
@Chrisdo82 : beliebige Spinner mit 1.5.2 möglich

https://public-ui.github.io/docs/components/spin#beispiel

**Comment by Chrisdo82** [comment]
@deleonio Ticket kann geschlossen werden

**Comment by deleonio** [comment]
Ticket kann mit Rücksprache mit dem Team geschlossen werden.
