### ISSUE TITLE
🛹 Feature: Halbkreis als Progress Cycle aufnehmen

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#3004]
Die Cycle Komponente sollte auch als Halbkreis mit Prozesswert und optionaler Beschreibung dargestellt werden.

![image](https://user-images.githubusercontent.com/118734593/233135158-bbe9e75f-ce19-425c-b9a8-b1b50ab19866.png)

**Comment by deleonio** [comment]
Hallo @gretaneumannn und @Chrisdo82 ,

ich denke, dieses neue Feature wäre ganz gut bei Euch aufgehoben.

Die Erweiterung um die Textanzeige machen wir.

**Comment by deleonio** [comment]
In Rücksprache mit dem Team geschlossen.
