### ISSUE TITLE
Nav: Horizontal - wenn die Breite nicht ausreicht -> Bürger-Menü

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3044]
Like: https://ec.europa.eu/component-library/ec/components/navigation/menu/code/

Die Menü-Punkte, die horizontal dargestellt sind, im Bürgermenü dann die MenüPunkte unter einander.

![Image](https://user-images.githubusercontent.com/6279703/235118613-67173b84-4cfc-4d1c-800b-5b1d801d1e06.png)

![Image](https://user-images.githubusercontent.com/6279703/235118698-5594a4b4-e6a0-475a-ba99-9e695d410c62.png)

Bürger-Button-Position sollte via CSS ausgerichtet werden können. Default ist rechts oben. Recht unten.

**Comment by Wolfram-Zell** [comment]
- [x] create mobile menu
- [x] create hamburger button to open/close
- [x] make switching available via prop

**Comment by deleonio** [comment]
- [ ] Bitte nach Lösungsvarianten schauen und Feedback geben

**Comment by sdvg** [comment]
Ansätze zum Umschalten zwischen regulärer und Burger-Navigation:

1) Vollautomatisch: Wenn die Breite nicht mehr ausreicht um die Navigation einzeilig zu rendern, wird zum Burger-Menu umgebrochen
    - zweizeilige Navigationselemente scheinen aktuell aber explizit unterstützt zu sein
2) boolean Attribut zum Umschalten (Projekt weiß ggf. am besten bis zu welcher Breite die reguläre Nav funktioniert): `_use-burger-menu="true|false"`
3) Attribut um einen media query zu übergeben, z.B. `_burger-menu-breakpoint="(max-width: 768px)"`
    - Sobald der media query "matched", wird das Burger-Menu verwendet.
    - Kann ebenfalls vom Projekt, produktspezifisch, konfiguriert werden, die Logik ist aber in der Komponente versteckt.


Zur Umsetzung vom Burger Menu:

- Wenn im burger modus: Kann die reguläre Nav mit `_orientation="vertical"` verwendet werden?
   - Womöglich die einfachste Variante 
    - Das [EU Menu](https://ec.europa.eu/component-library/ec/components/navigation/menu/code/) hat eine komplexere Struktur

Falls die reguläre- und die Burger-Nav sich stark unterscheiden, könnte sich folgende Struktur anbieten:

```
<kol-nav>
  {burger-menu
    ? <kol-nav-burger-wc></kol-nav-burger-wc>
    : <kol-nav-regular-wc></kol-nav-regular-wc>
  }
</kol-nav>

```
(Pseudo-Code zur Veranschaulichung)
