### ISSUE TITLE
🛹 Feature: TypeScript Theme Patch generierten Code von Applikation trennen

### ISSUE THREAD

**Issue by cyrdam** [public-ui/kolibri#3059]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Das generieren der Theme Patches kann in manchen Fällen tauende Zeilen beinhalten, was z.B. die react.main.tsx Datei sehr aufbläht. Zusätzlich sind Anpassungen nötig, wenn man die Ausgabe kopiert: z.B. die React Komponente muss zum rendern in den Code eingefügt werden.

## Beschreiben Sie die gewünschte Lösung
Das erstellte TypeScript Dokument könnte unabhängig sein, indem es einen Export bietet, den man dann nutzt und in der `react.main.tsx` importiert, um dort die Komponenten einzubauen.

In dem Fall könnte der Export so aussehen:

```typescript
// theme.ts
export default register(/* theme aus package */)
  .then(() => {
    // patch theme
})
  .catch(console.warn);

// react.main.tsx
import themePatch from './theme';
// ...

themePatch.then(() => {
  // react component part
}).catch(console.warn);
```

Alternative: eine Funktion zur Verfügung stellen, die alle Eingaben vereint, ohne dass man in der themePatch Datei register verwendet:

```typescript
// themes.ts
export default registerWithPatch({ // args als Objekt, reihenfolge der args muss nicht mehr beachtet werden
  themes: Theme,
  loaders: Loader,
  options: {}, // RegisterOptions
  patchTheme: {
    // theme patch
  },
});

// react.main.tsx
import themePatch from './theme';
// ...

themePatch.then(() => {
  // react component part
}).catch(console.warn);

// catch kann auch hier noch vor der React componente abgefangen werden, falls nötig:
themePatch.catch(console.warn)
  .then(() => {
    // react component part
  }).catch(console.warn);
```

Optional: Falls das Theme eine Ableitung eines bereits vorhandenen wäre, so könnte man den Namen vielleicht aus dem Theme Package einbeziehen.

**Comment by deleonio** [comment]
Ziel der Themes sind zentral bereitgestellt Styles für die Komponenten über beliebig viele Projekte unverändert teilen zu können.

Das Patchen dient der punktuellen Anpassung, falls Neuerungen eingearbeitet werden oder ggf. mal was gepatched werden muss. Bei der Verwendung der Patch-Methode ist es möglich auch nur eine Komponente zu patchen.

**Comment by cyrdam** [comment]
Das ist korrekt, mein Vorschlag ändert auch daran nichts.

Mein Vorschlag ist eine Datei erzeugen zu können, die dann einen Export hat, um den Patch zu verwenden, ohne dass man viele Anpassungen machen muss. Damit kommt eine Trennung zwischen Theme Patch als eigenständige Funktion und das Rendern der Komponenten zustande.

Die vorgeschlagene Funktion mit Patch ist eher eine Abkürzung, um das Promise nicht komplett ausschreiben zu müssen. Natürlich könnte man das auch selbst machen, wäre aber eine hilfreiche Funktion innerhalb der Bibliothek, und nicht besonders aufwändig.
