### ISSUE TITLE
kol-button: icon should be centered by default, width should not be 100%

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#3060]
An _icon-only kol-button should be 44*44 and the icon should be centered.

![Image](https://user-images.githubusercontent.com/117265922/235654685-ac66aa0f-e4a4-4f57-a22a-b12feb8c718d.png)

**Comment by deleonio** [comment]
This could become part of the basic style.

**Comment by deleonio** [comment]
Buttons sind 100% breit.

KolButton inline-block vs block

**Comment by deleonio** [comment]
Dass sich die Komponenten ausdehnen, ist schon immer so - und beabsichtigt. Das `inline`-Setzen kann von außen am Component-Tag erfolgen.
