### ISSUE TITLE
Live-Editor: Code-Formatierung

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#3079]
Die Code-Ansicht ist noch nicht optimal und es wäre schöner, wenn wir den Code halbwegs formatiert anzeigen könnten.

![Image](https://user-images.githubusercontent.com/6279703/236985885-f80e6c67-0928-4fc4-9724-051187b827e3.png)

**Comment by deleonio** [comment]
https://github.com/siemens/ix/blob/16007310ac4abda72b9c36c30c42073250d0d708/packages/documentation/src/pages/index.tsx#L691

https://github.com/public-ui/public-ui.github.io/blob/c4d13be79f97da01b3a2b0ac9f43489b0a939554/dev/src/components/LiveEditorCompact/CodeOutput.tsx#L68
