### ISSUE TITLE
Release 2 vorbereiten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3108]
README schreiben.

- Alle Deprecated entfernen und Protokollieren. (Nachricht beachten)
- Neue Properties muss in V2 required werden (z. B. `_label`)
- TODOs beachten, die für die V2 relevant sind
- Migration in eienen Projekten selbst durchführen (z. B. Designer, Sample-App, Website)

**Comment by sdvg** [comment]
Offene Fragen:

- `ariaControls` und `ariaExpanded` prop types sind als deprecated, markiert, werden aber in kol-button verwendet - `@deprecated`-Markierung entfernen?
- Die Modal-Komponente ist als deprecated markiert, wird laut Readme in der Version 2 aber noch unterstützt. Was ist der weitere Plan für die Komponente?
