### ISSUE TITLE
🛹 Feature: Designer um mehr Beispiele erweitern

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#3113]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Im Designer fehlen einige Beispiele. Um das Styling für diese Beispiele anzupassen, muss jedesmal das Attribut mühselig manuell über dem DOM hinzugefügt werden. 

## Beschreiben Sie die gewünschte Lösung
An folgenden Stellen ist es mir besonders aufgefallen, es gibt aber sicherlich viel mehr:

- KolSelect
  - [x] Beispiel mit _disabled fehlt
  - [x] Beispiel ohne Icons fehlt
- KolToast
  - [ ] die Toasts sollten nicht automatisch zu gehen, ansonsten ist es sehr sehr schwer diese zu stylen
  - [ ] mehr Möglichkeiten bieten um unterschiedliche Varianten manuell zu öffnen
- KolNav
  - [x] Beispiel mit `selected` fehlt

**Comment by deleonio** [comment]
Ticket kann mit Rücksprache mit dem Team geschlossen werden.
