### ISSUE TITLE
🛹 Feature: KolNav: CSS-Klasse für _compact Modus hinzufügen

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#3114]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Um die einzelnen Listenelemente der KolNav im kompakten Modus zu stylen, muss ich folgenden Selector verwenden: `.entry.text-center`. Das `text-center` ist soweit ich weiß derzeit die einzige Möglichkeit, um ein separates Styling zu erreichen.

## Beschreiben Sie die gewünschte Lösung
Eine eigene CSS-Klasse für den kompakten Modus hinzufügen.

**Comment by deleonio** [comment]
Hallo @Chrisdo82 ,

vielen Dank für den Hinweis. `text-center` ist eine Tailwind-Klasse, die wir nicht mehr verwenden. Diese CSS-Klasse muss in der Nav durchgehen durch `compact` ersetzt werden.

- [ ] Variable `textCenter ` durch `compact` ersetzen
- [ ] überflüssige Verwendung der Variable `compact` entfernen
- [ ] CSS-Klasse `text-center` durch `compact` ersetzen
- [ ] Verwendung der CSS-Klasse `text-center` im kompletten Theme-Paket und somit alles Themes gegen `compact` ersetzen

**Comment by deleonio** [comment]
@Chrisdo82 ist in 1.5.3 enthalten.
