### ISSUE TITLE
📖 Help: KolProgress - wie kann ich den SVG Tag für `bar` und `cycle` separat ansprechen?

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#3115]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

> _Beschreiben Sie möglichst genau, wobei wir Ihnen helfen können._
Ich würde gerne den SVG-Tag per CSS-Selector ansprechen können, abhängig davon welchen `_type` ich zuvor ausgewählt habe. Im speziellen möchte ich dem `cycle` gerne eine andere Höhe und Breite mitgeben. Ich fände es gut, wenn ich dies per CSS-Klasse tun könnte.

**Comment by deleonio** [comment]
Hallo @Chrisdo82 ,

gerne können wir die `_variant` (`_type`) als CSS-Klasse um die Grafik angeben, um die Gestaltbarkeit zu verbessern.

Zeilen:
- https://github.com/public-ui/kolibri/blob/7926af2d57871b9074a36ca25b084b414ccea11d/packages/components/src/components/progress/component.tsx#L56
- https://github.com/public-ui/kolibri/blob/7926af2d57871b9074a36ca25b084b414ccea11d/packages/components/src/components/progress/component.tsx#L29
