### ISSUE TITLE
🐞 Bug: KolInputPassword - onChange-Methode feuert nicht nach jedem Tastendruck

### ISSUE THREAD

**Issue by Zementaa** [public-ui/kolibri#3121]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Die onChange-Methode des KolInputPassword feuert nicht nach jedem Tastendruck, sondern erst nachdem der Eingabefokus nicht mehr auf dem KolInputPassword-Feld liegt.

## Reproduktion

- Link zu CodeSandbox: https://codesandbox.io/s/frosty-wiles-26e8bc?file=/src/App.tsx

Schritte zum Reproduzieren des Verhaltens:
- Konsole öffnen
- Eingabe ins KolInputPassword-Feld tätigen
- Eingabefeld verlassen 

## Erwartetes Verhalten
Nach jedem Tastendruck sollte eine Konsolenausgabe getriggert werden.

## Desktop
- Betriebssystem: Windows
- Browser: Chrome
- Version: 112.0.5615.50

**Comment by deleonio** [comment]
Danke @Zementaa, wir haben den Fehler schon gefunden und gefixed. Die Wert-Rückgabe wird mit den Release 1.5.1 wieder funktionieren.
