### ISSUE TITLE
BUG: Input-Styling lässt sich nicht mehr beliebig schmal machen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3127]
Die nicht deaktivierten Eingabefelder sollen sich verhalten, wie das deaktivierte Eingabefeld.

Hier exemplarisch vom BMF-Theme.

Link: https://public-ui.github.io/docs/components/input-text#beispiel

![Image](https://user-images.githubusercontent.com/6279703/238581943-6166bfb6-7e57-4cf0-aa70-e6f7822a73bf.png)

**Comment by deleonio** [comment]
Ticket - @Chrisdo82

**Comment by Wolfram-Zell** [comment]
<inputs> haben eine eigene min-width von 155px, diese muss überschrieben werden.
