### ISSUE TITLE
Feature: ScreenReader (NVDA)  KolButton _iconOnly 

### ISSUE THREAD

**Issue by eugen-cc** [public-ui/kolibri#3139]
> **Note**
> - [x ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung
Button mit _iconOnly wird vom Screenreader bei MouseOver nicht vorgelesen. 
Alle Attribute _label , _aria-label und aria-label sind gesetzt. Mit Tab-Navigation funktioniert es dann.

## Reproduktion
Getestet mit NVDA ScreenReader.

Schritte zum Reproduzieren des Verhaltens:
Erstelle zwei KolButtons. Einer mit Label , einer mit Label, aria-label etc und _iconOnly Attribut.

Fahre mit der Maus drüber. Der Button mit _iconOnly wird nicht vorgelesen. Der andere schon.
Nutzt man den Tabulator, so werden dann beide vorgelesen.

## Erwartetes Verhalten
_iconOnly Button sollte auch bei MouseOver vorgelesen werden.

**Comment by deleonio** [comment]
Hi @eugen-cc,

ich glaube diese Anforderung haben wir noch nicht umgesetzt. Super Hinweis!

**Comment by ElVariablo** [comment]
Hallo @eugen-cc, 

Screenreader werden im Normalfall von Blinden Menschen oder Menschen mit einem sehr geringen Rest Sehvermögen genutzt. Diese können die Maus nicht nutzen und sind ausschließlich Tastaturnutzende. Auf diese Nutzung sind Screenreader ausgelegt. Daher kann bzw. muss bei einem MouseOver keine Screenreader Ausgabe erfolgen. 

Bei Rückfragen gerne melden.
