### ISSUE TITLE
🐞 Bug: Modal wertet die _width nicht mehr aus

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#3158]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Die `_width` wird vom Modal nicht ausgewertet. Dies kann auch schon im Designer nachvollzogen werden, dort ist eine Breite von 80% hinterlegt die aber nicht angewendet wird. Daher habe ich jetzt mal keine Codesandbox erstellt.

@deleonio meinte ich solle dass an dich @Wolfram-Zell adressieren.

**Comment by deleonio** [comment]
@Chrisdo82 Bitte jetzt mit v1.5.3 nachtesten. Danke
