### ISSUE TITLE
_label Property konsequent als Bezeichnung umsetzen

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#3174]
- [x] Abbr - `_label` und `Expert-Slot` einführen
<s>- [ ] Table - `_caption` deprecaten durch `_label` ersetzen</s>
<s>- [ ] Detail - `_summary` deprecaten durch `_label` ersetzen</s>

**Comment by deleonio** [comment]
https://public-ui.github.io/docs/concepts/properties
