### ISSUE TITLE
🐞 Bug: [1.5.0] Browser-Schriftgröße wird nicht überall übernommen (BITV 11.7)

### ISSUE THREAD

**Issue by eugen-cc** [public-ui/kolibri#3228]
> **Note**
> - [x ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn man die Schriftgröße im Browser größer stellt, so wird das bei folgenden Komponenten nicht übernommen : Accordion (Heading) , KolCard, KolInputBox und KolLinkGroup (Heading) 

## Reproduktion

Schritte zum Reproduzieren des Verhaltens:

- Schriftgröße des Browsers ändern
  - Im Chrome: 
     - Einstellungen -> Darstellung -> Schriftgröße
  - Im Firefox:
    - Einstellungen -> Allgemein -> Schriftarten 

- Prüfe folgende Komponenten:
  - KolAccordion
  - KolCard
  - KolInputBox
  - KolLinkGroup
  
## Erwartetes Verhalten
Headings bzw. Texte der Komponenten werden mitskaliert

## Screenshots
![KolAccordion](https://github.com/public-ui/kolibri/assets/14055972/d26e7683-6c02-489c-bf7a-1694d664d9fd)
![KolCard](https://github.com/public-ui/kolibri/assets/14055972/3e3e893e-7694-4a44-b79b-4fe1d55832cb)
![KolInputRadio](https://github.com/public-ui/kolibri/assets/14055972/666a5e42-0da9-4d5b-8aec-ec25c6cd41ae)
![KolLinkGroup](https://github.com/public-ui/kolibri/assets/14055972/003ae4b4-fcde-494e-99b0-a56680ff5768)

**Comment by deleonio** [comment]
Hallo @ElVariablo, bitte nachprüfen.

**Comment by deleonio** [comment]
Hallo @eugen-cc , wurde wie beschrieben getestet?

https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/9-1-4-4-text-auf-200-vergroesserbar

**Comment by eugen-cc** [comment]
Hallo @deleonio,

es geht um Prüfschritt 11.7

https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/11-7-benutzerdefinierte-einstellungen

**Comment by deleonio** [comment]
CoP heute - Schriftgröße soll auch in den Komponenten übernommen werden. Benutzerdefinierte Einstellungen.

Wir können im A11y-Styleing `font-size: inherit` verwenden

**Comment by deleonio** [comment]
@eugen-cc

Basis-Componenten übernehmen die Font-Size.

Bitte mit v1.5.3 nachtesten und ggf. im Theme noch nachziehen.
