### ISSUE TITLE
Table - Selektieren von Tabellen-Zeilen (Auswahl) - einzeln und mehrfach

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#3295]
- [x] Die Tabelle soll um eine Checkbox-Spalte **erweitert** werden. 
- [x] _on Prop, um `onSelect` **erweitern**
- [x] Es wird ein **Callback** benötigt, der zurückgibt, welche Zeilen (`Tupel`) ausgewählt sind.
- [x] Callback liefern event und als 2 paramenter die Liste der gewählten Zeilen (`Tupel`)
- [ ] Für Checkbox `KolInputCheckbox` und für Radio `KolInputRadio` verwenden.
- [ ] `getSelection(): T[]` Methode
- [ ] Selektion beim Seitenwechsel
- [ ] Klären, was im Header steht
- [ ] Testbeispiel erstellen

Folgeticket:
- [ ] Alle auswählen weglassen
- [ ] Beispieltabelle mit „Alle selektieren“ mittels ToggleButton über der Tabelle

Anordnungsbeispiel:
![image](https://github.com/public-ui/kolibri/assets/37439758/d1cf654e-7159-4087-bb0b-f93758396e55)

~~Checkboxspalte bekommt Property-Names (analog zu den anderen Spalten). Beim Select werden die Properties genutzt und alle selektierten IDs als Array im Callback zurückgegeben.~~ `// in Überlegung`

![Image](https://user-images.githubusercontent.com/6279703/242511523-4cd7162a-6b0b-4db7-a909-553eb63ceb37.png)

## Diskussion ganze Zeile auswählen

Ganze Zeile ist kritisch, es für die Tastatur nicht gut umsetzen lässt. In der Zeile könnte es noch weiterer interaktive Elemente geben. Aria notwendig statt Semantik. Steuerung mit Pfeiltasten. Ggf. Problem bei der Tabellen-Steuerung von Screenreader.

Maus-Nutzer hat die ganze Zeile zum Klicken - Ungleichstellung zu Tastaturnutzung.

---

# Konzept

```json
[
 {
  name: Martin 
  },
  {
    name: Christian,
    selectLabel: "Christan aus Lala - 60 Jahre" // fachlich und KoliBri fordert!
  }
]
```

| [ ] | Header 1 | Header 2 (name) | Header 3 |
| --- |--- |--- |--- |
| [ ] "Zeile Martin ist ausgewählt" | - | Martin | - |
| [ ] "Zeile Christian ist ausgewählt" | - | Christian | - |

> :info:
> Es ist valide, dass die Checkbox und Radio ohne sichtbares Label ist.

**Comment by Wolfram-Zell** [comment]
NVDA testen.

**Comment by laske185** [comment]
Neue Property: `_selection`
In erster Version wird es nur eine Mehrfachauswahl mit Checkboxen geben.

Typ:
```ts
{
  label: (row: T) => string,
  selected?: (row: T) => bool
}
```

Anwendung:
```ts
<KolTable _selection={{type: "radio", label: (row) => row.name}} />
```

**Comment by laske185** [comment]
TODOs:

Offene Frage: Selektion innerhalb oder außerhalb der Tabelle managen.
Antwort: Beides

## Tabelle splitten

Stateless-Tabelle (`KolTableStateless`), die nur die Präsentation macht und per Event Sortierungsänderungen herausgibt.
Stateful-Tabelle (`KolTableStateful`), die die Stateless benutzt.
KolTableStateful auch mit KolTable alias exportieren.

Abwärtskompatibilität:
```
KolTable { // besser per doppele annotation mit component, alias, export, ...? 
  render: KolTableStateful {
    render: KolTableStateless
  }
}
```

Vielleicht geht:
```tsx
@Component({
	tag: 'kol-table',
	styleUrls: {
		default: './style.css',
	},
	shadow: true,
})
@Component({
	tag: 'kol-table-stateful',
	styleUrls: {
		default: './style.css',
	},
	shadow: true,
})
export class KolTableStateful implements API {
}
```

## Stateless erweitern um Selektion

- neues Attribut: `_selection`
- Typ: 
```ts
 {
  label: (row: T) => string,
  keyPropertyName: string, // default = `key`
  selectedKeys?: string[]
}
```
- Callback-Funktion `onSelectionChanged` und Event `onSelectionChange` gibt alle aktuell selektierten Rows (komplette Objekte) raus.
- in weiteren Iterationen könnte ein `onRowSelected` oder `onRowUnselected` hinzukommen
- Neue Spalte mit Checkboxen
  - Überschrift: erstmal ohne (wird noch im BITV-Team besprochen)
  - Die `KolInputCheckbox` nutzen

## Stateful erweitern um Selektion

- Analog Stateless: `_selection`
- Managed die Selektion intern
- Erweitern um `getSelection`-Methode

**Comment by laske185** [comment]
Umsetzung der Selektion schrittweise in separaten Tickets:
- #5858 
- #5859 
- #5860 

Daher wird dieses hier geschlossen.
