### ISSUE TITLE
Get started: Nachfrage zum Hinweis

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3296]
Ich glaube, der **Hinweis** ist nicht korrekt? Was meinst Du damit?

https://github.com/public-ui/kolibri/blob/main/docs/GET_STARTED.md#iv-ohne-framework

Antwort: 
Das hatten wir doch letztens und die Aussage war, dass man KoliBri nicht einfach durch Script-tag(s) einbinden kann.

```html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Title</title>
+    <script
+      type="module"
+      src="/node_modules/@public-ui/components/dist/kolibri/kolibri.esm.js"
+    ></script>
  </head>
  <body>
    <kol-spin _show />
  </body>
</html>
```

Edit 01.06.:
Der Link funktioniert nur mit einem Bundler. Sofern das über ein CDN beziehbar ist, bitte Link bereitstellen.

**Comment by deleonio** [comment]
Wenn du diese HTML Seite mittels eines Webservers abbildest, dann funktioniert das. Das einfach öffnen von der Platte ist kein angestrebtes Szenario.

```bash
pnpm i -g serve
serve
```

**Comment by Wolfram-Zell** [comment]
Eine statische Webseite ist ohne node modules. Alles was eingebunden werden muss, muss per CDN verfügbar sein. Dieser Link fehlt mir. (direkt von npmjs.com funktioniert nicht aufgrund von CORS)

**Comment by deleonio** [comment]
Siehe code: https://public-ui.github.io/cheat-sheet/

![image](https://github.com/public-ui/kolibri/assets/6279703/c1709ab4-303a-44ac-972a-20162399eb2e)

**Comment by Wolfram-Zell** [comment]
Bitte Tickets nicht zurück schieben, ohne einen Kommentar warum dies passiert.

**Comment by deleonio** [comment]
Ich hatte den PR kommentiert.
