### ISSUE TITLE
BITV-Prüfung: Tooltip auf Prüfschritt ↗ Prüfschritt 9.1.4.13 prüfen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3297]
↗ [Prüfschritt 9.1.4.13](https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/9-1-4-13-eingeblendete-inhalte-bedienbar) nicht zu erfüllen.

_________

-> https://github.com/public-ui/kolibri/issues/3169

**Comment by deleonio** [comment]
https://github.com/orgs/public-ui/projects/2/views/20?layout=table&filterQuery=sprint%3A%40current+-status%3A%22%E2%9C%85+Done%22&pane=issue&itemId=27719942

**Comment by ElVariablo** [comment]
Der Prüfschritt 9.1.4.13 hat drei Hauptanforderungen. Diese sind:

- Wenn zusätzliche Inhalte durch Darüberfahren mit dem Zeiger erscheinen, können Benutzer den Zeiger über diesen Inhalt bewegen, ohne dass er verschwindet.
- Es gibt die Möglichkeit, einen eingeblendeten Inhalt zu schließen, ohne den Fokus zu verschieben (z. B. durch Drücken der Escape-Taste oder durch Aktivieren des Elements, dessen Fokussierung den Inhalt einblendet).
- Der Inhalt schließt nicht selbsttätig nach einer gewissen Zeitspanne.

Diese werden in den Handout Beispielen vom [Design System Zoll V2](https://public-ui.github.io/sample-react/#/tooltip/basic?theme=zoll-v2) und vom [BMF ](https://public-ui.github.io/sample-react/#/tooltip/basic?theme=bmf) erfüllt. Daher ist dieser Prüfschritt für die Komponente Tooltip erfüllt
