### ISSUE TITLE
Live-Editor: Default-Slots fixen

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#3356]
![Image](https://user-images.githubusercontent.com/6279703/242759104-f4bf7d5c-5cf6-4e3f-bb69-bbdb7224e0ec.png)

**Comment by Wolfram-Zell** [comment]
Im custom-elements.json ist slots ein leeres Array, daher wird kein Slot angezeigt. Den Zustand aus dem Screenshot konnte ich nicht nachstellen. Generell fehlen Slots, nur für kol-accordion, kol-card und kol-split-button sind slots angegeben. 
@deleonio schaust du bitte mal nach der custom-elements.json?
![image](https://github.com/public-ui/kolibri/assets/117265922/090807ab-7fcc-4dfe-abe9-956fc2798091)

**Comment by deleonio** [comment]
Fehler gefunden - JSDoc

Falsch:
```tsx
/**
 * @slot default Der Begriff, der erläutert werden soll.
 */
```

Richtig
```tsx
/**
 * @slot default - Der Begriff, der erläutert werden soll.
 */
```
