### ISSUE TITLE
💡 Hinweis: Zielgröße der Klickfläche von Checkbox und Radiobutton (AAA Anforderung der WCAG)

### ISSUE THREAD

**Issue by ElVariablo** [public-ui/kolibri#3361]
> **Note**
> - [ X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**

> KoliBri setzt die [AAA Anforderung 2.5.5 der W3C "Zielgröße"](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) schon bei vielen Komponenten um. 
Es wäre wünschenswert, dass auch Checkbox und Radio Button diese Anforderung erfüllen da diese unter umständen ohne sichtbares Label eingesetzt werden könnten

**Comment by deleonio** [comment]
Duplikat
