### ISSUE TITLE
💡 Hinweis: Tabelle und Screenreader-Verhalten fuer Sortierung-Aendern verbessern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3365]
Wir haben die Rückmeldung, dass der Screenreader beim Ändern der Sortierung nicht korrekt vorliest.

- [x] "Sortierung geändert";
- [x] Sortier-Button: aufsteigend/absteigend

**Comment by ElVariablo** [comment]
Test erfolgte auf der Testseite v. 1.5.3 in dem Beispiel "table badge-size"

- Verhalten NVDA:
Der NVDA gibt keine Information über die Statusmeldung aus. Unabhängig davon, ob Auf- oder Absteigend sortiert wurde. Auch nach Verlassen und wieder Betreten der Zelle wird der Sortierstatus nicht ausgegeben. NVDA gibt lediglich den Tooltip aus.


- Verhalten JAWS:
JAWS gibt die Sortierung auf Englisch aus. 


- Gewünschtes Verhalten
Die Screenreader müssen den aktuellen zustand der Sortierung korrekt ausgeben und nach einem Wechsel der Sortierung direkt den neuen Zustand ausgeben.


andere Anmerkungen:
Tooltip sollte die Sortierung auch die aktuelle Sortierung wiedergeben.
Im aktuellen Beispiel befindet sich der Sortierbutton für Spalte 2 näher an spalte 3 und wird dieser somit visuell zugeordnet.  Entweder wird der Sortierbutton näher zu dem zugehörigen Header gesetzt oder die Tabellenzellen erhalten einen visuell gut sichtbaren Rahmen

**Comment by deleonio** [comment]
Wir können einen Schließenschalter anbieten, der über ein Property aktiviert werden muss und zeigen zusätzlich einen A11y-Advice in der Console an.

Im BITV-Test des Themes müssen diese Komponenten einen geschlossenen Rahmen haben.

**Comment by deleonio** [comment]
Related: https://github.com/public-ui/kolibri/issues/3436

**Comment by deleonio** [comment]
Wenn man die Sortierung der Spalte ändert, wird es nicht immer angesagt.

Wenn man die Inhalte vorlesen lässt, wird teilweise zu viel angesagt.

**Comment by ElVariablo** [comment]
Ausgabe vom NVDA im Lesemodus: 
Spalte 1  order
Spalte 2  date
Schalter    Sortierung von date ändern
_(schalter aktiviert)_
*Es folgt keine Ausgabe*

Nach der Aktivierung vom Schalter wird nicht ausgegeben, ob und in welcher Reihenfolge die Tabelle sortiert wurde. Dies soll jedoch bei jeder neuen Sortierung, ohne weitere Handlungen, ausgegeben werden.
Gewünschte Ausgabe wäre also:

Spalte 1  order
Spalte 2  date
Schalter    Sortierung von date ändern
_(Schalter aktiviert)_
Spalte 2  aufsteigend sortiert  
_(Schalter aktiviert)_
Spalte 2  absteigend sortiert  
_(Schalter aktiviert)_
Spalte 2  nicht sortiert

**Comment by deleonio** [comment]
@Wolfram-Zell schau mal, ob du daraus eine Umsetzung ableiten kannst.

**Comment by deleonio** [comment]
Hallo Sabine (@PippiViktualia), wir brauchen eine Abstimmungscall - der NVDA verhält sich komisch.

**Comment by deleonio** [comment]
1. npm run build:light
2. Verzeichnis table-nvda in static in Doku anlegen
3. cp -r www in https://github.com/public-ui/public-ui.github.io/tree/main/dev/static/table-nvda
4. commiten
5. https://public-ui.github.io/table-nvda
