### ISSUE TITLE
[BITV] Fehlermeldungen invalider Fehler bei onFokus vorlesen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3366]
Wenn eine Fehlermeldung an einem Eingabefeld schon angezeigt wird und man neu reintabt. Soll dann die Fehlermeldung vorgelesen werden?

**Comment by ElVariablo** [comment]
Fehlermeldungen müssen immer angesagt werden. Auch beim erneuten Betreten des fehlerhaften Feldes.

**Comment by deleonio** [comment]
Bitte mal testen - wir müssen nachprüfen, ob das bei uns schon geht.

**Comment by cbraehmig** [comment]
Auf dem Handout-Seite getestet, Fehlermeldung wird auch beim wiederholten Fokussieren ausgegeben.

**Comment by cbraehmig** [comment]
Ich setze es auf erledigt.
