### ISSUE TITLE
🛹 Feature: Alert und Card standardmäßig ein Schließen-Schalter anbieten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3403]
Alerts und Cards werden auch als schließbare Elemente verwendet. Der Schließen-Schalter rechts-oben war aktuell immer als nicht barrierefrei angesehen worden. Wir sollten überlegen, ob wir mit einer semantischen Sektion und weiteren Auszeichnungen doch dieses Feature anbieten können.

FYI: @Chrisdo82

**Comment by deleonio** [comment]
Bei diesem Thema gibt es das Problem der ggf. fehlenden Rahmen beim eingeschränkten Sichtfeld.

![image](https://github.com/public-ui/kolibri/assets/6279703/529bd4ea-6c2d-47a2-80cd-0d878d50c488)

**Comment by ElVariablo** [comment]
Alerts sind unproblematisch sofern sie eine deutlich wahrnehmbare Begrenzung zum Hintergrund haben (Border nicht Schattierung mit einem Kontrast von mind. 3:1). Es ist erwartungskonform, dass diese geschlossen werden können und dass sich ein Schließen Mechanismus rechts oben befindet. 

Bei dem Card Element ist es nicht erwartungskonform, dass dieses geschlossen werden kann. Wie würde ein "öffnen" Mechanismus hier aussehen? 
Die Frage ist, ob eine Card das semantisch richtige Element ist. Wenn es eine Vorschau geben soll, oder die Möglichkeit Inhalte zu "verstecken" bzw. "auszublenden" könnte die Accordion Komponente genutzt werden. Der dauerhaft sichtbare Teil kann ähnlich wie eine Card Komponente dargestellt werden und Inhalte die ausgeblendet werden sollen dann im Accordion body angezeigt werden.

**Comment by deleonio** [comment]
Wir können einen Schließenschalter anbieten, der über ein Property aktiviert werden muss und zeigen zusätzlich einen A11y-Advice in der Console an.

Hinweisetext: Das Styling muss aus Barrierefreiheitsgründen einen geschlossenen Rahmen haben, damit Menschen mit eingeschränkten Sichtfeld den Rand folgen können.

Technische Doku inside *.tsx English

**Comment by deleonio** [comment]
Die Card wird häufig als Dialog verwendet.

![Image](https://github.com/public-ui/kolibri/assets/6279703/28c5a8f4-fd01-4d25-8fcb-536bdc3ccb2c)

**Comment by deleonio** [comment]
Schließen-Button, analog zum Alert umsetzen. `_hasCloser`- und `_on`-Property dazu einführen.
