### ISSUE TITLE
🐞 Leanup-Bug: Datumsfeld schnelle Eingaben

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3406]
Datumsfeld übernimmt schnelle Eingaben nicht immer.

- https://codesandbox.io/s/public-ui-kolibri-reproduction-input-date-forked-5i2suc?file=/src/LeanupForm.tsx

![image](https://github.com/public-ui/kolibri/assets/6279703/c777d57b-db56-42e6-917d-2d9517dae167)

Reproduktion:
- Leere Datumsfelder
- Reinklicken
- Schnelle Eingabe
- ohne Leanup, kein Fehler
- mit Leanup, tritt der Fehler auf

**Comment by deleonio** [comment]
Workaround: Wenn das Datum vorbelegt wird, dann tritt der Fehler nicht mehr auf.

 https://codesandbox.io/s/public-ui-kolibri-reproduction-input-date-forked-5i2suc?file=/src/LeanupForm.tsx

> Ticket wird trotzdem weiter bearbeitet.

**Comment by Wolfram-Zell** [comment]
Ich kann kein Fehlverhalten der KoliBrikomponente feststellen. Sofern es tatsächlich ein Fehler in KoliBri ist, bitte ein Reproduktionsbeispiel, bei dem das Fehlverhalten der Komponente bewiesen werden kann erstellen und neues Ticket aufmachen.
Hinweis: für Daten ist die Komponente kol-input-date vorgesehen.
Hinweis2: kol-input-date liefert einen leeren String, bis in Tag, Monat und Jahr mindestens eine Ziffer eingetragen ist.
