### ISSUE TITLE
🛹 Feature: Scrollbar oben statt unten in der Tabelle

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3436]
Ideen
- http://jsfiddle.net/up82z6vk/15/, nur CSS
- https://jsfiddle.net/TBnqw/, JavaScript- und CSS-Trick

**Comment by laske185** [comment]
Was wollen wir damit erreichen?

![Image](https://github.com/public-ui/kolibri/assets/37439758/1054d723-afbe-4dc7-bd3c-1ff571f42469)

```html
<div class="table" tabindex="-1" style="transform: rotateX(180deg);">
  <table style="transform: rotateX(180deg);min-width: 600px;">
  </table>
</div>
```
