### ISSUE TITLE
Logo-Komponente verstecken

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3452]
Die Logo-Komponente sollte auf lange Sicht in eine eigene Lib verschoben und in einem internen Git-Repo verwaltet werden. Als ersten Schritt soll diese öffentlich nicht mehr so präsent sein.

Akzeptanzkriterien:

- [x] Logo ist aus der Sample-App entfernt
- [x] Logo ist aus Doku entfernt
- [x] Komponente ist deprecated

**Comment by sdvg** [comment]
Hier gibt es noch ein zweites PR, für die Docs: https://github.com/public-ui/public-ui.github.io/pull/210
