### ISSUE TITLE
Vereinheitlichung Properties: Prüfen welche Typen vereinheitlicht werden können

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3503]
Siehe: https://public-ui.github.io/docs/concepts/properties

**Comment by laske185** [comment]
Property `_list`:
- `input-number`: Kommentar in "Gibt die Liste der Vorschlagswerte an."
- "Gibt die Liste der Vorschlagswörter an." in "Gibt die Liste der Vorschlagswerte an." ändern.
- `input-range`: typ könnte auch einfach `number[]` statt `Option<number>` sein
- Typen passen in Doku nicht. Sind immer `string[]`, außer bei `input-range`

Am besten sollte es gesplittet werden in `suggestions` (text, color, number, date, ...) und `options` (select, radio), da `list` nicht aussagekräftig ist (auch wenn es beim HTML inputs so benannt ist).

**Comment by laske185** [comment]
Property `_size`:
- `select`: umbenennen in `_visible-options`
- bei den inputs passt es
    - eher auf depricated stellen, da es über CSS gesteuert wird

**Comment by laske185** [comment]
`_icon: string` ist die Property der Icon-Komponente selbst. Muss also bleiben.

**Comment by laske185** [comment]
`_links`:

- Breadcrump: Umstellung auf neue interne Komponente Button-Link-Text-Switch geplant
- LinkGroup: ist deprecated
- SkipNav: Umstellung ergibt keinen Sinn, da es immer nur Links und keine Buttons oder Texte sind

**Comment by laske185** [comment]
`_min` Text bei Progressbar an `_max` anpassen
