### ISSUE TITLE
Button: Value wird nicht an button gesetzt

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3505]
Einmal das Value-Handling prüfen. Der `value` soll auch am nativen Input gesetzt werden.

```html
<kol-button _label="Test" _value="5" />

```

![Image](https://user-images.githubusercontent.com/6279703/244659932-1a972698-2379-4d32-8308-3e1677036691.png)

**Comment by Wolfram-Zell** [comment]
Liegt vermutlich an `Stringified<unknown>`, das ist der einzige Unterschied den ich zu _id sehe.
_value ist im render der shadow schon undefined.

**Comment by deleonio** [comment]
Wusste Ihr (@Wolfram-Zell, @laske185), dass der Button vom Input (`type="button"`) abstammt und deshalb als Input verstanden wird. Der Value eines Buttons, Input (`type="button"`) wird mit gesendet.

**Comment by deleonio** [comment]
Wird mit diesem Ticket bearbeitet: https://github.com/public-ui/kolibri/issues/3968
