### ISSUE TITLE
🐞 Bug: Radio-Inputs müssen unterschiedliche Slot-Namen bekommen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3514]
Es kann zu Darstellungsfehlern kommen, wenn der `input`-Slot mehrfach vorkommt und nicht richtig zugeordnet werden kann. Das Problem kann nur beim InputRadio auftreten, weil sie als einzige Komponente mehrere Inputs haben kann.

![image](https://github.com/public-ui/kolibri/assets/6279703/6acce865-1405-4845-9ce0-9a841420dd78)

Damit das geht, muss jedes Input einen eigenen Slot-Namen innerhalb der InputRadio-Komponente bekommen.

- [x] KolInput um ein internes Property (`@internal`) `_slot-name` erweitern.
- [x] `_slot-name` wird an die die `<slot name="..."/>` im KolInput für das Eingabefeld gesetzt
- [x] `_slot-name` in KolInputRadio wiederverwenden und die Slots so unterschiedliche Namen geben

**Comment by Wolfram-Zell** [comment]
Jeder Slotname muss im kol-input bekannt sein. Wir könnten die durchnummerieren, aber wie viele sind genug? 10/20/50/100?
Vielleicht ist es eine Alternative ein kol-input-radio-button-wc zu erstellen, und diesen zu verwenden?
