### ISSUE TITLE
InputRange: Werteanzeige als input-number einfügen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3515]
- [x] native Input `type="number"` hinter das native Input `type="range"` (via CSS vertauschbar)
- [x] werte synchonisieren 
- [x] 1 label - 2 input richtig label ansagen
<s>- [ ] Events werden nur vom Number Input nach außen propagated (onChange)</s>
- [x] onChange wird bei Klick auf Range, sowohl als Änderungen im Eingabefeld aufgerufen (value berücksichtigt _min/_max)

Code-Vorlage

```tsx
<label for="price" id="label">Price-Limit</label>
<div>
<input tabindex="-1" aria-labelledby="label" type="range" />
<input type="number" id="price" name="price" />
</div>
```
Edit Wolfram: veralteten Text entfernt.

**Comment by deleonio** [comment]
https://www.frontendplanet.com/css-range-slider-examples/ ?!

**Comment by Wolfram-Zell** [comment]
<s>Ich sehe hier drei unterschiedliche Dinge:
1) "Werteanzeige ggf. über Slider-Dot"
2) `<output>`
3) das Aneinanderreihen zweier Elemente und deren Synchronisation<br>
Bitte klarstellen, was das Ziel dieses Tickets ist und ggf. weitere Tickets für andere Punkte erstellen.</s>
