### ISSUE TITLE
Nav: Auf- und Zuklappen: aria-expanded überprüfen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3516]
`aria-expanded` ist falsch rum gesetzt.

![Image](https://user-images.githubusercontent.com/6279703/245061539-770f228d-fbde-4907-8cf6-a85b21aacdbd.png)

**Comment by weingardt** [comment]
In welcher KoliBri-Version ist geplant, diesen Fix auszuliefern?
