### ISSUE TITLE
Refactoring: Synchronisation von _aria-label und _label entfernen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3518]
Das geht erst nach folgenden Ticket: https://github.com/public-ui/kolibri/issues/3517

- [ ] Folgende Methode entfernen: https://github.com/public-ui/kolibri/blob/2cb9632d5cf47e1fe484a2ad455136fab5bf1645/packages/components/src/types/props/label.ts#L83
- [ ] Verwendung zurückbauen
- [ ] ariaLabel entfernen
  - [ ] @Prop
  - [ ] @Watch
  - [ ] componentWillLoad()
- [ ] label Pflicht machen
  - [ ] types
  - [ ] @Prop
  - [ ] default im state setzen/überprüfen

**Comment by Wolfram-Zell** [comment]
<s>#3517 ist nicht in diesem Sprint.</s>
