### ISSUE TITLE
Reduced-Motion: Accordion auf-/zuklappen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3528]
Wie beim Spin im CSS eine halb so schnelle Animation unter `reduce-motion` einbauen.

Normal: `0.5s`
Reduced: `0s`

- Was ist, wenn das Accordion sehr viel Inhalt hat?!

Siehe: https://github.com/public-ui/kolibri/blob/8edb9ecfad57f2accb82d6692ecf72c6588974d5/packages/components/src/components/spin/dot.css#L63

**Comment by Wolfram-Zell** [comment]
Das gezeigte Beispiel und der Spin sind konstante Animationen, das Auf-/Zuklappen des Akkordeons ist eine einmalige Animation und somit nicht vergleichbar.
