### ISSUE TITLE
🐞 Bug: NavBar - Tooltip geht verloren

### ISSUE THREAD

**Issue by eugen-cc** [public-ui/kolibri#3529]
> **Note**
> - [ x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung
Wenn die NavBar mal expanded war, kommen keine Tooltips mehr, wenn man Sie wieder zuklappt / collapsed.

## Beschreibung des Fehlers

- Ist die NavBar initial expanded, so erscheinen keine Tooltips auf den Menüpunkten, wenn man sie dann collapsed.
- Ist die NavBar initial collapsed, sind Tooltips sichtbar. Wenn man sie anschließen expanded und dann wieder collapsed, kommen keine Tooltips mehr.

## Erwartetes Verhalten
Tooltips werden immer angezeigt, wenn die NavBar zugeklappt wird.

**Comment by deleonio** [comment]
Wird mit 1.6 gelöst.
