### ISSUE TITLE
🐞 Lint:  jsx-a11y/click-events-have-key-events in Details-Komponente  

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#3558]
Linting-Regel schlägt bei der Details-Component plötzlich an: 

/home/runner/work/kolibri/kolibri/packages/components/src/components/details/component.tsx
Error:   40:6  error  Visible, non-interactive elements with click handlers must have at least one keyboard listener                                                                                                     jsx-a11y/click-events-have-key-events
Error:   40:6  error  Avoid non-native interactive elements. If using native HTML is not possible, add an appropriate role and support for tabbing, mouse, keyboard, and touch inputs to an interactive content element  jsx-a11y/no-static-element-interactions

Die Regel wurde aktuell ignoriert, da das Details bereits mit Leertaste oder Enter die Detailsanzeige öffnen und schließen kann.

**Comment by deleonio** [comment]
@laske185: Hallo Peter, was ist mit diesem Ticket?!

**Comment by laske185** [comment]
@deleonio Gute Frage, ich sollte damals nur das Ticket anlegen.

**Comment by deleonio** [comment]
Die Lint-Warnung entfernen können wir später machen.

**Comment by sdvg** [comment]
Wird gefixt in: https://github.com/public-ui/kolibri/issues/4996
