### ISSUE TITLE
🛹 Feature: Multiselect Felder setzen ersten Eintrag per Default

### ISSUE THREAD

**Issue by joschakaisr** [public-ui/kolibri#36]
**Description**
Multiselect Felder (KolSelect mit mit _multiple) haben immer den ersten Wert vorausgewählt. Dies war ursprünglich einmal nicht so und lässt sich auch mit Übergabe einer leeren Wertemenge nicht ändern.

**To Reproduce**
Tritt sowohl mit als auch ohne LeanInputAdapter auf. MinBsp.:

```
export const MinTstMultiSelect = () => {
  const [list, setList] = useState([
    { label: 'Herr', value: 'Herr' },
    { label: 'Frau', value: 'Frau' },
  ]);
  return (
   <KolForm slot="content">
      <KolSelect 
        _list={list} 
        _multiple 
        _size={3} 
        _id={'test'} 
        _name={'test'} 
        //_value={[]}   <-- bewirkt nichts
        >
      </KolSelect>
    </KolForm>
  );
};
```

**Expected behavior**
Beim initialen Laden sollten Multiselect Felder per Default keinen Wert ausgewählt haben.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/114665693/195563924-dfef6b6f-733c-40c8-8f63-343d3742efb8.png)

**Desktop (please complete the following information):**
 - Browser Chrome, Firefox, ...
 - Version 1.1.9

**Comment by deleonio** [comment]
Reprod: https://codesandbox.io/s/sweet-panini-ru2nzs?file=/src/App.tsx

Spezifikation Select - `kein Wert ist gewählt' - prüfen.

Wenn nichts gewählt: gibt die Komponente `[]` zurück.

Betrachten ob ein List bzw Value Sync nicht mehr erfolgt. Die PRop Werte werden 1zu1 so genommen, wie sie reingeeben werden.

Hier steht die korrekte Definition: https://html.spec.whatwg.org/#attr-select-multiple

Die Komponente funktioniert aktuell nicht so.

**Comment by deleonio** [comment]
Spezifikation Select - `kein Wert ist gewählt' - prüfen.

Wenn nichts gewählt: gibt die Komponente `[]` zurück.

**Comment by deleonio** [comment]
Betrachten ob ein List bzw Value Sync nicht mehr erfolgt. Die PRop Werte werden 1zu1 so genommen, wie sie reingeeben werden.
