### ISSUE TITLE
Fix: Pagination Sprung-Schalter außen disablen, wenn man auf 1 oder n steht

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#3625]
![Image](https://user-images.githubusercontent.com/6279703/246812409-57c423e6-c308-46ee-af02-2b0871767d85.png)

**Comment by Wolfram-Zell** [comment]
<s> - Zurückbuttons deaktivieren wenn auf erster Seite</s>
<s> - Weiterbuttons deaktivieren wenn auf letzter Seiter</s>
 Ist bereits das Verhalten.

**Comment by Wolfram-Zell** [comment]
Kein Fehler feststellbar.

**Comment by deleonio** [comment]
@Chrisdo82 Die Schalter sind deaktiviert, wenn man an den Rändern ist.
