### ISSUE TITLE
Live-Editor defaultValues berücksichtigen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3687]
Die defaultValues sind im JSON enthalten. Es wäre cool, wenn die Props initial diese Werte hätten.

**Comment by Wolfram-Zell** [comment]
Ursprünglich hatte ich mich dagegen entschieden, da die Standards sonst den copierfertigen Code zumüllen.
-> Defaults bei Codeerzeugung ausfiltern.
