### ISSUE TITLE
Progress: Label und Wertangabe bricht nicht um

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3691]
Die Progress-Komponente bricht in der Anzeige nicht zwischen Label und der Prozentangabe um.

![Image](https://user-images.githubusercontent.com/37439758/248212145-f453ccb8-bdfe-45d9-b37b-836622d271c6.png)

Für die Reihenfolge gibt es verschiedene Use-Cases:
- Wert oben: 

![Image](https://user-images.githubusercontent.com/37439758/248212617-4a2e1e78-c076-482c-9b52-f802d1694426.png)

- Wert unten:

![Image](https://user-images.githubusercontent.com/37439758/248212860-7e80a5f0-6f73-4a8e-bb4d-d35742a79d28.png)

@deleonio: Reihenfolge sollte konfigurierbar sein?

Ich finde die Idee gut.

Für unterschiedliche Darstellungen können wir das `_variant` Property nutzen. Mit passenden Literalen.

- `value-label`
- `label-value`

**Comment by Wolfram-Zell** [comment]
Das SVG Element `<text>` ignoriert `display=flex/grid`.
