### ISSUE TITLE
New Component: SingleSelect

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3693]
SingleSelect entspricht 1zu1 der aktuellen Select-Komponente, nur dass wir den Value von `string` auf `string[]` reinmappen und von `string[]` auf `string` rausmappen.

**Comment by laske185** [comment]
@deleonio : Worauf wartet das Ticket?

**Comment by laske185** [comment]
Verschiedene Lösungen: Fassade, SingleSelect als Default. 

Risiko: Zu viele kleinteilige Komponenten.

**Comment by deleonio** [comment]
Wurde mit #3694  so umgesetzt.
