### ISSUE TITLE
JSDoc: Alle Code-Kommentare auf English übersetzen - Developer-Spec ist dann nur auf English.

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3695]
- Nur die TSX Files
- Nicht die MDs

**Comment by deleonio** [comment]
@sdvg, @laske185, das haben wir ja quasi schon gemacht, nicht?

**Comment by sdvg** [comment]
@deleonio Für die Types haben wir das meiste übersetzt, damit dürfte schon viel behandelt sein. Es gibt aber noch deutschsprachige Kommentare an anderen Stellen, z.B. InputController.
