### ISSUE TITLE
🛹 Feature: Wertebereich für das Datumsfeld

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#37]
Das Datumsfeld soll durch Maxima in seinen gültigen Werten einschränkbar sein. Beim Setzen der Werte sollte die ungültigen Daten bereits nicht auswählbar sein.
Per Default soll der 31.12.9999 als Maximum gesetzt sein, um fünf- oder sechsstellige Jahreszahl zu verhindern.

Neue Eigenschaften am Feld
| Name | Beschreibung | Standardwert |
| --- | --- | ---: |
| min | Der kleinste gültige Datumswert (inklusive) | ? |
| max | Der größte gültige Datumswert (inklusive) | 31.12.9999 |

**Comment by deleonio** [comment]
Ich schlage vor ...

- neue Sub-Component `KolInputNumberDate` ohne Shadow-Dom, die die Component `KolInputNumber` wiederverwendet.
- die API wird jeweils entsprechend spezifiziert / bei `KolInputNumberDate` entsprechend nur 'date'
- `Date` ist nicht `date` - siehe https://www.rfc-editor.org/rfc/rfc3339#section-5.6
- neue Type, nutze regex as type: https://stackoverflow.com/questions/51445767/how-to-define-a-regex-matched-string-type-in-typescript
- componente `KolInputNumber` rückbau und nur den type ergänzen.
