### ISSUE TITLE
🐞 Bug: KolSelect liefert Array Index als Value anstelle der fachlichen Id

### ISSUE THREAD

**Issue by haube** [public-ui/kolibri#3767]
Das erzeugte Select hat den laufenden Index als Value anstelle des für die Eingabe benutzten fachlichen value/id. So ist eine Zuordnung und Weiterverarbeitung der Eingabewerte nur erschwert möglich.

Siehe Beispiel https://public-ui.github.io/docs/components/select
Value ist Index Position mit vorgestelltem Bindestrich, anstelle des erwarteten Zweistelligen Iso Codes ` value: country.alpha2` für die Länder. 
```
<select title="" aria-describedby="7fb484-error" aria-labelledby="7fb484-label" autocapitalize="off" autocorrect="off" id="7fb484" slot="input" spellcheck="true">
<option disabled="" value="-0">- Keine Auswahl</option>
<option value="-1">Afghanistan</option>
<option value="-2">Ägypten</option>
<option value="-3">Albanien</option>
<option value="-4">Algerien</option>
<option value="-5">Andorra</option>
<option value="-6">Angola</option>
<option value="-7">Antigua und Barbuda</option>
<option value="-8">Äquatorialguinea</option>
```

**Comment by deleonio** [comment]
Hallo @haube,

das ist so konzipiert. Wir stellen hier ein kleines Beispiel bereit: https://codesandbox.io/s/issues-3767-ccngvj?file=/src/index.tsx

In Version 2 werden wir ein SingleSelect und eine MultiSelect-Komponente liefern, damit bei Single-Mode nicht mit Arrays gearbeitet werden muss.
