### ISSUE TITLE
🐞 Bug: KolSelect zeigt keine Inhalte wenn in den Options ein leeres Label enthalten ist.

### ISSUE THREAD

**Issue by haube** [public-ui/kolibri#3768]
Das Select soll initial mit einem leeren Eintrag in Kombination mit `required=true` vor belegt sein um eine bewusste Auswahl zu erzwingen. 
Gibt man allerdings ein Leeres Label für den Dummy Eintrag ein, rendert die gesamte Komponente keinen Inhalt.
```
 const STATUS_OPTIONS: SelectOption<string>[] = [
  {
    label: "",
    value: "",
    disabled: true
  }
```
![leeres_label_in_option](https://github.com/public-ui/kolibri/assets/5847053/0b415239-204a-4ae7-89b2-66ab67818a43)];

**Comment by deleonio** [comment]
Hallo,

vielen Dank für den Hinweis. Wir schauen uns das an: https://codesandbox.io/s/issues-3768-xc8dn6?file=/src/index.tsx

Wir kümmern uns darum!

**Comment by Wolfram-Zell** [comment]
Wie der "Fehler" (in Anführungszeichen, weil nur in console.debug) in der Konsole angibt, ist ein label der Länge 0 nicht valide und das gesamte _list-Objekt wird ignoriert.
![image](https://github.com/public-ui/kolibri/assets/117265922/58499d25-dc9f-4e93-be07-f1041e557593)

Daraus ergeben sich folgende TODOs:
 - sollten Einträge ohne label zugelassen werden? Wenn ja, unter welchen Bedingungen? (z.B. value = null, disabled = true)
 - Fehlermeldungen sollten sichtbarer werden (siehe https://github.com/orgs/public-ui/projects/2/views/25?pane=issue&itemId=32124736)

**Comment by Wolfram-Zell** [comment]
@haube Vorerst bitte "Bitte Auswahl treffen..." oder ähnliches als label für diesen leeren Eintrag verwenden.
Es hat sich herausgestellt, dass die Entscheidung ob ein leeres label erlaubt ist und wenn ja unter welchen Bedingungen nicht ganz trivial ist.

**Comment by AntnSaj** [comment]
Es sollten keine leeren Listeneinträge möglich sein. D.h. keine leeren Label.

**Comment by deleonio** [comment]
Lösungsvorschlag:

```tsx
 const STATUS_OPTIONS: SelectOption<string>[] = [
  {
    label: "Bitte auswählen",
    value: "",
    disabled: true
  },
  ...
```

**Comment by deleonio** [comment]
KoliBri sollte die Robustheit verbessern.

Vorschläge:
- ~~Wenn Label leer, dann setzen wir den Text `Bitte auswählen` (Umsetzung mit Sprach-Key-Value, i18n)~~
- Für ein bessere Nachvollziehbarkeit, was in den Validatoren falsch war, dediziertes Exeptionwerfen und einsammel (TEUER)
- Label trimmen und auf Leer prüfen - a11yHint belassen, min Länge 3

**Comment by deleonio** [comment]
Bitte dem Label einen Text geben.
