### ISSUE TITLE
📖 Help: Buttons mit eigenen Icons

### ISSUE THREAD

**Issue by AndreasZimnas** [public-ui/kolibri#379]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**Hilfeanfrage**

Ist es möglich für Buttons custom Images bzw. Icons zu benutzen?

**Comment by deleonio** [comment]
Je nach Theme wird eine oder mehrere Icons-Fonts definiert/integriert und alle enthaltenen Icon-CSS-Class-Names können verwendet werden.

Wir prüfen aktuell, ob wir beim Button auch einen Slot anbieten sollten.

https://github.com/public-ui/kolibri/blob/ce9cb61bffd9521584c6a5369d71a0d0342b4744/packages/library/src/components/span/component.tsx#L78

**Comment by deleonio** [comment]
@AndreasZimnas 

Kannst Du uns bitte ein Beispiel geben?

**Comment by AndreasZimnas** [comment]
![custom_icon_button](https://user-images.githubusercontent.com/28750796/201118680-eb94a9ab-b97b-4dd7-a9bd-50c7a77d4503.png)
Zum Beispiel haben wir diese Buttons. Der erste Button von Links hat ein Icon das das Logo der Anwendung ist. Ist so etwas möglich?

**Comment by deleonio** [comment]
Ist das Icon aus einer Font, dann ist das standardmäßig möglich.

Alternativ können wir den neuen Slot-Modus verwenden.

**Comment by deleonio** [comment]
See with v1.1.10: https://codesandbox.io/s/practical-currying-hgrih1

**Comment by AndreasZimnas** [comment]
Vielen Dank, das war genau was wir suchten.
