### ISSUE TITLE
🛹 Feature: Select All Property für MultiSelect

### ISSUE THREAD

**Issue by joschakaisr** [public-ui/kolibri#38]
**Is your feature request related to a problem? Please describe.**
Wir haben MultiSelect Felder mit vielen Einträgen und es kommt häufig vor, dass der User sämtliche Werte auswählen/deselektieren möchte.

**Describe the solution you'd like**
Die KolSelect Props um ein "_selectAll" Flag erweitern, welches an erster Stelle einen zusätzlichen Eintrag "Alle auswählen" mit Checkbox (o.ä. hervorgehoben) einblendet. 

Mögliche Darstellung:
![grafik](https://user-images.githubusercontent.com/114665693/195603516-253a1916-20d6-4f19-8fc3-5c0933d60858.png)
https://i.stack.imgur.com/wb9Sd.png

**Comment by deleonio** [comment]
Überlegung ist:
- Eine Option als Schalter verwenden (Semantisch nicht korrekt)
- Technisch möglich - Frage ob der Screenreader Text so "okay" ist.
