### ISSUE TITLE
📖 Help: Figuring out how to properly use the KolSelect Component 

### ISSUE THREAD

**Issue by CherifTeclead** [public-ui/kolibri#3824]
Hi,

in the following example I am demonstrating my issues using KolSelect: https://codesandbox.io/s/public-ui-kolibri-reproduction-input-date-forked-5w3s9y?file=/src/form.tsx

Issues:
1.  why is the `target` not strongly typed? I always to cast it in ts to be able to use the .value in it
2. why is the value a negative index of the selected object instead of the actual value declared in `_list`?

Thank you in advance.

**Comment by CherifTeclead** [comment]
@deleonio auf eine Rückmeldung würde ich mich freuen

**Comment by deleonio** [comment]
Hi @CherifTeclead ,

thanks for direct adressing the issue.

1. Looks like

```tsx
<KolSelect
        _list={[
          { label: "value1", value: 1 },
          { label: "value2", value: 2 }
        ]}
        _on={{
          onChange: (e, v) => {
            // Issue:
            setOnChangeState(v); // 😉
          }
        }}
      />
```

2. In v2 we will handle all form values as string, like native html. So we can support also complete static forms without additional JS.
It is a design mistake in v1.
