### ISSUE TITLE
🛹 Feature: Fehlermeldung in Fieldsets (zusammenhängende Eingabefelder)

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#3852]
Beispiel für zusammenhängende Eingabefelder (Fieldsets): 

Datum:
<img width="866" alt="image" src="https://github.com/public-ui/kolibri/assets/118734593/5345eeb6-dc1f-4996-9668-008b915300a9">

Beträge
<img width="858" alt="image" src="https://github.com/public-ui/kolibri/assets/118734593/cc75d741-8d67-4765-80b2-21b5bdd22b33">

Anforderungen:
- Umrandung der fehlerhaften Felder (Vorschlag von Martin mit true und false) ermöglichen
- Fehlermeldung außerhalb der Input-Komponente muss zugewiesen werden können
- eine gemeinsame Fehlermeldungen für alle Input-Komponente eines Fieldsets

Idee/Orientierung: Gov UK Umsetzung (https://design-system.service.gov.uk/components/error-message/)

**Comment by deleonio** [comment]
Idee:

- `_error=true` -> Macht Feld rot ohne Fehlermeldung
  - Problem -> Shadow-Roots zwischen den Inputs
- Neue Komponente - Fieldset
  - eine Fehlermeldung für alle Felder
  - Felder werden über JSON definiert
  - Anordnung der Felder `flex`

> Umsetzung nicht trivial.

**Comment by deleonio** [comment]
Teilaufgaben:

- https://github.com/public-ui/kolibri/issues/5268

**Comment by Chrisdo82** [comment]
@deleonio 

wenn ich `_hideError` gesetzt habe und die Fehlermeldung somit ein `aria-hidden=true` bekommt, wie kann ich dann meine eigene Fehlermeldung mit dem InputFeld verknüpfen? Wenn ich ein `aria-describedby` ans Eingabefeld packe, dann wird das nicht bis zum input durchgereicht.

**Comment by deleonio** [comment]
@Chrisdo82, @sdvg 

Hallo,

vielen Dank für den Hinweis. Stefan, wie heute Morgen beschrieben, habe ich versehentlich ein Detail falsch umsetzen lassen. Bitte das `aria-hidden` wieder entfernen, damit die Fehlermeldung von der KoliBri-Komponente vorgelesen wird und kein `aria-discribeedby` erforderlich ist.

Christian: Ihr müsst Eure äußere Fehlermeldung, die mit der eines Feldes übereinstimmen sollte, mit `aria-hidden` für den Screenreader ausblenden.

**Comment by Chrisdo82** [comment]
@deleonio super danke Martin. Wir verwenden für unsere Fehlermeldungen auch die KolAlert Komponente. Kann ich der das `aria-hidden` direkt mitgeben oder muss ich es am äußeren Wrapper setzen? Und müsste ich auch das `_alert` Flag auf false setzen oder ist dass an dieser Stelle irrelevant?

**Comment by deleonio** [comment]
@Chrisdo82 gib der `kol-alert`-Komponente einfach ein `aria-hidden="true"`.
