### ISSUE TITLE
🐞 Bug: Remove unwanted "..."

### ISSUE THREAD

**Issue by CherifTeclead** [public-ui/kolibri#3874]
Unwanted "..." appears in different places in the app:
https://github.com/public-ui/kolibri/blob/dc224021a26af0a02c7ad22b022e5b1ee172aa31/packages/components/src/components/breadcrumb/component.tsx#L48C5-L48C5
&
https://github.com/public-ui/kolibri/blob/dc224021a26af0a02c7ad22b022e5b1ee172aa31/packages/components/src/components/textarea/component.tsx#L48

**Comment by deleonio** [comment]
Hi @CherifTeclead ,

please set the label with `_label`-Prop or set it empty string.
