### ISSUE TITLE
Cheat-Sheet: links to esm not working

### ISSUE THREAD

**Issue by Wolfram-Zell** [public-ui/kolibri#3952]
https://public-ui.github.io/cheat-sheet/

**Comment by Wolfram-Zell** [comment]
Aktuell scheint esm.sh ein Problem zu haben: https://github.com/esm-dev/esm.sh/issues/676#issuecomment-1624375013

**Comment by ije** [comment]
seem it works for me, please clean your browser cache and try again

**Comment by Wolfram-Zell** [comment]
@ije 
I cleared cache and tried other browsers (that I have not been to any related site) in inkognito, still the same issue: 
The base file (https://esm.sh/@public-ui/components@1.6.0-rc.1) gets loaded, the components (https://esm.sh/v128/@public-ui/components@1.6.0-rc.1/es2022/dist/kol-table.entry.js) return 404 with the text "Module not found".
You can test it for yourself here: https://public-ui.github.io/cheat-sheet/
Tested with Edge, Chrome and FireFox.
With an older version specified or without version the outcome is the same.
