### ISSUE TITLE
🐞 Bug: Fehlender title in Kol-Button nativem Element

### ISSUE THREAD

**Issue by BenRichter** [public-ui/kolibri#3953]
# Fehlermeldung

## Beschreibung des Fehlers
Kol-Button Webcomponents in Angular haben keinen "title" am nativen <button>-Element. Der Titel wird nur an die <kol-button> Komponente gehangen. Im Test nach BitV wurde uns das als Mangel angezeigt.

## Erwartetes Verhalten
Es wird das Attribut _title_ an das native Element übergeben

**Comment by PippiViktualia** [comment]
Das `title`-Attribut ist nicht barrierefrei.
Der KoliBri-Button ohne sichtbare Beschriftung (`_hide-label`) stellt die sichtbare Beschriftung automatisch mittels des barrierefreien KoliBri-Tooltips dar. Die Verwendung des `title`-Attributs sehen wir nicht als notwendig an.

Welcher Prüfschritt wurde im BITV-Test angemerkt?

**Comment by BenRichter** [comment]
Der Icon-Button wurde unter dem Prüfschritt "9.2.4.4 Aussagekräftige Linktexte" als fehlerhaft ausgewiesen.

Ich kann jedoch mittlerweile nicht mehr genau nachvollziehen, ob der fehlende title bzw. aria-label durch ein Tool oder die Firefox DevTools als Fehlerhaft ausgewiesen wurde, oder ob der Screenreader NVDA keine Bezeichnung für den Button ausgegeben hat.
