### ISSUE TITLE
Tooltip Positionierung mit fixed

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#3966]
Damit die Positionierung des Tooltips nicht durch Elemente mit `position: relative` beeinflusst wird, sollte `position: fixed` verwendet werden.

**Comment by laske185** [comment]
`position: fixed` löst das Problem nicht.

**Comment by deleonio** [comment]
Hier tritt der Fehler auf: https://public-ui.github.io/v2/sample-react/#/handout/basic

Auf und Zuklappen in der Nav

**Comment by sdvg** [comment]
Position Fixed funktioniert bei mir tatsächlich gut. Ich musste neben der CSS-Anpassung aber auch die strategy für `computePosition` auf `fixed` setzen.

Einordnung seitens Floating UI zum Nachlesen: https://floating-ui.com/docs/misc#clipping
