### ISSUE TITLE
Button, Link usw.: Aria-Label statt Aria-LabelledBy verwenden bei _hide-label=true

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3967]
Hier im Bild sieht man, dann wir bei Icon-Button auch `aria-label` verwenden kann, statt `aria-labelledby`.

![Image](https://user-images.githubusercontent.com/6279703/248685593-3de59e93-9435-4215-bd57-9d114511c0e0.png)

Die Änderung kann bei allen Komponenten vorgenommen werden, die ein Tooltip haben.

- Button
- Link
- Input
- Select
- Textarea
- usw.

**Comment by deleonio** [comment]
Meiner Meinung nach kann `aria-labelledby` weg.

**Comment by deleonio** [comment]
Wenn `_hide-label` verwendet wird, dann wird der `slot` für das Label mittels `hidden` versteckt. Dadurch würde das Label ohne `aria-labelledby` nicht mehr vorgelesen.

Aus diesem Grund muss `aria-labelledby` und auch die `id` am Tooltip bleiben.

**Comment by laske185** [comment]
Das Inputbeispiel muss in den Kontext eines Suchfeldes gebracht werden.
