### ISSUE TITLE
🛹 Feature: CJS mit ausliefern

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#398]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.

Bei Jest ist ESM leider noch experimental (https://jestjs.io/docs/ecmascript-modules). Alle Tests mit Jest schlagen mit der Version 1.1.9 nun leider fehl.

## Beschreiben Sie die gewünschte Lösung

Den Build so anpassen, das cjs weiterhin mit ausgeliefert wird.

**Comment by deleonio** [comment]
@Chrisdo82 alle Module werden mit CJS ausgeliefert. Wir haben auch den Package-Type auf 'module' gestellt.

Lass uns Freitag mal schauen, was wir an der Konfiguration verbessern können.

**Comment by deleonio** [comment]
Bitte ein kleines Reproduktionsbeispiel.

**Comment by Chrisdo82** [comment]
Das Problem saß vor dem Bildschirm ;-) ich hatte in der Jest Config noch ein fileTransform mit drin, der für die Probleme gesorgt hat:

```
transform: {
    "^(?!.*\\.(js|jsx|json)$)": "<rootDir>/tests/__mocks__/fileTransform.js",
}
```

Das habe ich nun auskommentiert und jetzt laufen auch die Tests wieder durch.
