### ISSUE TITLE
💡 Hinweis: Themes sind derzeit nicht tree shakeable

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#399]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

**Hilfreicher Hinweis**

Die Themes-Datei (`node_modules/@public-ui/themes/dist/index.mjs`) ist derzeit 2,1 MB groß, und ist nicht tree shakeable da alle Themes in einer Datei enthalten sind. Bitte die Themes in einzelne Dateien aufsplitten.

**Comment by deleonio** [comment]
@Chrisdo82 

Das ist eine gute Idee.

Idealerweise verwaltet jeder Mandant sein Theme-Paket selbst. Ggf. können wir das BMF-Theme auf Open CoDE umziehen und dort einzeln und direkt durch Euch pflegen.

**Comment by deleonio** [comment]
@Chrisdo82 

Mit dem Release 1.1.10-rc.16 haben wir die Themes etwas optimiert und konnten die Bundle Size einer App um 1.43 MB reduzieren.

See: https://github.com/public-ui/kolibri/tree/main/packages/themes/src/themes/defaults

**Comment by Chrisdo82** [comment]
@deleonio Danke schön, ich probiere es aus sobald die 1.1.10 released wurde.

**Comment by deleonio** [comment]
@Chrisdo82 kannst Du das Ticket schließen - wenn das soweit i.O ist?!

**Comment by Chrisdo82** [comment]
sieht gut aus
