### ISSUE TITLE
Cheat-Sheet: Anleitung von esm.sh auf Assets-Einbindung umschreiben

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4057]
Wir haben festgestellt, dass der `esm.sh`-Server unzuverlässig ist und eine KoliBri-Integration evaluiert, die eine lokale Verwendung ermöglicht.

Hierzu muss das Cheat-Sheet inhaltlich überarbeitet werden:

- [ ] Download Sourcen
- [ ] Einbindung-Snippet anpassen

**Comment by Wolfram-Zell** [comment]
duplicate of https://github.com/orgs/public-ui/projects/2/views/20?pane=issue&itemId=32604310
