### ISSUE TITLE
🐞 Bug:  Aufzählungszeichen innerhalb der Pagination werden vom Screenreader angesagt

### ISSUE THREAD

**Issue by AntnSaj** [public-ui/kolibri#4091]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Aufzählungszeichen innerhalb der Pagination werden vom Screenreader angesagt

## Beschreibung des Fehlers
Die Aufzählungszeichen zwischen den Seiten-Buttons enthalten keine zusätzliche Information. Einem Screenreader Nutzenden wird durch das Konstrukt der Pagination verständlich, dass nicht alle Seiten fortlaufend dargestellt werden und es Lücken geben kann. Diese Punkte sollten daher keine unnötige Screenreader Ausgabe erzeugen.

## Reproduktion
Im Lesemodus des NVDA in der Pagination navigieren.

## Erwartetes Verhalten
Keine Screenreader Ausgabe der Aufzählungszeichen.

## Screenshots
![2023-07-14_10h30_45](https://github.com/public-ui/kolibri/assets/126143994/fe6d15f8-a254-43e3-bd18-9eecc95eace7)

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows 10
- Browser Chrome
- Version 114.0.5735.134

**Comment by deleonio** [comment]
@laske185: Bitte mit @PippiViktualia refinen und RoD machen.

**Comment by laske185** [comment]
Der Span des Separators hat bereits aria-hidden gesetzt. Bitte neu prüfen.
