### ISSUE TITLE
🛹 Feature: Programmatische Namen der Seitenbuttons in der Pagination ergänzen oder kenntlich machen, dass sich der User auf einer Pagination befindet

### ISSUE THREAD

**Issue by AntnSaj** [public-ui/kolibri#4092]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Programmatische Namen der Seitenbuttons in der Pagination ergänzen oder kenntlich machen, dass sich der User auf einer Pagination befindet

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Aktuell wird bei den Seitenbuttons der Pagionation nur der sichtbare Name (Schalter 1) ausgegeben. Ohne den den Zusatz "Seite" ist dies nicht sehr aussagekräftig.

## Beschreiben Sie die gewünschte Lösung
Im NVDA sollte anstelle von aktuell Schalter 1 künftig Schalter Seite 1 ausgegeben werden. Dies könnte mit Aria-label realisiert werden. 

Noch besser wäre es allerdings, wenn beim an navigieren der Pagination auch das Wort "Pagination" ausgegeben wird, damit Screenreader Nutzende wissen, dass es sich um eine Pagination handelt. Dies kann z.B. mit aria-label="Pagianation" umgesetzt werden. In diesem Fall ist der Zusatz "Seite 1" nicht notwendig und die Ausgabe der Buttons kann bleiben wie sie gerade ist.

**Comment by deleonio** [comment]
@laske185: Bitte mit @PippiViktualia refinen und RoD machen.

**Comment by deleonio** [comment]
- Label an den Schaltern
- Bereich Paginierung benennen
- Localisierung berücksichtig

**Comment by deleonio** [comment]
TODO

- [x] https://www.a11ymatters.com/pattern/pagination/ 
  - nav, ul, li
  - `_aria-label` muss an jede Nav - Default: "Pagination"
  - neues Prop `_label` / optional
- [x] Table: Label der Pagination ist "Pagination für die Tabelle " + "Caption" (Label der Tabelle)
- [x] Basis-Styling
- [ ] Themes mal durchschalten (auf Release 1.7-rc.0 warten)
