### ISSUE TITLE
🛹 Feature: Tooltip-Rand mit Dreieck vereinen 

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#4099]
wie besprochen, benötigen wir einen umschließenden Rand inklusive Spitze:

<img width="85" alt="image" src="https://github.com/public-ui/kolibri/assets/118734593/9674bcc6-9de9-4409-9b53-a90e97844cff">

**Comment by deleonio** [comment]
@laske185 - wie können wir das lösen?

**Comment by deleonio** [comment]
![image](https://github.com/public-ui/kolibri/assets/6279703/5331cbcf-7434-490a-9932-e2dcff3808d1)

```
<div class="container">
  <div class="arrow" />
  <div class="content" />
</div>
```

**Comment by sdvg** [comment]
Die Component Styles scheinen mir bereits in Ordnung zu sein, der Fehler scheint im Theme zu liegen.
Um welches Theme handelt es sich in dem Screenshot?

Im ITZBund-Theme konnte ich das gewünschte Verhalten mit folgenden Änderungen nachstellen:

```diff
        kol-tooltip .area {
                background-color: #f2f2f2;
        }
+       kol-tooltip #floating {
+               border: 1px solid #626262;
+       }
        kol-tooltip #arrow {
-               background-color: #626262;
+               border: 1px solid #626262;
        }
        kol-tooltip kol-span-wc {
                padding: 0.25rem 0.5rem;
                font-size: 0.875rem;
                line-height: 1.25rem;
                border-radius: 2px;
-               border: 1px solid #626262;
        }`,
```

<img width="210" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/48f1625d-a05a-49b4-b6c0-0c09951066c9">

**Comment by sdvg** [comment]
Das verlinkte PR löst das Problem im BMF-Theme.
