### ISSUE TITLE
🛹 Feature: Static Form Handling for Input File

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4107]
Wir gehen wir mit Input-File mit dem File-Objekt um?

**Comment by deleonio** [comment]
https://y7yqwv.csb.app/

**Comment by deleonio** [comment]
@laske185 wie wollen wir das lösen?

**Comment by laske185** [comment]
Wurde bereits umgesetzt. Files werden über das File-Objekt über das input außerhalb des Shadow-DOMs ausgegeben.
