### ISSUE TITLE
💡 Hinweis: Assistive Label-Unterstützung doppelt gemoppelt?!

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4193]
https://codesandbox.io/s/kolibri-public-ui-react-hide-label-input-jg4gpp?file=/src/index.tsx

![image](https://github.com/public-ui/kolibri/assets/6279703/25e9024c-8bc7-4026-8880-6e846637c082)

**Comment by ElVariablo** [comment]
nach eingehender Prüfung wurde folgendes festgestellt:


ist stand:

- Im Label wird teilweise "anklickbar" vorgelesen
- das Label wird im "Lesemodus" des Screenreaders zwei mal vorgelesen(im Label und im Input Feld)

![Image](https://github.com/public-ui/kolibri/assets/118798973/2d463a8d-c295-4033-a760-63a810045568)


Soll:

- anklickbar soll nicht vorgelesen werden
- das label soll im "Lesemodus" des Screenreaders nur einmal, beim Label selbst, vorgelesen werden und nicht noch einmal am Eingabe Feld


To-Do:


- das aria-labeledby im Input sollte entfernt werden. Durch dieses entsteht die Ausgabe "anklickbar" sowie die zweite Ausgabe am Eingabefeld


![Image](https://github.com/public-ui/kolibri/assets/118798973/926dd703-2a89-4b38-a370-de3ed82f3f40)

**Comment by deleonio** [comment]
- https://github.com/public-ui/kolibri/issues/4193
- https://github.com/public-ui/kolibri/issues/4194
- https://github.com/public-ui/kolibri/issues/5272
