### ISSUE TITLE
Vereinheitlichung: _size komplett deprecaten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4199]
Abhängig von:
- https://github.com/public-ui/kolibri/issues/4198

Für alle Input, Select, Textarea das Property `_size` deprecaten.

Kommentar: `Wird ersatzlos gestrichen, weil die Breite i.d.R. mit CSS gemacht wird.`

**Comment by sdvg** [comment]
Ich sehe `_size` nur noch in `input-email`, `input-password`, `input-text` und `select`.
Alle genannten Komponenten haben die prop bereits als deprecated markiert (#4198 vorausgesetzt) ✅ 

@deleonio Können wir das Ticket schließen?
