### ISSUE TITLE
Vereinheitlichung: _suggestions statt _list bei allen Eingabefelder (Inputs)

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4200]
Inputs
- `_list: string[]` Property-Name auf `_suggestions`
- `props._list` auf `state.suggestions` umleiten
- `_list` deprecaten

**Comment by sdvg** [comment]
Components:

- [x] input
- [x] input-color
- [x] input-date
- [x] input-email
- [x] input-number
- [x] input-range
- [x] input-text

`select`, `input-radio` ~~und `link-group`~~ haben ebenfalls eine `list` prop, diese haben aber einen anderen Nutzen und ich hätte sie hier nicht angepasst.

**Comment by deleonio** [comment]
`link-group` hat kein `_list`-Property, ich glaube das war nur ein Versehen, oder?

https://github.com/public-ui/kolibri/blob/main/packages/components/src/components/link-group/types.ts

**Comment by sdvg** [comment]
Korrekt, ich habe es oben gestrichen.
