### ISSUE TITLE
Vereinheitlichung: _options statt _list bei Radio und Select

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4201]
- _options Property einführen, gleich wie _list
- _list deprecaten
- props._list auf state._options umleiten

**Comment by sdvg** [comment]
@deleonio 

Radio und Select unterstützen verschiedene Props:

Select verwendet `SelectOption[]`, welches neben `Option` auch `Optgroup` ermöglicht, Radio direkt `Option`.

Ich würde deshalb vorschlagen, die Props nicht als `_options` zu vereinheitlichen, sondern `SelectOptions` und `RadioOptions` anzubieten?

Oder sollten wir ein Konstrukt analog zu `label` erstellen, das sowohl `OptionsPropType` als auch `OptionsWithOptgroupPropType` exportiert?

**Comment by deleonio** [comment]
@sdvg Danke für den Hinweis.

Bitte Variante 2 umsetzen: `Oder sollten wir ein Konstrukt analog zu label erstellen, das sowohl OptionsPropType als auch OptionsWithOptgroupPropType exportiert?`
