### ISSUE TITLE
Vereinheitlichung: _label statt _caption, _heading, _headline, _summary, _title

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4202]
Bitte pro abzulösendes Property einen eigenen PR machen.

- _caption
- _heading
- _headline
- _summary
- _symbol
- _title

**Comment by sdvg** [comment]
@deleonio Ticket wiedereröffnet, es kommen noch ein  paar PRs (ein PR pro property)

**Comment by sdvg** [comment]
link-group eine `_heading` prop, aber auch bereits ein `_label`. Soll hier etwas angepasst werden?

**Comment by sdvg** [comment]
Ähnliches Problem mit `_symbol` bei der symbol Komponente. Hier hat eine `_symbol` eine legitime Rolle und ist kein Synonym zu `_label`, denke ich.

**Comment by deleonio** [comment]
> link-group eine `_heading` prop, aber auch bereits ein `_label`. Soll hier etwas angepasst werden?

Hier bitte überspringen, ja.

**Comment by deleonio** [comment]
> Ähnliches Problem mit `_symbol` bei der symbol Komponente. Hier hat eine `_symbol` eine legitime Rolle und ist kein Synonym zu `_label`, denke ich.

Stimmt, label wurde schon eingeführt.
