### ISSUE TITLE
Vereinheitlichung: _list komplett deprecaten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4208]
Abhängig von:
- https://github.com/public-ui/kolibri/issues/4201
- https://github.com/public-ui/kolibri/issues/4200

Für alle Input, Select, Textarea das Property _list deprecaten.

Kommentar: Wird ersatzlos gestrichen, weil die Breite i.d.R. mit CSS gemacht wird.

**Comment by sdvg** [comment]
@deleonio 

Die einzige Verwendung von `_label`, die nicht bereits als deprecated markiert wurde, ist in `input-radio-group`. Besagte Komponente ist allerdings selber schon als ganzes deprecated.

Ich schätze das Ticket kann geschlossen werden?
