### ISSUE TITLE
🐞 Bug: Hochkontrast-Modus kann über CSS erkannt werden und ggf. Custom Style nicht verwenden

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#4261]
# Fehlermeldung
Schieberegler (Input Range) im Windows-Hochkontrast-Modus nicht mehr nutzbar. 

## Beschreibung des Fehlers
Wechselt man in den Windows-Einstellungen in den Hochkontrast-Modus, werden diese vom Browser (Chrome) übernommen. Den Schieberegler (Punkt) kann man dann leider nicht mehr sehen. 

## Reproduktion
- Link zu CodeSandbox: 
- https://public-ui.github.io/sample-react/#/input-range/basic?theme=zoll-v2
- https://public-ui.github.io/sample-react/#/input-range/basic?theme=bmf

Schritte zum Reproduzieren des Verhaltens:
- Windows Einstellungen "Hoher Kontrast" aktivieren (befindet sich in den Einstellungen "Erleichterte Bedienung"). 

## Erwartetes Verhalten
Das Bedienelement wird auch im Hochkontrast-Modus korrekt dargestellt und ist bedienbar. Ein weißer Rand um das Bedienelement wird erwartet. 

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/124779450/25b10499-03f3-430d-8442-fbaddaf4450a)

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows 10
- Browser: Chrome
- Version: v1.6.0-rc.17

**Comment by laske185** [comment]
Wenn #4316 abgeschlossen ist, sieht die Komponente so aus:
<img width="536" alt="image" src="https://github.com/public-ui/kolibri/assets/37439758/c55f418f-4bea-49d8-881d-485d039ede1b">

**Comment by deleonio** [comment]
Wir denken, dass dieser Stand barrierefrei ist, weil eine Eingabe über das Number-Field default ist. Der Slider ist quasi beim Slider sekundär.


Wir schauen uns MediaType für Hochkontrast an.

**Comment by ElVariablo** [comment]
Die Umsetzung ist barrierefrei. Es wäre aber wünschenswert, wenn auch der Schieberegler einen Rahmen hätte.

**Comment by Sommerli2** [comment]
Anmerkung: Im Firefox wird bereits jetzt mit der momentanen Lösung im Hochkontrast ein Rahmen um den "Hebel" dargestellt. Der [HTML 5 Standard-Slider](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) besitzt im Chrome auch im Hochkontrastmodus einen adäquaten Rahmen: 
![image](https://github.com/public-ui/kolibri/assets/124779450/e272f5b5-ae43-43aa-9ea0-28f10202e391) ggf. gibt es hier noch die Möglichkeit der Optimierung.

**Comment by Sommerli2** [comment]
Info: https://runebook.dev/de/docs/css/@media/-ms-high-contrast

**Comment by ElVariablo** [comment]
https://kulturbanause.de/blog/css-media-prefers-contrast-staerkere-kontraste-aktivieren/
