### ISSUE TITLE
🐞 Bug: Der Drehschalter besitzt keinen sichtbaren Rahmen und ist daher nicht als Bedienelement erkennbar. 

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#4264]
# Fehlermeldung
Kein sichtbarer Rahmen beim Bedienelement "Drehschalter". 

## Beschreibung des Fehlers
Der Drehschalter (eigenes Element unterhalb des Schiebereglers) besitzt keinen Rahmen und ist daher nicht als Bedienelement erkennbar. 

## Reproduktion
- Link zu CodeSandbox: Style: BMF
- https://public-ui.github.io/sample-react/#/input-range/basic?theme=bmf

## Erwartetes Verhalten
Die für die Identifizierung notwendige visuelle Information von informationstragenden Grafiken und grafischen Bedienelementen sowie deren Zuständen soll einen Kontrast von mindestens 3:1 zu angrenzenden Farben haben.

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/124779450/610b7e90-7285-4394-a738-486c111de686)

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows 10
- Browser: Chrome
- Version: v1.6.0-rc.17

**Comment by deleonio** [comment]
@Chrisdo82,
@gretaneumannn

Die Range müsste bzgl. der Wertanzeige noch nach gestyled werden.

**Comment by laske185** [comment]
Mit #4316 hat das number input wieder seinen Standardrahmen im Basisstyle.

**Comment by Sommerli2** [comment]
Nachtest erfolgreich
