### ISSUE TITLE
Live-Editor: `defaultValue`'s aus Metadaten initial übernehmen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4377]
Die Informationen für den Live-Editor werden aus einer Meta-Datei ausgelesen, die auch den defaultValue zu den einzelnen Properties enthalten kann. Es wäre schön, wenn diese initialen Werte auch die initialen Werte beim Konfigurator jeder Komponente wären.

**Comment by sdvg** [comment]
Die defaultValues waren grundsätzlich schon implementiert, hatten aber einen Bug bei den Select-Feldern. Die anderen Feld-Typen schienen mir alle in Ordnung zu sein.
