### ISSUE TITLE
Blog-Post: Wie wird der ToastService verwendet?

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4392]
Bitte schreibe mal eine Anleitung, wie man den ToastService in eine App verwenden soll. Gerne als Blog-Post auf der Website.

- const Toaster = new ToastService()
- export ToastService nicht mehr / deprecaten
- setOption ... ToastOptionType ?!
- https://codesandbox.io/s/kolibri-public-ui-react-toaster-jlgrhh

Akzeptanzkriterien:
- [ ] Toaster exportieren
- [ ] Dokumentation erweitern
- [ ] Bitte dieses Ticket im Anschluss: https://github.com/public-ui/kolibri/issues/4647

**Comment by laske185** [comment]
Als "Singleton" umsetzen. Pro HTML-Element eine Instanz.
Aus der Register (initKoliBri) die Initialisierung  entfernen.
