### ISSUE TITLE
a11y - Button-Beispiele optimieren

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4399]
- [x] Mehr Abstand zwischen den Schaltern, damit jeder Tooltip ohne Überlagerung dargestellt wird.
- [x] Bitte bei allen Button Beispielen
- [x] `icon-only` gegen `hide-label` ersetzen
- [x] Tooltips in verschiedene Richtung ausrichten nur bei dem `hide-label` Beispiel

**Comment by sdvg** [comment]
Es steht nicht explizit im Ticket, aber ich glaube wir hatten besprochen, die Tooltip Examples ganz zu entfernen, weil Tooltip eine interne Komponente darstellt.
Die Beispiele sind ja (wie oben beschrieben) über Button abgedeckt.
