### ISSUE TITLE
a11y - Sperren von input E-Mail liste

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4401]
Die Option liste im Input E-Mail sollte aufgrund von mehreren, teils schwerwiegenden Barrierefreiheitsproblemen gesperrt werden. Als alternative kann ein Select mit E-Mail Adressen befüllt werden. Sollte dieser Teil der Komponente nicht entfernt werden, müssen wir eine Stärkere Abwertung im BITV Test vornehmen.

Folgende Probleme hinsichtlich der Barrierefreiheit wurden festgestellt:

Der Dokumententitel wird vorgelesen, nachdem ein Eintrag aus der Liste ausgewählt wurde
![Image](https://user-images.githubusercontent.com/126143994/247935532-d9506bff-9b88-4165-b0f9-9e5e47a51115.png)

Der Dropdown-Pfeil ist sehr weit rechts und kann ggf. nicht wahrgenommen werden
![Image](https://user-images.githubusercontent.com/126143994/247935755-75374c86-977b-4e75-9a1f-47bf282d2002.png)

Das Dropdown Menü scrollt nicht an der Komponente mit, sondern bleibt immer an der selben Stelle des Bildschirms
![Image](https://user-images.githubusercontent.com/126143994/247936001-202e4306-37fb-4b58-81ef-b0fce825bb8b.png)

Das Dropdown Menü zoomt nicht mit
![Image](https://user-images.githubusercontent.com/126143994/247936129-2179bfd3-bd27-4243-9760-9d69a71a564c.png)

Bei Benutzerdefinierten Einstellungen verschwindet der Dropdown Pfeil
![Image](https://user-images.githubusercontent.com/126143994/247936314-924126ee-ef03-4884-ad4c-038158aa5196.png)

**Comment by deleonio** [comment]
Argumentation das das Browser-Overlay vom Select nicht zur Abwertung führt, sollte auch hier gelten?!

**Comment by ElVariablo** [comment]
Prinzipiell kann so argumentiert werden. Aus Sicht der Barrierefreiheit ist dieses Option für viele Menschen nicht nutzbar und es gibt sehr viel bessere Alternativen. Daher sollte die input E-Mail liste trotzdem gesperrt werden (um auch nicht abwertbare Barrieren zu vermeiden).
