### ISSUE TITLE
a11y - Beispielanpassung beim Input E-Mail

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4402]
- [x] Initiale Fehlermeldung Entfernen. Fehlermeldungen können provoziert werden. Einfach ein kol-form drumrum anlegen.
- [ ] Pflichtfelderläuterung muss auch auf der Beispielseite vorhanden sein

**Comment by sdvg** [comment]
`kol-form` zeigt in der React Sample App leider nur den Platzhalter für die Pflichtfelderläuterung an. Ist das ausreichend oder sollten wir eine Sprache registrieren? (@laske185)
