### ISSUE TITLE
a11y - Tooltip entfernen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4405]
Beispiel für Tooltip kann entfernt werden, da Tooltips nur in andern KoliBri-Komponenten verwendet werden sollen und nicht alleinstehend funktioniert.

**Comment by ElVariablo** [comment]
Aus Sicht der Barrierefreiheitstests wäre es besser die Beispiele beizubehalten. Da die Tests komponentenbasiert erfolgen müsste der Tooltip beim Entfernen des Beispiels bei anderen Komponenten mit getestet werden. Das würde an mehreren stellen zu Fehlern führen.

**Comment by deleonio** [comment]
Ein Tooltip ist allein keine barrierefreie Komponente.
