### ISSUE TITLE
Inputs, Select, Textarea - Sample App - Formular-Beispiele optimieren

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4408]
- [x] Formularfelder in ein `kol-form` einbetten
- [x] Alle Fehlermeldungen initial ausblenden `_touched` nicht verwenden
- [x] Fehlermeldungen aber exemplarisch einbauen

**Comment by sdvg** [comment]
Checkbox, email und file lasse ich aus, da bereits in anderen Tickets (offene PRs) behandelt.
