### ISSUE TITLE
Component: Tree pilotieren nach WCAG-Beispiel

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4410]
Die Tree-Componente anhand des WCAG-Beispieles umsetzen: https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/

Lösungsansatz ist, eine Kombination von Kol-Komponenten zu verwenden:

```html
<kol-tree _label="Überschrift">
    <kol-tree-item _label="Item A" />
    <kol-tree-item _label="Item B" />
    <kol-tree-item _label="Item C with children">
        <kol-tree-item _label="Item CA" />
        <kol-tree-item _label="Item CB" />
    </kol-tree-item>
</kol-tree>
```

Related: https://github.com/public-ui/kolibri/issues/2478

Mutation-Observer ermöglicht das beobachten von DOM-Änderungen:

```js
var MutationObserver = window.MutationObserver || window.WebKitMutationObserver;
var observer = new MutationObserver(function(mutations) {
    // updateDom - stencil method (https://stenciljs.com/docs/methods)
    mutations[0].target.updateDom();
    console.log(mutations);
});

var config = { childList: true }
observer.observe(element, config);
```

**Comment by sdvg** [comment]
Noch offene Punkte:

- [ ]  Fehlende Keyboard-Shortcuts implementieren:
    - [ ]  home/end
    - [ ]  a-z, A-Z
    - [ ]  Arrow right auf offener Node: Fokus auf erstes Child
    - [ ]  Arrow left: Fokus auf Parent Node (wenn nicht gerade auf geöffneter Node)
- [x]  Link Click-Event muss weitergegeben werden, um Kontrolle über den Fokus zu ermöglichen
- [x]  Tree benötigt _label, als aria-label für `<nav>`
- [x]  Tabindex-Management:
    - [x]  Alle Links haben `tabindex="-1"`
    - [x]  Nur der aktive Link (aria-current) hat `tabindex="0"`
- [x]  Wenn der Baum den Fokus verliert muss sicher gestellt werden, dass das aktive Element im Baum geöffnet ist.
- [ ]  Styling
    - [x]  Tree wird hinterlegt, wenn einer der Links Fokus hat
    - [x]  Aktiver Link wird hinterlegt
    - [ ]  Fokus Styles, hover, etc. sicherstellen
- [ ]  HTML Attribute
    - [ ]  links (`a` element) (benötigt Anpassungen von link component oder direkte Nutzung von `a`)
        - [ ]  role=treeitem
        - [ ]  aria-expanded
        - [ ]  aria-owns
- [ ]  Dokumentation
- [ ]  Tests
