### ISSUE TITLE
Vereinheitlichung der Property-Handling Implementierung für v2

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4411]
Die Implementierung des Property-Handling überall vereinheitlichen.

`types/props/*.ts`
- Nur English
- Property Type
- API-Property - Sicherstellen des Prop-Names `{ label: LabelPropType;}` - stellt sicher, dass Label immer `_label` heißt und den gleichen Typ hat
- Validator

**Comment by sdvg** [comment]
Nicht weiter bearbeitet weil deprecated:
* `aria-controls`
* `aria-current`
* `aria-expanded`
*  `aria-label`
*  `aria-selected`
* `compact`
* `has-compact-button`
* `stealth`

**Comment by sdvg** [comment]
Zur `color` Prop hätte ich gerne Feedback, bevor ich etwas ändere. Definiert ist sie zurzeit so:

```
export type ColorPair = {
	backgroundColor: string;
	foregroundColor: Stringified<CharacteristicColors>;
}

export type PropColor = ColorPair;
```
(Die deprecated Alternative einmal ausgeklammert)

Diese Variante wäre korrekt, wenn es zwei Attribute `_backgroundColor` und `_foregroundColor` gäbe.

Meines Erachtens müsste es so aussehen:

```
export type ColorPairPropType = {
  backgroundColor: string;
  foregroundColor: Stringified<CharacteristicColors>;
}

export type PropColorPair = 
  colorPair: ColorPairPropType
};
```

In den Komponenten ist nämlich durchaus `_color` als ein Attribut implementiert, nicht `backgroundColor` und `foregroundColor` separat. Zusätzlich gibt es ein dann (zu umständliches?) mapping von `_color` auf `backgroundColor` und `foregroundColor`.

**Comment by laske185** [comment]
Ich finde den type für den Propertytypen übertrieben. Es macht den Code schlechter lesbar und bringt keinen Mehrwert, da der Typ an der Propertydefinition auch so fest hinterlegt wird:
```ts
export type PropLabel = {
	label: string | boolean;
};
```
oder
```ts
export type PropShow = {
	show: boolean;
};
```
Ich würde bei primitiven Typen und strings und deren Verkettungen **keine** Typdefinition erstellen!
