### ISSUE TITLE
Komponenten-API (`types.ts`) pro Komponent separieren

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4412]
Vorlage ist der Avatar, der Fokus sollte aber erstmal nur auf den Types liegen.

"Problematisches" Beispiel sind die `button-link.ts` auflösen.

![Image](https://user-images.githubusercontent.com/6279703/256842187-bbf55a62-3a79-4f65-a313-cf6058ae0802.png)

**Comment by sdvg** [comment]
Branch basiert auf `4411-vereinheitlichung-der-property-handling-implementierung-für-v2`
