### ISSUE TITLE
Inputs, Select, Textarea: bei `_hideLabel` Sternchen und A11y-Hint erweitern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4413]
Wenn Label ausgeblendet und das Feld required ist, soll nicht mehr das Label angezeigt werden. Sondern der neue Tooltip mit Sternchen.

```html
<kol-input-text _hide-label _label="Eingabe" _required />
```

![Image](https://user-images.githubusercontent.com/6279703/256846160-5b6ced36-c426-46f8-b0a3-61d26bbc19e8.png)

**Comment by laske185** [comment]
Aussage der BITV-Leute: "Der Tooltip geht gar nicht."

**Comment by sdvg** [comment]
Ich würde dieses Ticket dann erst einmal überspringen, bis das geklärt ist.

**Comment by deleonio** [comment]
[Wir müssen zunächst klären und umsetzen, wo Eingabefelder kein dauerhaft sichtbares Label haben dürfen.](https://github.com/public-ui/kolibri/issues/4677)

**Comment by deleonio** [comment]
Ich möchte, dass die umgesetzten Tooltip vorerst bleiben und um folgende Features erweitert werden:

- [ ] Bei `_hide-label=true` wird ein A11y-Hint in der Dev-Console angezeigt, dass ein sichtbares Label sein sollte.
- [ ] Der Tooltip sollte ein `*` Sternchen bei `_required=true` bekommen.

**Comment by sdvg** [comment]
@deleonio  Ein paar Beobachtungen im Zuge des Tickets:

- `input-color` und `input-range` haben keine `required` property. Stimmt das so?
- Ein Teil der Inputs verwendet den Controller aus dem `@deprated`-Ordner. Sollte das vor der 2.0 angepasst werden?
- (Die übrigen Input-Komponenten haben nicht so ganz einfach nachvollziehbar aufeinander aufbauende Controller, vielleicht könnte das auch einmal refactored werden.)

**Comment by deleonio** [comment]
> @deleonio Ein paar Beobachtungen im Zuge des Tickets:
> 
> * `input-color` und `input-range` haben keine `required` property. Stimmt das so?
> * Ein Teil der Inputs verwendet den Controller aus dem `@deprated`-Ordner. Sollte das vor der 2.0 angepasst werden?
> * (Die übrigen Input-Komponenten haben nicht so ganz einfach nachvollziehbar aufeinander aufbauende Controller, vielleicht könnte das auch einmal refactored werden.)

Vielen Dank für das Feedback:

- es gibt Input-Typen bei denen immer ein Wert gesetzt ist, dadurch sieht die W3C kein required vor (https://public-ui.github.io/docs/concepts/formular)
- (1, 2) Das ist vollkommen korrekt. Da das ausschließlich internal Code ist, können wir das jederzeit refactorn, wenn es passt.
