### ISSUE TITLE
🐞 Bug: Badge mit HideLabel erzeugt keinen Tooltip

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#4552]
# Fehlermeldung

## Beschreibung des Fehlers

Der Badge erzeugt keinen Tooltip, wenn `_hideLabel` gesetzt ist.

## Reproduktion

```tsx
<KolBadge _label="das ist ein tipp" _hideLabel _color={{ backgroundColor: '#000', foregroundColor: '#fff' }} _icon={'codicon codicon-info'} />
```

## Erwartetes Verhalten
Wenn _hideLabel gesetzt ist, erscheint ein Tooltip.

## Screenshots
Das Beispiel oben ergibt diesen schwarzen Block, der nicht mit der Tastatur erreichbar ist und auch per Maus keinen Tooltip erzeugt:
<img width="29" alt="image" src="https://github.com/public-ui/kolibri/assets/37439758/f4b98fdf-8754-40d4-9d7a-bfb7e2df59c3">

## Zusätzlicher Kontext
Version: 1.6.0-rc.23

**Comment by deleonio** [comment]
@laske185 Nachfrage: Badge sollte kein `_hideLabel`-Property haben¿!
