### ISSUE TITLE
Mutli-Select with Autocomplete-Search

### ISSUE THREAD

**Issue by AlexITZB** [public-ui/kolibri#4607]
> **Note**
> - [ ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

Wie im Meeting vom 10.8.2023 beschrieben bräuchten wir eine Eingabemöglichkeit, die auch bei großen Wertemengen eine komfortable Werteauswahl (Mehrfachauswahl) erlaubt.

Bei Eingabe eines Präfixes bzw. ab 2-3 Anfangsbuchstaben soll die Auswahl aus einer Wertemenge beschränkt werden.

Als Lösung gäbe es ein Input-Textfeld mit Autocomplete (bevorzugt) oder eine "Find-Zeile" bei einer Multi-Selectbox.

Screenshots:

InputText Autocomplete Multiple (bevorzugte Lösung):

<img width="576" alt="autocompleteMultipleInput" src="https://github.com/public-ui/kolibri/assets/141934283/42a56c52-dd07-4082-9554-16889dd51782">

SelectBox mit Finderzeile:
<img width="576" alt="Multiselect mit Find" src="https://github.com/public-ui/kolibri/assets/141934283/67c61a85-b077-4c80-9dfe-bbbcd5121bac">

**Comment by laske185** [comment]
Wird mit https://github.com/public-ui/kolibri/issues/3694 umgesetzt.
