### ISSUE TITLE
ToastService: Mehrere Toasts anzeigen in einem Container

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4647]
Momentan werden Toasts übereinander gestapelt. Die Toasts sollen untereinander angezeigt werden, in einem separaten Scrollbereich. Bitte auch Ein- und Ausblenden berücksichtigen ("Nachrutschen" implementieren → CSS-Klasse dafür setzen und im Theme eine Animation verstecken → "faden").

> Es ist notwendig in der App eine eigene `Toaster`-Instanz mit `new ToastService(document)` zu initiieren und diesen zu verwenden.

- [ ] Option im ToastService hinzufügen, default `1`, Validator >=1
- [ ] Wenn mehr als 1 Toasts angezeigt wird, einen schalter `Alle schließen` (mal schauen wie es die anderen machen)
- [ ] CSS-Klasse für das Einblenden
- [ ] CSS-Klasse für das Ausblenden
- [ ] Neueste Nachricht oben einfügen
- [ ] Vertical Scollbar

Optional:
- [ ] Immer so viele Toasts gleichzeitig anzeigen, wie Option

**Comment by Chrisdo82** [comment]
Und eine Dokumentation des ToastService wäre super :-)

**Comment by laske185** [comment]
Lösungsskizze:

- neue **interne** Komponente `ToastContainer`
  - Managt die anzuzeigenden Toasts
  - Toasts als Kinderelemente
  - Shadow-DOM Komponente
  - Basis-Style mit Standardeinstellungen: rechts am Rand und Toasts dann top-down
- `ToastService` initialisiert den `ToastContainer` statt einen `Toast`
- Beim `enqueue` wird ein neuer Toast angelegt und an den `ToastContainer` angehängt
