### ISSUE TITLE
🛹 Feature: Toasts untereinander anzeigen

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#4652]
Momentan werden Toasts übereinander gestapelt. Die Toasts sollen untereinander angezeigt werden in einem separaten Scrollbereich. Bitte auch Ein- und Ausblenden berücksichtigen ("Nachrutschen" implementieren → CSS-Klasse dafür setzen und im Theme eine Animation verstecken → "faden").

**Comment by deleonio** [comment]
https://github.com/public-ui/kolibri/issues/4647
