### ISSUE TITLE
💡 Hinweis: Tabellen Footer "Einträge pro Seite"

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#4653]
In der aktuellen Umsetzung wurden die "Einträge pro Seite" in der Tabelle mit einem Select umgesetzt. Aus Barrieresicht ist ein Button dafür besser geeignet, da eine Aktion ohne Bestätigung ausgelöst werden kann. 

Da dieses Element häufig in Anwendungen verwendet wird, z. B. bei Menüs, wäre es hilfreich eine eigene Komponente dafür zu bauen: "Dropdown-Button" oder "Select-Button":

Default (Ghost Button, regular):
<img width="446" alt="image" src="https://github.com/public-ui/kolibri/assets/118734593/34b6aee4-07f2-4e0f-887f-e7f71040942e">

Hover und Klick:
<img width="256" alt="image" src="https://github.com/public-ui/kolibri/assets/118734593/a8ad643f-ee74-4f9a-870f-55e07423d6db">

Dropdown-Menu:
<img width="301" alt="image" src="https://github.com/public-ui/kolibri/assets/118734593/5c1f7d73-3f6b-4dab-9e39-7a566bbb5737">

**Comment by deleonio** [comment]
https://github.com/public-ui/kolibri/issues/4646
