### ISSUE TITLE
💡 Hinweis: Form Input Roles `search` and `searchbox`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4654]
![image](https://github.com/public-ui/kolibri/assets/6279703/7f1935fe-9357-4e53-8c18-8ab36678f0f7)

**Comment by laske185** [comment]
Betrifft die WCAG 2.1 Kapitel 1.3.5: https://outline-rocks.github.io/wcag/translations/WCAG21-de/#bestimmung-des-zwecks

Die Rolle „search“ soll aber nicht dem Input zugewiesen werden, sondern dem umgebenden Element, um den Anwender mit Screenreader darauf hinweisen zu können. Also beispielsweise hätte dann die umgebende Form die Rolle „search“.

```html
<form role="search">
  <!-- search input -->
</form>
```

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/search_role
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/roles/searchbox_role

**Comment by deleonio** [comment]
Wir müssen überlegen, ob wir eine Role am `KolForm` setzen lassen wollen? Das zieht nach sich, dass auch ein `_label` gesetzt wrden muss.
