### ISSUE TITLE
Hinweis: InputCheckbox / InputRadio zeigt keinen :focus state an

### ISSUE THREAD

**Issue by SemihZerdeli** [public-ui/kolibri#4655]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

## Beschreibung des Fehlers
Die Checkbox und Radio Button Komponenten zeigen keinen Focus State an. Das heißt man kann diese zwar erfolgreich mit der Tab-Taste ansteuern, bekommt jedoch keine visuelle Indikation das ein Element angewählt ist.

## Reproduktion

https://public-ui.github.io/docs/components/input-checkbox --> Das Verhalten kann schon in den Beispielen beobachtet werden

Schritte zum Reproduzieren des Verhaltens:
- Gehe zu (https://public-ui.github.io/docs/components/input-checkbox)
- Klicke in den Beispielen auf die erste Checkbox
- Drücke die Tabulator Taste
- Siehe Fehler

## Erwartetes Verhalten
Ein visuell Erkennbaren Fokus-State der Komponente. Genauso wie bei den anderen InputKomponenten

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows10
- Browser Chrome
- Version 107.0.5304.107 (Offizieller Build) (64-Bit)

**Comment by deleonio** [comment]
Leider konnten wir das Problem nicht nachvollziehen. Können Sie uns Screenshots zeigen oder gerne in unserer CoP kommen.

**Comment by SemihZerdeli** [comment]
Ich hoffe mit diesen Screenshots ist das Problem anschaulicher dargestellt.

Schritt 1: Ich habe die KolInputSelect ausgewählt:
![select-input-auswahl](https://github.com/public-ui/kolibri/assets/11487294/11f82b29-eb0e-4ec4-84cf-20b6b50a3063)

Schritt 2: Ich drücke die Tabulator Taste auf meiner Tastatur (man sieht die RadioGroup, ist nicht angewählt - keine blaue Outline)
![select-input-auswahl-1-tab](https://github.com/public-ui/kolibri/assets/11487294/ec4f6b95-b56a-4e99-b06c-14d8fcc8b8f7)

Schritt 3: Erneutes Drücken der Tabulator-Taste (das nächste Element - der Button - ist ausgewählt):
![select-input-auswahl-2-tab](https://github.com/public-ui/kolibri/assets/11487294/0751dd4b-f509-4b7d-802b-ba6316df4499)

Dazu muss gesagt sein, es sind durch react-hook-forms kontrollierte Komponenten. Ich habe nach deinem Kommentar auch noch einmal das Beispiel auf der Kolibri Seite ausprobiert und zu meinem Erstaunen hatte das Anwählen funktioniert. Bei mir funktioniert es jedoch weder mit @leanup/form, react-hook-form und auch nicht mit der basis KolInputRadio oder KolInputCheckbox Komponente.

**Comment by laske185** [comment]
Wurde in der Zwischenzeit behoben.
