### ISSUE TITLE
🐞 Bug: Es muss IMMER ein sichtbares Label (Beschriftung) bei Input Elementen geben

### ISSUE THREAD

**Issue by ElVariablo** [public-ui/kolibri#4677]
> **Note**
> - [X ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Nach dem BIK BITV [Prüfschritt 9.3.3.2 "Beschriftungen von Formularelementen vorhanden"](https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-3-3-2-beschriftungen-von-formularelementen-vorhanden) muss geprüft werden, ob alle Formularelemente (alle Ausprägungen des Input tags) eine **_sichtbare_** Beschriftung haben.

## Ausnahme
Wenn ein einfaches Suchformular nur aus einem Eingabefeld und einem Button besteht, ist oftmals keine sichtbare Beschriftung notwendig. Voraussetzung ist jedoch, dass visuell verständlich ist, dass es sich um eine Suche handelt (z.B. durch Verwendung eines Lupe-Icons). 

## Hinweise
Das placeholder-Attribut ist keine ausreichende Beschriftung im Sinne dieses Prüfschritts. Es verschwindet bei (auch versehentlichen) Nutzereingaben.

**Comment by deleonio** [comment]
@ElVariablo, @PippiViktualia, @AntnSaj, @laske185 

Der Tooltip (so, wie es aktuell umgesetzt ist) ist eine sichtbare Beschriftung des Eingabefeldes und besteht m.E. den Prüfschritt. In den Prüfanforderungen steht nicht, dass die Beschriftung dauerhaft angezeigt werden muss.
