### ISSUE TITLE
💡 Hinweis: Dokumentation Input onChange ergänzen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4679]
- [ ] Readme von input-file um einen Absatz zu onChange erweitern.
  - Besonderheit: files wird als zweiter Parameter übergeben
- Beispiel: https://codesandbox.io/s/kolibri-public-ui-minimal-react-input-file-get-value-93p5nv
- ebenfalls onInput prüfen

**Comment by deleonio** [comment]
Dieses Ticket sollte er nach folgendem Ticket bearbeitet werden: https://github.com/public-ui/kolibri/issues/6030

**Comment by laske185** [comment]
Bereits erledigt.
