### ISSUE TITLE
Create-KoliBri / CLI - Samples fixen

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#4700]
Es gehen offensichtlich einige Create-Templates nicht mehr.

Anleitung:
- in das Teilprojekt: `packages/create-kolibri`
- `npm run test -- my-app` kann man direkt ausführen und ausprobieren
- `my-*` nicht mit einchecken!

Todo's:
- [x] Angular
- [x] React
- [x] Vue
- [x] Static
- [x] Vite-React
- [x] Vite-Vue

**Comment by sdvg** [comment]
Angular wird mit dem nächsten KoliBri-Release automatisch gefixt (Type Error)

**Comment by deleonio** [comment]
Kannst du bitte mit dem neuen Release noch einmal Angular und Vite-Vue testen. Bitte auch noch einmal npm run build ausführen. Danke

**Comment by sdvg** [comment]
Alle Templates aus der Checkliste wie folgt erfolgreich getestet:

- `npm start` funktioniert.
- `npm run build && npx http-server dist` funktioniert.
- Keine Fehler im Terminal oder der JS-Konsole.
