### ISSUE TITLE
Token-based Theme in Designer und Sample App einbauen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4722]
https://github.com/public-ui/kolibri/blob/224e9adbfad7964e0a05ecc6b1518c92ef082f2b/packages/designer/src/solid.main.tsx#L9

- [x] Umbenennung in DEFAULT und "default".
- [x] Designer einbauen
- [x] React-Sample einbauen
- [x] Website / Doku einbauen

**Comment by sdvg** [comment]
PRs für KoliBri und Website stehen bereit. Leider ungetestet, da das Theme nach dem Umbennen ja noch nicht importiert werden kann (ohne publish/dependency upgrade).
