### ISSUE TITLE
Link: _on-Property deprecation zurücknehmen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4724]
Wir werden die Deprecation für `_on` an den Link-Komponenten zurücknehmen.

Gründe:
- Das Öffnen des Links/Buttons im neuen Tab möglich. (Killer-Argument)
- Im Browser würde der HREF links unten angezeigt werden. (Sekundäres Argument)

TODO:
- [x] Alle Link-Komponenten Dreprecation entfernen
- [x] Dokumentation bei Bedarf anpassen
- [ ] Blog-Post in Dokumentation korrigieren

FYI @Chrisdo82

**Comment by sdvg** [comment]
Das KoliBri-PR ist bereit.
Im Website-PR habe ich bisher nur die Tabellen angepasst und dort [einen Kommentar](https://github.com/public-ui/public-ui.github.io/pull/176#discussion_r1301203621) hinterlassen.
