### ISSUE TITLE
Badge - expert slot funktioniert nicht

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#4740]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Lt. https://public-ui.github.io/docs/concepts/expert-slot sollte es bei der Badge einen Expert-Slot geben. Wenn ich diesen einbaue, wird der Inhalt jedoch nicht gerendert.

## Reproduktion

- Link zu CodeSandbox: https://codesandbox.io/s/minimal-kolibri-sample-forked-xqmzdr?file=/src/App.tsx

## Erwartetes Verhalten
Der Inhalt des Expert-Slots wird angezeigt.

**Comment by deleonio** [comment]
Hallo @Chrisdo82,

wir haben festgestellt, dass beim Badge kein Expert-Slot vorgesehen ist.

Welche Anforderung habt Ihr?

**Comment by Chrisdo82** [comment]
Bestimmte Elemente des Textes sollen anders formatiert (Fett, kursiv, etc.) werden können.

**Comment by deleonio** [comment]
@laske185: was denkst Du? Wenn wir das machen, dann müssen wir auch Tooltip slot'en.

**Comment by laske185** [comment]
Oder könnte man auch eine Markdown-Notation nutzen, um eine reine Formatierung zu ermöglichen?

**Comment by deleonio** [comment]
@Chrisdo82 

Wir überlegen hierzu einen Markdown-Feature umzusetzen. @laske185 hat das schon gemacht. Damit könnt Ihr dann auch gestalterisch als Zeichenkette arbeiten.

Slot ist noch nicht ganz von der Liste.

> https://marked.js.org/

**Comment by gretaneumannn** [comment]
Wir haben zwei weitere Anforderungen zu der Badge Komponente gesammelt: 

- Wir benötigen bestimmte Badges (mit bestimmten Farbkombinationen), die aus dem Farbenspektrum des Styleguides der Bundesregierung stammen --> Dafür muss die Schriftfarbe anpassbar sein und nicht automatisch generiert werden
![image](https://github.com/public-ui/kolibri/assets/118734593/35fdf13b-a5ae-4b23-ad5e-147822fc7d92)
- Badge mit Schalter soll auf eine sichtbare Höhe von 32px angepasst werden (die Klickhöhe soll bei 44px belassen werden)
![image](https://github.com/public-ui/kolibri/assets/118734593/af3dcc91-c6eb-43a2-9b0f-4fbd70453af4)

**Comment by laske185** [comment]
Die Schriftfarbe kann bereits gesetzt werden:
```jsx
<kol-badge _label="Beispieltext" _color='{ "backgroundColor": "#000", "foregroundColor": "#f00" }' _icon="codicon codicon-home"></kol-badge>

```

**Comment by Chrisdo82** [comment]
@laske185 funktioniert das mit Version 1.6.2? Bei mir läuft es irgendwie nicht so wie gewollt, die `color` ist nicht die die ich mitgegeben habe: https://codesandbox.io/s/minimal-kolibri-sample-forked-d8g348?file=/src/Badge.tsx:601-608

**Comment by deleonio** [comment]
Hallo @Chrisdo82,

es scheint m.E. alles korrekt zu sein: https://stackblitz.com/edit/vitejs-vite-lmkayf?

**Comment by Chrisdo82** [comment]
<img width="1466" alt="Bildschirmfoto 2023-09-11 um 09 23 15" src="https://github.com/public-ui/kolibri/assets/6606913/9db0e729-b385-4cb7-8843-1fde25c6794b">

Die Farben sind zwar ähnlich und mit dem bloßen Auge nicht zu erkennen, aber es sind nicht exakt die gleichen. @deleonio

**Comment by deleonio** [comment]
Hallo @Chrisdo82 , @gretaneumannn -

Bezüglich der Umcodierung, werden wir erstmal keine Änderungen vornehmen. Die Farbwerte am Property werden über eine Lib berechnet und in diesem Format bei genügend Abstand zurückgegeben.

Ich lasse das Ticket auf, jedoch ist im Vergleich zu anderem Tickets muss ich herunter priorisieren.

- [ ] Wenn die reingegebenen Farbwerte genügend Abstand haben, dann könnte man auch diese 1zu1 auf den State mappen.
