### ISSUE TITLE
Readme Code-Snippets auf den aktuellen Stand bringen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4746]
Zahlreiche Code-Beispiel in den Readme's sind veraltet. Sollte out-of-the-box funktionieren.

Bspw.

![Image](https://github.com/public-ui/kolibri/assets/6279703/9eecb160-b4dc-42e0-bc46-3c367950743d)

**Comment by sdvg** [comment]
Toast habe ich erst einmal übersprungen. Hier wird zur Zeit `kol-alert` dokumentiert. Vielleicht kann man hier Teile des Blog-Posts übernehmen, sobald dieser fertig ist?

**Comment by sdvg** [comment]
Dialog, Modal und Popover sind ebenfalls Spezialfälle, die gerade kein Beispiel haben.

**Comment by sdvg** [comment]
Hier wird die Readme zur Zeit gar nicht eingebunden: https://public-ui.github.io/docs/components/kolibri
Absicht?
