### ISSUE TITLE
💡 Hinweis: Button mit Export-Slot und _iconOnly

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4747]
Guten Morgen,

ich habe einen LoadingButton gebaut der nach dem Wechsel des Ladezustands, noch für ein paar Sekunden einen Haken anzeigt. Hier zu sehen: https://codesandbox.io/p/sandbox/minimal-kolibri-sample-forked-r3df27?file=%2Fsrc%2FButton.tsx%3A86%2C27

Allerdings funktioniert das Ganze nicht, wenn _iconOnly gesetzt ist, da dann der expert Slot nicht verwendet wird. 

Hast du eine Idee, wie wir die gleiche Funktionalität auch für _iconOnly gewährleisten können?

**Comment by sdvg** [comment]
Was soll der Button im Erfolgsfall genau darstellen? Das Plus Icon UND den Haken, oder nur den Haken?
Für mich würde letzteres mehr Sinn ergeben, weil dann auch die Breite des Buttons gleich bleibt.

In dem Fall könnte  schon eine Änderung wie folgt in L53 ausreichen:
```diff
-_icon={_iconOnly ? _icon : undefined}
+_icon={_iconOnly ? showCheckmark ? "success" : _icon : undefined}
```

(Ich kann es leider gerade nicht testen weil Code Sandbox mich nicht einloggen lässt.)

**Comment by deleonio** [comment]
Gehören die Issues zusammen? https://github.com/public-ui/kolibri/issues/4740

**Comment by sdvg** [comment]
@deleonio Ich glaube der große Unterschied ist, dass bei Badge gar kein Expert Slot vorgesehen ist.

**Comment by deleonio** [comment]
Spin Komponente im Button wiederverwenden. Standard-Animation oder `expert-spin` für eigene

**Comment by deleonio** [comment]
redundant
