### ISSUE TITLE
Docusaurus / Dokumentation - Multi-Version Konfiguration erarbeiten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#4748]
Wir müssen für das 2. Release die Dokumentation in min. zwei Versionen anbieten. Dazu muss die Konfiguration gesucht und erprobt werden.

Ein repräsentatives Beispiel reicht erstmal: https://docusaurus.io/

**Comment by sdvg** [comment]
Referenz: https://docusaurus.io/docs/versioning

- `readmes` müssen nach `docs` verschoben werden, damit sie mit versioniert werden (im PR bereits angepasst).
- Workflow: Nach jedem Release muss die aktuelle Version "getaggt" werden: `npm run docusaurus docs:version $version`.
  - 💡 Gut zu wissen: Wenn man versucht die selbe Version mehr als einmal zu erstellen, schlägt der Build fehl.
- Die zuletzt getaggte Version wird per default angezeigt, über die Nav lassen sich der aktuelle main stand ("Next") sowie ältere Versionen auswählen:
<img width="338" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/85f6bbbe-a654-426c-9edd-728fbc657460">

- Docusaurus generiert automatisch Hinweise für die nicht aktuell Version:
<img width="1170" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/cc82f009-6fa6-4018-b7fe-00689e4732df">
<img width="1004" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/3c776b4d-ce55-4c40-90a0-760910dc7c9d">

**Comment by sdvg** [comment]
Das PR beinhaltet jetzt die versionierten Docs für die letzten beiden Versionen: `1.6.0` und `1.6.1`.
