### ISSUE TITLE
Hinweistext am Input als Tooltip

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#4761]
Der Hinweistext an Eingabefeldern nicht mehr darunter platziert werden, sondern in einem Tooltip über einem I-Icon hinter dem Eingabefeld. 

![Image](https://user-images.githubusercontent.com/37439758/262253289-ed68e0d5-a7bd-475b-81ae-357ac76314b8.png)

**Comment by deleonio** [comment]
Bei der Umsetzung ist aufgefallen, dass diese Form Problem mit sich bringt. Daher wird es nicht umgesetzt.

@laske185 Begründen

**Comment by laske185** [comment]
Hinweistexte über Tooltips anzuzeigen, hat folgende Nachteile:
- Es kann immer nur ein Tooltip angezeigt werden.
- Somit kann man Hinweistexte nicht abgleichen.
- Es muss immer mehrmals getappt werden, um in das nachfolgende Feld zu gelangen.

Eine geeignete Möglichkeit, Hinweistexte innerhalb eines Formulars einzubetten, ist:
- Texte weiterhin unterhalb des Eingabefeldes anzeigen.
- Die Schriftfarbe sollte leicht heller sein, als die der Labels, um sie in den Hintergrund zu rücken.
- Über einen Schalter (z. B. `<KolInputCheckbox _variant="switch" ... />`) die Hinweise ein- und ausblenden.
- Anfangs die Texte ausblenden, damit der Benutzer explizit Hinweise zuschalten kann, falls nötig. Andere Nutzer werden nicht beeinträchtigt.
