### ISSUE TITLE
KolKolibri not found in starter app (create-app cli)

### ISSUE THREAD

**Issue by timde** [public-ui/kolibri#485]
Hi,

KolKolibri Component is not imported: 

https://github.com/public-ui/kolibri/blob/82632e255b0650c6049d6dedf08d77a605838754/packages/create-kolibri/templates/react/src/components/app/component.tsx#L21

Kind regards
Dennis

**Comment by deleonio** [comment]
Vielen Dank

Wird mit Release 1.1.8. behoben.
