### ISSUE TITLE
Multi-Select zu schmal

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#4918]
Das Multi-Select nimmt nicht mehr die volle Breite ein. In der 1.5.3 war es noch ok.

![Image](https://user-images.githubusercontent.com/37439758/259731172-cb4094fd-635c-4964-90a5-5b18145994df.png)

**Comment by sdvg** [comment]
`bamf`: zu schmal
`bzst`: Breite passt, aber Optionen werden on hover unsichtbar
`bmf`: zu schmal
`desy-v1`: passt 
`desy-v2` passt
`ecl-ec`: zu schmal
`ecl-eu`: zu schmal
`mfm`: zu schmal
`mapz`: zu schmal
`default`: zu schmal
`zoll-v2`: zu schmal

Lösung:
- `width: 100%` in den Component-Styles hinzufügen
- Hover-Farbe für `bzst` korrigieren
