### ISSUE TITLE
Card: Breite kann nicht ganz ausgenutzt werden

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#4924]
Layout-Bug: Card-Breite kann nicht vollständig genutzt werden.

![Image](https://user-images.githubusercontent.com/971072/263279419-3e445210-69de-4273-92c7-1de574890170.png)

**Comment by deleonio** [comment]
Hi @sdvg, ich habe mir das angesehen und ich habe das Gefühl, die Konstruktion ist nicht okay.
