### ISSUE TITLE
💡 Hinweis: Prüfen der Klickflächenhöhe bei Checkbox, Switch, Radio 

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#4993]
Die Klickflächenhöhe bei Checkbox, Switch, Radio beträgt nicht 44px. Muss dies auch eingehalten werden für AAA?

**Comment by gkollotzek** [comment]
Es ist auch aufgefallen, dass es momentan einen Bereich zwischen Checkbox und Label gibt, der nicht klickbar ist.

**Comment by deleonio** [comment]
Basis-Styling beinhaltet die erforderliche Definition von 44px.

**Comment by deleonio** [comment]
- [x] EU Themes optimieren
- [x] TH entfernen / Dep entfernen

**Comment by laske185** [comment]
Todo: Klickflächen beim Default und EU-Themes prüfen und fixen.

Bei Unklarheiten bitte auf Test-Team zugehen!
