### ISSUE TITLE
🐞 Bug: Kol-Password - Passwort an- und auszeigen funktioniert nicht

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#4994]
Der Schalter, um das Passwort ein- und auszublenden funktioniert nicht mit Maus und Tastatur. Frage wäre, ob sobald die Funktion hinterlegt ist, das Ansteuern per Tastatur möglich ist.

**Comment by deleonio** [comment]
@gretaneumannn @Chrisdo82 

Bitte hier anschauen: https://youtu.be/0REpAEzopmA?si=OcNgrJeUk_yvgLSl&t=1113
