### ISSUE TITLE
🛹 Feature: Paginierung - Nicht ausgewählten Seiten in „regular“

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#4995]
Bei nicht ausgewählten Seiten in der Paginierung sollte die Schriftart „regular“ sein. Nur bei der ausgewählten Seite soll die Schriftart "bold" sein, damit auch über die Form und nicht nur über die Farbe unterschieden wird (Barrierefreiheitsanforderung).

![image](https://github.com/public-ui/kolibri/assets/118734593/44e9cd07-5c9b-4ff6-9aeb-ea184f6a051f)

**Comment by deleonio** [comment]
Wird mit dem Ticket https://github.com/public-ui/kolibri/issues/5026 bearbeitet.
