### ISSUE TITLE
Fehlender Open-Callback im Details

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#4996]
Es wird ein Callback benötigt, der aufgerufen wird, wenn die Details-Komponente auf oder zugeklappt wird. Damit kann die Details-Komponente initial als offen eingesetzt werden.

```tsx
const [isOpen, setOpen] = React.useState(true);

return <>
	<KolDetails _label="Header" _open={isOpen} _on={{onOpen=(o) => setOpen(o)}}>
		<span>Ich bin der Inhalt</span>
	</KolDetails>
</>;
```

**Comment by sdvg** [comment]
Ich habe as Event `onToggle` genannt, analog zur HTML-Spec. Falls das nicht passt, gerne noch mal was sagen.
