### ISSUE TITLE
🐞 Bug: KolInputRadio horizontal - Darstellungsfehler nach Rerendering

### ISSUE THREAD

**Issue by robertdue** [public-ui/kolibri#5003]
# Bug: KolInputRadio horizontal - Darstellungsfehler nach Rerendering

## Beschreibung des Fehlers
Nach dem Rerendern des KolInputRadio werden alle RadioInputs außer des Ersten falsch dargestellt:

![image](https://github.com/public-ui/kolibri/assets/32411533/325faf24-2227-481d-9857-cb78c5371198)

Im DOM-Baum wird jeweils ein zweites leeres Input gerendet:
![image](https://github.com/public-ui/kolibri/assets/32411533/38758325-5bf3-4f20-a284-be4e7552e3d6)

## Reproduktion
https://codesandbox.io/s/minimal-kolibri-sample-forked-l2xrlm?file=/src/App.tsx

Schritte zum Reproduzieren des Verhaltens:

KolInputRadio rendern, danach das Element ausblenden und erneut rendern (siehe CodeSandbox Beispiel)
Versionen:

    "@public-ui/components": "1.6.2",

    "@public-ui/core": "1.6.2",

    "@public-ui/react": "1.6.2",

    "@public-ui/themes": "1.6.2",

## Erwartetes Verhalten
Korrekte Darstellung auf einer Höhe

## Desktop:
- Betriebssystem: MacOS
- getestet unter Chrome & Safari

**Comment by deleonio** [comment]
Fixed: https://public-ui.github.io/v2/sample-react/#/input-radio/horizontal
