### ISSUE TITLE
Markdown-Support

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#5025]
Das Badge und der Tooltip sollen für die Formatierung die Markdown-Notation unterstützen. Dabei wird der Text der `_label`-Property entsprechend geparst.

Mit diesem Framework soll es realisiert werden: https://marked.js.org/ 

Löst dieses Issue: https://github.com/public-ui/kolibri/issues/4740

**Comment by deleonio** [comment]
- Bitte prüfen
  - [ ] Unterstreichung von Buchstaben
  - [ ] Bagde via Markdown im `_label`

**Comment by gretaneumannn** [comment]
Wie soeben besprochen, sollen folgende Features zu diesem Ticket aufgenommen werden: 

- [ ] Prüfen der technischen Machbarkeit von Badges in Tooltip? 
- [ ] Prüfen, ob einzelne Buchstaben in Tooltips formatiert werden können, z. B. unterstreichen?

![image](https://github.com/public-ui/kolibri/assets/118734593/50d214d6-694c-492d-947e-dddc097cfaff)

**Comment by deleonio** [comment]
Soll das "a" auch vorgelesen werden?

- [ ] HTML-Support bei Markdown aktivieren
- [ ] `aria-hidden` von außen mitgeben

_u_

<u>u</u>
<ins>u</ins>

`<kol-badge _label={`<u>A</u>nzeigen <kol-badge aria-hidden="true" _label="a"/>"`} />`

**Comment by gretaneumannn** [comment]
> Soll das "a" auch vorgelesen werden?
> 
> * [ ]  HTML-Support bei Markdown aktivieren
> * [ ]  `aria-hidden` von außen mitgeben

Ja, das "a" soll vorgelesen werden , aber kenntlich als Tastaturkürzel

**Comment by deleonio** [comment]
@gretaneumannn, @Chrisdo82 

Wir werden dieses Feature wie folgt umsetzen:



![Image](https://github.com/public-ui/kolibri/assets/6279703/c6f967c4-25dd-43a7-a3e9-ba56146e3ada)

- Ohne Unterstreichung
- Ohne notwendiges Markdown
- Über das Property `_accessKey` wird automatisch der Buchstabe in einem kleinen `span` mit `aria-hidden="true"` angezeigt

**Comment by deleonio** [comment]
Wird in diesem Ticket gemacht: https://github.com/public-ui/kolibri/issues/5392
