### ISSUE TITLE
💡 Hinweis: Pagination die Shadow-Buttons gegen NonShadow-Buttons austauschen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5026]
Damit die Pagination frei gestaltbar ist, sollen die `<kol-button ` in `<kol-button-wc ` ausgestauscht werden und die Themes entsprechen nachgestyled werden.

Die Frage wäre hier, ob man bei der Pagination noch die Varianten benötigen würde?

![image](https://github.com/public-ui/kolibri/assets/6279703/a2c376d6-f2ef-4021-b60d-f3eda2f8aed5)

**Comment by Chrisdo82** [comment]
Meinst du die Varianten der anderen Buttons oder des aktiven @deleonio?

**Comment by deleonio** [comment]
Arbeitsteilung + Refactoring BMF - Themes nachziehen KoliBri
