### ISSUE TITLE
💡 Hinweis: Readme.md in allen Packages auf den Kontext anpassen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5029]
Die `README.md`'s der NPM-Pakete muss auf den Inhalt des Pakets angepasst werden. Zudem sollte eine kurze Anleitung enthalten sein, wie das Paket verwendet werden kann.

**Comment by sdvg** [comment]
Checklist:

- [x] packages/adapters/angular/v11
- [x] packages/adapters/angular/v12
- [x] packages/adapters/angular/v13
- [x] packages/adapters/angular/v14
- [x] packages/adapters/angular/v15
- [x] packages/adapters/angular/v16
- [x] packages/adapters/angular/v17
- [x] packages/adapters/hydrate
- [x] packages/adapters/preact
- [x] packages/adapters/react
- [x] packages/adapters/react-standalone
- [x] packages/adapters/solid
- [x] packages/adapters/vue
- [x] packages/components
- ~~packages/core~~
- [x] packages/designer
- [x] packages/samples/react
- [x] packages/schema
- [x] packages/themes
- [x] packages/themes/bmf
- [x] packages/themes/bzst
- [x] packages/themes/default
- [x] packages/themes/ecl
- [x] packages/themes/itzbund
- [x] packages/themes/mfm
- [x] packages/tools/kolibri-cli
- [x] packages/tools/visual-tests
