### ISSUE TITLE
Blog-Post: Require-Handling bei Fieldsets

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5054]
Wie wird die Barrierefreiheit sichergestellt, wenn in einem Fieldset mehrere Checkbox angeboten werden, aber mindestens eine ausgewählt werden muss.

https://codesandbox.io/s/fieldset-many-checkboxes-required-yhf3hr

![image](https://github.com/public-ui/kolibri/assets/6279703/673982cc-3c57-4d28-a687-e9d719d6c997)

- [ ] Form Readme
- [ ] Blog-Post

**Comment by cbraehmig** [comment]
So könnte eine mögliche Umsetzung aussehen.

![image](https://github.com/public-ui/kolibri/assets/93573283/53b79cf9-44bf-485e-8ec3-42a2fe94cd32)

Dabei ist zu überlegen, an welchem Element das "required"-Attribut definiert werden muss. Sehr wahrscheinlich am Fieldset. Dazu passen das folgende Issue.

https://github.com/whatwg/html/issues/6868
