### ISSUE TITLE
🐞 Bug: Tooltip innerhalb von Details falsch positioniert

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#5056]
# Fehlermeldung

## Beschreibung des Fehlers
Tooltips, die innerhalb der `KolDetails` Komponente dargestellt werden, sind falsch positioniert.

## Reproduktion

- Link zu Codesandbox: https://codesandbox.io/s/public-ui-kolibri-tooltip-in-details-8687x5?file=/src/index.tsx:3911-4572

## Erwartetes Verhalten
Der Tooltip sollte an der richtigen Stelle darrgestellt werden.

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/37439758/c1c35d81-a998-4fc7-b132-bd6c981171d7)

**Comment by sdvg** [comment]
Das Problem kommt von der scale-Property, die beim öffnen/schließen von details animiert wird.

Man könnte das bestimmt fixen, ich würde aber vorschlagen, die property einfach raus zu nehmen. Grund: Der Effekt ist wirklich minimal, und m.E. gehören solche Animationen nicht in die Component-Styles sondern eher in ein Theme?

<details>

```
@keyframes details-show {
	to {
		opacity: 1;
		scale: 1;
	}
}
.content {
	opacity: 0;
	scale: 1 0;
	transform-origin: top;
}
details[open] > .content {
	animation: 250ms ease-in-out forwards details-show;
}
```

</details>

**Comment by sdvg** [comment]
Falls die Animation wieder hinzugefügt werden soll, sollte dies auf einem der inneren Elemente, nicht auf der von float-ui verwendeten Wrapper-Componente, geschehen.
