### ISSUE TITLE
🛹 Feature: KolHeading - Größe der Überschriften veränderbar unabhängig von _level

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5096]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Die jeweilige Größe der Überschrift wird derzeit ausschließlich über das _level Attribut gesetzt. Das ist aber nicht ideal. Wir möchten beispielsweise in der Lage sein eine h3 wie eine h2 darzustellen.

## Beschreiben Sie die gewünschte Lösung
Ich kann die font-size und line-height von außen verändern ohne dabei das Level verändern zu müssen. Egal wie.

**Comment by deleonio** [comment]
Wir haben Deine Anfrage ins Backlog aufgenommen. Möglichkeit wäre auch hier `_variant` einzuführen und dort zwischen allen 7 Typen wechseln zu können.

- [ ] Styling nicht über den Tag sondern über eine einzuführende CSS-Klasse, z. B. `h1`

| `_level` | `_variant` (default) | 
| :---: | :---: |
| 0 | `strong` |
| 1 | `h1` |
| 2 | `h2` |
| 3 | `h3` |
| 4 | `h4` |
| 5 | `h5` |
| 6 | `h6` |
