### ISSUE TITLE
Checkbox: Icons für `checked`, `indeterminate`, `unchecked`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5100]
Es gibt schon die Möglichkeit, die Icons anzugeben. Bisher wurden sie jedoch noch nicht in der Komponente weiterverarbeitet.

**Comment by deleonio** [comment]
![Image](https://github.com/public-ui/kolibri/assets/6279703/1f49f47b-6ab0-47eb-afcb-7239daf49e0f)

**Comment by sdvg** [comment]
Themes passe ich an, bis auf BzSt und Thüringen, die haben aktuell kein richtiges Styling für den Switch-Button ([siehe Bsp.](https://public-ui.github.io/sample-react/#/input-checkbox/basic?theme=th))

**Comment by deleonio** [comment]
Hallo @sdvg,

**Comment by deleonio** [comment]
Hallo @sdvg 

hier passt noch etwas nicht, kannst Du bitte noch einmal drüberschauen?

<img width="337" alt="image" src="https://github.com/public-ui/kolibri/assets/6279703/11e4d245-b744-434e-88a2-a78b348ea885">

Ich habe den Merge reverted und den Branch wiederhergestellt.

- Branch: https://github.com/public-ui/kolibri/tree/revert-5291-revert-5274-5100-checkbox-icons-f%C3%BCr-checked-indeterminate-unchecked
- PR: https://github.com/public-ui/kolibri/pull/5294

**Comment by sdvg** [comment]
Das Problem sollte jetzt gepatcht sein, über die Ursache würde ich die Tage gerne einmal sprechen @deleonio.
