### ISSUE TITLE
🛹 Feature: Inputs, Select and Textarea can switch beetween alert type `default`, `error`, `info`, `success` or `warning`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5102]
An den Formular-Feldern sollen alle Typen von `Alert`'s möglich sein. Dafür müssen wir erst ein Umsetzungskonzept auflegen.

- [ ] Motivation und Spezifikation kären

![image](https://github.com/public-ui/kolibri/assets/6279703/2d1f49ec-7849-40df-b425-8d14cafbb651)

**Comment by deleonio** [comment]
Lasst uns dazu noch einmal im Daily oder Refinement sprechen: hier ist ggf. ein neues Property `_error-type` hilfreich

**Comment by chriskrj** [comment]
genau wir hatten ein weiteren `_type` bei der Alert Komponente im Blick z.B. `form-error` welcher für Validation Messages verwendet werden kann. Der `_error-type` sollte dies dann für Form-Elemente als Standard `_type` setzen. 

Ob noch andere "error-types" für Inputs, Select & Textarea sinnvoll ist, würde ich erstmal infrage stellen. Zurzeit ist mir kein Use-Case bekannt.

**Comment by deleonio** [comment]
@chriskrj, was genau unterscheidet ein `form-error` von einem `error`?

**Comment by chriskrj** [comment]
Grundsätzlich unterscheiden sich die beiden Typen in der Darstellung / Anwendung. 
![image](https://github.com/public-ui/kolibri/assets/23551989/f8031065-cf5e-4ed2-bb3b-0022a4c88277)

Hinweis oberhalb eines Formulars. Zusammenfassung von Formularfehlern usw. 

Oder direkt als Validierungshinweis unterhalb eines Formularfeldes.
![image](https://github.com/public-ui/kolibri/assets/23551989/79600be4-62f8-4c3b-ad5c-bbff0b14f98f)


Die Funktionalität ändert sich hierbei nicht. 
Theoretisch reden wir hier eigentlich von möglichen CSS Classes, die angesteuert werden können, je nach `_type`

**Comment by laske185** [comment]
Optimal wäre es, wenn der Hinweis mit einer `_alert` Property gesetzt wird. Diese wird im Ticket https://github.com/public-ui/kolibri/issues/6138 obsolete. Das Entfernen kann erst in V3 geschehen. Deshalb muss die Meldung übergangsweise in `_msg` hinterlegt werden. Der Typ ist `Alert`. In der V3 kann `_msg` in `_alert` umbenannt werden.

- _error wird deprecated und wird auf _msg gemappt
- _msg hat den Type von der KolAlert-API (später zu v3 wird _msg durch _alert ersetzt, so es dann ungenutzt)

**Comment by sdvg** [comment]
Im ersten Schritt belassen wir die Property _alert, wie sie ist.
