### ISSUE TITLE
Icon-Klasse innerhalb der Komponenten generisch benennen

### ISSUE THREAD

**Issue by chriskrj** [public-ui/kolibri#5103]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

> _Beschreiben Sie möglichst genau, wobei wir Ihnen helfen können._

Moin, ich würde gerne das Card Template und die dazugehörigen AlertType Icons überschreiben. 
Wir nutzen die Material-Symbols Icon Bibliothek und beim Alert werden standardmäßig codicon icons verwendet.

```js
const AlertIcon = (props: { label?: string; type?: AlertType }) => {
	switch (props.type) {
		case 'error':
			return <Icon ariaLabel={translate('kol-error')} icon="codicon codicon-error" label={props.label} />;
		case 'info':
			return <Icon ariaLabel={translate('kol-info')} icon="codicon codicon-info" label={props.label} />;
		case 'warning':
			return <Icon ariaLabel={translate('kol-warning')} icon="codicon codicon-warning" label={props.label} />;
		case 'success':
			return <Icon ariaLabel={translate('kol-success')} icon="codicon codicon-pass" label={props.label} />;
		default:
			return <Icon ariaLabel={translate('kol-message')} icon="codicon codicon-comment" label={props.label} />;
	}
};
```
 
Grundsätzlich nutzen wir die Kolibri-library und wrapen die bestehenden Komponenten mit unserem eigenen namespace und teilweise anderen properties.

Im Return sieht das dann bei der Alert Komponente z.B. so aus:

```js
public render(): JSX.Element {
  return (
    <kol-alert
      onClick={this.state._onClick}
      _custom-class={this.state._customClass}
      _type={this.state._type}
      _variant="card"
      _label={this.state._label}
      // _icon={this.state._icon}
      _level={this.state._level}
    >
      <slot />
    </kol-alert>
  );
}
```

**Comment by chriskrj** [comment]
ich konnte die Icons im CSS Überschreiben. sodass codicon-info für mich dann ein material symbol ist. 

Wir sollten hier aber auf die Bezeichnung Codicon verzichten und nur eine Statusklasse verwenden. Je nachdem welches Iconset verwendet wird, es nicht zu Verwirrungen kommt. 

Wird Codicon durch das Basis-Theme immer geladen?

**Comment by deleonio** [comment]
Ja, Codicon wird immer mitgeliefert, aber nicht geladen. Alle Iconfonts müssen in der Rahmenseite eingebunden sein.

**Comment by deleonio** [comment]
Änderungswunsch:

- [ ] Erst beginnen, wenn visuelle Regressionstests stehen
- [ ] Es soll kein fester Font-Bezug in KoliBri sein.
- [ ] Klassen generisch benennen
- [ ] Themes müssen angepasst werden
