### ISSUE TITLE
📖 Feature: Table - Nutzung von render

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5124]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

Das `render`-Attribut das innerhalb der `_header` Spalten gesetzt werden kann, ist nicht dokumentiert. Ich möchte das jetzt verwenden, weiß allerdings nicht wie.

**Comment by deleonio** [comment]
Hi @Chrisdo82,

das Rendern im Header ist nicht umgesetzt. Daraus müssten wir ein Feature-Request machen.

**Comment by Chrisdo82** [comment]
Hi @deleonio, es ist doch umgesetzt: siehe Types `KoliBriTableRender`. Nur in der Dokumentation beschrieben ist es nicht. 

Mittlerweile habe ich auch rausgefunden wie man es benutzt. Denke aber, dass das auch in eurer Dokumentation stehen sollte.

**Comment by deleonio** [comment]
- [ ] Beispiel in Doku aufnehmen, wie man Zellen rendern kann.

**Comment by deleonio** [comment]
Funktion: ist umgesetzt

**Comment by gretaneumannn** [comment]
Kann geschlossen werden, da nur noch die Doku ausstehend ist.
