### ISSUE TITLE
🐞 Bug: Tooltip - zu schmale Breite des Tooltips innerhalb eines Flex Containers

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5165]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn sich ein Element das ein Tooltip rendert (z.B. Button) innerhalb eines Flex-Containers befindet, dann wird der Tooltip genauso schmal wie der flex-Container. Die Tooltips sind so sehr schwer lesbar.

## Reproduktion

Nutzen Sie die [StackBlitz](https://stackblitz.com/edit/vitejs-vite-dcg6xo), um ein reproduzierbares Beispiel zu erstellen.

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-ee2sip?file=src%2FApp.tsx

Schritte zum Reproduzieren des Verhaltens:
- Hover auf den Button 

## Erwartetes Verhalten
Die Tooltips nehmen nicht die Breite des Containers an.

**Comment by sdvg** [comment]
Lösungsansatz: Tooltip-Breiten werden durch CSS-Custom-Variables steuerbar:

Verwendung:
```
<kol-button style="--kol-tooltip-width: 30rem" _label="Tooltip Content" _hide-label>
```

bzw. im CSS, auch in Kombination mit Media Queries, etc.:

```
@media(min-width: 768px) {
  .button-with-tooltip {
    --kol-tooltip-width: 30rem
  }
}
```


Skizze zur Implementierung:

```
.tooltip {
  width: var(--kol-tooltip-width)
}
```

**Comment by deleonio** [comment]
@sdvg Hi Stefan, das ist doch schon umgesetzt, nicht?

**Comment by sdvg** [comment]
@deleonio nein, nicht dass ich wüsste. Können wir aber gerne bald einplanen.
