### ISSUE TITLE
🐞 Bug: Inputs - style Prop bei _icon wird ignoriert

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5173]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Lt. des Types `KoliBriCustomIcon` kann einem Inputfeld (z.B. KolText) ein Icon mit Styles übergeben werden (z.B. `_icon={{ left: { icon: 'fas fa-lock', style: { color: '#fff' } } }}`). Das `style`-Property wird jedoch ignoriert.

## Reproduktion

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-vhm9o6?file=src%2FApp.tsx

## Erwartetes Verhalten
`style` sollte entweder aus dem `KoliBriCustomIcon`-Type entfernt oder die Funktion implementiert werden. So sorgt es jetzt für Verwirrung.

**Comment by deleonio** [comment]
Das Styling der Schmuck-Icons soll nachgerüstet werden:

- [ ] siehe KolSpan https://github.com/public-ui/kolibri/blob/92d05301929f1e00ced60f32983e4da32e2d57bd/packages/components/src/components/span/component.tsx#L29
