### ISSUE TITLE
invalid input ids

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5272]
Many inputs (including kol-select and kol-textarea) have 
a) an id that starts with a number (nonce) and
b) the same id as the hidden input

![Image](https://user-images.githubusercontent.com/117265922/253482199-be5b90c2-9abf-4a7b-9dbe-61fd4917488e.png)

![Image](https://user-images.githubusercontent.com/6279703/268659628-4dbc6966-33d2-4002-b852-b317c4a1da45.png)

**Comment by sdvg** [comment]
Ich kann hier kein Problem mehr feststellen:
* Das hidden-Field bei selects (erster Screenshot) scheint es nicht mehr zu geben.
* IDs bei selects und inputs sind jetzt grundsätzlich mit `id-` prefixed.
* Die Zuordnung der labels über das `for`-Attribut passt, auch bei "hidden labels".
* Die tooltip-area (letzter Screenshot) hat eine nicht zugeordnete ID, eine Solche Zuordnung wäre aber auch redundant zum eigentlichen Label.

**Comment by deleonio** [comment]
- https://github.com/public-ui/kolibri/issues/4193
- https://github.com/public-ui/kolibri/issues/4194
- https://github.com/public-ui/kolibri/issues/5272
