### ISSUE TITLE
Themes überarbeiten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5297]
Folgende Themes sollte, in der React Sample App ein grundsätzlich gutes Bild abgeben. Dazu sollen notwendige Stylings nachgezogen und ggf. in den Basis-Styles zusammengeführt werden.

> Es geht in diesem Ticket nicht darum, die Stylegruids "pixelgenau" umzusetzen. Es ist wichtiger, dass der Gesamteindruck über alle relevante Theme gut ist. Die Detailarbeit pro Theme erfolgt in separaten Arbeitsgruppen.

- [ ] BMF
- ~~BZSt.~~
- [ ] Default
- [ ] ECL EC -> https://ec.europa.eu/component-library/ec/components/ (hier möglichst genau arbeiten)
- [ ] ECL EU -> https://ec.europa.eu/component-library/eu/components/ (hier möglichst genau arbeiten)
- [ ] ITZBund
- ~~MFM~~
- [ ] MAPZ
- [ ] ZollV2

Umsetzungshinweise:

- Arbeiten in drei Modulen
  - `components`
    - ggf. ergeben sich zu konsolidierende Styles für die Basis-Styles
  - `samples/react`
    - `npm start`
    - URL`**/all` nutzen, damit mehrere Themes auf einer Seite sichtbar werden
      - http://localhost:8080/#/nav/active/all
      - https://github.com/public-ui/kolibri/commit/a99257d9e2689f64515ee1662baa90907ed46a6b (develop)
  - `themes/**`
    - um `nodemon` erweitern für live reload
- gerne kann diese Ticket in kleiner Etappen aufgeteilt werden

![Image](https://github.com/public-ui/kolibri/assets/6279703/aae81cc5-255b-4e35-b515-d4b1dc403ef0)

**Comment by sdvg** [comment]
Ich sammle in diesem Kommentar Änderungen, die ich nicht sofort umsetze, die aber vielleicht noch sinnvoll wären:

1) Alerts als Messages sehen teilweise seltsam aus, wenn man das label weglässt. Um das zu beheben müsste man die Komponente etwas umstrukturieren.
<img width="1299" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/abb93ee4-c8b8-42db-a4d6-3f22591cd32f">
<img width="642" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/cce7b1d6-b95d-4896-a460-2fb047d18784">

2)
Nicht alle Card-Themes haben einen Innenabstand für Inhalt und Footer. Unklar, ob so gewollt.
<img width="305" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/878779a5-5ebb-4936-821d-744dd379dd35">

3) Nav: Noch nicht klar, wie es korrekt aussehen soll (insbesondere icons-only-Variante). 

4) Buttons in Table, nur BMF Theme: Sehen zur Zeit so aus, die Styles dafür wurden aber erst [[kürzlich hinzugefügt](https://github.com/public-ui/kolibri/commit/010c4bca#diff-33d52becd0ebe41c9bce7f43ec10d0e5ab3469a7f69f768c7564438e4ce75168R1567)](010c4bca). Nicht sicher, wie ich das anpassen kann ohne an anderer Stelle ggf. etwas kaputt zu machen.
<img width="1319" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/0a508af9-a431-47dd-93be-42581ab79dde">
