### ISSUE TITLE
💡 Hinweis: Tastaturfokus prüfen bei Radiobutton ohne selektiertes Item

### ISSUE THREAD

**Issue by cbraehmig** [public-ui/kolibri#5317]
Ist in einer Radiobutton-Gruppe kein Item selektiert, kann diese Gruppe nicht per Tastatur fokussiert werden. Wird mit der Maus ein Radiobutton selektiert, funktioniert die Tastatursteuerung wieder.

![image](https://github.com/public-ui/kolibri/assets/93573283/d79ded87-ff0f-4619-82c7-0aea98c50c6b)

**Comment by deleonio** [comment]
Der Grund ist wahrscheinlich, dass die Option `Herr` `selected` und `disabled` ist.

- Sollte man das verbieten?
 
> Rationale: Ich stelle mir aber auch vor, dass ein altes Datum aus der DB `Herr` ist und die Maske diese Option `Herr` nicht mehr anbieten soll. Da kann man nicht einfach erzwingen, das alte Daten geändert werden müssen.

**Comment by sdvg** [comment]
Problem nicht mehr reproduzierbar
