### ISSUE TITLE
💡 Hinweis: Modal Dokumentation redaktionell verbessern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5321]
Der Dialog Hinweis muss im Fokus stehen.

Die Modal Dokiumentation sollte besser entfernt und auf einen Blog-Post verschoben werden.

**Comment by laske185** [comment]
Modal wird in https://github.com/public-ui/kolibri/issues/5844 erweitert. Hier wird dann auch die Doku verbessert/aktualisiert.
