### ISSUE TITLE
Scenario: "Komplexes Workflow Formular"

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5371]
- [x] Vorbedingung: "Terminreservierungsbeispiel aus alter Demo bereitgestellt."

---

- min. 3 Schritte
- Validierung
  - Fehlerliste über Form
  - Fehler an den Feldern
  - asynchrone Validierung
- Verschieden Eingabefelder und Ausprägungen
- Accordion, Tabs
- Dynamische Felder
  - weitere Angaben
  - geänderte Validierung
- filtern asynchron über viele Daten (Request-Simulation / Debouncing)

**Comment by sdvg** [comment]
Bereit für ein erstes Review. Im PR stehen ein paar wichtige Kommentare: https://github.com/public-ui/kolibri/pull/5414
