### ISSUE TITLE
Kein Tooltip bei `_disabled="true"`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5390]
Bei den interaktiven Elementen Button, Link und Inputs wird auch bei `_disabled` der Tooltip angezeigt. Der Tooltip soll jedoch nicht angezeigt werden, wenn die Elemente deaktiviert sind.

**Comment by sdvg** [comment]
Die Änderung ist jetzt wie beschrieben umgesetzt, ich finde sie aus Nutzersicht aber zunächst fragwürdig:

Tooltips haben wir ja nur an Elementen, die kein sichtbares Text-Label haben. Das heißt, mit dieser Änderung kann es z.B. Buttons geben, die nur aus einem Icon bestehen, disabled sind, man aber mglw. nicht erkennen kann, was der Button eigentlich tun würde, wenn er aktiv wäre.

Hier würden mich die Hintergründe noch interessieren.

**Comment by ElVariablo** [comment]
Kurz vorab: Disabled Elemente sollten nicht verwendet werden. Dadurch dass sie bei vielen Prüfschritten eine Ausnahme bilden, bringen sie oft ungetestete Barrieren in das Projekt (Bspw. Kontraste). 

In der Barrierefreiheit geht es generell um die Gleichbehandlung von allen Nutzenden. Gleichbehandlung heißt in diesem Kontext, dass alle Nutzenden die gleichen Informationen erhalten. 

"Disabled" Elemente sind Elemente, die zwar sichtbar sein sollen aber von Nutzende nicht bedient werden können. 

Ein Tooltip ist ein Element, das nur auf Fokussierung bedient werden kann. Dabei muss die Art der Fokussierung (Maus/Tastatur) irrelevant sein (damit alle Nutzenden gleichgestellt sind).  

Daraus folgt, dass somit ein Tooltip nicht auf ein "Disabled" Element angewendet werden darf.

**Comment by deleonio** [comment]
Wir warten, bis hierauf eine Antwort kommt: https://github.com/w3c/wcag/discussions/3522#discussioncomment-7390259

**Comment by deleonio** [comment]
Wir werden aktuell die Tooltips nicht entfernen, bis es eine klare Begründung von Seiten der WCAG dazu gibt.
