### ISSUE TITLE
🐞 Bug: wenn ein Modal per ESC geschlossen wird, kann es nicht noch einmal geöffnet werden

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5395]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Das Modal kann nicht erneut geöffnet werden, wenn es zuvor mit ESC geschlossen wurde.

## Reproduktion

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-ceoip6?file=src%2FApp.tsx,src%2FModal.tsx

Schritte zum Reproduzieren des Verhaltens:
- Klicke auf Modal öffnen (egal welcher Button)
- Wenn Modal geöffnet, tippe auf ESC
- Klicke den selben Button noch einmal an

## Erwartetes Verhalten
Das Modal kann erneut geöffnet werden, wenn es zuvor per ESC geschlossen wurde.

**Comment by sdvg** [comment]
Als Sofort-Lösung würde ich vorschlagen, den State durch eine Ref zu ersetzen und `modalElement._activeElement` direkt anzusprechen.
Ich habe das Beispiel hier einmal angepasst: https://stackblitz.com/edit/vitejs-vite-ljdauc?file=src%2FApp.tsx,src%2FModal.tsx

Das Problem: Das `onClose`-Callback, das hier verwendet wird, funktioniert aktuell nicht, wird also gar nicht aufgerufen.
Dadurch wird der State beim Schließen nicht korrekt auf `null` gesetzt und beim Versuch, das Modal erneut zu öffnen, bleibt der State gleich. Der Watcher auf `_activeElement` im Modal wird in dem Fall nicht ausgelöst und nichts passiert.

Unabhängig von der oben beschriebenen Lösung sollten wir das `onClose`-Callback wohl fixen/implementieren. Ich werde das als Teil von diesem Ticket erledigen.
