### ISSUE TITLE
Migration: `_iconOnly` would not migrate ?!

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5404]
```tsx
<KolButton
	_icons="icofont-trash"
	_iconOnly // will not be migrate ?!
	_label="Entfernen"
	_on={{
		onClick: console.log,
	}}
	_variant="danger"
/>
```

**Comment by deleonio** [comment]
Anpassung nur in `v2` vornehmen.

Im Teilprojekt `kolibri-cli` muss ein neuer Task für `ReplaceAttr` hinzugefügt werden, der `_iconOnly` gegen `_hideLabel` ersetzt.

Der Migrationstask ist für Version `1.7` und größer gültig.

**Comment by chrisalat** [comment]
Migration wurde mit der neusten CLI-Version auf der `v1.7` getestet. Der Fehler konnte allerdings bei keiner Komponente (welche das `_iconOnly`-Attribut verwendet) reproduziert werden. Alle `_iconOnly`-Attribute wurden durch `_hideLabel ` ersetzt.

**Comment by laske185** [comment]
Kann nicht repoduziert werden.
