### ISSUE TITLE
💡 Hinweis: Ausrichtung von Kol-Button mit Icon

### ISSUE THREAD

**Issue by cbraehmig** [public-ui/kolibri#5413]
Beschreibung:

Werden mehrere Buttons in einer Reihe abgebildet, und mindestens eines der Buttons beinhaltet ein Icon (Standard oder Linksplatziert), dann werden die restlichen Buttons aus derselben Reihe um einige Pixel nach unten gedrückt (siehe zweite Reihe des nachfolgenden Bildes):

![image](https://github.com/public-ui/kolibri/assets/93573283/750c0bd6-3860-458d-953f-3153b8aebe86)

Reproduktionsbeispiel

https://stackblitz.com/edit/vitejs-vite-4zkq1w?file=src%2FApp.tsx

**Comment by deleonio** [comment]
Gehen wir nach @cbraehmig.

**Comment by sdvg** [comment]
<img width="637" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/73e7aae6-270b-45a7-9e01-38145980d5e2">

Die Baseline wird vom ersten Element im Button definiert, in diesem Fall vom Icon.

**Comment by sdvg** [comment]
Ich würde erwägen, einfach mit dem Problem zu leben und bei inline-block Elemente bei Bedarf `vertical-align` händisch zu setzen.

Ich lege trotzdem einmal einen PR mit einem etwas hacky Workaround an. Vielleicht hat ja auch jemand eine bessere Lösung parat.
(Bisher nur gegen `develop`, `1.7` würde ich nach dem entsprechenden Feedback anlegen.)

**Comment by deleonio** [comment]
Relates with https://github.com/orgs/public-ui/projects/2/views/25?pane=issue&itemId=25661790

**Comment by deleonio** [comment]
@sdvg - wenn nichts gegen Deine hacky Lösung spricht - funktioniert diese aber recht gut.

Spricht sonst noch etwas dagegen - Du würdest ja erwägen, es von außen handle zu müssen.

**Comment by sdvg** [comment]
@deleonio Der Gedanke war, dass die Lösung nicht unbedingt notwendig ist. Buttons auf der Baseline platzieren zu müssen scheinen mir ein seltener Fall zu sein und man kann das vertical-align immer selber definieren wo notwendig. Oder eben mit Flex oder Grid arbeiten.

Aber der Workaround scheint mir tatsächlich gut zu funktionieren und ich sehe keine Probleme damit, ihn so umzusetzen.
