### ISSUE TITLE
🛹 Feature: Höhe eines Links je nach Verwendung (inline oder standalone) anpassbar machen

### ISSUE THREAD

**Issue by gkollotzek** [public-ui/kolibri#5421]
Je nach Verwendung würden wir gerne die Linkhöhe anpassen, um die WCAG Anforderung 2.5.5 Zielgröße (AAA) erfüllen zu können. Wenn der Link im Fließtext steht, muss die Höhe nicht min. 44px sein. Für Links, die allerdings alleine stehen, müsste die Höhe auf min. 44px gesetzt werden können.

**Comment by deleonio** [comment]
Vielen Dank @gkollotzek,

diesen Aspekt nehme ich mit. Ich kann mir gut vorstellen, dass wir Links zukünftig in einen "Standalone"-Variante anbieten.

- [ ] Neues Property:`_variant` : `inline` | `standalone`
- [ ] Neue Beispiel in Sample-App aufbauen
- [ ] Nachstylen aller Themes erforderlich

**Comment by gretaneumannn** [comment]
BMF versucht selbst Feature umzusetzen.

**Comment by deleonio** [comment]
Hi @gkollotzek,

Planänderung: **Würde Euch die Verwendung des `LinkButton` in der Variante `ghost` dafür genügen?**

> Ghost würde wie ein Link gestyled. Die 44px kommen out-of-the-box vom Basis-Style Button.

**Comment by gretaneumannn** [comment]
Kann geschlossen werden. Umsetzung erfolgt durch das DESYBRI-Team

**Comment by laske185** [comment]
- [ ]
