### ISSUE TITLE
🛹 Feature: Modal über Modal anzeigen

### ISSUE THREAD

**Issue by gkollotzek** [public-ui/kolibri#5422]
Für den Fall, dass ein Modal auf einem Modal geöffnet wird, soll das erste Modal weiterhin im Hintergrund sichtbar sein und nicht ausgeblendet werden. 

Anwendungsbeispiel: Der Nutzer gibt in einem Modal viele Daten ein und klickt dann auf den "Abbrechen" Button. Dann soll der Dialog "Wollen Sie Ihre eingegebenen Daten wirklich verwerfen?" angezeigt werden, wobei das erste Modal (mit den Eingaben) im Hintergrund weiterhin sichtbar sein soll.

**Comment by deleonio** [comment]
Hallo @gkollotzek,

das von uns bereitgestellt Modal ermöglicht nur ein sichtbares Modal. Wobei mehrere Modal parallel geöffnet werden können. Der Modal-Service merkt sich die Reihenfolge und öffnet beim Schließen den letzten Kontext.

Alternativ haben Sie die Möglichkeit, den nativen `dialog`-Tag zu verwenden. Bitte schauen Sie mal, ob Sie so mehrere Modale übereinander legen können.

Siehe auch: https://public-ui.github.io/docs/components/dialog - Einleitungstext

**Comment by deleonio** [comment]
Wir im Projekt mit dialog umgesetzt.
