### ISSUE TITLE
🛹 Feature: Closable Badge Höhe anpassen

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#5438]
Closable Badge mit Schalter soll auf eine sichtbare Höhe von 32px angepasst werden (die Klickhöhe soll bei 44px belassen werden). 

![image](https://github.com/public-ui/kolibri/assets/118734593/56ce2a95-b2dd-48ab-b040-5fa03bb67d48)

**Comment by deleonio** [comment]
Wir sollten die Farb-Definition als CSS-Property machen.

![image](https://github.com/public-ui/kolibri/assets/6279703/e035645b-2297-4fc0-9100-acb9321c08c2)

So wäre es möglich, im Theme die Variable beliebig nutzen.

Der Schalter muss weiterhin 44px groß sein.

**Comment by deleonio** [comment]
![image](https://github.com/public-ui/kolibri/assets/6279703/a352b863-fd7c-470b-ae78-cb9fea2b6ab8)

`kol-span-wc`'s verkleinern

**Comment by sdvg** [comment]
Bei welchen Themes soll das so umgesetzt werden?

**Comment by sdvg** [comment]
Umsetzung erfolgt durch das DESYBRI-Team

**Comment by gretaneumannn** [comment]
Kann geschlossen werden. Umsetzung erfolgt durch das DESYBRI-Team.
