### ISSUE TITLE
🐞 Bug: hidden kol-tooltip-wc nimmt Platz ein

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5440]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Ich wollte es gerade fixen, allerdings ist mir aufgefallen, dass das Verhalten überall wo `_hide-label` gesetzt ist, auftritt. Wenn das Attribut gesetzt wird, dann reserviert das `kol-tooltip-wc` Element Platz im DOM der optisch das Design zerschießt. Siehe Screenshots.

### Ohne `_hide-label`
<img width="1030" alt="Bildschirmfoto 2023-10-17 um 08 53 42" src="https://github.com/public-ui/kolibri/assets/6606913/0cbd7d31-1752-4e05-928a-741379f67d42">

### Mit `_hide-label`
<img width="1025" alt="Bildschirmfoto 2023-10-17 um 08 53 58" src="https://github.com/public-ui/kolibri/assets/6606913/bc949237-7b4a-4d9a-9e73-43fbab58889e">

## Reproduktion

Kann z.B. im Designer bei jedem Inputfeld nachgestellt werden. Aufgefallen ist mir es zuerst beim `kol-input-checkbox`. Nachstellen konnte ich es stichprobenartig bei `kol-input-radio` und `kol-input-text`.

**Comment by deleonio** [comment]
Danke für den Hinweis. Wir prüfen, wie wir das `gap` weg bekommen.
