### ISSUE TITLE
📖 Help: description in ToasterService 

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5442]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

Hi, die Dokumentation geht nur darauf ein wie man den `ToasterService` verwendet, wenn die `description` ein string ist. Das ist bei uns aber eher selten der Fall. Stattdessen möchte ich alles reingeben können und hier nicht eingeschränkt werden. Mit alles meine ich Markup.

@deleonio

**Comment by deleonio** [comment]
@Chrisdo82, der Tooltip ist nur für kurze Texte bis glaube 32 (80, Label) vorgesehen. Für richtige Overlays haben wir dir Popover-Komponente mit Slot bereitgestellt.

-> https://public-ui.github.io/docs/components/popover

**Comment by Chrisdo82** [comment]
Warum Tooltips? Ich spreche vom Toast-Element?! Hast du evtl. aufs falsche Ticket geantwortet?

Mit dem unten stehenden Codeschnipsel, komme ich der Lösung recht nah. 
Damit das funktioniert, bräuchte ich allerdings eine HTML Referenz aufs einzelne Toast-Element. 
Ohne diese Referenz, kann ich die 1.7.x Version leider nicht nutzen, da eure Anpassung die vorherige Toast Nutzung leider nicht mehr funktionieren lässt (hätte m.E. dadurch eigentlich ins 2.x Release gehört).

```typescript
toaster.enqueue({
  type: notification.type,
  label: notification.headline,
  description: (() => {
    if (typeof notification.message === 'string') {
      return notification.message
    }
    ReactDOM.render(<>{notification.message}</>, ref.current)
    return ''
  })(),
})
```

**Comment by deleonio** [comment]
Hi @Chrisdo82,

Danke für die Rückmeldung.

- Wenn Du die Toast-Komponent weiterverwendest, wie bisher - also ohne ToastService, kannst Du ja auch auf 1.7 wechseln. Oder?
- Klar der ToastService verhält sich anders, ja.
- Okay, Du brauchst am besten Referenzen auf die Toast's.

@sdvg Hast du da eine Idee?

**Comment by Chrisdo82** [comment]
@deleonio 
> Wenn Du die Toast-Komponent weiterverwendest, wie bisher - also ohne ToastService, kannst Du ja auch auf 1.7 wechseln. Oder?

Leider nicht, zum einen scheint es kein `_heading` mehr zu geben (ok, das kann ich ersetzen mit `_label`) und zum anderen scheinen auch die Styles von euch angepasst worden zu sein. Zumindest sind sie nicht mehr absolut positioniert. Ich weiß nicht wie sinnvoll es ist, hier auf unserer Seite einen Workaround drumzubasteln.

**Comment by deleonio** [comment]
@Chrisdo82 

Wir arbeiten an einer Render-Funktion, wie bei der Table. Hier wird die Referenz auf den Slot übergeben, so dass eigener Kontext gerendert werden kann.

**Comment by Chrisdo82** [comment]
Funktioniert, danke :-)
