### ISSUE TITLE
🛹 Feature: Migration auf Storybook 7

### ISSUE THREAD

**Issue by bastiW** [public-ui/kolibri#5445]
> **Note**
> - [ x ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

Storybook 7 besitzt etliche Neuerungen, von denen die Storybook Kolibri Integration profitieren könnte: 
- Weniger Boilerplate bei den Stories
- 🚄 Vite Support für eine verbessere Startzeit !!! 
- Verbesserte Type Sicherheit
- Neuer Test Runner für das Integrations testing

## Beschreiben Sie die gewünschte Lösung
Upgrade auf Storybook 7 

## Zusätzlicher Kontext
https://storybook.js.org/releases/7.0
https://www.youtube.com/watch?v=P0hJm5v8TJw

**Comment by deleonio** [comment]
Hallo @bastiW,

vielen Dank für den Hinweis und die Tipps.

Wir haben aktuell noch eine Storybook-Integration in unserem Library-Template. Nutzen aber selbst kein Storybook mehr.

Die Version im Template zu aktualisieren, nehme ich mit.

In welchem Case verwenden Sie Storybook aktuell?


VG Martin

**Comment by bastiW** [comment]
Wir nutzen Storybook um Designanpassungen von Kolibri an das CI der Behörde anzupassen und um zusätzliche Komponenten die speziell für den Anwendungsfall vorgesehen sind anzuzeigen.
