### ISSUE TITLE
💡 Advice: Change the `role` to `status` for the input error message

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5470]
- [ ] we should change the alert implementation
- [ ] we use the `role` `status` for inline error messages

Aktuell wird die role `alert` verwendet, sollten wir sie zu `status` ändern?

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role
Als Beispiel ist hier aufgelistet:
> An invalid value was entered into a form field

**Comment by cbraehmig** [comment]
Abstimmung BF-Team. Fazit: Die Verwendung von `role="alert"` ist absolut korrekt.
