### ISSUE TITLE
📖 Help: Buttons, Links und Inputs ohne sichtbares Label sollen auch keinen `Tooltip` haben

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5481]
Wir haben eine Anfrage erhalten, dass Buttons, Links und Inputs ohne sichtbares Label (`_hideLabel`) auch keinen Tooltip haben sollen. Das ist bewusst von Seiten KoliBri so umgesetzt worden, um allen Menschen die gleichen Informationen über den Nutzungskontext bereitzustellen.

Szenario: Wenn wir ein Suchfeld haben, welches aus einem Texteingabefeld und einem Schalter direkt daneben besteht. Dann muss das Suchfeld kein sichtbares Label und dann auch keinen Tooltip haben.

**Comment by AntnSaj** [comment]
Wenn ein Button ohne Label (nur mit Icon) keinen Tooltip bekommt, können NICHT-Screenreader Nutzende ggf. nicht an die Informationen kommen, was der Button macht. Somit sollte unserer Meinung nach der Tooltip immer eine Option bleiben.

Beispiel: Mehrere Buttons für die Bearbeitung mit verschiedenen Icons (Bleistift, Büroklammer, Diskette usw...). Hier werden Tooltips benötigt um zu unterscheiden, welche Funktion hinter welchen Buttons steckt.

**Comment by deleonio** [comment]
Eine Lösung hierfür ist, die Verwendung des Experr-Slots, da hier kein Tooltip von KoliBri mitkommt.

Siehe https://public-ui.github.io/docs/concepts/expert-slot

Beispiel-Code: https://codesandbox.io/s/kolibri-public-ui-react-static-form-sample-forked-sqvv95?file=/src/index.tsx
