### ISSUE TITLE
📖 Help: Deaktivierte Schalter scheinen beim `dialog`-Tag durch

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5484]
Wenn man statt der Modal-Komponente den HTML `dialog`-Tag verwendet, kann es passieren, dass deaktivierte Elemente im Hintergrund durch den Dialog sichtbar sind.

<img width="733" alt="image" src="https://github.com/public-ui/kolibri/assets/6279703/3c3c4aeb-07f1-4621-8099-caf974b27f8c">

**Comment by deleonio** [comment]
Hier haben wir das nachgestellt: https://stackblitz.com/edit/vitejs-vite-qjbem3?file=src%2FApp.tsx,src%2Fmain.ts

Workaround / Lösung ist: Den Dialog im DOM möglichst am Ende zu verwenden. So scheinen die deaktivierten Elemente nicht mehr durch den Dialog.

**Comment by deleonio** [comment]
Known Issue:
- [ ] Browser-Bug in die Liste aufnehmen: https://github.com/public-ui/kolibri/blob/develop/KNOWN_ISSUES.md
- [ ] Bitte auf das Reproduktionsbeispiel verlinken: https://stackblitz.com/edit/vitejs-vite-qjbem3?file=src%2FApp.tsx
- [ ] Mal mit Firefox anschauen.
- [ ] Bitte mal schauen, ob wir ein Ticket bei Chromium oder Firefox dazu finden.
- [ ] Inhalt
  - Wenn ein `dialog`-Tag vor `button`'s im DOM verwendet wird und Schalter "unterhalb" des Dialogs sind, dann scheinen diese im deaktivierten Zustand durch das darüberliegende Dialog durch.

**Comment by sdvg** [comment]
Ich habe mal ein minimales Beispiel ohne KoliBri gebaut, hier kann ich das Problem nicht reproduzieren: https://codepen.io/sdvg/pen/yLrJYzj

**Comment by sdvg** [comment]
Problemursache: `opacity` auf deaktivierten Buttons: https://stackoverflow.com/a/11742116

**Comment by sdvg** [comment]
Praktisch ist hier keine Änderung an KoliBri notwendig, es reicht, dem `<dialog>` einen `z-index` von mindestens `1` zuzuweisen.
Angepasstes Beispiel: https://stackblitz.com/edit/vitejs-vite-qbm5eb?file=src%2FApp.tsx,package.json

**Comment by sdvg** [comment]
@deleonio Hier gibt es kein PR, weil der Bugfix ausschließlich im Projekt bzw. auf Stackblitz stattfindet. Ist die Lösung so i.O. und können wir das Ticket schließen?

**Comment by deleonio** [comment]
@Chrisdo82 Es muss der `z-index` am Dialog gesetzt werden.
