### ISSUE TITLE
💡 Hinweis: künstlichen Klickgeräusches / berührungsempfindlichen Bildschirm

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5493]
Klick-Geräusch beim Klicken eines interaktiven Elements als zusätzliches Feedback, dass die Aktion ausgeführt wird.

- Touchscreens

> Hint: Sollte dieses Feature nicht eher bei den Screenreader verortet werden?!

**Comment by laske185** [comment]
Sollte bei Bedarf in der Anwendung beim onClick geschehen. Nicht aber immer in der Komponentenbibliothek.
