### ISSUE TITLE
🛹 Feature: ToastService - Callback zum schließen der Toasts benötigt

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5508]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Wir benötigen einen Callback am ToastService womit alle toasts geschlossen werden können. 

Ich dachte erst, dass dafür die `dispose` Funktion zuständig sei. Aber sobald ich die verwende, kann ich kein neues Toast mehr erstellen. So habe ich es beispielsweise versucht:

```tsx
function ErrorFallback({ error }: Omit<FallbackProps, 'error'> & { error: Error }) {
  useEffect(() => {
    const toaster = ToasterService.getInstance(document)
    void toaster.enqueue({ label: error.name, type: 'error', description: error.message })

    return () => toaster.dispose()
  }, [error.message, error.name])

  return null
}
```

Wenn ich nun `ErrorFallback` erneut rendere, dann wird kein Toast mehr erstellt.

## Beschreiben Sie die gewünschte Lösung
Es gibt eine Möglichkeit die Toasts über den ToastService zu schließen und im Anschluss neue zu erstellen.

**Comment by Chrisdo82** [comment]
Mein derzeitiger Workaround ist der hier: 

```typescript
return () => {
  // TODO fix it as soon as KoliBri provided a cleanup function (https://github.com/public-ui/kolibri/issues/5508)
  toaster.dispose()
  // @ts-expect-error fix it as soon as KoliBri provided a cleanup function (https://github.com/public-ui/kolibri/issues/5508)
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
  ToasterService.instances.delete(document)
}
```

**Comment by deleonio** [comment]
Bitte einen entsprechenden Callback vorsehen. Ggf. im Team absprechen, wie genau.
