### ISSUE TITLE
Pilot: Next.js + Lit real SSR Lab

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5513]
Bitte hier auch einmal ein Pilot aufsetzen.

Die Idee wäre, dass aber die Lit Componenten über NPM kommen.

Ich glaube bei Remix war immer das so, dass man sie direkt im Remix-Projekt mit verbaut.

Bitte das Samples (Mono-Repo, wenn mehr als 1) in folgendes Repo pushen: https://github.com/public-ui/lab-ssr-lit

**Comment by sdvg** [comment]
Paket zur Integration von Next.js und Lit: https://github.com/lit/lit/tree/main/packages/labs/nextjs
Funktionierendes Beispiel von Lit: https://stackblitz.com/edit/nextjs-lit-ssr
