### ISSUE TITLE
🐞 Bug: 9.1.4.10 Breadcrumb: Text überlappt bei starker Vergrößerung

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5518]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Text im Breadcrumb überlappt bei starker Vergrößerung

## Beschreibung des Fehlers
Bei einer starken Vergrößerung oder Darstellung auf mobilen Geräten überlappen sich die Zeilen des Breadcrumbs, und sind daher unleserlich.

## Reproduktion
Style: BMF, Default
Komponente: breadcrumb basic (https://public-ui.github.io/sample-react/#/breadcrumb/basic)
Version: v2.0.0-rc.6

**Schritte zum Reproduzieren des Verhaltens:**
- In Chrome das Browserfenster auf eine Breite von 1280 CSS-Pixeln und eine Höhe von 1024 CSS-Pixeln einstellen. Hierzu lässt sich die Resize-Funktion der Web Developer Toolbar nutzen.
- Auf 400% zoomen
- Die Seite neu laden

## Erwartetes Verhalten
Der Breadcrumb sollte so umbrechen, dass genug Abstand zwischen den Zeilen ist.

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/149500785/1e1c2829-fc12-4277-9c23-785cc4dff579)

**Comment by deleonio** [comment]
Der Breadcrumb sollten ein Fließtext Verhalten haben. Es scheine mehrzeilige Text einzuengen.

**Comment by deleonio** [comment]
Bitte auch mal schauen, ob der Fehler bei den anderen Themes auftritt.

**Comment by KawaiiMochiAhri** [comment]
Browser: Firefox
Theme: Default
Zoom: 100%

Der Fehler lässt sich auch durch das Resizen des Fensters rekonstruieren.
Wenn eines der Elemente zu lang ist und selbst über mehrere Zeilen geht, wird das Folgende Element nicht um eine weitere Zeile verschoben. 


![BugBreadcrumb](https://github.com/public-ui/kolibri/assets/158447329/7178cdcf-9211-4397-a91b-e3f867deb6ec)

**Comment by KawaiiMochiAhri** [comment]
Hier nochmal ein Bsp, wenn das Element mehrere Zeilen benötigt, bleibt das Folgeelement dort wo es ist.
![BugBreadcrumb2](https://github.com/public-ui/kolibri/assets/158447329/9f274de6-ed45-468a-ba7a-7038401a2786)
