### ISSUE TITLE
🐞 Bug: 9.1.4.3 Badge: Textkontrast ist zu gering

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5519]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Textkontrast von Badges ist zu gering

## Beschreibung des Fehlers
Der Textkontrast von blauen Badges (4,1:1) und grünen Badges (4,4:1) ist unter 4,5:1 und ist daher nicht ausreichend.

Hinweis: Der Kontrast des roten Badge ist 6,7:1 und daher unter der AAA-Grenze.

## Reproduktion

Style: BMF, Z2
Komponente: badge basic (https://public-ui.github.io/sample-react/#/badge/basic) 
Version: v2.0.0-rc.6

Schritte zum Reproduzieren des Verhaltens:
- Kontrastmessung mit dem Color Contrast Analyser

## Erwartetes Verhalten
Der Kontrast muss mindestens über 4,5:1 sein (im Idealfall über 7:1).

**Comment by deleonio** [comment]
Die Badges sollten alle min. 7:1 haben. Dafür ist ein Algorithmus zuständig. Er berücksichtigt jedoch nicht die Schrifdicke.

Bitte nachlesen.

**Comment by deleonio** [comment]
![image](https://github.com/public-ui/kolibri/assets/6279703/161ca46a-d989-4e7a-9932-9ccd3deffe55)

Die Dev-Tools bestätigen den Fehler.

Bitte für unserer Beispielfarben mit ausreichend Kontrastabstand wählen. Farben aus dem mittleren Spektrum können weder zu schwarz noch zu weiß genügend Kontrast haben.

**Comment by fohi17** [comment]
Huhu @deleonio & @sdvg. Kann man das wieder auf machen oder noch korrigieren? Die Farben in der "badge basic" Komponente haben jetzt einen Kontrast von 7:1, bei "badge button" sehe ich aber noch die alten Farben : )

**Comment by sdvg** [comment]
Danke @fohi17! Ich habe hier ein Followup-Ticket angelegt und werde mich zeitnah darum kümmern: https://github.com/public-ui/kolibri/issues/5622
