### ISSUE TITLE
🐞 Bug: 9.1.4.1 button-link: Links im Fließtext sind farbkodiert

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5520]
JIRA-545

# Links im Fließtext sind farbkodiert

## Beschreibung des Fehlers
Die Links befinden sich im Fließtext und unterscheiden sich nur anhand der Farbe vom umgebenden Text. Der Kontrast zwischen blauen Links und schwarzem Text ist 2,7:1, und daher auch nicht ausreichend zur Unterscheidung. 

## Reproduktion

Style: Z2
Komponente: button-link basic (https://public-ui.github.io/sample-react/#/button-link/basic?theme=zoll-v2) 
Version: v2.0.0-rc.6

## Erwartetes Verhalten
Die Links sollten unabhängig von der Farbe erkennbar sein, bspw. durch eine Unterstreichung. (Alternativ sollte der Kontrast zum umliegenden Text über 3:1 sein.)

**Comment by deleonio** [comment]
Der Styleguide sieht aktuell keinen Unstreichung vor. Dass sollten wir hinterfragen. 

Und Kontraste Härten lassen.

**Comment by fohi17** [comment]
Das ist auch bei der Komponente "link basic" der Fall.

**Comment by deleonio** [comment]
Muss mit Fachseite/ UX besprochen werden.

**Comment by cbraehmig** [comment]
Laut Design-Guidelines ist einem Link immer durch ein vorangestelltes Icon gekennzeichnet.
