### ISSUE TITLE
Vorschlag zur Verbesserung der CSS Wartbarkeit

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5544]
1. 

**Problem**: Einzelne Selektoren und nicht klar und fragil. Beispiel: `:host > div > div > .close`
- Welche div-Elemente sind hier gemeint? Warum müssen sie Teil des Selektors sein?
- Was passiert, wenn die HTML-Struktur geändert wird?

**Lösung**: Ein Theme aussuchen (z.B. Default) und konsequent auf Klassen-Selektoren refactoren. Benötigte Klassen dabei in den Components ergänzen.

2.

**Problem**: Die Theme-Component-Styles sind in einer sehr großen TS-Datei schwer zu überblicken. Es ist schwer zu erkennen, wo eine Komponente anfängt und endet und die Editor-Navigation kann lästig sein.
**Lösung**: Themes nach Komponenten in Module splitten. TS oder direkt CSS (siehe auch Punkt 3).

3.

**Problem**: Styles sind dupliziert. Wenn z.B. allgemeine Input-Styles angepasst werden, müssen diese in bis zu 12 Komponenten angepasst werden. Das macht es auch schwierig herauszuarbeiten, wenn Komponenten zusätzlich eigene Styles haben, welche die allgemeinen Input-Styles ergänzen oder überschreiben.
**Lösung**: CSS-Preprocessor wie z.B. [PostCSS mit mixins](https://github.com/postcss/postcss-mixins) verwenden.

**Comment by sdvg** [comment]
Ticket in "Review" bedeutet: Initiales Beispiel ist im PR und kann angeschaut und besprochen werden.

**Comment by deleonio** [comment]
@sdvg haben wir das nicht schon komplett?

**Comment by deleonio** [comment]
Hierbei sollten wir uns auch die Herangehensweise von @mfranzke mal anschauen.

Link: https://github.com/db-ui/mono/discussions/2152#discussioncomment-8303028
