### ISSUE TITLE
🐞 Bug: 9.4.1.2 input checkbox button: Elemente werden ohne Rolle ausgegeben

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5546]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In der Komponente "input-checkbox button" werden die interaktiven Elemente vom Screenreader ohne Rolle ausgegeben (Ausgabe lediglich als "anklickbar"). Screenreader-Nutzer können daher den Zweck der Elemente und deren Status nicht erkennen. Die Ursache ist, dass die Elemente nicht mit HTML-Standard-Elementen umgesetzt wurden.

Zusätzlich wird bei den Elementen mit verstecktem Label (hideLabel) dadurch auch keine Beschriftung ausgegeben.

**Hinweis:** Beim BMF-Theme hat die Gruppe "hideLabel" noch sichtbare Label.

## Reproduktion
Style: BMF, Z2
Komponente: input-checkbox button (https://public-ui.github.io/sample-react/#/input-checkbox/button)
Version: v2.0.0-rc.6

Schritte zum Reproduzieren des Verhaltens:

- input-checkbox button öffnen
- Screenreader (NVDA) öffnen
- Mit der TAB-Taste navigieren

## Erwartetes Verhalten
Der Screenreader sollte eine Rolle (hier: Kontrollfeld/Checkbox), einen Status (aktiviert/deaktiviert) und eine Beschriftung ausgeben.

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/149500785/cbe8da18-049f-4143-aeb1-5f4eab57faa8)

**Comment by deleonio** [comment]
Erstmal reproduzieren mit einer reinen HTML ohne WebComponents( nachgetestet.

**Comment by sdvg** [comment]
Ich kann das Problem nicht (mehr) nachvollziehen. Die Checkboxen werden bei mir korrekt als solche erkannt:

![checkboxes](https://github.com/public-ui/kolibri/assets/971072/55e0ea1e-4458-4115-a10b-064d3ddc605b)

**Comment by deleonio** [comment]
Das wurde schon gefixed.

#5654 
#5653
