### ISSUE TITLE
🐞 Bug: 11.7 input-checkbox basic: Teilweise aktive Checkboxen sind bei hohem Kontrast nicht sichtbar

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5548]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn man die Farben im Browser (Firefox) anpasst (gemäß BIK BITV 11.7), oder den Windows Hochkontrastmodus verwendet, ist der Status der teilweise aktivierten Checkboxen ("Unbestimmt (Indeterminate)") nicht sichtbar.

## Reproduktion
Komponente: input-checkbox basic (https://public-ui.github.io/sample-react/#/input-checkbox/basic)
Version: v2.0.0-rc.6

Schritte zum Reproduzieren des Verhaltens:
**Farben anpassen im Firefox:**
Einstellungen -> Allgemein -> Farben

**Windows Hochkontrastmodus:**
Windows-Suche nach "Kontrast" -> Hoher Kontrast -> An

## Erwartetes Verhalten
Der Status (also der Strich) der Checkbox sollte auch bei benutzerdefinierten Farben/Kontrasten sichtbar sein.

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/149500785/69f3f72f-14a3-4dcf-8345-43f9540282ad)

**Comment by deleonio** [comment]
Lösung ist ein neues Feature: Wir nutzen die ICons (schon vorhanden) und setzen diese in die Checkbox. Die Icons werden im Hochkontrastmodus angezeigt.
