### ISSUE TITLE
🐞 Bug: 9.4.1.2 input-color basic: Farbauswahl ist für Screenreader unbeschriftet, ohne Rolle und ohne Status

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5549]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In der Komponente "input-color basic" bestehen mehrere Probleme für den Screenreader:

- Die interaktiven Elemente werden vom Screenreader ohne Rolle ausgegeben (Ausgabe lediglich als "anklickbar"). Screenreader-Nutzer können daher den Zweck der Elemente nicht erkennen.
- Zusätzlich wird nicht die korrekte Beschriftung ausgegeben, sondern nur der jeweilige Farbwert. 
- Der Status ist nicht erkennbar (bspw. disabled) beim linearen Lesen.
- Der Hint-Text wird nicht ausgegeben.
- Der Fehlertext wird nur beim Erscheinen ausgegeben, aber nicht, wenn das Element erneut angetabbt wird.

## Reproduktion
Komponente: input-color basic (https://public-ui.github.io/sample-react/#/input-color/basic)
Version: v2.0.0-rc.6

Schritte zum Reproduzieren des Verhaltens:

- input-color basic öffnen
- Screenreader (NVDA) starten
- Mit der TAB-Taste navigieren

## Erwartetes Verhalten
Der Screenreader sollte die Rolle (bspw. Schalter), den Status und die korrekte Beschriftung ausgeben.
Die Hinweis- und Fehlertexte sollten bei Fokus des Elements ausgegeben werden. 

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/149500785/d3dece46-821a-4905-b1db-364ab56ef4b2)

**Comment by deleonio** [comment]
Natives HTML zum reproduzieren.

**Comment by sdvg** [comment]
![color-input](https://github.com/public-ui/kolibri/assets/971072/e08f403b-f985-4f84-b886-acb5990029ff)

**Comment by sdvg** [comment]
Tests mit Minimalbeispiel (reines HTML ohne Webcomponents):

* `anklickbar` mit dem aktuellen Farbwert als RGB scheint die native Ausgabe mit Chrome/NVDA zu sein.
* Das verknüpfte Label wird beim Fokussieren des Input auch nativ nicht vorgelesen.
* Das Farbeingabefeld wird also nicht wie ein gewöhnliches Eingabefeld behandelt, vermutlich wird deshalb auch die Fehlermeldung nicht beim Fokussieren vorgelesen.
