### ISSUE TITLE
🐞 Bug: 9.1.4.13 Tooltips können nicht immer mit ESC geschlossen werden

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5550]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei den meisten interaktiven Elementen (ohne Label) wird ein Tooltip bei Fokussierung mit der Tastatur (TAB) angezeigt und kann mit der Tastatur (ESC) wieder geschlossen werden. Bei einigen Elementen ist dies jedoch nicht der Fall. Der Tooltip wird zwar angezeigt, kann jedoch nicht mit der Tastatur geschlossen werden. Das kann ein Problem werden, wenn der Tooltip wichtige Inhalte überdeckt. 

## Reproduktion

Style: BMF, Z2 (Alle)
Version: v2.0.0-rc.6

Rechte Seite (hideLabel) folgender Komponenten:
- input-date
- input-email
- input-number
- input-password

Schritte zum Reproduzieren des Verhaltens:
- Mit der TAB-Taste Navigieren
- Versuchen, das Tooltip zu schließen, ohne den Fokus zu verschieben bspw. ESC-taste

## Erwartetes Verhalten
Die Tooltips sollten mit ESC geschlossen werden können.

**Comment by deleonio** [comment]
Hallo @fohi17,

kannst Du das bitte noch einmal nach testen. Bei mir funktioniert das wunderbar.

Wichtig ist, dass auch der Fokus im Fenster liegt, damit ESC erkannt wird.

Danke.

**Comment by fohi17** [comment]
@deleonio Ich habe es eben nochmal gegengetestet und das Verhalten bleibt gleich, auch bei der Kollegin, liegt also nicht an meinem Browser. Es passiert auch wirklich nur bei den genannten Komponenten und beim Navigieren mit der Tastatur (bei Maus-Hover geht es).
