### ISSUE TITLE
9.4.1.2 input-number basic: Readonly ist mit Screenreader nicht erkennbar

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5554]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei dem Eingabefeld "Zahleneingabe (Readonly)" wird vom Screenreader nicht ausgegeben, dass das Feld schreibgeschützt ist. 

## Reproduktion
Komponente: input-number basic (https://public-ui.github.io/sample-react/#/input-number/basic)
Version: v2.0.0-rc.6

Schritte zum Reproduzieren des Verhaltens:

- input-number basic öffnen
- Screenreader (NVDA) starten
- Mit der TAB-Taste navigieren bis "Zahleneingabe (Readonly)"

## Erwartetes Verhalten
Der Status, also "schreibgeschützt", sollte vom Screenreader ausgegeben werden.

**Comment by deleonio** [comment]
Vielen Dank @fohi17,

hier wäre noch interessant, was JAWS ausgibt. VoiceOver von Apple gibt Readonly aus und es ist auch im Code gesetzt.

<img width="817" alt="image" src="https://github.com/public-ui/kolibri/assets/6279703/2666ac0a-0e58-49c1-8ba6-2685817d10e1">

**Comment by deleonio** [comment]
Wir testen einmal das Input ohne WebComponent nach.

`<input title="" aria-label="Zahleneingabe (Readonly)" autocapitalize="off" autocomplete="off" autocorrect="off" id="id-663da7" max="" min="" readonly="" spellcheck="true" type="number">`

**Comment by fohi17** [comment]
@deleonio Das scheint wirklich an NVDA zu liegen, bei JAWS wird es ausgegeben.

**Comment by deleonio** [comment]
Danke @fohi17, wir legen das Ticket dann erstmal auf `wartend` und greifen es wieder auf, wenn sich etwas Neues ergibt.

**Comment by deleonio** [comment]
- [x] [`KNOWN_ISSUES.md`](https://github.com/public-ui/kolibri/blob/develop/KNOWN_ISSUES.md) dokumentieren und auf dieses Ticket verlinken
