### ISSUE TITLE
Ticketspezifische (PR) Deployments zum Nachtesten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5570]
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
- Sample-App deployend (Mono-Repos)

**Comment by sdvg** [comment]
Ich habe mich hier auf Netlify fokussiert und sehe zwei verschiedene generelle Ansätze. Beide habe ich getestet und sie funktionieren grundsätzlich gut.

1) Build mit GitHub Actions, anschließendes Deployment auf Netlify

* Der Build wird analog zu `publish` als Workflow in einer Yaml-Datei konfiguriert. Wir haben hier die volle Flexibilität und können bestehende Konfiguration wiederverwenden. Im letzten Schritt werden die Artifakte mit Hilfe der CLI auf Netlify deployed und die Deployment-URL im Log ausgegeben.
* Wir können solche Deployments entweder manuell triggern oder auch in Pull Requests automatisch auslösen. Im zweiten Fall können wir die Deployment-URL auch automatisch in das PR kommentieren lassen.

2) Build komplett auf Netlify

* Hier wird alles auf Netlify bzw. über die `netlify.toml`-Konfigurationsdatei eingestellt.
* Pull Requests erzeugen bei Erstellung und Commits automatisch einen neuen Build + Deployments seitens Netlify.
* Netlify kommentiert die Deployment-URL im Pull Request. Bei Änderungen wird dieser aktualisiert (kein Spam).
* Optional kann hier der [Netlify Drawer](https://docs.netlify.com/site-deploys/deploy-previews/#collaborative-deploy-previews) hinzugefügt werden. Eine UI, über die z.B. Fehler direkt auf GitHub reported werden können:  <img src="https://github.com/public-ui/kolibri/assets/971072/cd99ef4a-e6dd-427a-a71e-023c1fa07824" width="300" valign="top">



Zusätzlich können Branch-Deployments konfiguriert werden. Bestimmte Branches werden dann automatisch neu deployed. Z.B. `develop` und `release/1.7` wären so immer aktuell einsehbar.

Konfiguration für GitHub Workflow (Ansatz 1): https://github.com/sdvg/kolibri/blob/develop/.github/workflows/draft-deploy.yml
Konfiguration für Netlify (Ansatz 2): https://github.com/sdvg/kolibri/blob/develop/netlify.toml
Beispiel für ein PR mit Netlify Preview Deployment (Ansatz 2): https://github.com/sdvg/kolibri/pull/1

**Comment by deleonio** [comment]
@laske185 gib morgen mal eine Präferenz ab. Danke

**Comment by deleonio** [comment]
Done 👍
