### ISSUE TITLE
Feature: Fehlerliste in KolForm

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5571]
- Der KolForm kann man eine Fehlerliste (Fehlertext + Selector (`kol-input-text[_name="vorname"]`) für `input`'s) übergeben (serialisierbar).
- Die KolForm zeigt bei Fehlern eine Alert-Box mit einer Link-Liste an.
- Der Fehlertext ist der Link-Text. Bei Klick scrollt man zum Eingabefeld (focus, CSS Scroll smooth)

**Comment by sdvg** [comment]
Ticket wird von @cyrinermd bearbeitet.

**Comment by deleonio** [comment]
Ggf. Überschneidungen: https://github.com/public-ui/kolibri/issues/5743
