### ISSUE TITLE
Bug: Inputs (React): Fehler lassen sich ohne re-render nicht mehr ausblenden

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5574]
Beispiel:

```
import React, { FC, useState } from 'react';
import { KolInputText, KolSelect } from '@public-ui/react';

export const SelectBasic: FC = () => {
	const [inputsVisible, setInputsVisible] = useState<boolean>(true);
	const [error, setError] = useState<string | undefined>(undefined);

	return (
		<div>
			{inputsVisible && (
				<>
					<KolSelect _label="testing errors" _touched _error={error}></KolSelect>
					<KolInputText _label="testing errors" _touched _error={error}></KolInputText>
				</>
			)}

			<button onClick={() => setError('faulty')}>set</button>
			<button onClick={() => setError(undefined)}>unset</button>
			<br />
			<button onClick={() => setInputsVisible(false)}>hide inputs</button>
			<button onClick={() => setInputsVisible(true)}>show inputs</button>
		</div>
	);
};
```

---

Das Problem: Änderungen von Properties zu `undefined` werden in der Property-Validation nicht übernommen.

Bugfix-Ansatz, der allerdings andere Probleme verursacht: [df51f3afbc816f727abe51a053db662b2f3b82eb](https://github.com/public-ui/kolibri/commit/df51f3afbc816f727abe51a053db662b2f3b82eb)

**Comment by deleonio** [comment]
Wir können schauen, ob wir die Condition einfach weglassen können.


![Image](https://github.com/public-ui/kolibri/assets/6279703/eb40995b-a3e7-49e9-aba7-b1ed3e48d63a)

**Comment by deleonio** [comment]
@sdvg - Diese Condition ist schon entfernt worden?!

`develop` - https://github.com/public-ui/kolibri/blob/1d232aa7bd9660dff5ba7bffd73a74385dc15f0b/packages/components/src/utils/prop.validators.ts#L102

`release/1.7` - https://github.com/public-ui/kolibri/blob/2824974425714cb94fb9ec437e4f3467ca106bc9/packages/components/src/utils/prop.validators.ts#L102

**Comment by sdvg** [comment]
@deleonio Ich bin mir nicht ganz sicher, was du meinst.

Die Condition über die wir gesprochen hatten war, so habe ich verstanden, genau diese, wie sie gerade in allen Versionen vorhanden ist (`component.nextState.get(propName) !== value`).

Falls es um den Zusatz `|| value === undefined` geht: Den hatte ich nur kurz einmal drin und hier als Referenz verlinkt, weil er das Problem für mich an der Stelle gepatched hatte. Allerdings war er kein richtiger Fix, weil er an anderer Stelle Probleme verursacht hat. Dieser Zusatz war also nie in develop/main sondern nur ganz kurzzeitig in einem Branch vorhanden.

Wenn ich dich in unserem Call richtig verstanden habe war die Überlegung tatsächlich, die gesamte Bedingung (`if (component.nextState.get(propName) !== value) { `) herauszunehmen, weil sie nicht wirklich notwendig ist.

**Comment by deleonio** [comment]
Reopen for v1.

**Comment by deleonio** [comment]
Reopen for v1
