### ISSUE TITLE
🛹 Feature: Angular 17 & 16 Adapter

### ISSUE THREAD

**Issue by bastiW** [public-ui/kolibri#5590]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.

Vor kurzem wurde Angular 17 released. Hier gibt es noch kein npm package. 

Der Adapter für Version 16 ist noch nicht dokumentiert.

**Comment by deleonio** [comment]
Seit Angular 15 scheint kein Versions-spezifischer Adapter mehr erforderlich zu sein. Hier haben wir eine kleine Beispiel-App mit Angular 17 und dem Adapter für Version 16.

Wir schauen mal, ob wir zukünftig ein NPM-Paket anbieten. So wie es für die anderen Frameworks ja auch geht.

**Comment by deleonio** [comment]
Wir sollten auch gleich die Doku um Angular 16 und 17 erweitern.

- https://public-ui.github.io/docs/get-started/frameworks

**Comment by bastiW** [comment]
Hopefully, that will work in the long run... 

From my experience with Angular Material, you need to deal with breaking changes every six months...
