### ISSUE TITLE
Workflow for Issue-Handling

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5604]
Primäres Ziel:

- Schließen, nach 180 Tagen
- Frag ChatGPT - Angular, Stencil
- Nice2Have Holiday-Comment

**Comment by sdvg** [comment]
Diese Action erledigt ziemlich genau, was wir möchten und kann über einen Cronjob z.B. täglich angestoßen werden: https://github.com/marketplace/actions/close-stale-issues

Vorschlag zur Konfiguration folgt im PR.

**Comment by deleonio** [comment]
Gerne die Action umsetzen.

**Comment by sdvg** [comment]
@deleonio Dafür müssten wir es einmal mergen, Review steht noch aus. Anschließend kann ich die Action im Debug Mode ausführen und wir sehen in den Logs, ob alles in Ordnung ist.
