### ISSUE TITLE
🐞 Bug: Tabellenzelle mit Renderfunktion wird als anklickbar ausgewiesen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#5617]
# Fehlermeldung

## Beschreibung des Fehlers
Wenn für eine Tabellenspalte eine Renderfunktion verwendet wird, die direkt auf dem jeweiligen Element rendert, wird die jeweilige Tabellenzelle von Screenreadern in jedem Fall als anklickbar ausgegeben, selbst wenn keine interaktiven Elemente enthalten sind.

## Reproduktion

[Link zu StackBlitz](https://stackblitz.com/edit/vitejs-vite-qeps2m?file=package.json,src%2FApp.tsx)

Schritte zum Reproduzieren des Verhaltens:
- Öffne Stackblitz
- Bleibe im ersten Tab
- Tabelle mit Screenreader vorlesen lassen.

## Erwartetes Verhalten
Celle wird nicht als anklickbar ausgewiesen.

**Comment by sdvg** [comment]
Siehe auch: https://github.com/public-ui/kolibri/issues/4191
Fork vom StackBlitz, bei dem das Tab mit der Tabelle geöffnet ist: https://stackblitz.com/edit/vitejs-vite-s86r7b?file=package.json,src%2FApp.tsx

**Comment by sdvg** [comment]
Geschlossen als Duplikat
