### ISSUE TITLE
🐞 Bug: 11.7 Elemente haben keinen Rahmen bei hohem Kontrast

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5626]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In einigen Komponenten haben Elemente keinen sichtbaren Rahmen, wenn man die Farben im Browser (Firefox) anpasst (gemäß BIK BITV 11.7), oder den Windows Hochkontrastmodus verwendet. Dadurch sind die Elemente schlecht zu erkennen oder von der Umgebung abzugrenzen. Die Lösung ist bspw. den Elementen einen (transparenten) Rahmen (border) zu geben.

## Reproduktion

Version: v2.0.0-rc.10
Folgende Komponenten Prüfen:

- avatar (wenn kein Bild, sondern Text enthalten ist)
- badge
- heading badge (badges nicht von Überschrift unterscheidbar)
- (Schließen Button in alert bspw. Z2)
- card (nur BMF)
- input-checkbox Switch (nur BMF)
- modal (Fenster nicht vom Hintergrund unterscheidbar, nur BMF)

Schritte zum Reproduzieren des Verhaltens:
Farben anpassen im Firefox:
Einstellungen -> Allgemein -> Farben

Windows Hochkontrastmodus:
Windows-Suche nach "Kontrast" -> Hoher Kontrast -> An

## Erwartetes Verhalten
Auch bei benutzerdefinierten Farben/Kontrasten sollten die Elemente gut Unterscheidbar/Erkennbar sein bspw. zum Hintergrund oder zu anderen Inhalten.

**Comment by laske185** [comment]
Setzen der Border in den Component-Styles.

**Comment by fohi17** [comment]
@sdvg Huhu, mir ist eben aufgefallen, dass bei der input-checkbox switch Komponente noch ein transparenter Rahmen schön wär, für die toggles (im default Theme und BMF).

**Comment by sdvg** [comment]
@fohi17 Danke für den Hinweis! Ich habe hier ein neues Ticket dazu aufgemacht: https://github.com/public-ui/kolibri/issues/5910
Schau gerne mal drauf, ob das so passt.

Haben wir bei [input-checkbox button](https://public-ui.github.io/v2/sample-react/#/input-checkbox/button) vielleicht das gleiche Problem, oder kann das so bleiben?

**Comment by fohi17** [comment]
@sdvg Passt für mich. 
Bei der Button-Variante ist es diskutabel. Hier gibt es (zumindest im default theme) auch in hell keinen Rahmen, daher finde ich es "fair" dass es auch im Hochkontrast keinen gibt.

**Comment by deleonio** [comment]
Reopen for v1.

**Comment by deleonio** [comment]
Ist für v2 gefixed und für v1 obsolet. Für v3 implizit behoben.
