### ISSUE TITLE
🐞 Bug: 9.1.4.10 Schlechter oder kein Umbruch bei Vergrößerung

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5628]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei einer starken Vergrößerung brechen die meisten Komponenten korrekt um.
Bei eineigen Komponenten muss jedoch horizontal gescrollt werden, da sie nicht umbrechen.
Teilweise brechen die Komponenten zwar um oder werden gestaucht, die Inhalte sind aber dadurch nicht oder schlecht lesbar.
Vermutlich liegen einige der Fehler daran, dass es sich um Beispiele handelt. Diese sollten jedoch trotzdem korrekt umbrechen.

## Reproduktion
Version: v2.0.0-rc.10
Folgende Komponenten Prüfen:
-	button width (Kein Umbruch)
-	button access-key (Nur Text in Buttons bricht um)
-	card selection (Karten selbst brechen nicht um, Text nicht lesbar
-	link-button (Nur Text in Buttons bricht um)
-	nav (Text bricht um, ist dann aber schlecht lesbar z.B. Z2)
-	table (werden gestaucht, bei Tabellen ist horizontales Scrollen erlaubt)
-	table with-pagination (Umbruch ungünstig in pagination)
-	toast (Passt sich nicht an Fensterbreite an, daher garnicht lesbar)

**Schritte zum Reproduzieren des Verhaltens:**
- In Chrome das Browserfenster auf eine Breite von 1280 CSS-Pixeln und eine Höhe von 1024 CSS-Pixeln einstellen. Hierzu lässt sich die Resize-Funktion der Web Developer Toolbar nutzen.
- Auf 400% zoomen
- Die Seite neu laden

## Erwartetes Verhalten
Alle Beispiele/Komponenten sollten so umbrechen, dass nicht horizontal gescrollt werden muss (Ausnahme Tabellen, Bilder etc.). Alle Inhalte müssen weiterhin erreichbar und lesbar sein.

**Comment by sdvg** [comment]
@fohi17 Eine Frage zu folgendem Punkt:

> nav (Text bricht um, ist dann aber schlecht lesbar z.B. Z2)

Welche Variante der Nav ist hier gemeint? Bei mir sehen auf 1024px bei 400% tatsächlich alle in Ordnung aus.

Die horizontale Navigation wir vermutlich nicht ganz responsive hin. Hier wäre es aus meiner Sicht sinnvoll, ab einem bestimmten Breakpoint in der Anwendung automatisch auf die vertikale Navigation umzuschalten.

**Comment by sdvg** [comment]
Ticket wird aktuell von @cyrinermd bearbeitet.

**Comment by fohi17** [comment]
@sdvg Danke für den Hinweis! Ja, ich meinte bei der nav-Komponente tatsächlich die horizontale Variante. Je nach Theme bricht hier z.T. jeder Buchstabe um. Die Lösung, ab einem bestimmten Punkt zur vertikalen Navigation zu wechseln finde ich gut. Meiner Meinung nach wäre es ausreichend, wenn das als Hinweis in der Doku o.ä. steht. 

![image](https://github.com/public-ui/kolibri/assets/149500785/63087536-b1a1-45c7-a2cb-ddcc19bd44cd)

**Comment by laske185** [comment]
Könnte durch [#3044](https://github.com/public-ui/kolibri/issues/3044) behoben werden.
