### ISSUE TITLE
🛹 Feature: Sample in Version 1 und 2 anbieten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5637]
Zum Nachtesten, wollen wir online auch die Version 1 als Sample App zum Abrufen haben. Wir müssen dazu den Workflow für die Dokumentation public-ui.github.io erweitern und in zwei verschiedene Ordner kopieren.

Aktuell:
- https://public-ui.github.io/sample-react

Zukünftig:
- https://public-ui.github.io/v1/sample-react
- https://public-ui.github.io/v2/sample-react

**Comment by deleonio** [comment]
FYI: @sdvg @Chrisdo82 @Sommerli2 @fohi17 @Andreas-Englisch

**Comment by fohi17** [comment]
@deleonio Cool! Kann es sein, dass dann der iFrame in den Beispielen der Doku noch angepasst werden muss oder bin ich da falsch? z.B. https://public-ui.github.io/docs/components/accordion
