### ISSUE TITLE
🛹 Feature: Verzögerung bei Tooltips

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#5639]
Die Nielsen-Group und Bfit Bund empfehlen die Erscheinung von Tooltips nach 0.3 - 0.5 Sekunden. Ablauf sieht wie folgt aus: 

1. Mouse cursor enters target area: display visual feedback within 0.1 seconds.
2. Wait 0.3–0.5 seconds.
3. If cursor remains stopped within target area, display corresponding hidden content within 0.1 seconds.
4. Keep displaying the exposed content element until the cursor has left the triggering target area

Quelle: https://www.nngroup.com/articles/timing-exposing-content/
Bfit Bund: https://handreichungen.bfit-bund.de/barrierefreie-uie/0.4/tooltip.html

Plan: Defaultwert auf 0.5 setzen, aber überschreibbar machen

**Comment by sdvg** [comment]
Anpassen auf 0.3 Sekunden, im Code auf die Referenz verweisen: https://www.nngroup.com/articles/timing-exposing-content/

**Comment by laske185** [comment]
Nach ausgiebiger Diskussion - Todo:

- [ ] Verzögerung fest auf 0,3 Sekunden (es gibt bereits ein delay)
- [ ] Es gibt keinen neuen Parameter

**Comment by deleonio** [comment]
@chrisalat Hi Chris, machst Du das bitte auch für `v1`. Danke
