### ISSUE TITLE
🐞 Bug: 9.4.1.2 input-range: Auf Schieber wird falscher Wert ausgegeben

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5658]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Der Schieberegler kann mit dem Screenreader durch lineares Lesen wahrgenommen werden (vor dem Drehfeld). Dabei wird der wert des Schieber ausgegeben. Allerdings entspricht dieser Wert immer dem, der über den Schieberegler selbst (mit der Maus) eingestellt wurde. Wird der Wert über das Drehfeld angepasst, wird dies nicht für den Schieber übernommen. Der Wert des Schiebers und dem Drehfeld stimmen dann für Screenreader-Nutzer nicht überein.

## Reproduktion
Komponente: input-range basic (https://public-ui.github.io/v2/sample-react/#/input-range/basic)
Version: v2.0.0-rc.11

Schritte zum Reproduzieren des Verhaltens:
- Screenreader (NVDA) starten
- Linear lesend (Pfeiltasten) zum Schieberegler navigieren => Wert wird ausgegeben
- Den Wert im Drehfeld anpassen
- Erneut den Schieber linear lesen => Alter Wert wird ausgegeben

## Erwartetes Verhalten
Der Wert des Schiebers und des Drehfelds sollten übereinstimmen, auch für Screenreader.

**Comment by laske185** [comment]
Initialwert ist nicht im input-number gesetzt. Bei Pfeil-Hoch wird vom Minimalwert gestartet anstatt vom aktuellen Wert.

**Comment by fohi17** [comment]
Beschluss: Um die Dopplung des Elements für Screenreader-Nutzer zu verhindern, sollte der Schieber mit aria-hidden ausgeblendet werden, sodass nur das Drehfeld ausgegeben wird. Damit ist auch das Problem mit dem Wert gelöst.

**Comment by deleonio** [comment]
- [x] input type range wird `aria-hidden="true"` hinzugefügt, um das Screenreader-Vorlese-Problem zu beheben und es ist für blinde Nutzer so und so irrelevant
- [x] wir übernehmen den Initialwert vom Range in das Numberfeld, wenn kein Wert gesetzt ist
