### ISSUE TITLE
🐞 Bug: 9.2.1.1 input-radio: Auswahl erhält nicht den Fokus

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5659]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Da im ersten Beispiel der aktive Radiobutton disabled ist, erhält die Auswahl nicht den Tastaturfokus und kann daher nicht bedient werden. Das ist als Beispiel eher ungünstig und sollte generell nicht möglich sein. 

## Reproduktion

Komponente: input-radio basic (https://public-ui.github.io/v2/sample-react/#/input-radio/basic)
Version: v2.0.0-rc.11

Schritte zum Reproduzieren des Verhaltens:
- input-radio öffenen
- mit TAB navigieren

## Erwartetes Verhalten
Im Bespiel sollte der initial aktive Radiobutton nicht disabled sein (und ein Hinweis im Erklärtext dazu stehen).

**Comment by laske185** [comment]
Ist das ausgewählte Element der Radio-Group deaktiviert, kann man die gesamte Gruppe nicht mittels Tastatur anwählen.

<img width="412" alt="image" src="https://github.com/public-ui/kolibri/assets/37439758/6a8eb3e2-a2b2-433f-8e30-df60eca0ca3f">

**Comment by sdvg** [comment]
Ich habe mich kurz mit der Frage beschäftigt, ob das Verhalten hier angepasst werden könnte, man die Radio-Gruppe also fokussierbar machen könnte, obwohl gerade eine deaktivierte Option angehakt ist.

Hier habe ich keinen guten Weg gefunden: Chrome und Firefox überspringen die Radio-Gruppe automatisch in der Tab-Reihenfolge. Selbst wenn man den Fokus händisch mit JS setzt, wird die Fokus-Markierung nicht korrekt aktualisiert, wenn man die gewählte Option mit den Pfeiltasten ändert.

Deshalb würde ich tatsächlich einfach das Beispiel anpassen und solche Konstrukte komplett vermeiden.
