### ISSUE TITLE
🐞 Bug: 9.2.2.2 kolibri animated: Farbwechsel kann nicht abgeschaltet werden

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5668]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Der Farbwechsel des Kolibri-Logos kann im Beispiel nicht abgeschaltet werden. Dadurch ist ständig Bewegung auf der Seite, was ablenkend ist.

## Reproduktion
Komponente: kolibri animated (https://public-ui.github.io/v2/sample-react/#/kolibri/animated?theme=unstyled)
Version: v2.0.0-rc.11

## Erwartetes Verhalten
Wenn es unbedingt eine animierte Version geben muss, sollte es einen Button oder Option geben, die Animation zu stoppen.

**Comment by laske185** [comment]
Die Komponente soll nach 5 Sekunden den Farbverlauf stoppen.
Media-Query zum generellen deaktivieren.

**Comment by deleonio** [comment]
KoliBri ist kein Test-Objekt. Dann eher das Feature entfernen.
