### ISSUE TITLE
🐞 Bug: 9.1.1.1a link target: Hinweis auf neuen Tab wird bei Icon nicht ausgegeben (2)

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5670]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei Links die keinen Linktext haben (hier nur Haus-Icon) wird der Hinweis auf einen neuen Tab vom Screenreader nicht ausgegeben. Die Ursache ist, dass der Link bereits durch ein aria-label beschriftet ist, und daher das aria-label der Grafik im inneren nicht vom Screenreader ausgegeben wird.

## Reproduktion
Komponente: link target (https://public-ui.github.io/v2/sample-react/#/link/target)
Version: v2.0.0-rc.11

Schritte zum Reproduzieren des Verhaltens:
- Screenreader (NVDA) starten
- Mit TAB bis zum letzten Link navigieren

## Erwartetes Verhalten
Der Hinweis sollte bei Links ohne Text ausgegeben werden, wie bei Links mit Text. Evtl. ist es eine Überlegung wert, den Hinweis generell nicht in die Beschriftung zu packen, da dadurch der Linktext sehr lang wird und die Rolle erst ganz am ende kommt.

**Comment by laske185** [comment]
Aria-Label um Text erweitern: "(Wird in einem neuen Tab geöffnet.)".

**Comment by deleonio** [comment]
![image](https://github.com/public-ui/kolibri/assets/6279703/06c8e215-61b0-4100-aa42-a99bf2012690)

> [!Warning]
> Das das nur für `_hideLabel` so umgesetzt werden!

- [x] aria-label um den Text vom Neuen Tab ergänzen / kurze Variante verwenden
- [x] Neuen Tab Icon auf aria-hidden stellen

**Comment by deleonio** [comment]
- [x] Dieses Ticket gleich mit bearbeiten: https://github.com/public-ui/kolibri/issues/5729

**Comment by deleonio** [comment]
Rückmeldung von Test:

Der Hinweis auf neuen Tab wird jetzt ausgegeben und der Text ist schön kurz.
Allerdings ist das Beispiel grade noch falsch. Der Hinweis auf neuen Tab ist aktuell an allen 3 Haus-Icons, sollte aber nur auf dem letzten mit dem entsprechenden Icon sein.

**Comment by fohi17** [comment]
------------- A11y-Test Rückmeldung -------------
Die Versionen in den hier verlinkten Pull requests hatte einen Bug und sind daher noch nicht richtig
https://github.com/public-ui/kolibri/pull/5815: Alle Haus-Icons haben den Hinweis auf den neuen Tab.
https://github.com/public-ui/kolibri/pull/5842: Die Icons sind nicht beschriftet, es wird die URL ausgegeben.

Das Problem und der Bug wurden beide dann hier gelöst: https://github.com/public-ui/kolibri/issues/5873
=> daher **A11y-Test erfolgreich**
