### ISSUE TITLE
🐞 Bug: 9.4.1.2 nav: Aktuelle Seite ist mit Screenreader nicht wahrnehmbar

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5671]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In den nav-Komponenten ist mit dem Screenreader nicht erkennbar, welche die aktuell gewählte Seite ist, da diese nur visuell (abhängig vom Theme) markiert ist. Es gibt zwar eine Komponenten nav aria-current, das aria-Attribut wird hier jedoch scheinbar gar nicht verwendet bzw. wird auch dort nicht die gewählte Seite vom Screenreader ausgegeben.

## Reproduktion
Komponente: nav (alle arten) (https://public-ui.github.io/v2/sample-react/#/nav/basic)
Version: v2.0.0-rc.11

Schritte zum Reproduzieren des Verhaltens:
- Screenreader (NVDA) starten
- Mit TAB über die Navigationslinks navigieren
- Bis zum Eintrag mit "active"

## Erwartetes Verhalten
Die aktuelle Seite sollte vom Screenreader ausgegeben werden, und zwar in allen Beispielen.

**Comment by laske185** [comment]
Das Beispiel muss so korrigiert werden, dass die aktive Komponente auf die reale Seite zeigt.

Link: `#/nav/active`

**Comment by deleonio** [comment]
Achtung: hier bitte erst den aria-current Provider umsetzen.

**Comment by sdvg** [comment]
> Achtung: hier bitte erst den aria-current Provider umsetzen.

Das ist bereits umgesetzt 👍 

Ich habe folgende Änderungen an den Nav Beispielen umgesetzt:

* `active` Markierungen, die nicht zutreffend waren, habe ich alle entfernt.
* Das "active"-Sample habe ich ganz entfernt, da vermutlich redundant?
* Beim "aria-current"-Sample habe ich einen Link zur aktuellen Seite hinzugefügt. Das `aria-current`-Attribut erhält der Link so bereits automatisch. Zusätzlich habe ich, da hier zutreffend, die `active`-Property gesetzt.
* Bei allen Beispielen außer der horizontalen Navigation habe ich die Breite begrenzt, damit man die Navigation besser als solche wahrnehmen kann uns sie nicht mehr so getreckt ist.
