### ISSUE TITLE
🐞 Bug: 9.4.1.2 progress: Keine Screenreader Ausgabe

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5673]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Für Screenreader-Nutzer erfolgt keinerlei Ausgabe der progress-Komponente. Die Ursache ist, dass das SVG keinen Alternativtext hat und der Text mit aria-hidden versteckt wurde. Es gibt zwar ein <span> mit aria-live, dieses hat aber nur Wirkung wenn Inhalt sich dynamisch ändert, und ist daher im Beispiel nicht wahrnehmbar.

## Reproduktion
Komponente: progress basic (https://public-ui.github.io/v2/sample-react/#/progress/basic)
Version: v2.0.0-rc.11

Schritte zum Reproduzieren des Verhaltens:

- Screenreader (NVDA) starten
- Mit den Pfeiltasten navigieren => keine Ausgabe nach dem letzten Komponentenlink

## Erwartetes Verhalten
Wenn sich der Fortschritt dynamisch anpassen soll, sollte dies sich im Beispiel wiederfinden. Andernfalls, wenn es sich um eine statische Anzeige handelt, sollte der Fortschritt mit dem Screenreader beim linearen Lesen wahrnehmbar sein.

**Comment by laske185** [comment]
Alternativtext setzen und aria-hidden entfernen.

**Comment by deleonio** [comment]
> Alternativtext setzen und aria-hidden entfernen.

⚠️ Rücksprache mit @deleonio

**Comment by sdvg** [comment]
`hidden` durch `visually-hidden` ersetzen.
