### ISSUE TITLE
🐞 Bug: 9.2.4.3: Nicht-interaktives Element wird fokussiert

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5674]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei der Split-Button Variante bei der nur der Pfeil den Ausklappbereich öffnet, wird der Text trotzdem fokussiert und vom Screenreader als aktiver Button ausgegeben. Das ist irreführend, da das Element keine Funktion hat. 

## Reproduktion
Komponente: split-button basic (https://public-ui.github.io/v2/sample-react/#/split-button/basic)
Version: v2.0.0-rc.11

## Erwartetes Verhalten
Elemente die keine  interaktive Funktion haben sollten nicht den Tastaturfokus erhalten und vom Screenreader als nicht verfügbar o.ä. ausgegeben werden. 
Generell sollte der Aufbau der Komponente überdacht werden, da in beiden Varianten 2 TAB-Schritte notwendig sind, die aber die keine oder die gleiche Funktion haben, was verwirrend und nicht effizient ist.

**Comment by laske185** [comment]
Kein Fehler. Beim Drücken auf den Button soll etwas passieren. Am besten einen Toast erstellen, der sagt, dass der Button geklickt wurde.
Die Breite der Komponente im Beispiel reduzieren.

**Comment by laske185** [comment]
Neues Ticket erstellen, in dem alle Split-Buttons nachgestyle werden – analog des normalen Buttons des Themes.

**Comment by sdvg** [comment]
Ticket wird von @cyrinermd bearbeitet.

**Comment by sdvg** [comment]
> Neues Ticket erstellen, in dem alle Split-Buttons nachgestyle werden – analog des normalen Buttons des Themes.

Ticket wurde erstellt: https://github.com/public-ui/kolibri/issues/5767

**Comment by sdvg** [comment]
PR: https://github.com/public-ui/kolibri/pull/5769
