### ISSUE TITLE
🐞 Bug: 9.1.3.1e table: Sortierung wird in jeder Spalte ausgegeben

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5675]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Da die Sortierung der Tabellen durch einen Button im Spaltenkopf umgesetzt ist, wird die Beschriftung dieses Buttons bei der Tabellennavigation jedes Mal mit ausgegeben, wenn man die Spalte mit dem Screenreader betritt. Das ist verwirrend und störend.

## Reproduktion
Komponente: table (alle arten mit sortierung) (https://public-ui.github.io/v2/sample-react/#/table/badge-size)
Version: v2.0.0-rc.11

Schritte zum Reproduzieren des Verhaltens:
- Screenreader (NVDA) starten
- Zu der Tabelle Navigieren (z.B. mit T)
- Bspw. zur 2ten Zeile navigieren
- Mit der Tabellennavigation (STRG + ALT + Pfeilrecht) zur sortierbaren Spalte wechseln.

## Erwartetes Verhalten
Die Sortierung sollte nur auf der Spaltenüberschrift ausgegeben werden.
**Empfehlung:** Umsetzung mit Buttons und aria-sort. Es kann davon ausgegangen werden, dass Nutzer wissen, dass <th>s die Buttons sind eine Sortierung bewirken, oder wie im Beispiel ein Hinweistext eingefügt werden: https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/

**Comment by laske185** [comment]
Recherche, wie man verhindert, dass der Button-Text beim Durchgehen der Zellen jedes Mal mit vorgelesen wird.

**Comment by sdvg** [comment]
Als Referenz, hier wird seitens NVDA ebenfalls vorgeschlagen, keinen expliziten Sortier-Button zu verwenden: https://github.com/nvaccess/nvda/issues/6826#issuecomment-277163924

**Comment by deleonio** [comment]
Wir nehmen Button-WC für die Header und Icon rechts

**Comment by sdvg** [comment]
Hier ein aktuelles Test-Deployment zum Nachtesten: https://65804134a6dfa73ecab101e8--magenta-gingersnap-274e19.netlify.app/
