### ISSUE TITLE
The kolibri theme designer does not work page not found 

### ISSUE THREAD

**Issue by kahursro** [public-ui/kolibri#5680]
The page with kolibri designer is not working and im unable to generate theme using the designer.

**Comment by deleonio** [comment]
Es gibt neue Links (Redirects funktionen offensichtlich noch nicht)

- https://public-ui.github.io/v1/designer/
- https://public-ui.github.io/v2/designer/
- https://public-ui.github.io/v1/sample-react/
- https://public-ui.github.io/v2/sample-react/

**Comment by deleonio** [comment]
Redirect sind eingerichtet und funktionieren jetzt. Ticket wird geschlossen.

- https://public-ui.github.io/designer/
- https://public-ui.github.io/sample-react/
