### ISSUE TITLE
📖 Help: Howo change theme in react in runtime

### ISSUE THREAD

**Issue by kahursro** [public-ui/kolibri#5681]
Hello I have been trying to work around for quite some time to get it working, but i haven't seen anywhere something about how to switch between themes if you create one and u need to switch in runtime. I've tried to update root tag, tags with data-theme but it wasn't react at all.

**Comment by deleonio** [comment]
Hi @kahursro,

if you want to change themes dynamically, you have to register several themes, set the theme detection to `auto` and use the data attribute `data-theme`.

Here are a few short links that may help:
- https://github.com/public-ui/kolibri/blob/cc24292ce450069f4c826cd818d2d490292bd569/packages/samples/react/src/react.main.tsx#L26
- https://github.com/public-ui/kolibri/blob/cc24292ce450069f4c826cd818d2d490292bd569/packages/samples/react/src/react.main.tsx#L28
- https://github.com/public-ui/kolibri/blob/cc24292ce450069f4c826cd818d2d490292bd569/packages/samples/react/src/App.tsx#L124

> [!NOTE]
> It is important to note that the components must be re-rendered once after setting so that they take the new theme into account.
