### ISSUE TITLE
💡 Hinweis: `dialog`-Tag nachprüfen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5692]
Bitte hinsichtlich des folgenden Blog-Post die Barrierefreiheit des Standard-Tags `dialog` nachtesten. 

- https://www.linkedin.com/posts/marcelhageman_when-youre-a-semantic-html-and-accessibility-activity-7137387566814638081-INgv

**Comment by cbraehmig** [comment]
Besprochen und wird überprüft.

**Comment by ElVariablo** [comment]
In dem Artikel geht es vornehmlich darum, wie der Hintergrund eines Dialog Element gestylt werden kann, wenn dieser nicht über den im Standard definierten weg geöffnet werden kann. Der Grund warum über diesen Weg nachgedacht wird ist der, dass die Befehle zum öffnen des Modal momentan angeblich noch im "experimental" Status befindet ist für mich nicht nachvollziehbar. [Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal#browser_compatibility) schreibt zu dem Befehl, dass dieser in allen gängigen Browsern vollständig unterstützt wird. 

Da das der Fall ist, ist der Rest des Artikels irrelevant. Das Element hat kein Problem mit der Barrierefreiheit.
