### ISSUE TITLE
🛹 Feature: Select mit Suchfunktion

### ISSUE THREAD

**Issue by agnieszkaw61** [public-ui/kolibri#5693]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Ich brauche ein Selectkomponent mit viele Optionen und es ist frustrierend so lang zu scrollen.

## Beschreiben Sie die gewünschte Lösung
Ich hätte gerne die Möglichkeit, in der Selectkomponent nach möglichen Optionen zu suchen/zu filtern

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Möglicherweise gibt es eine Problemumgehung oder eine Beispielimplementierung für dieses Problem, die Sie uns mitteilen könnten

## Zusätzlicher Kontext
Hier habe ich ein Beispielimplementierung gefunden, wie sollte es funktionieren: https://stackblitz.com/edit/angular-searchable-dropdown?file=src%2Fapp%2Fapp.component.ts

**Comment by deleonio** [comment]
Hallo @agnieszkaw61,

vielen Dank für die Anfrage. Die gewünschte Komponente war schon mehrfach im Gespräch und wir sehen sie auch aus den genannten Gründen als relevant für KoliBri an.

Vielen Dank für das Implementierungsbeispiel. Wir haben das Thema ins Backlog aufgenommen und priorisiert. Zunächst werden wir uns mit der Komponenten-Konstruktion und barrierefreien Semantik auseinandersetzen. Anschließend würde es dazu eine erste Umsetzung geben.

Kurzfristig, können wir mal schauen, was man mit den aktuellen KoliBri schon umsetzen könnte. Ich sehe da eine Kombination aus einem Search und einem Select Input - die ineinander greifen. Das Search-Input reduziert die Options des Select und die gewählte Select-Option gibt den ausgewählten Wert an.

**Comment by deleonio** [comment]
Dieses Feature, wird mit der ComboBox umgesetzt.
