### ISSUE TITLE
🐞 Bug: input-checkbox: hideLabel hat sichtbare Label

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5694]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Im Theme BMF hat die Komponenten "input-checkbox button" auf der rechten Seite sichtbare Labels, obwohl diese versteckt sein sollten (siehe andere Themes).

## Reproduktion
Komponente: input-checkbox button (https://public-ui.github.io/v2/sample-react/#/input-checkbox/button?theme=bmf)
Version: v2.0.0-rc.12

![image](https://github.com/public-ui/kolibri/assets/149500785/82201f0f-bfff-4f59-8649-1b7af8fd66ce)

**Comment by sdvg** [comment]
Habe ich heute zufällig auch entdeckt und wird in diesem Ticket mit behoben: https://github.com/public-ui/kolibri/issues/5548
