### ISSUE TITLE
💡 Hinweis: input-number: Zahlengrenzen werden nicht evaluiert

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5696]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
In der Komponente "input-number basic" (v2.0.0-rc.12) werden im 2ten Zahleneingabefeld die Werte die mit der Tastatur eingegeben werden nicht evaluiert. Es können Werte über 10 und ungerade Werte eingegeben werden. Für ein gutes Beispiel sollte in diesem Fall die Fehlermeldung angezeigt werden. 

![image](https://github.com/public-ui/kolibri/assets/149500785/beebd6c3-2c82-441d-b726-198786537284)

**Comment by deleonio** [comment]
Der W3C Standard blockiert die freie Eingabe nicht, da sonst mögliche Eingabe blockiert werden. Z.B. Mindestwert ist 1.000 und man beginnt die Eingabe mit 1.

~~Um unser Beispiel valide umzusetzen, erweitern wir die Sample-App um ein Change-Handling (Formatter-Parser-Konzept) - onBlur.~~

- [ ] Die Eingabe darf nicht eingeschränkt sein. Wir müssen dieses Beispiel konkret beschreiben.
- [ ] Dass wir den Kontext von KoliBri als Präsentationsschicht noch einmal dokumentieren. Und dass es sich bewusst aus der Funktionalität (Validierung) heraushält, um flexible für die Wiederverwendung zu bleiben. (https://public-ui.github.io/docs/concepts/formular)

**Comment by laske185** [comment]
Basisfunktionalität der Komponente
Native Eigenschaften der input-Komponente wird gesetzt
Natives Verhalten der HTML-Komponente - reines HTML
Nur teilweise unterbindung. Freie Eingabe ohne Einschränkung möglich.
Es ist keine Validierungsregel. Beispiele sind ohne Form-Validierung.

Keine zusätzliche Validierung über die native HTML-Element-Validierung findet nicht statt.

Ähnlicher Text für alle Input-Beispiele.
