### ISSUE TITLE
🐞 Bug: 9.3.3.1 input-range: Automatische Korrektur wird nicht vom Screenreader ausgegeben

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5697]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei der Eingabe von Werten über das Drehfeld (nicht den Schieber) werden die Werte automatisch korrigiert, wenn sie größer sind als der erlaubte Wert. Diese Korrektur ist mit dem Screenreader nicht wahrnehmbar. Screenreader-Nutzer bemerken daher ihren Fehler und den neuen Wert im Drehfeld nicht. 

## Reproduktion

Komponente: input-range basic (https://public-ui.github.io/v2/sample-react/#/input-range/basic)
Version: v2.0.0-rc.12

Schritte zum Reproduzieren des Verhaltens:
- Screenreader (NVDA) starten
- Mit TAB zum einer Drehfeld navigieren
- Mit der Tastatur einen Wert über 50 in das Drehfeld eintippen => Wert wird ohne Rückmeldung auf 50 gesetzt.

## Erwartetes Verhalten
Der Nutzer muss über automatische Korrekturen Informiert werden, auch bei der Nutzung eines Screen-Readers. Besser wäre, die automatische Korrektur zu entfernen, und stattdessen eine Fehlermeldung anzuzeigen/auszugeben. Automatische Korrekturen können leicht übersehen werden, wohingegen eine Fehlermeldung konkret auf den Fehler hinweist und Nutzer diesen beheben können.

**Comment by deleonio** [comment]
Dieses Ticket wird durch https://github.com/public-ui/kolibri/issues/5658 bearbeitet.
