### ISSUE TITLE
💡 Hinweis: Themes mit Draft-Status versehen

### ISSUE THREAD

**Issue by cbraehmig** [public-ui/kolibri#5704]
Themes, die aktuell noch in der Entwicklung sind bzw. noch nicht freigegeben sind, sollten entsprechend gekennzeichnet werden.

**Comment by deleonio** [comment]
Folgende Themes sind exemplarisch umgesetzt, aber nicht hinsichtlich der BITV nachgetestet. Bei diesen Themes steht die Machbarkeit der Design-Anforderung auf KoliBri-Komponenten im Vordergrund. Es fördert und fordert die Flexibilität der KoliBri-Komponenten-Konstruktion und Basis-Styles.

- ECL - EU
- ECL - EC
- ITZBund
- TH

> Banner auf der Beispielseite für die vier Themes: https://github.com/public-ui/kolibri/blob/c1efc5cd114d8d16bad712d5c12dffd6aa10bc79/packages/samples/react/src/App.tsx#L137

- [ ] Hinweis-Alert muss bei `hideMenus` ausgeblendet werden.
