### ISSUE TITLE
💡 Hinweis: badge: Alle "Entfernen"-Buttons sind gleich beschriftet

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5705]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
In der Komponente "badge Button" sind die Buttons zum Entfernen eines Badge alle mit "Entfernen" beschriftet. Je nach Anwendungsfall ist dies ungünstig, da bspw. mit dem Screenreader nicht gut erkennbar ist, welcher Badge entfernt wird. 
**Besseres Beispiel:** badges individuelle Beschriftungen geben und den Button jeweils damit Beschriften bspw. "Badge1 Entfernen", "Badge 2 Entfernen"
Andernfalls sollte in der Dokumentation darauf hingewiesen werden, dass die Beschriftung der Buttons einen Bezug zum Badge haben sollte bzw. nicht mehrere Buttons mit der gleichen Beschriftung vorhanden sein sollten.

**Comment by deleonio** [comment]
- [x] Unterschiedliche Label vergeben: Beispiel Farben "blau"
- [ ] Badges brauchen außen einen Kontext / Überschrift - Hinweis in die Readme.md einarbeiten
- [ ] Im Beispiel muss einen Überschrift ergänzt werden.
- [ ] Label-Text für das Schließen wird: `Entfernen von <Label>`
