### ISSUE TITLE
💡 ResizeObserver loop limit exceeded - Tooltip

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5715]
Wir benötigen für das Problem ein Reproduktionsbeispiel. Anschließend können wir prüfen, wodurch dieser Fehler ausgelöst wird.

**Comment by laske185** [comment]
Woher kommt der Fehler? Wer hat ihn gemeldet? Wie kann man es nachvollziehen?

**Comment by deleonio** [comment]
Kann nicht mehr reproduziert werden.
