### ISSUE TITLE
🐞 Bug: Namenskonflikt mit i18next Bibliothek

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5716]
Historie: https://github.com/public-ui/kolibri/issues/5572

Auftreten:
- nicht im Develop
- nur im Production
- bei deaktivierten Cache passiert es auch nicht (@Chrisdo82 ?!)

Reproduktionsbeispiel erforderlich.

**Comment by nefarius4schmu** [comment]
Hallo zusammen,
ich konnte endlich ein Reproduktionsbeispiel mittels Stackblitz umsetzen. Das nachfolgende Beispiel basiert auf dem Playground, entspricht aber unseren Build-Einstellungen, damit der Produktiv-Build überhaupt funktioniert (Kopieren der KoliBri-Assets etc.).

Link:
https://stackblitz.com/edit/vitejs-vite-zemsmp?file=src%2Fmain.tsx
(Browser-Konsole öffnen, um die Warning zu sehen. Wenn das Problem auftritt, bleibt die Vorschau weiß)


Anmerkungen:
- das Problem tritt verstärkt auf, wenn ein Custom-Theme verwendet wird (Chance liegt bei 50%, was die Vermutung eines Timing-Problems stützt)
- es lässt sich nur im Produktiv-Build nachstellen
- unter Verwendung eines Vorgegebenen-Theme tritt das Problem ebenfalls auf, jedoch wesentlich seltener (vllt. 20% Chance)


Ich kann nach wie vor nicht genau ermitteln, warum das Problem auftritt oder ob wir hier eine falsche Build-Konstellation verfolgen.
Folgende Möglichkeiten ziehe ich in Betracht:
- Namenskonflikt durch doppelte Initialisierung von i18next (Timing-Problem)
- Build-Konstellation sorgt für doppelte Initialisierung von KoliBri oder i18n (Möglichkeit lässt sich aktuell auch nicht ausschließen)

Hier nochmal der letzte erfolgreiche Hack, das Problem zu umgehen: https://github.com/public-ui/kolibri/issues/5572#issuecomment-1835638141

Viele Grüße
Steffen

**Comment by deleonio** [comment]
V1
