### ISSUE TITLE
💡 Hinweis: Nav Beispiel nicht korrekt

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5727]
Bei der Komponente Nav wird die Verwendung im HTML-Kontext als Beispiel verwendet. Hier ist es wichtig, dass die Werte stringifiziert übergeben werden und nicht als JSON-Objekt.

Siehe: https://public-ui.github.io/docs/components/nav

**Comment by sdvg** [comment]
Ticket wird von @cyrinermd bearbeitet.
