### ISSUE TITLE
💡 Hinweis: link target: Hinweis auf neuen Tab kann verkürzt werden

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5729]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
Der Hinweis, dass ein Link in einem neuen TAB geöffnet wird ist sehr lang. Er sollte gekürzt werden bspw. auf "Wird im neuen Tab geöffnet".

Komponente: link target
Version: v2.0.0-rc.12

**Comment by sdvg** [comment]
Behoben in #5670
