### ISSUE TITLE
💡 Hinweis: pagination: Beschriftung der Seiten sollte deutlicher oder einstellbar sein

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5730]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
Bei der Nutzung der Pagination mit dem Screenreader werden die Seitenbuttons mit der jeweiligen Seitenzahl als Beschriftung ausgegeben (z.B. "1 Schalter", "2 Schalter"). Das ist zwar nicht falsch, geht aber auch deutlicher bspw. "Seite 1", "Seite 2". 
Selbiges gilt für die aktuelle Seite. Diese wird ebenfalls nur als Zahl ausgegeben und der Button als deaktiviert. Dadurch kann man sich erschließen, dass das die aktuelle Seite ist. Schöner wäre aber auch die Ausgabe als gewählte Seite o.ä.

Die Entscheidung sollte evtl. beim Nutzer der Komponente liegen, also die Beschriftung der Seiten-Buttons einstellbar sein. In diesem Fall sollte dies in der Doku beschrieben.

**Comment by deleonio** [comment]
![image](https://github.com/public-ui/kolibri/assets/6279703/1758ba0e-48c7-4f20-a257-20a5659755c9)

Gute Vorlage: https://design-system.w3.org/components/pagination.html

**Comment by anicyne** [comment]
- wir verwenden .visually-hidden
- Translate Funktion benutzen
- Alle Buttons berücksichtigen "Aktuelle Seite", "Erste Seite", "Letzte Seite", "Vorherige Seite", "Nächste Seite"
