### ISSUE TITLE
💡 Hinweis: split-button: Beschriftung nicht sinnvoll/Rechtschreibfehler

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5731]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**

Der Inhalt des geöffneten Split-Buttons ist "Drowndown-Inhalt". Sollte wahrscheinlich Dropdown heißen. 
Evtl. wäre etwas mehr Text in einem Beispiel auch nicht schlecht.

Zusätzlich ist der Inhalt des Tooltips mit "ohne Label" nicht so schön.

Link: https://public-ui.github.io/v2/sample-react/#/split-button/basic

**Comment by deleonio** [comment]
Beispiel wie empfohlen verbessern.
