### ISSUE TITLE
🐞 Bug: 1.1.1b version: Versions-Icon sollte keine Layoutgrafik sein

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5732]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Visuell ist anhand des Versions-Icons erschließbar, was hiermit dargestellt werden soll. Das Icon ist jedoch für Screenreader ausgeblendet und daher die Hervorhebung und Bedeutung der Zahl für Screenreader-Nutzer nicht erkennbar.

## Reproduktion
Komponente: version basic (https://public-ui.github.io/v2/sample-react/#/version/basic)
Version: v2.0.0-rc.12

## Erwartetes Verhalten
Das Icon sollte programmatisch mit "Version" beschriftet werden, oder das ganze Element eine Beschriftung erhalten, damit die Bedeutung mit dem Screenreader erkennbar ist.

**Comment by deleonio** [comment]
- [ ] Das Icon bei Version sollte das Label `Version` erhalten. (Bei Alerts mit Fehler usw. ist das auch so.)
- [ ] `v` entfernen

**Comment by laske185** [comment]
Dem Icon kann aktuell kein Label gegeben werden.

**Comment by deleonio** [comment]
v1

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich** -------------
