### ISSUE TITLE
🐞 Bug: Alert: Oft fehlerhaftes Layout nach erstem Render

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#5735]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Beim ersten Rendern der Alert-Komponente sieht die Komponente oft so aus:
<img width="622" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/d9db809a-d957-441a-8f85-6a72d6a32036">

Nach dem Neuladen wird sie dann korrekt dargestellt:
<img width="710" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/b1a7a54c-18c4-4504-9de6-56e9d834888b">

## Reproduktion

Schritte zum Reproduzieren des Verhaltens:

1) [Beispiel aufrufen](https://public-ui.github.io/v2/sample-react/#/alert/basic)
2) Über die Pfeil-Buttons ggf. mehrfach zur vorherigen Komponente und zurück navigieren

## Zusätzlicher Kontext

Vermutlich ein Problem mit den Slots, Inhalte werden außerhalb des Slots gerendert.

**Comment by deleonio** [comment]
Rerender-Problem: -> das hat [Gemeinsamkeiten mit dem Radio-Problem ](https://github.com/public-ui/kolibri/issues/3514)

![image](https://github.com/public-ui/kolibri/assets/6279703/1b0fcc81-a4f9-41ae-a04d-210a841e347b)
