### ISSUE TITLE
🐞 Bug: 9.2.4.3 appointment-form: Fokus wird nicht auf Fehlerliste gesetzt

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5743]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei einem Fehler in einem Formular wird eine Fehlerliste angezeigt. Der Tastaturfokus verbleibt jedoch auf dem Absenden/Weiter-Button. Tastaturnutzer müssen Rückwärts navigieren um den Fehler zu korrigieren.

## Reproduktion
Komponente: Scenarios Appointment-form (https://public-ui.github.io/v2/sample-react/#/scenarios/appointment-form?theme=default)
Version: v2.0.0-rc.13

## Erwartetes Verhalten
Beim Versuch ein fehlerhafte Formular abzuschicken sollte der Tastaturfokus auf die Fehlerliste gesetzt werden.

**Comment by deleonio** [comment]
Test-Link: https://65a7fbb1c5ca3b00785e767a--kolibri-public-ui.netlify.app/#/scenarios/appointment-form

**Comment by deleonio** [comment]
Blocked by https://github.com/public-ui/kolibri/pull/5908#issuecomment-1905452942

**Comment by fohi17** [comment]
@anicyne @deleonio (hoffe ihr 2 seit die richtigen dafür)
Ich hab das eben hier nachgetestet, weil da steht es ist behoben: https://github.com/public-ui/kolibri/pull/6034. Richtig?
Da habe ich jetzt eine fette Tastaturfalle drin, ab Seite 2: Sobald die Fehlerliste angezeigt wird kann man das Formular nicht korrigieren und navigieren, weil der Fokus direkt wieder zur Fehlerliste springt.

**Comment by deleonio** [comment]
Hi @anicyne,
wir sollten das KolAlert außerhalb des forms machen, damit das Return nicht zum onSubmit führt.
