### ISSUE TITLE
🐞 Bug: appointment-form: Inkonsistentes Fehlermanagement

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5744]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Das Fehlermanagement im Beispiel-Formular ist inkonsistent. Folgende Probleme bestehen:
- Freie Termine: Die Verlinkung in der Fehlermeldung zu den Radiobuttons funktioniert nicht.
- Persönliche Daten: Bei den Feldern "Anrede" und "Name" werden die Fehlermeldungen nicht ausgeblendet, wenn der Fehler korrigiert wird (bspw. wenn das Pflichtfeld ausgefüllt wird).
- Persönliche Daten: Manche Felder werden direkt beim übertabben fehlerhaft angezeigt (z.B. Name), andere erst beim Absenden, oder wenn das folgende Feld validiert wird (z.B. Anrede).
- Persönliche Daten: Die Fehlerliste ist hier nicht verlinkt.

## Reproduktion

Komponente: Scenarios Appointment-form (https://public-ui.github.io/v2/sample-react/#/scenarios/appointment-form?theme=default)
Version: v2.0.0-rc.13

## Erwartetes Verhalten
Das Fehlerverhalten sollte für alle Felder und Seiten konsistent sein, und die oben erwähnten Punkte korrigiert werden.

**Comment by deleonio** [comment]
Prüfen, was genau geändert werden kann.

**Comment by deleonio** [comment]
Test-Link: https://65a7fbb1c5ca3b00785e767a--kolibri-public-ui.netlify.app/#/scenarios/appointment-form

**Comment by deleonio** [comment]
Blocked by https://github.com/public-ui/kolibri/pull/5908#issuecomment-1905452942

**Comment by fohi17** [comment]
------------- A11y-Test Erfolgreich für v1-------------

**Comment by sdvg** [comment]
@deleonio Ich glaube das kann geschlossen werden, hier war eigentlich alles erledigt, die PRs sind gemerged. Falls ich falsch liege bitte wieder öffnen :)
