### ISSUE TITLE
💡 Hinweis: appointment-form: Ausgabe von Fehlerhinweis ist störend

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5745]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
Komponente: Scenarios Appointment-form (https://public-ui.github.io/v2/sample-react/#/scenarios/appointment-form?theme=default)
Version: v2.0.0-rc.13

In dem Beispiel wird im Tab "Freie Termine" zwischen jedem Wechsel der Radiobuttons "geladen" also die Spin-Komponente angezeigt. Dadurch wird auch bei jedem Wechsel der Hinweis "Aktion wir ausgeführt... Benachrichtigung beschäftigt" vom Screenreader ausgegeben. Dies ist störend, und sollte im Beispiel so nicht verwendet werden. Die Spin-Komponente sollte an einer anderen Stelle demonstriert werden.

**Comment by deleonio** [comment]
Tendenz ist:
- Beispiel optimieren
- Ausgabetext mittels eines neuen Prop anpassbar zu machen

**Comment by deleonio** [comment]
Fragen sind:
- Welchen Sinn macht das Label-vorlesen beim Spin. Label-vorlesen zusätzlich zum `aria-busy` notwendig?
- Ist das `aria-busy` am Spin falsch und muss an die Region, wo geladen wird?
- Reicht nur die visuelle Ausgabe - und für Screenreader ist `aria-busy`

**Comment by deleonio** [comment]
@cbraehmig bitte mit in das JF am Dienstag mitnehmen.

**Comment by fohi17** [comment]
@deleonio 
Nach Rücksprache: Ja, das Label soll dran bleiben. Nein, das aria-busy darf am Spin bleiben. Nein, für Screenreader reicht aria-busy nicht.
Soll heißen: Die Komponente soll so bleiben wie sie ist, aber das Beispiel geändert werden. D.h. dass die Spins nicht an der Stelle demonstriert werden, wenn zwischen den Radiobuttons gewechselt wird.

**Comment by deleonio** [comment]
- [ ] Konzept schreiben und mit ins Beispiel einbauen
- [ ] Beispiel noch einmal neu umsetzen

**Comment by chrisalat** [comment]
#6183
