### ISSUE TITLE
💡 Hinweis: alert html: Überschriftenhierarchie ist nicht korrekt

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5747]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**

Das Beispiel ist ein schlechtes Vorbild, da die Überschriftenhierarchie nicht korrekt ist. 
- Der blaue Hinweis ist die h1, ist aber nicht visuell die Hauptüberschrift
- Die Ebene h3 wird übersprungen.

Komponente: alert html (https://public-ui.github.io/v2/sample-react/#/alert/html)
Version: v2.0.0-rc.13

**Comment by anicyne** [comment]
wir würden folgendes ändern:

- H2 Überschrift entfernen
- H4 Überschriften zu H2 ändern

@fohi17 passt das so?

**Comment by fohi17** [comment]
@cyrinermd Ja, fände ich ok so : )
