### ISSUE TITLE
💡 Hinweis: alert html: Spalten brechen nicht um

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5748]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
Bei starkem Zoom brechen die Spalten (links, rechts) nicht um. Im Beispiel ist der Inhalt weiterhin gut wahrnehmbar. Je nach dem was sich in den Spalten befindet kann das jedoch zu Problemen führen. 

Komponente: alert html (https://public-ui.github.io/v2/sample-react/#/alert/html)
Version: v2.0.0-rc.13

**Comment by deleonio** [comment]
Hier muss nur beim `sm` den breakpoint auf einspaltig geändert werden.
