### ISSUE TITLE
🐞 Bug: 9.4.1.2 input-date basic: Readonly wird von Screenreader nicht ausgegeben

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5749]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Bei dem Eingabefeld "Zahleneingabe (Readonly)" wird vom Screenreader nicht ausgegeben, dass das Feld schreibgeschützt ist.

(Hinweis: Das Feld ist zur Zeit fälschlicherweise als "Zahleneingabe" beschriftet, es sollte "Datumseingabe" heißen und wird in diesem Ticket ebenfalls korrigiert)

Ähnlich https://github.com/public-ui/kolibri/issues/5554
Readonly ist zwar im Code gesetzt, es erfolgt aber weder mit NVDA noch JAWS eine Ausgabe. Getestet in Chrome und Firefox.

## Reproduktion

Komponente: input-date basic (https://public-ui.github.io/v2/sample-react/#/input-date/basic)
Version: v2.0.0-rc.13

Schritte zum Reproduzieren des Verhaltens:
- input-number basic öffnen
- Screenreader (NVDA) starten
- Mit der TAB-Taste navigieren bis "Zahleneingabe (Readonly)"

## Erwartetes Verhalten
Der Status, also "schreibgeschützt", sollte vom Screenreader ausgegeben werden.

**Comment by deleonio** [comment]
- [x] [`KNOWN_ISSUES.md`](https://github.com/public-ui/kolibri/blob/develop/KNOWN_ISSUES.md) dokumentieren und auf dieses Ticket verlinken

**Comment by sdvg** [comment]
Ich hab's auch noch mal nachgetestet: Beim nativen Minimalbeispiel mit `<input type=date readonly>` ließt NVDA das "Readonly" ebenfalls nicht vor.
Verwandtes Ticket: https://github.com/nvaccess/nvda/issues/13672
