### ISSUE TITLE
💡 Hinweis: input-text basic

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5750]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
Auf der linken Seite, bei den Beispielen mit sichtbaren Label, hat das erste Feld "Suche" kein sichtbares Label, sondern nur ein Tooltip (wie rechts).

Komponente: input-textbasic (https://public-ui.github.io/v2/sample-react/#/input-text/basic)
Version: v2.0.0-rc.13

**Comment by deleonio** [comment]
- [ ] Label vom 2. Feld nach oben
- [ ] Icon-Only links deaktivieren
- [ ] AccessKey mit übernehmen
- [ ] 2. Beispiel links und rechts entfernen

![image](https://github.com/public-ui/kolibri/assets/6279703/dfce2c52-ef9d-4cc1-81c2-aca4a8a1c6eb)
