### ISSUE TITLE
🐞 Bug: Nav: Ausblenden der Navigation funktioniert nicht

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5751]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Über den Button "Navigation minimieren" wird nur der Text ausgeblendet. Enthaltene Icons, die Buttons der Untermenüs und die farbliche Markierung (je nach Theme) bleiben stehen. Auch die klickbaren Bereiche bleiben gleich groß. 

## Reproduktion
Komponente: nav basic (https://public-ui.github.io/v2/sample-react/#/nav/basic)
Version: v2.0.0-rc.13

![image](https://github.com/public-ui/kolibri/assets/149500785/e03bc758-9108-4256-b4b2-28ce0334bc6f)

**Comment by deleonio** [comment]
- Neues Property für Icons sichtbar im ausgeklappten Modus
- Im eingeklappten Modus immer Icons, Fallback symbol-method
- Beispiel optimieren, für das Auf- und Zuklappen

**Comment by sdvg** [comment]
Teilweise hier schon umgesetzt: https://github.com/public-ui/kolibri/pull/5833

**Comment by sdvg** [comment]
@deleonio

1) Das [Vorgängerticket](https://github.com/public-ui/kolibri/issues/5810), auf dem ich hier aufbauen würde, war nur für `v2` ausgelegt. Wäre das auch hier ausreichend oder müssen wir die Änderungen backporten?

2) Weißt du noch, was mit diesem Punkt gemeint war?
> Beispiel optimieren, für das Auf- und Zuklappen

**Comment by sdvg** [comment]
PR: https://github.com/public-ui/kolibri/pull/6007
