### ISSUE TITLE
🐞 Bug: tabs:  Schneller Tastaturnavigation führt zu doppeltem Fokus

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5752]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Der Wechsel der Registerkarten mit der Tastatur (Pfeiltasten) ist recht langsam. Wird schnell mit den Pfeiltasten zwischen den Tabs navigiert kommt die Fokusanzeige nicht hinterher, und es werden zwei Reiter als fokussiert angezeigt.

## Reproduktion
Komponente: tabs basic (https://public-ui.github.io/v2/sample-react/#/tabs/basic)
Version: v2.0.0-rc.13

Schritte zum Reproduzieren des Verhaltens:
- Mit TAB-Taste auf der Seite zur ersten Registerkarte navigieren.
- Zwei mal schnell hintereinander die Pfeiltaste nach rechts drücken
- => Der Rahmen des Tastaturfokus ist auf der 2ten Registerkarte, die farbliche Hervorhebung auf der 3ten.

## Erwartetes Verhalten
Das navigieren zwischen Registerkarten sollte nicht verzögert sein und der Fokus synchron.

![image](https://github.com/public-ui/kolibri/assets/149500785/827318df-9fcc-4d92-bd02-ca7afbbb09a1)

**Comment by deleonio** [comment]
Wir schauen uns den Algorithmus hinter den Tabs an.
