### ISSUE TITLE
💡 Hinweis: textarea: Readonly Feld zeigt eine Fehlermeldung

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5753]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**
Wir das Textfeld fokussiert und der Fokus wieder aufgehoben (sowohl Mauls als auch Tastatur) wird eine Fehlermeldung angezeigt, was bei einem Readonly-Feld nicht sinnvoll ist.

Komponente: textarea readonly (https://public-ui.github.io/v2/sample-react/#/textarea/readonly)
Version: v2.0.0-rc.13

**Comment by deleonio** [comment]
- [ ] readonly Beispiele ohne Fehler verwenden - Alles Samples anschauen.

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich für v1** -------------

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich für v2** -------------
