### ISSUE TITLE
🐞 Bug: Submit Button löst bei Klick einen Rerender aus (v2)

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5762]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn ich in der Kombination `react-hook-form` und `<KolButton _type="submit" .../>` auf den Button klicke, dann wird ein kompletter Rerender durchgeführt.

## Reproduktion

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-lkr2bf?file=src%2FApp.tsx

Schritte zum Reproduzieren des Verhaltens:
- Klicke auf den Submit-Button
- in der Console ist der Output vom `onSubmit`-Callback zu sehen, jedoch wird die Seite zusätzlich neu gerendert

## Erwartetes Verhalten
Ein Klick auf einen Submit-Button löst keinen Rerender der Seite aus.

**Comment by deleonio** [comment]
@sdvg wir haben letztens event.stopProp... ausgebaut. Lass uns dazu mal sprechen.

**Comment by deleonio** [comment]
@Chrisdo82 

Damit das FormHandling in KoliBri funktioniert, bitte die KolForm verwenden.

Stackblitz: https://stackblitz.com/edit/vitejs-vite-lkr2bf?file=src%2FForm.tsx

```tsx
    <FormProvider<TFieldValues> {...methods}>
      {/* eslint-disable-next-line @typescript-eslint/no-misused-promises */}
      <KolForm
        _on={{
          onSubmit: methods.handleSubmit(onSubmit) as () => void,
        }}
        className="relative flex h-full flex-col"
      >
        <FormContent<TFieldValues>
          renderRequiredInfoText={renderRequiredInfoText}
        >
          {children}
        </FormContent>
      </KolForm>
    </FormProvider>
```
