### ISSUE TITLE
🛹 Netlifly: Deployments auf Netlifly manuell triggern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5779]
https://dev.to/thiernope/trigger-netlify-deploys-using-github-workflow-cicd-lcm

**Comment by sdvg** [comment]
Wie heute besprochen: Wir können zunächst die Möglichkeit antesten, Deployments weiterhin automatisch zu triggern, den Build aber zu GitHub Actions zu verlagern. Netlify wäre dann nur noch für das reine Hosting der Artefakte zuständig.

Wenn das gut funktioniert, könnten wir auch einen automatisierten Kommentar im PR/Ticket mit der Deployment-URL (analog der bisherigen Netlify-Action) einrichten.

Siehe auch die hier beschriebene erste Variante: https://github.com/public-ui/kolibri/issues/5570#issuecomment-1810584815

**Comment by sdvg** [comment]
@deleonio 

Die Action im PR ist jetzt wie folgt eingerichtet:
Immer wenn ein PR erstellt wird bzw. sich ändert, wird auf GitHub gebaut und der dist-Ordner der Sample-App auf Netlify deployed. Anschließend werden Deployment-URL und Logs in das PR kommentiert. Falls schon ein Kommentar existiert wird dieser aktualisiert. Beispiel: https://github.com/sdvg/kolibri/pull/3

Damit das funktioniert, ist es notwendig, dass du zwei [Variablen auf GitHub definierst](https://github.com/public-ui/kolibri/settings/secrets/actions):

* `NETLIFY_SITE_ID` als Variable: Das müsste bei uns `kolibri-public-ui` sein.
* `NETLIFY_AUTH_TOKEN` als Secret. Hierfür müssen wir ~~eine neue "private integration"~~ eine neuen [Access Token](https://docs.netlify.com/cli/get-started/#obtain-a-token-in-the-netlify-ui) auf Netlify anlegen.
