### ISSUE TITLE
🛹 Feature: Lazy loaded web components mit vite

### ISSUE THREAD

**Issue by mello-r** [public-ui/kolibri#5784]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Zur Zeit testen wir die [Playwright Component Tests](https://playwright.dev/docs/test-components). Leider funktionieren diese nicht so gut mit KoliBri. Die Playwright Component Tests verwenden intern Vite zum Bundling. Stencil lazy loaded Components funktionieren nicht out of the box mit Vite, wie im [Issue](https://github.com/ionic-team/stencil/issues/2827) beschrieben. 

## Beschreiben Sie die gewünschte Lösung
Damit Stencils lazy loaded Components mit Vite funktionieren, wurde ein extra Config Flag `enableImportInjection` hinzugefügt. Siehe dazu in die [Dokumentation] (https://stenciljs.com/docs/v4.3/config-extras#enableimportinjection). Es wäre hilfreich, dieses Flag in der Build Config hinzuzufügen. Dies könnte allerdings die Bundle-Size etwas erhöhen.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Ich habe versucht die `dist-custom-elements` Ausgabe zu verwenden, aber da dort `customElementsExportBehavior` noch auf `default` und nicht `bundle` steht, muss ich jede einzelne KoliBri Komponente einzeln importieren. Außerdem gibt es Probleme mit dem Styling. Die Basisstyles sind dann zwar vorhanden, aber das registrierte Theme wird dann nicht verwendet.

## Zusätzlicher Kontext
Ich habe das Flag schon lokal ausprobiert und das Package in das Repository mit den Playwright Component Tests verlinkt. Damit funktioniert die Definition über `import { defineCustomElements } from '@public-ui/components/dist/loader'` und die Styles sind auch vorhanden. Anscheinend kann man jetzt auch in der `index.html` das `<script type="module" src="/node_modules/@public-ui/components/dist/kolibri/kolibri.esm.js"></script>` weglassen. Ich habe das aber nur flüchtig getestet.

**Comment by deleonio** [comment]
@mello-r hierfür brauchen wir bitte ein Reproduktionsbeispiel.

**Comment by mello-r** [comment]
Hier ein Repo mit Playwright Component Tests https://github.com/mello-r/kolibri-playwright-component-tests. 

Um die Tests zu starten, einfach `pnpm test` ausführen. Es wird die Playwright UI gestartet und dort sind zwei Beispiel Tests hinterlegt. Ein Test mit KoliBri und ein Test ohne KoliBri. Während des Tests mit KoliBri kann man in der Playwright UI Console diesen Fehler `TypeError: Failed to fetch dynamically imported module: http://localhost:3100/assets/kol-badge.entry.js undefined` sehen.

Ich hab ein neues Repo mit `pnpm create kolibri@latest kolibri-playwright-component-test` erstellt. Leider bekommt man dort selbst mit den Anpassungen aus https://github.com/public-ui/kolibri/issues/5773, den Fehler `TypeError: can't redefine non-configurable property "I18n"` bei dem Registrieren des Themes. Also hab ich erstmal die Registrierung dort optional gemacht.

Das Hinzufügen von `enableImportInjection` würde dieses Problem wahrscheinlich auch lösen, da man nicht in der `index.html` mehr `<script type="module" src="/node_modules/@public-ui/components/dist/kolibri/kolibri.esm.js"></script>` hinzufügen müsste und wieder direkt `import { defineCustomElements } from "@public-ui/components/dist/loader"` in der `main.tsx`  nutzen könnte.

**Comment by deleonio** [comment]
Vielen Dank @mello-r,

sehr interessant Beitrag. Es funktioniert mit der empfohlenen Einstellung. Wir prüfen aktuell, welche Auswirkungen die Extras auf die KoliBri-Pakete und die Nachnutzung haben.
