### ISSUE TITLE
💡 Bug: Backspace-Verhalten von InputDate

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5800]
in den KoliBri-Versionen bis einschließlich 1.7.7 ein unerwartetes Verhalten von KolInputDate bei Bedienung mit der Tastatur aufgefallen.

Vorgehen:
1. Zahlen in KolInputDate eingeben.
2. Backspace betätigen.

Erwartetes Verhalten:
Bei Betätigung von Backspace wird das jeweils zuletzt eingegebene Zeichen gelöscht.

Tatsächliches Verhalten:
Bei Betätigung von Backspace wird das Eingabefeld komplett geleert.

```html
<kol-input-date></kol-input-date>
<input type="date">
```

Beobachtung: Bei KoliBri wird der Wert ohne Jahr insgesamt invalide und wird deshalb komplett zurückgesetzt. Bei nativen Input können die einzelnen Segmente des Datums einzeln gelöscht und bearbeitet werden.

**Comment by deleonio** [comment]
- [x] Lösungsidee ist, die Eingabe immer erst beim Verlassen des Feldes auszuwerten.
- [ ] Als Erstes erstmal eine Analyse, was vorliegt und was ggf. eine gute Lösung wäre.

**Comment by laske185** [comment]
Das Setzen des neuen Wertes an die Komponente soll erst beim onBlur geschehen, damit während des Tippens diese Aktion nicht den Wert leert.
