### ISSUE TITLE
🐞 Bug: 9.1.4.1 tabs: Aktiver Tab ist nur durch Farbe unterscheidbar

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5801]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Je nach Theme (hier default) ist der gewählte/aktive Tab nur durch die blaue Farbe con den inaktiven grauen Tabs zu unterscheiden. Dies ist für farbfehlsichtige Nutzer ein Problem und ist auch bei einer Kontrastanpassung nicht mehr sichtbar.

## Reproduktion
Komponente: tabs basic (https://public-ui.github.io/v2/sample-react/#/tabs/basic)
Version: v2.0.0

## Erwartetes Verhalten
Der aktive Tab sollte unabhängig von der Farbe erkennbar sein, anhand vom Styling.

**Comment by deleonio** [comment]
- [ ] bei nicht aktiven Tabs keine Unterstreichung
- [ ] für BMF
- [ ] für Default

![image](https://github.com/public-ui/kolibri/assets/6279703/c0f82e7b-538b-4a04-9828-7b8e9a8cba74)

**Comment by anicyne** [comment]
Hi @laske185, Ich habe den Fix für die Tabs umgesetzt und gepusht.

**Comment by laske185** [comment]
Ok, sehr gut.

**Comment by fohi17** [comment]
------------- A11y-Test Rückmeldung -------------
Sieht in der normalen Ansicht jetzt gut aus. Dadurch, dass die Unterstreichung transparent gemacht wurde ist der aktive TAB bei der Kontrastanpassung aber trotzdem nicht sichtbar.
![image](https://github.com/public-ui/kolibri/assets/149500785/d807e7c2-14a4-4d5d-a135-daefe88c2555)

**Comment by sdvg** [comment]
Danke für die Rückmeldung! Das passen wir dann noch mal an und verwenden statt dem transparenten Rahmen z.B. einen einfachen Innenabstand, um den Rahmen auszugleichen.

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich für v1** -------------

**Comment by sdvg** [comment]
@fohi17 Kann jetzt auch für v2 getestet werden: https://github.com/public-ui/kolibri/pull/6080#issuecomment-1945663695

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich für v2** -------------
