### ISSUE TITLE
🐞 Bug: 3.2.1 Textarea: Felder werden bei Fokussierung größer

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5803]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Die Eingabefelder haben zu Beginn eine feste Größe. Wenn Sie den Tastaturfokus erhalten, passt sich die Größe an den Textinhalt an. Beim Verlassen der Textfelder bleibt die Größe angepasst und wird nicht wieder klein. Das Verhalten ist unerwartet.

## Reproduktion

Komponente: https://public-ui.github.io/v2/sample-react/#/textarea/adjust-height
Version: v2.0.0

![image](https://github.com/public-ui/kolibri/assets/6279703/5bfeb2b5-aa49-4a5d-8745-1b9c0f2ac315)

Schritte zum Reproduzieren des Verhaltens:
- Navigieren mit der TAB-Taste

## Erwartetes Verhalten
Die Textfelder sollten initial die passende Größe zum enthaltenen Text haben. (Andernfalls, wenn das Vergrößern gewollt ist, sollte beim Verlassen auch wieder verkleinert werden.)

**Comment by deleonio** [comment]
- [ ] Beim Setzen des Values der Komponente, muss die Höhe entsprechend dem Text angepasst werden.

**Comment by sdvg** [comment]
Ticket wird von @cyrinermd bearbeitet.

**Comment by sdvg** [comment]
Reopen für `v1`.

**Comment by deleonio** [comment]
@cyrinermd Können wir das auch für v1 bekommen. Vielen Dank.

**Comment by anicyne** [comment]
@deleonio  Die v1 Änderungen sind im Issue  #5959

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich**-------------
