### ISSUE TITLE
🐞 Bug: nav: Default Theme muss valide gestyled werden.

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5810]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Die nav-Komponente hat noch mehrere Baustellen. Zunächst muss einmal das default Theme valide gestyled werden. Es treten bspw. folgende Probleme auf:
- Es gibt keine visuelle Unterscheidung zwischen normalen, aktiven und ausklappbaren Einträgen.
- Navigation mit reinem Text belegen sollte nicht möglich sein, wie es im horizontal Beispiel gemacht ist.
- Active: Ist Evtl. hinfällig. Außerdem sind alle Einträge Buttons bis auf einen Link. Außerdem ist die Nav-Region mit "..." beschriftet. Daher ist das Beispiel nicht so gut.
- Nice to have: Wenn ein Ausklappbarer Eintrag nicht selbst anklickbar ist, sollte der ganze Eintrag zum ausklappen verwendbar sein, wie es in der Kolibri-Dokus Navigation gemacht ist.

## Reproduktion
Komponente: nav (https://public-ui.github.io/v2/sample-react/#/nav/basic)
Version: v2.0.0

**Comment by deleonio** [comment]
- [x] Vollständig valides Nav-Styling muss für Default-Theme umgesetzt werden.
- [x] Es gibt keine Text-Menüpunkte mehr
- [x] Aufklappmenüs ohne eigene Seite - sind ein Schalter aus Label und Aufklapp-Icon
- [x] Hat der Menüpunkt eine eigene Seite sind Link und Expand-Button getrennt.
- [x] Wenn man sich auf einem Menüpunkt befindet (aktiv), dann ist das Untermenü, falls vorhanden, aufgeklappt.

![image](https://github.com/public-ui/kolibri/assets/6279703/4559d720-5d00-4193-8730-8ad9686427b0)
