### ISSUE TITLE
🐞 Bug: input-field: Mauszeiger zeigt Error auf klickbarer Fläche

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5814]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Beim Hochladen einer Datei kann das ganze Element, nicht nur der "Datei auswählen"-Button angeklickt werden, um den Explorer zu öffnen. Beim Überfahren des Bereichs um den Button wird der Mauszeiger jedoch zum Error (nicht verfügbar Zeichen), was irreführend ist.

## Reproduktion

Komponente: input-file basic (https://public-ui.github.io/v2/sample-react/#/input-file/basic?theme=default)
Version: v2.0.0

## Erwartetes Verhalten
Über einem klickbaren Bereich sollte der Mauszeiger nicht als nicht verfügbar angezeigt werden.

**Comment by deleonio** [comment]
- [ ] Der Sperren-Mauszeige darf bei allen Inputs, Select und Textarea nur bei `disabled` gesetzt werden. Bitte nicht nur für InputFile betrachten.
- [ ] Zuerst im Basis-Style prüfen, ob der "Fehler" dort verursacht wird.
- [ ] Für alle Themes.

**Comment by laske185** [comment]
`input:read-only` greift beim `input` vom typ `file` immer. Daher griff die CSS-Regel.

Siehe: https://developer.mozilla.org/en-US/docs/Web/CSS/:read-only
