### ISSUE TITLE
🛹 Feature: Default-Theme automatisch als Template für Create-App kopieren (v2)

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5840]
Das Default-Theme ist das optimale Anfangsbeispiel, um ein Theme zu erstellen. Daher sollten wir dieses einfach automatisch beim Bauen für die Create-App wiederverwenden. Alle, die sich ein eigenes Theme erstellen wollen, haben dann eine gute Ausgangsbasis.

- [ ] Build von Create-App muss `src` vom Default-Theme kopieren
- [ ] Ggf. Anpassungen am Code, wegen der Template-Engine

**Comment by deleonio** [comment]
Obsolete.

**Comment by sdvg** [comment]
@deleonio Ist das Ticket mit der Deprecation der Create Apps noch relevant?
Siehe #6129
