### ISSUE TITLE
🐞 Bug: 9.1.1.1a link target: Hinweis auf neuen Tab wird bei Icon nicht ausgegeben (v1)

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5841]
See Issue-Description https://github.com/public-ui/kolibri/issues/5670 and PR https://github.com/public-ui/kolibri/pull/5815.

**Comment by sdvg** [comment]
PR (Verlinken schlägt fehlt): https://github.com/public-ui/kolibri/pull/5874
