### ISSUE TITLE
🛹 Feature: Pagination / Anzahl in Tabelle oben oder unten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5845]
Abgeleitet von dem Ticket: https://github.com/public-ui/kolibri/issues/1839

Folgende Verbesserungen:

- [ ] Neues Prop (`_paginationPosition`) für die Sichtbarkeit der Pagination - default: `top`
  - [ ] Werte: `top`, `bottom`, `both`
- [ ] Im DOM wird die Pagination immer dort gerendert, wo sie auch angezeigt wird (aktuell ist dieser Prüfschritt bei `bottom` nicht erfüllt)

**Comment by sdvg** [comment]
Ticket wird von @cyrinermd bearbeitet.
