### ISSUE TITLE
🛹 Feature: Selektion in `KolTableStateless`

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#5859]
Die im Ticket #5858 erstellte `KolTableStateless` soll um eine Selektion von Reihen erweitert werden.

## Akzeptanzkriterien

- [x] neues Attribut: `_selection`
  - Typ: 
```ts
 {
  label: (row: T) => string,
  keyPropertyName: string, // default = `key`
  selectedKeys?: string[]
}
```
- [x] Neue Spalte mit Checkboxen
  - ohne Überschrift (wird noch im BITV-Team besprochen)
  - Die `KolInputCheckbox` nutzen
  - Das Label der Checkbox wird durch die Labelfunktion im selection-Objekt erzeugt
- [x] Callback-Funktion `onSelectionChanged` und Event `onSelectionChange` gibt alle aktuell selektierte Rows (komplette Objekte) zurück
  - in weiteren Iterationen könnte ein `onRowSelected` oder `onRowUnselected` hinzukommen

**Comment by sdvg** [comment]
In der Spec (oben) haben wir geschrieben: 

> Callback-Funktion onSelectionChanged und Event onSelectionChange gibt alle aktuell selektierte Rows (komplette Objekte) zurück

Ich würde das von "komplette Objekte" erst einmal zu "selectedKeys" ändern. Das scheint mir für die Stateless-Tabelle sinnvoller, weil wir hier auch nur selectedKeys als Prop rein geben und der State von außen gemanaged wird. Bei der Stateful-Tabelle halte ich "komplette Objekte" wiederum für sinnvoll.
