### ISSUE TITLE
📖 Help: Theme patchen

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#5869]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

Ich verwende die aktuelle Version 2.0.3 in Kombination mit statischen HTML-Seiten. Da ich eine sehr breite Tabelle habe, sieht diese wegen der word-wrap Einstellung sehr unschön (zusammen gequetscht) aus. Daher möchte ich nur diese eine Einstellung anpassen. Leider gelingt mir das nicht mit dem als Hilfe angezeigten Code.

    [Theming] The theme process is locked. This means that the theme "itzbund" should not be patched.

	import { register } from 'adopted-style-sheets';
	import { defineCustomElements } from '...';
	import { THEME } from '...';

	register(THEME, defineCustomElements)
	.then(() => {
		// run your app or website
	})
	.catch(console.warn);

Fehlermeldung:
Uncaught TypeError: Failed to resolve module specifier "adopted-style-sheets". Relative references must start with either "/", "./", or "../".

Mir ist es dann gelungen, diese Meldung zu beheben, indem ich statt "adopted-style-sheets" -> https://cdn.jsdelivr.net/npm/adopted-style-sheets@1.1.3/+esm eingebunden habe. Damit habe ich dann aber wieder den Fehler "theme process is locked".

Mein aktueller Header:

    import { register } from 'https://cdn.jsdelivr.net/npm/adopted-style-sheets@1.1.3/+esm';
    import { KoliBriDevHelper } from 'https://unpkg.com/@public-ui/components/dist/esm/index.js';
    import { defineCustomElements } from 'https://unpkg.com/@public-ui/components/dist/loader/index.js';
    import { ITZBund } from 'https://unpkg.com/@public-ui/themes/dist/index.mjs';
    register(ITZBund, defineCustomElements)
        .then(() => {
            KoliBriDevHelper.patchThemeTag("itzbund", "GLOBAL", "th > div {word-break: normal}");
        })
        .catch(console.warn);`

**Comment by deleonio** [comment]
Hi @webbird,

bitte verwende dazu das `_minWidth`-Property bei der Spaltendefinition: https://public-ui.github.io/docs/components/table

**`word-wrap` abschalten, ist nicht barrierefrei!**

**Comment by webbird** [comment]
Danke! Das löst einerseits das konkrete "Problem" mit der Tabelle, andererseits aber nicht das Problem mit dem Patchen des Themes. Vermutlich ist das in 99% der Fälle auch nicht nötig, man muss nur umdenken. Daher danke für den Stups.

**Comment by schwoortz** [comment]
Warum sollte der Browser-Default (word-wrap: normal;) per se nicht barrierefrei sein? Irgendwelche Quellen?
Insbesondere in Tabellenzellen reicht der Umbruch bei Leerzeichen oder Bindestrichen völlig aus.

_(Zumal das im Theme verwendete "word-wrap: break-word;" deprecated ist:
https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/word-break )_
