### ISSUE TITLE
🐞 Bug: (?) render-Methode bei Tabelle zeigt HTML als Quelltext an

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#5870]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Ich verwende zum Rendern von Zellen, in denen als Wert "true" oder "false" stehen würde, eine eigene Render-Methode. Das funktioniert auch so weit, nur wird das HTML, welches von der Methode zurückgeliefert wird, als Quelltext ausgegeben. Ursache dürfte dieser Codeabschnitt sein:

    if (typeof html === 'string') {
        el.textContent = html;
    }

Hier wird ja explizit der textContent belegt, daher auch die Anzeige als Quellcode. Wenn ich aber nun statt eines Strings ein HTML-Objekt zurückliefere, wird gar nichts mehr angezeigt. Für diesen Fall existiert in der cellRender-Methode aber auch keine Fallbehandlung.

https://github.com/public-ui/kolibri/blob/2afc84f058ddd3b6acb4e9d789f4bb3c9e3c62e6/packages/components/src/components/table/component.tsx#L573

Vielleicht "soll das so", dann könnte ich aber kein "custom HTML" in einer Tabellenzeile verwenden.

Ich verwende Version 2.0.0 lokal installiert in Kombination mit statischen HTML-Seiten.

**Comment by deleonio** [comment]
@sdvg wir sollten hier bitte in der Sample-App alle 3 Varianten zeigen.

- [ ] `innerText`, `textContent`
- [ ] `innerHTML`
- [ ] `React.render`

**Comment by deleonio** [comment]
@webbird bitte anstatt `textContent`, `innerHTML` verwenden.

```js
if (typeof html === 'string') {
    el.innerHTML = html;
}
```

**Comment by webbird** [comment]
Der Code kommt aber aus der table-Komponente, siehe Link im Eingangspost. ;)

https://github.com/public-ui/kolibri/blob/2afc84f058ddd3b6acb4e9d789f4bb3c9e3c62e6/packages/components/src/components/table/component.tsx#L592

**Comment by deleonio** [comment]
Ok, ich dachte das kommt aus Deiner App. Ja in unserem Code sollte das nicht mehr html heißen, sondern text. Das wurde aus Sicherheitsgründen refactored.

**Comment by webbird** [comment]
Wenn ich keine React-App habe sondern nur statisches HTML, bleibt mir doch nur der render-Callback, oder? Ansonsten müßte ich nachträglich per JavaScript alle Zeilen durchgehen und meine Änderung einfügen. Aktuell möchte ich die Einträge in der ersten Spalte mit einem Link versehen, über den man sich alle Details (= die aktuelle Zeile) in einem Modal nochmal anzeigen lassen kann.

**Comment by deleonio** [comment]
Vielleicht können wir dieses Thema am Donnerstag in der CoP behandeln? @sdvg lass uns bitte am Donnerstag im Daily mal darüber sprechen. Ein kleines Sample sollte recht schnell umsetzbar sein.

**Comment by sdvg** [comment]
Im Pull Requests sind jetzt alle Beispiele einmal in React und einmal direkt über die DOM-APIs umgesetzt.

Besonders relevant ist vermutlich dieses Beispiel: https://github.com/public-ui/kolibri/pull/5907/files#diff-29dfd41cd53fe025863d43c09642ab780ffd2bf1821d985a1e46234a9965b6acR54

**Comment by deleonio** [comment]
@webbird Wir werden die Render-Optionen heute im Public Call CoP 14 Uhr vorstellen. -> https://github.com/public-ui/kolibri/discussions/516

**Comment by webbird** [comment]
Super, vielen Dank! Ich habe es schon erfolgreich eingebaut. Um einen ehemals bekannten und beliebten Tennisspieler zu zitieren: "Das war ja einfach!"
