### ISSUE TITLE
💡 Hinweis: Zweck des Schalters nur aus visuellem Kontext 

### ISSUE THREAD

**Issue by gkollotzek** [public-ui/kolibri#5872]
In der Handreichung des bfit Bund zur barrierefreien Gestaltung von User Interface-Elementen steht folgender Absatz: 

<img width="654" alt="image" src="https://github.com/public-ui/kolibri/assets/138562317/373b0fa4-d0eb-4d95-9c22-9788e83315bf">

https://handreichungen.bfit-bund.de/barrierefreie-uie/0.4/schalter.html#programmierungschnittstellen (Nr. 503)

Dadurch stellt sich die Frage, ob bspw. beim Alert das aria-label erweitert werden soll bzw. mit aria-describedby ein Verweis zum betroffenen Element hergestellt werden soll. Oder es aus dem (nicht-visuellen) Kontext klar genug wird. 
<img width="559" alt="image" src="https://github.com/public-ui/kolibri/assets/138562317/fce5b841-619f-417a-ace8-394af56d4db0">

Ein weiterer Fall wären Filter-Badges die mit "x" geschlossen werden können. Hier wird derzeit für das x ein aria-label mit "Filter entfernen" genutzt.
![image](https://github.com/public-ui/kolibri/assets/138562317/7cbbbc67-6cc7-41a8-bfa3-c0f185bd176a)

In Rücksprache mit Christian B. hier das Ticket um zu dem Thema zu diskutieren :)

**Comment by deleonio** [comment]
@cbraehmig - bitte bewerten lassen.

**Comment by AntnSaj** [comment]
Das Element, dass geschlossen werden soll braucht einen sprechenden Namen bzw. eine sprechende Beschreibung Bsp. Pup-Up. Dieser Name/Beschreibung muss beim betreten des Elementes ausgegeben werden. Dann kann im schließen Schalter darauf verwiesen werden Bsp. Pop-Up schließen oder Schließen Pop-Up. 
Die Überschrift vom Pop-Up im Schließen Button zu integrieren ist unserer Meinung nach nicht Sinnvoll, weil die Audioausgabe zu lang sein könnte.
Bei den Badges von KoliBri ist es in der 2.0.3 bereits so umgesetzt, dass beim schließen Button auch das zu schließende Element vorgelesen wird.

**Comment by cbraehmig** [comment]
https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/

Entscheidung:

Für das Element "alert" wird der Schließen-Schalter mit der Bezeichnung "Schließe Meldung" versehen.

Allgemeiner Hinweis für Meldungen:

Aufbau: Aktion + Element z.B. "lösche Datei", "öffne Bericht"

**Comment by laske185** [comment]
TODO:

- [ ] Der Button bekommt das Label "Schließen"
- [ ] Button bekommt als `_ariaDescription` den Wert "von ${Titel des Alerts}" gesetzt
