### ISSUE TITLE
🐞 Bug: Link mit _hideLabel: Label wird nicht vorgelesen (VoiceOver)

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#5873]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Wird ein Link ohne sichtbares Label (_hideLabel, mit Tooltip) mit VoiceOver fokussiert, so wird nur der Link `href` beschrieben, aber nicht der das eigentlich definierte Label vorgelesen.

## Reproduktion

Schritte zum Reproduzieren des Verhaltens:

1) Beispiel öffnen: https://public-ui.github.io/v2/sample-react/#/link/target
2) VoiceOver starten
3) Zum vierten Link tabben

## Erwartetes Verhalten

Das definierte Label wird vorgelesen.

## Screenshots

![image](https://github.com/public-ui/kolibri/assets/971072/8b7ef817-af6d-4385-93fb-d01385705c62)

## Desktop
- Betriebssystem: macOS
- Browser Chrome

**Comment by deleonio** [comment]
Retest:
- v1: -
- v2: https://65b1394ca64cb624606e2cfb--kolibri-public-ui.netlify.app/#/link/target

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich**-------------
