### ISSUE TITLE
🐞 Bug: Checkbox "click" Event wird zweimal getriggert

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#5881]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Ich habe eine **kol-input-checkbox** mit Hilfe von **addEventListener** mit einer Behandlung des "click"-Events verknüpft. Beim Anklicken wird das Event zweimal getriggert. _e.stopPropagation()_ hat nicht geholfen.

Im HTML-Quellcode der Seite sieht die Checkbox so aus:
`<kol-input-checkbox name="Orange" id="Orange" data-attr="advice" data-value="Orange" _label="Orange" _alert="" class="hydrated" _checked="" style="" _touched=""></kol-input-checkbox>`

Die Checkbox wird zur Laufzeit erzeugt.

    function createKolCheckbox(id, attr, value) {
      let checkbox = document.createElement("kol-input-checkbox");
      checkbox.setAttribute("name", id);
      checkbox.setAttribute("id", id);
      checkbox.setAttribute("data-attr", attr);
      checkbox.setAttribute("data-value", value);
      checkbox.setAttribute("_label", value);
      checkbox.addEventListener("click", toggleCheckbox);
      return checkbox;
    }

    function toggleCheckbox(e) {
      e.stopPropagation();
      console.log("click event",e.target);
    }

## Reproduktion

Nutzen Sie die [StackBlitz (v1)](https://stackblitz.com/edit/vitejs-vite-dcg6xo) oder [StackBlitz (v2)](https://stackblitz.com/edit/vitejs-vite-kkfhk5), um ein reproduzierbares Beispiel zu erstellen.

https://stackblitz.com/edit/vitejs-vite-muunxb?file=src%2FApp.tsx

Da wird der alert() sogar 4x ausgegeben.

## Erwartetes Verhalten
Ich hätte erwartet, dass stopPropagation() unterbindet, dass das Event mehrfach verarbeitet wird. Ich habe ja das Event auch nicht dem shadowRoot hinzugefügt. Womöglich ist das auch das Problem. (?)

Mit _on habe ich es nicht geschafft, ein onChange-Event zu verknüpfen. Es wurde nicht getriggert. Der Code war (Ergänzung zu oben):

  checkbox.setAttribute("_on", "{onChange:toggleCheckbox}");

**Comment by webbird** [comment]
Nachtrag: Ich verwende jetzt als Workaround "normale" Checkboxen, hier funktioniert das Klick-Event einwandfrei.

**Comment by deleonio** [comment]
Hallo @webbird,

leider ist Ihr Reproduktionsbeispiel nicht so lauffähig, da Sie React mit reiner HTML-Schreibweise mischen. Wir haben diese geforkt und auf eine rein React-spezifische Implementierung korrigiert: https://stackblitz.com/edit/vitejs-vite-etfdkv?file=src%2FApp.tsx

Beobachtungen:
- Listener wird 2. Mal hinzugefügt.
- onChange-Callback funktioniert korrekt
- in der KolInputCheckbox wurde die onChange von Checkbox und von Input (allgemein) aufgerufen, hier soll nur Checkbox aufgerufen werden - PR

**Comment by deleonio** [comment]
v1

**Comment by webbird** [comment]
Sorry, aber ich verwende statisches HTML, kein React. Daher habe ich auch im Beispiel statisches HTML verwendet.
