### ISSUE TITLE
Dialog hat keine Hintergrundfarbe

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#5885]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Ich habe einen _kol-modal_ auf Basis des Beispiels in der Dokumentation eingebaut. (Statische HTML-Seiten.) Dieser hat zwar eine Rahmen-, aber keine Hintergrundfarbe. Dadurch sieht man durch das Overlay hindurch die dahinterliegende Seite und kann den Text nur schwer lesen. Im Modal befindet sich keine Kolibri-Komponente, sondern nur eine "unordered list". Somit wäre das Verwenden z.B. einer kol-card ein Workaround. 

Ich verwende derzeit Version 2.0.0, lokal installiert.

## Erwartetes Verhalten
Es sollte eine zum Theme passende Hintergrundfarbe gesetzt sein. Sofern das nicht gewünscht ist, wäre eine entsprechende Option hilfreich.

**Comment by deleonio** [comment]
Es ist aktuell so angelegt, dass der Inhalt frei wählbar ist. Das Modal implementiert die Anforderungen an ein Modal, ohne festzulegen, was es beinhaltet. Zum Beispiel eine Card.

https://public-ui.github.io/v2/sample-react/#/modal/basic

**Comment by webbird** [comment]
Ist okay. Vielleicht in der Doku etwas genauer hervorheben.

**Comment by laske185** [comment]
Die Komponente wird im Issue https://github.com/public-ui/kolibri/issues/5844 erweitert und entsprechend auch die Dokumentation angepasst.
