### ISSUE TITLE
🐞 Bug: ToasterService - render callback wird 2x aufgerufen

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5887]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn ein render callback an `toaster.enque` übergeben wird, dann wird dieser 2x aufgerufen. In React 18 führt dies dazu, dass folgende Meldung in der Console angezeigt wird: `Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.`

## Reproduktion

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-nba89w?file=src%2FApp.tsx

Schritte zum Reproduzieren des Verhaltens:
- Rufe den StackBlitz Link auf
- Öffne die Browser Console
- Klicke auf den Button "Toast anzeigen"
- Es wird 2x die Nachricht `called render` in der Console angezeigt, zudem erscheint die oben beschriebene Warnung

## Erwartetes Verhalten
Render wird nur 1x aufgerufen.

**Comment by deleonio** [comment]
Ist Version 1 relevant?

**Comment by Chrisdo82** [comment]
Nein
