### ISSUE TITLE
🐞 Bug: Schließen eines Alerts funktioniert nicht (v2.0.0)

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#5890]
> **Note**
> - [ ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Ich arbeite mit statischem HTML und habe einem Alert mit _has-closer="true" die "Schließen"-Option mitgegeben. Klick auf das X bewirkt aber nichts. Das ist auch bei den Beispielen so: https://public-ui.github.io/docs/components/alert

## Erwartetes Verhalten
Nach meinem Verständnis sollte die Funktion zum Schließen des Alerts bereits vorhanden sein.

**Comment by deleonio** [comment]
Das Property `_has-closer="true` besagt lediglich, dass das X zum Schließen dargestellt wird. Auf dem Callback-Schließen muss von Außen ("Dir") mit JavaScript reagiert werden.
