### ISSUE TITLE
🛹 Feature: Startseite/Unterseite für basic breadcrumb sample

### ISSUE THREAD

**Issue by Schollkolade** [public-ui/kolibri#5899]
# Featureanfrage

Im Sample React unter basic breadcrumb gibt es keine Unterseiten/Startseiten. Wenn man auf die Links klickt, kommt man auf leere Seiten. (https://public-ui.github.io/v2/sample-react/#/breadcrumb/basic)

## Beschreiben Sie die gewünschte Lösung
Eine Beispiel Unterseite/Startseite mit Inhalt erstellen und verlinken.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Damit leben und es nicht tun. 

## Zusätzlicher Kontext
-

**Comment by sdvg** [comment]
Wir könnten hier eine allgemeine Beispiel-Seite erstellen, die für alle Samples mit Links verwendet wird (z.B. auch Link, Link-Button, etc.).
Die Seite würde dann kurz mitteilen, dass man einem Test-Link gefolgt ist und einen Link zurück zur vorherigen Seite anbieten.

Das löst zwei Probleme: Beispiel-Links wirken nicht mehr "kaputt"; Man kommt schnell zurück, wenn man einen Link versehentlich betätigt hat.

**Comment by deleonio** [comment]
`<button onclick="history.back()">Go Back</button>` nutzen

**Comment by anicyne** [comment]
- KolButton verwenden 
- Alle Links in allen Beispielen anpassen

**Comment by sdvg** [comment]
Ticket wieder geöffnet für `v1`
