### ISSUE TITLE
🐞 Bug: 11.7 input-checkbox basic: Icons verschieben sich bei der Anpassung der Schriftgröße

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#5909]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Wenn man die Schriftgröße im Browser größer (oder kleiner) stellt (gemäß BITV 11.7), verschiebt sich die Position der Icons (Kreuz und Häkchen) in den Checkboxen. 

## Reproduktion

Komponente: input-checkbox basic in firefox, input-checkbox switch in chrome
Version: v2.0.3

Schritte zum Reproduzieren des Verhaltens:

**Schriftgröße des Browsers ändern**

Im Chrome:
Einstellungen -> Darstellung -> Schriftgröße
Im Firefox:
Einstellungen -> Allgemein -> Schriftarten

## Erwartetes Verhalten
Die Häkchen und Kreuze sollten immer innerhalb des Checkboxrahmens angezeigt werden.

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/149500785/13745aac-93ee-417b-b0f0-a2e0ec5a6e73)

**Comment by deleonio** [comment]
Ansatz: Das Styling mittels `rem` umsetzen und schauen ob es passt.

**Comment by deleonio** [comment]
Dieses Ticket sollte erst nach folgendem Ticket angegangen werden: https://github.com/public-ui/kolibri/issues/5517

**Comment by chrisalat** [comment]
Kann nicht reproduziert werden. Weder in `v1` , noch `v2`:

`v2`

![Image](https://github.com/public-ui/kolibri/assets/3756995/930eef37-7edf-4285-9189-43e895090095)

`v1`

![Image](https://github.com/public-ui/kolibri/assets/3756995/6185d506-064d-4550-89ff-974148ad2f1d)

**Comment by sdvg** [comment]
Firefox passt ebenfalls, haben wir gemeinsam verifiziert.

**Comment by AntnSaj** [comment]
Komponente wurde getestet. Fehler ist Behoben
