### ISSUE TITLE
🐞 Bug: Input checkbox switch mit forced colors schlecht sichtbar

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#5910]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Checkboxen vom Typ `switch` sind im forced-colors-mode schlecht sichtbar.

## Erwartetes Verhalten

Die Checkboxen sollten einen zusätzlichen (transparenten) Rahmen haben.

## Screenshots
<img width="1336" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/da5c088e-389c-4710-a428-cd53b7d52d8d">

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: macOS
- Browser Chrome

## Zusätzlicher Kontext

via https://github.com/public-ui/kolibri/issues/5626#issuecomment-1898233197

**Comment by laske185** [comment]
- [x] Transparenten border setzen.
