### ISSUE TITLE
Neues Sample Table: Seitliches Scrollen - Viele Spalten und geringe Tabellenbreite

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5912]
Um das Beispiel umzusetzen, muss man viele Spalten mit einer Breite (`width`) haben und die `kol-table`-Breite kleiner machen. Somit werden Spalten abgeschnitten und der Scollbalken wird sichtbar.

`caption`-Optimieren
- [x] Tabindex nicht mehr auf die `table`, sondern auf die `caption` ändern (man könnte auch `tr` mir `aria-hidden` und `tabindex` stattdessen probieren)
- [x] Der `caption`-Text muss zwingend linksbündig
- [x] Beispiel in Sample-App umsetzen

**Comment by sdvg** [comment]
Tabindex: Nur noch setzen, wenn scroll breite > container breite (wenn Scrollbar sichtbar)
Caption: `text-align: start`
Focus-style bleibt auf tabellen

**Comment by AntnSaj** [comment]
Beim fokussieren der Tabelle im Formularmodus (Tab) wird der Tabellentitel 3 mal vorgelesen.
![2024-02-02_09h09_27](https://github.com/public-ui/kolibri/assets/126143994/7d77d870-7f6b-40d3-b03c-a565e917c5e6)

**Comment by sdvg** [comment]
@AntnSaj Danke für die Rückmeldung! Wird in #6015 weiter bearbeitet.
