### ISSUE TITLE
🐞 Bug: Details `open` wird vom Screenreader `VoiceOver` nicht immer vorgelesen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5921]
Beim wiederholten Öffnen und Schließen des angegebenen Beispiels wird der Status nicht immer korrekt ausgegeben.

Link: https://public-ui.github.io/docs/components/details#beispiel

<img width="955" alt="image" src="https://github.com/public-ui/kolibri/assets/6279703/d16df24f-a77e-44de-8f2b-9a8075d97592">

Hinweis: Möglicherweise müssen wir hier zusätzlich ARIA-Attribute einsetzen, um das Problem zu beheben.

### Aufgaben:

- Ein Beispiel erstellen, in dem ein KolDetails-Element und ein natives `<details>`-Element nebeneinander dargestellt werden.
- Das Problem reproduzieren und mögliche Ursachen identifizieren.

### Hinweis:

- Animation könnte eine Rolle hierbei spielen.

---

> [!NOTE]  
>  [Siehe Kommentar](https://github.com/public-ui/kolibri/issues/5921#issuecomment-2355836891) für neuen Lösungsansatz.

**Comment by laske185** [comment]
Bei nativer Umsetzung tritt das Problem nicht auf. Vielleicht hängt mit der Animation zusammen.

**Comment by deleonio** [comment]
@AntnSaj, @fohi17: Bitte mit den anderen Screenreader mal nachtesten und Feedback geben.

**Comment by fohi17** [comment]
@deleonio Funktioniert bei mir mit NVDA und JAWS sowohl in Chrome als auch in Firefox ohne Probleme.

**Comment by sdvg** [comment]
Folgende Lösung wurde mit Martin besprochen:

* Wir passen die Implementierung der Details-Komponente so an, das sie intern kein natives `<details>`-Element mehr verwendet.
* Dabei wird sichergestellt, dass das aktuelle Styling und Verhalten gleich bleiben.
* Die entfernte "Semantik" des nativen Elements wird durch die entsprechenden Roles bzw. Aria-Attribute ersetzt.
  * https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded
* Als Vorlage kann hier kol-accordion verwendet werden. Womöglich lässt sich auch Code wiederverwenden.

Hintergrund: Die Komplexität und die Probleme der Komponente kommen primär daher, dass sich der Open-State eines nativen Details-Element und Animationen schwer in Einklang bringen lassen. Wir haben das mit der aktuellen Implementierung versucht, offenbar gibt es damit aber weiterhin Probleme, weshalb wir ihn nicht länger verfolgen wollen.

**Comment by laske185** [comment]
Sinnvoll wäre es, wenn das Akkordeon und das Details die gleiche WC-Komponente nutzen.
```mermaid
flowchart 

KolAccordion --> KolCollapsibleWc
KolDetails --> KolCollapsibleWc
```
