### ISSUE TITLE
📖 Help: KolInputRadio selektierten Wert zur Laufzeit ändern

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#5924]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

Vorweg, ich verwende statische HTML-Formulare.

Ich möchte zur Laufzeit den selektierten Wert einer RadioGroup ändern. Der Benutzer klickt auf eine Schaltfläche und in der RadioGroup wird daraufhin ein bestimmter Wert ausgewählt. Ich habe es mit _value probiert, das bewirkt aber nichts. Pseudocode:

`(document.querySelector("#myradiogroup"))._value = -0;`

(Auch der "echte" Wert, in diesem Fall "all", funktioniert nicht.)

**Comment by deleonio** [comment]
Hier ein Beispiel: https://stackblitz.com/edit/lit-element-3nnnnr?file=src%2Findex.js
