### ISSUE TITLE
DevOps: Netlify Deployment für `develop` und `release/*`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5926]
Deployment von vorhandener Pipe ableiten: https://github.com/public-ui/kolibri/blob/develop/.github/workflows/draft-deploy.yml

**Comment by sdvg** [comment]
Zusätzlich: Können wir die fehlschlagenden Deployments bei externen PRs vermeiden?

**Comment by sdvg** [comment]
PR (Verlinken schlägt fehlt): https://github.com/public-ui/kolibri/pull/5977

**Comment by sdvg** [comment]
Reopen für `v1`
