### ISSUE TITLE
🛹 Feature: Tooltip die `role="tooltip"` geben 

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5927]
Ein Tooltip kann die Rolle `tooltip` haben. Hierbei muss das Element, welches einen Tooltip hat, mittels `aria-describedby` auf ein Tooltip-Element mit der `id` verweisen.

Link: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role#description

```html
<label for="password">Password:</label>
<input aria-describedby="passwordrules" id="password" type="password" />
<div role="tooltip" id="passwordrules">
  <p>Password Rules:</p>
  <ul>
    <li>Minimum of 8 characters</li>
    <li>
      Include at least one lowercase letter, one uppercase letter, one number
      and one special character
    </li>
    <li>Unique to this website</li>
  </ul>
</div>
```

Effekt:
- Die `_id` wird erforderlich, damit `aria-describedby` auf die ID des Tooltips verweisen kann.
- Wird die ID am Tooltip nicht genutzt, dann passiert einfach nichts.
- Beim Button (Accordion) liest VoiceOver die Beschreibung vor. Bei Abbr, Details und Link macht er es trotz identischer Implementierung nicht.

**Comment by laske185** [comment]
Die aktuelle Umsetzung der Tooltips ist in Ordnung und bedarf keiner Verbesserung.
