### ISSUE TITLE
🐞 Bug: Umlaut in <kol-link> bei UTF-8 Kodierung der Datei falsch dargestellt

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#5929]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Ich habe eine statische HTML-Seite. META Charset ist utf-8, alle Dateien sind mit UTF-8 Kodierung gespeichert. Bei Verwendung eines <kol-link> mit einem Umlaut im Label wird dieses falsch dargestellt.

Beispiel:
    `<kol-link _href="#0" _label="Barrierefreiheitserklärung"></kol-link>`

Als Workaround habe ich die betreffende Datei im ANSI-Format gespeichert, dann wird der Umlaut korrekt dargestellt. Was ebenfalls funktioniert ist die Verwendung von z.B. "&auml", sowohl bei ANSI- als auch bei UTF-8 Kodierung der Datei. (Bei unverändertem META Charset.)

Ich verwende Kolibri Version 2.0.3, lokal installiert.

## Reproduktion

Reproduktion via Stackblitz leider nicht möglich, da dort keine statischen HTML-Seiten verwendet werden. Außerdem weiß ich leider nicht, ob und wie man dort die Charsets ändern könnte. Ich kann aber ITZBund intern eine Testseite anbieten.

## Erwartetes Verhalten

Bei konsequenter Verwendung von UTF-8 sollte es eigentlich keine Umlaut-Probleme geben.

## Sonstiges

Die Doku zu "Link" ist nicht ganz auf dem aktuellen Stand. Dort steht im Beispiel-Code noch

    <kol-link _href="https://www.w3.org" _target="_blank">Hier steht ein Link</kol-link>

**Comment by deleonio** [comment]
Ich habe es kurz nachgetestet. Ich vermute der Charset wurde im Head nicht definiert: https://www.w3schools.com/tags/att_meta_charset.asp

**Comment by deleonio** [comment]
Doc wird hier gefixed: https://github.com/public-ui/kolibri/issues/5931

**Comment by webbird** [comment]
META-Charset ist gesetzt.
![2024-01-23_16h49_11](https://github.com/public-ui/kolibri/assets/147354/36f61d4e-1215-43ed-a263-79933f70aa33)

**Comment by deleonio** [comment]
Lass uns morgen zusammen darauf schauen.

**Comment by laske185** [comment]
Gibt es hierfür ein Reproduktionsbeispiel? Einfach eine Beispiel HTML-Datei ans Ticket hängen würde schon helfen.

**Comment by deleonio** [comment]
@webbird - ist das Problem noch relevant?

**Comment by webbird** [comment]
Bei mir sind die Seiten aus Einzelteilen zusammen gesetzt. Anscheinend kommt da irgendwo das UTF-8 unter die Räder. Demnach liegt die Ursache nicht in in der Komponente.
