### ISSUE TITLE
🐞  Firefox-Bug: Tooltips mit Version `115.6.0esr` defekt

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5942]
![image](https://github.com/public-ui/kolibri/assets/6279703/de457b18-f733-4483-bd26-89e7a44eb279)

Download: https://ftp.mozilla.org/pub/firefox/releases/115.6.0esr/

Reproduktion: https://public-ui.github.io/v2/sample-react/#/input-text/basic

- [x] Tooltips werden nicht ausgeblendet, wenn man das Feld mit der Maus fokussiert hat.

**Comment by deleonio** [comment]
Wir haben den Fehler mit der neusten ESR-Version nachgetestet. Der Fehler tritt nicht mehr in Version 115.7.esr auf.

Download: https://www.mozilla.org/de/firefox/all/#product-desktop-esr

**Comment by laske185** [comment]
Das Theme nutzt CSS Nesting, welches erst ab dem FF 117 supported wird:
https://caniuse.com/?search=nested%20css

**Comment by deleonio** [comment]
Hallo @laske185 und @sdvg,

bitte macht das soweit erforderlich mal zusammen. Peter hat die Entwicklungsumgebung dazu und kann die notwendigen Änderungen einpflegen.

VG

**Comment by sdvg** [comment]
Ich kann das Problem auch unter macOS reproduzieren und würde das Ticket übernehmen.
