### ISSUE TITLE
🐞 Bug: appointment-form: Fehlerliste bleibt beim Wechsel der Tabs erhalten

### ISSUE THREAD

**Issue by anicyne** [public-ui/kolibri#5961]
Fehlerlisten sollten bei einem Tab Wechsel entweder Gelöscht oder ausgeblendet werden, damit nur Fehler des jeweiligen Tab angezeigt werden

Initiales Ticket: https://github.com/public-ui/kolibri/issues/5925 (wird geschlossen)

**Comment by anicyne** [comment]
Dieses Issue wurde im #6034 behoben

**Comment by AntnSaj** [comment]
Komponente wurde erfolgreich getestet und der Fehler ist behoben
