### ISSUE TITLE
🐞  Firefox-Bug: Nested Styles mit Version `115.6.0esr` defekt

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5979]
Download: https://ftp.mozilla.org/pub/firefox/releases/115.6.0esr/

- [ ] Prüfen, ob es nur im Basis-Theme verursacht wird.
- [ ] Prüfen, ob es nur im Kunden-Theme verursacht wird.
- [ ] Prüfen, ob es nur eine Preprocessor gelöst werden kann. Weil wir so weniger "zurückbauen" müssen.
- [ ] Die Themes müssen refactored werden, sodass sie auch ohne `Nested Styles`-Feature funktionieren.

Das Theme nutzt CSS Nesting, welches erst ab dem FF 117 supportet wird: https://caniuse.com/?search=nested%20css

**Comment by deleonio** [comment]
Hallo @laske185 und @sdvg,

bitte macht das soweit erforderlich mal zusammen. Peter hat die Entwicklungsumgebung dazu und kann die notwendigen Änderungen einpflegen.

VG

**Comment by laske185** [comment]
@sdvg : Basis-Styles
@laske185 : interne Themes

**Comment by laske185** [comment]
Im components paket müssen folgende Sachen geprüft werden:

- prüfen, ob es überhaupt aktuell nesting gibt
- stencil config: plugins: welche relevanz haben die, postcss (gut) oder sass (optional, da css eigentlich reichen sollte)

**Comment by laske185** [comment]
Es gibt nested styles in folgenden CSS-Dateien:

- `packages\components\src\components\button.css`
- `packages\components\src\components\input-checkbox\checkbox.css`
- `packages\components\src\components\table\style.css`
- `packages\components\src\components\tree\style.css`

**Comment by laske185** [comment]
In der `stencil.config.ts` ist nur `postcss` konfiguriert.
