### ISSUE TITLE
📖 Help: Wiederverwendung des `schema`-Moduls 

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5985]
Bei der Wiederverwendung des Schema-Moduls `@public-ui/schema` treten Fehler auf. Wir müssen mal schauen, wieso die fehlenden Types sich so durchziehen. Auf Ebene des Moduls haben wir die Types hinterlegt.

_"Aktuell weiß ich keinen Rat."_

Reproduktion:

1. `git clone https://github.com/leanupjs/kolibri`
2. `cd kolibri`
3. `pnpm i`
4. `pnpm -r build`

Fehlerbild:

```bash
[ ERROR ]  TypeScript: ../../node_modules/.pnpm/@public-ui+schema@2.0.4/node_modules/@public-ui/schema/dist/index.d.ts:2:38
           Could not find a declaration file for module 'color-rgba'.
           '/Users/***/Workspace/leanup/kolibri/node_modules/.pnpm/color-rgba@2.4.0/node_modules/color-rgba/index.js'
           implicitly has an 'any' type.Try `npm i --save-dev @types/color-rgba` if it exists or add a new declaration
           (.d.ts) file containing `declare module 'color-rgba';`

      L1:  import { Generic, Theme } from 'adopted-style-sheets';
      L2:  export { default as colorRgba } from 'color-rgba';
      L3:  import { RGB } from 'color-convert/conversions';

[ ERROR ]  TypeScript: ../../node_modules/.pnpm/@public-ui+schema@2.0.4/node_modules/@public-ui/schema/dist/index.d.ts:3:21
           Could not find a declaration file for module 'color-convert/conversions'.
           '/Users/***/Workspace/leanup/kolibri/node_modules/.pnpm/color-convert@2.0.1/node_modules/color-convert/conversions.js'
           implicitly has an 'any' type.Try `npm i --save-dev @types/color-convert` if it exists or add a new
           declaration (.d.ts) file containing `declare module 'color-convert/conversions';`

      L2:  export { default as colorRgba } from 'color-rgba';
      L3:  import { RGB } from 'color-convert/conversions';
      L4:  export { default as rgbaConvert } from 'rgba-convert';

[ ERROR ]  TypeScript: ../../node_modules/.pnpm/@public-ui+schema@2.0.4/node_modules/@public-ui/schema/dist/index.d.ts:4:40
           Could not find a declaration file for module 'rgba-convert'.
           '/Users/***/Workspace/leanup/kolibri/node_modules/.pnpm/rgba-convert@0.3.0/node_modules/rgba-convert/index.js'
           implicitly has an 'any' type.Try `npm i --save-dev @types/rgba-convert` if it exists or add a new
           declaration (.d.ts) file containing `declare module 'rgba-convert';`

      L3:  import { RGB } from 'color-convert/conversions';
      L4:  export { default as rgbaConvert } from 'rgba-convert';
```

**Comment by sdvg** [comment]
@deleonio Das PR wurde gemerged, kann dieses Ticket geschlossen werden?

**Comment by agnieszkaw61** [comment]
@sdvg @deleonio Halo zusammen. Ich habe versucht, Kolibri von 1.7.4 auf 2.0.8 zu aktualisieren, aber ich habe den 'missing module' Fehler  für '@public-ui/schema' erhalten (ich verwende es nicht in meiner App, es war nur ein Abhängigkeitspaket). Als ich es installiert habe, sind die von Ihnen in dieser Ausgabe erwähnten Fehler aufgetreten. Hängt das irgendwie zusammen? Sollte es jetzt nach diesem Fix nicht funktionieren?
![image](https://github.com/public-ui/kolibri/assets/115545729/9da6f083-87a3-4a9d-bc98-bf4f4204d4d8)

**Comment by agnieszkaw61** [comment]
ich kann color-convert installieren und diese 2 exports entfernen, und dann es arbeitet, es erfordert jedoch das Ändern von Dateien in node-modules

**Comment by deleonio** [comment]
@agnieszkaw61: Danke für Deine Hinweise, wir schauen uns das an. Hast Du ein React-Projekt oder was anders?

**Comment by agnieszkaw61** [comment]
@deleonio Angular v.16

**Comment by deleonio** [comment]
@agnieszkaw61 Kannst Du bitte mal prüfen, ob Du in Eurer `package.json` in den `dependencies` noch `@public-ui/core` drin habt. Danke.

In diesem Angular-Template funktioniert die aktuellste Version `2.0.8`: https://github.com/public-ui/create-kolibri-templates/tree/main/templates/angular-webpack

**Comment by agnieszkaw61** [comment]
@deleonio ja, die letzte Version die ich installierent konnte war:   
`  "@public-ui/core": "^1.7.6",
`
also ich habe jetzt:

```
    "@public-ui/angular-v16": "2.0.8",
    "@public-ui/components": "2.0.8",
    "@public-ui/core": "^1.7.6",
    "@public-ui/schema": "2.0.8",
    "@public-ui/themes": "2.0.8",
```

aber das Problem besteht weiterhin

**Comment by deleonio** [comment]
@agnieszkaw61 das Core Paket wurde mit Version 2 entfernt und muss aus den `dependencies` raus.

Siehe hier https://github.com/public-ui/kolibri/blob/develop/MIGRATION.md

Falls das Problem dann auch noch besteht, brauchen wir ein Reproduktionsbeispiel.

Vg und schönes WE

**Comment by agnieszkaw61** [comment]
Hallo @deleonio,
Hier ist Repo mit Beispiel: https://github.com/agnieszkaw61/kolibri-migration-demo
Problem ist, dass wir 'KolibriDevHelper' benutzen, und es braucht @public-ui/schema:
![image](https://github.com/public-ui/kolibri/assets/115545729/4adccb23-3e9f-42d5-a847-4f4b92d86f6d)

 Wenn ich es installiere, ich habe diese Fehler die du beschrieben hast:
![image](https://github.com/public-ui/kolibri/assets/115545729/d8da7f22-66b5-467c-bc92-767eabe5fb3e)
