### ISSUE TITLE
🐞 Bug: `Popover` wird nicht als Adapter-Komponente generiert und bereitgestellt

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5988]
# Akzeptanzkriterien

- [x] Der Hinweis im Tooltip soll als Variante `card` bekommen und als Typ ´info´. Siehe Beispiel unten.
- [x] Dokumentation vom Popover erweitern, dass das Popover wie der Tooltip auch nicht alleine stehen darf.
- [x] Umsetzung der Card analog zum Tooltip.

Alert box:
```html
<kol-alert _type="info" _variant="card" style="" class="hydrated">
Die <strong>Tooltip</strong>-Komponente wird innerhalb von KoliBri verwendet und ist nicht dafür vorgesehen in der Anwendungsentwicklung verwendet zu werden. Denn der Tooltip ist nur dann wirklich barrierefrei, wenn von einem Referenzelement auf das Tooltip verwiesen wird.
</kol-alert>
```

**Comment by deleonio** [comment]
@laske185, @sdvg wir haben die Komponente bewusst nicht als öffentliche Komponente umgesetzt. Was war die Begründung?!

**Comment by laske185** [comment]
Dokumentation erweitern, dass das Popover analog zum Tooltip nicht alleine stehen darf.

**Comment by laske185** [comment]
Card-Variante bei dem Alert verwenden.
