### ISSUE TITLE
🐞 Bug: Sample App geht bei 404 auf Handout

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5991]
Wenn eine Route nicht definiert ist, dann geht die Sample App immer auf das Handout-Beispiel.

- `packages/samples/react`

**Comment by anicyne** [comment]
@deleonio ich habe zwei mögliche Lösungen:
1 : wir können den " Zurück Button" deaktivieren, wenn wir auf packages/samples/react (seite 0) befinden.
2: Alternativ könnte ein klick auf  "Zurück Button" den Benutzer zur letzten Komponente in der Liste bringen, anstatt auf der gleichen Seite zu bleiben (packages/samples/react)

Was denkst du ?
