### ISSUE TITLE
🛠️ Todo: Trigger UpdateSnapshots-Workflows by GitHub-Action Bot

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5993]
KI:

Wenn Sie einen Workflow starten möchten, sobald ein neuer Commit auf einen Branch gepusht wird, auch wenn dieser Commit von einem GitHub Action Bot stammt, können Sie den `push`-Event in Ihrer Workflow-Definition verwenden. Wie bereits erwähnt, verhindert GitHub standardmäßig, dass Workflows durch Aktionen ausgelöst werden, die von GitHub Actions selbst innerhalb desselben Repositories verursacht werden, um zirkuläre Workflow-Auslösungen zu vermeiden. 

Eine Lösung für dieses Problem ist, die Einstellungen für die Workflow-Ausführung anzupassen, um auch Workflows auszulösen, die durch Aktionen von `github-actions[bot]` verursacht wurden. Dies kann durch die Verwendung eines Personal Access Tokens (PAT) anstelle des standardmäßigen `GITHUB_TOKEN` erreicht werden. Das `GITHUB_TOKEN` hat Einschränkungen, um rekursive Workflow-Auslösungen zu verhindern, während ein PAT diese Einschränkung umgehen kann.

Hier ist ein grundlegendes Beispiel für eine Workflow-Definition, die auf jeden `push`-Event reagiert:

```yaml
name: Mein CI Workflow
on: 
  push:
    branches:
      - main  # Setzen Sie hier den Namen Ihres Zielbranches ein

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Fügen Sie hier weitere Schritte für Ihren Workflow hinzu
```

Um sicherzustellen, dass Ihr Workflow auch bei Commits von GitHub Actions ausgelöst wird, sollten Sie folgende Schritte beachten:

1. **Verwenden eines Personal Access Tokens (PAT):**
   - Erstellen Sie einen Personal Access Token (PAT) mit den notwendigen Berechtigungen über die GitHub-Einstellungen.
   - Speichern Sie diesen Token in den Geheimnissen Ihres Repositories.
   - Modifizieren Sie den Workflow, der den Commit macht, um diesen PAT für Aktionen zu verwenden, die eine erneute Auslösung anderer Workflows ermöglichen sollen.

2. **Aktionen mit dem PAT durchführen:**
   - Stellen Sie sicher, dass Aktionen, die Commits oder Tags erstellen, den PAT anstelle des `GITHUB_TOKEN` verwenden. Dies kann oft einfach durch Setzen eines Headers in einem `curl`-Befehl oder durch Konfigurieren der Aktionen, die GitHub API-Anfragen durchführen, erreicht werden.

Beachten Sie jedoch, dass die Verwendung eines PAT zusätzliche Sicherheitsüberlegungen mit sich bringt, da PATs mit umfangreichen Berechtigungen das Sicherheitsrisiko erhöhen können. Es ist wichtig, dass der PAT minimale Berechtigungen hat, die für die erforderlichen Aktionen ausreichend sind, und sicher gespeichert wird.

Wenn Sie diesen Ansatz verfolgen, sollten Sie in der Lage sein, Workflows auszulösen, selbst wenn die Commits von einem GitHub Actions Bot kommen, ohne von Ereignissen anderer Workflows abhängig zu sein.

**Comment by sdvg** [comment]
Der Workflow ist für `v1` angepasst. Damit alles funktioniert, müssen wir in der `public-ui`-Orga noch folgendes erledigen:

1) [GitHub App anlegen](https://github.com/organizations/public-ui/settings/apps) und wie folgt unter General konfigurieren:
- Name: z.B. `KoliBri Bot`
- Webhook ist nicht notwendig, kann deaktiviert werden
- Logo hochladen wäre ein Nice To Have
- Private Key erstellen und sicher ablegen

2) GitHub App Permissions konfigurieren
- Im Bereich "Permissions & events", dann "Repository permissions": `Contents` ready & write erlauben

3) GitHub App installieren
- Im Bereich "Install App" für das `kolibri`-Repository installieren

4) Neue [Secrets für `kolibri`-Repository konfigurieren](https://github.com/kol-testing/kolibri/settings/secrets/actions)
- Folgende Secrets konfigurieren: `APP_ID`, `PRIVATE_KEY`. App ID kann im Bereich "General" der App gefunden werden. Private Key ist der zuvor heruntergeladene Key.
