### ISSUE TITLE
🐞 Bug: Fokusierbare Tabelle: Beschreibung wird 3 mal vorgelesen

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6015]
Follow up von: https://github.com/public-ui/kolibri/issues/5912#issuecomment-1923310896

---

Beim fokussieren der Tabelle im Formularmodus (Tab) wird der Tabellentitel 3 mal vorgelesen.
![2024-02-02_09h09_27](https://github.com/public-ui/kolibri/assets/126143994/7d77d870-7f6b-40d3-b03c-a565e917c5e6)

**Comment by sdvg** [comment]
Das Problem ist hier vermutlich, dass Caption-Element _und_ "Tabellenbeschreibung" (entspricht der Caption) beim Fokus vorgelesen werden.
Angedachte Lösung: Fokus auf ein leeren Div mit `tabindex=0` statt auf die Caption setzen.

**Comment by AntnSaj** [comment]
Die Ausgabe mit dem NVDA ist gut. Es wird das vorgelesen, was erwartet wird. Der JAWS sagt beim Fokussieren der Tabelle im Formularmodus (Tab-Modus) nichts an. Das erzeugt einen leeren Tab Schritt und kann ggf. zu einer Abwertung im BITV-Test führen.

**Comment by deleonio** [comment]
> Die Ausgabe mit dem NVDA ist gut. Es wird das vorgelesen, was erwartet wird. Der JAWS sagt beim Fokussieren der Tabelle im Formularmodus (Tab-Modus) nichts an. Das erzeugt einen leeren Tab Schritt und kann ggf. zu einer Abwertung im BITV-Test führen.

Die Umsetzung sollte mit `aria-labelledby="caption"` erfolgen, nicht mit `aria-describedby="caption"`.

**Comment by sdvg** [comment]
@deleonio Was ist hier die Entscheidung am Ende? `aria-labelledby`, wie du oben schreibst, oder `aria-describedby` laut [diesem Kommentar](https://github.com/public-ui/kolibri/pull/6017#issuecomment-1954231614)?

**Comment by laske185** [comment]
`aria-describedby` verwenden, da es bei `aria-labelledby` doppelt vorgelesen wird.
