### ISSUE TITLE
🐞 Bug: Screenreader Probleme Tabellenzellen

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6018]
Die folgenden Fehler beziehen sich auf die NVDA/JAWS Ausgabe.
Bei dem initialen fokussieren des Sortierschalters (Formularmodus-Tab) wird nur Schalter vorgelesen und es wird nicht deutlich, was dieser Schalter macht.

**Version 1.7.9:**
table badge-size:
NVDA: Es wird nicht bei jeder um Sortierung eine Screenreader Ausgabe erzeugt.
JAWS: Der Sortierstatus wird immer ausgegeben. Bei dem unsortierten Status wird "sortiert" angesagt

table column-allignment:
NVDA: Der Sortierstatus wird immer richtig ausgegeben.
JAWS: Der Sortierstatus wird immer ausgegeben. Bei dem unsortierten Status wird "sortiert" angesagt

table render-cell:
NVDA: Status "Nicht sortiert" wird nicht ausgegeben.
JAWS: Der Sortierstatus wird immer ausgegeben. Bei dem unsortierten Status wird "sortiert" angesagt

table sort-data:
NVDA: Es wird nicht bei jeder um Sortierung eine Screenreader Ausgabe erzeugt.
JAWS: Der Sortierstatus wird immer ausgegeben. Bei dem unsortierten Status wird "sortiert" angesagt

**Version 2.0.3:**
table badge-size:
NVDA: Sortierung wird gar nicht angesagt. 
JAWS: Sortierung wird gar nicht angesagt. 

table column-allignment:
NVDA: Der Sortierstatus wird immer richtig vorgelesen.
JAWS: Der Sortierstatus wird immer ausgegeben. Bei dem unsortierten Status wird "sortiert" angesagt

table render-cell:
NVDA: Status "Nicht sortiert" wird nur manchmal ausgegeben. "Aufsteigend" und "Absteigend" werden immer ausgegeben.
JAWS: Der Sortierstatus wird immer ausgegeben. Bei dem unsortierten Status wird "sortiert" angesagt

table sort-data:
NVDA: Sortierung wird gar nicht angesagt.
JAWS: Sortierung wird gar nicht angesagt.

_Originally posted by @AntnSaj in https://github.com/public-ui/kolibri/issues/4191#issuecomment-1923436047_

**Comment by deleonio** [comment]
Wir haben festgestellt, dass das Rendern der Tabelle das Vorlesen stört. Bei einer einfachen Tabelle, wird es sogar immer vorgelesen.

- [ ] Tabellen neu Rendern geschickter lösbar?
- [ ] Der `key` muss für das Zeilenrendern eindeutiger werden. Hierzu wird eine `Map<Object, string> -> set(Object, nonce())` erstellt. Object ist hierbei die Refenz auf eine Zeile aus `_data`.
- [ ] Attribut für `aria-sort` erst setzen (`el.setAttr...`) und dann erst rendern (setTimeout(()=>{})).
