### ISSUE TITLE
🛹 Feature: Mehrere KoliBri-Versionen gleichzeitig nutzen

### ISSUE THREAD

**Issue by mello-r** [public-ui/kolibri#6019]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
In unserem Projekt verwenden wir eine Microfrontend-Architektur. Daher kann es vorkommen, dass verschiedene Microfrontends verschiedene Versionen von KoliBri benötigen. Normalerweise ist das bei JavaScript Bibliotheken kein Problem, aber da KoliBri auf WebComponents aufbaut, kommt es zu Konflikten bei der Registrierung der WebComponents. Deshalb registrieren wir KoliBri nur einmal in der Anwendung, die die Microfontends lädt. Das Problem dabei ist, dass bei einem Major Update alle Microfrontends, die noch nicht aktualisiert werden konnten, ein Fehlverhalten zeigen, da sie noch eine veraltete KoliBri Version erwarten.

## Beschreiben Sie die gewünschte Lösung
Der übliche Weg, dieses Problem für WebComponent Komponentenbibliotheken zu lösen, besteht darin, die Komponenten mit einem Major Version Pre- oder Suffix zu versehen. 

Ein Beispiel, wie dies mit Stenciljs aussehen könnte, ist hier zu finden: https://dev.to/sanderand/running-multiple-versions-of-a-stencil-design-system-without-conflicts-2f46. Hier werden die WebComponents zur Laufzeit umbenannt. Dies hat den Vorteil, dass jeder Benutzer selbst entscheiden kann, ob er dieses Pre- oder Suffix verwenden möchte. Zu beachten ist, dass die Umbenennung auch den Wrapper Libraries (React, Angular, Vue...) bekannt gemacht werden muss.

Eine alternative Lösung wäre, das Präfix oder Suffix nicht zur Laufzeit anzugeben, sondern hardcodiert für jede Version. Der Vorteil ist, dass die Stencil Wrapper weiterhin funktionieren sollten. Der Nachteil wäre, dass die Benutzer gezwungen wären, den Pre- oder Suffix zu verwenden.

## Zusätzlicher Kontext

- https://micro-frontends.org

**Comment by deleonio** [comment]
@mello-r Danke.

**Comment by deleonio** [comment]
Vielen Dank für die Feature-Anfrage. Wir haben uns den Blog-Post angeschaut und werden zunächst eine Referenzimplementierung unter folgenden Gesichtspunkten angehen:

- Opt-in Ansatz (Projekt kann Suffix frei wählen)
- `tagNameTransform` - wird eingeführt
- `transformTagName` - wird für `kol-button` pilotiert
- Refactoring der `render`-Methoden
- Anpassung von Stylings, soweit noch erforderlich

**Comment by deleonio** [comment]
FYI @sdvg ... ich habe das mal für mein `Solid`-Plugin gemacht: https://github.com/deleonio/stencil-ds-output-targets/commit/f483531087829474ad357808dc8fecf136841b7c

**Comment by deleonio** [comment]
Aus unserer Sicht ist das Feature fertig.
