### ISSUE TITLE
📖 Help: `textarea` value change event comes with blur?!

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6030]
Mir ist ein Problem beim onChange-Event einer KolTextarea aufgefallen. Es scheint mir, als würde dieses Event erst getriggert, wenn man aus dem Feld raus klickt. Bei einer HTML-Textarea oder auch einem KolInputText funktioniert es wie erwartet.

Einfaches Beispiel bei dem der onChange den Button freigibt: https://stackblitz.com/edit/vitejs-vite-cpybg7?file=src%2FApp.tsx

**Comment by sdvg** [comment]
Kurze Anmerkung: Aus meiner Sicht ist das kein Bug, weil wir hier das normale HTML Verhalten haben.
Dass React beim Input-Event (bei jedem Tastenanschlag) auch `onChange` feuert ist ein React-Spezialfall\*.

Falls noch nicht vorhanden würde ich vorschlagen, das `input` event für KoliBri-Input-Komponenten einzuführen. Das scheint hier das gewünschte Event zu sein.

\* Ich habe dazu auf die schnelle nicht viel gefunden, aber hier ist es erwähnt: https://preactjs.com/guide/v10/differences-to-react/#use-oninput-instead-of-onchange

**Comment by deleonio** [comment]
Bisher haben alle Eingabefelder mit onChange von Stencil gearbeitet und nicht mit onInput. Das würde bedeutet, dass alle anderen Eingabefelder refactored werden müssten.

Siehe hier: https://stackblitz.com/edit/vitejs-vite-2tlb5u?file=src%2FApp.tsx,index.html

Gewünschtes Verhalten (offen):
- [x] `onChange` - Event feuert bei Verlassen des Feldes
- [x] `onInput` - Event feuert bei jeder Änderungen des Feldwertes
- [x] `onBlur`, wie `onChange` - genauer Unterschied noch unklar
- [x] Das muss für alle Eingabefelder, Select, Textarea
- [x] Kleine Doku für den "Breaking Change" für das Release-Changelog
