### ISSUE TITLE
🛠️ Todo: BMF-Theme auf SCSS umstellen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6050]
Like: https://github.com/public-ui/kolibri/issues/6000

Könnt Ihr vom BMF-Team bitte Feedback geben: @Chrisdo82, @mello-r, @simonhesse

**Comment by mello-r** [comment]
Mit #6054 kommt in dieser Richtung nochmal Arbeit auf uns zu, können wir da warten und das bündeln oder würde das dann von euch übernommen werden?

**Comment by deleonio** [comment]
Hi @mello-r,

aktuell ist das bmf-Theme in unserem Repo. Somit nehmen wir auch alle Anpassungen vor und covern das mit den Visuellen Regression-Tests.

Wenn immer Ihr Änderungen vornehmen, solltet Ihr unbedingt unseren aktuellen Stand als Basis nehmen. 

Zukünftig könntet Ihr live (serve) über die IDE am Theme und allen Sample im Browser dargestellt arbeiten/stylen.

**Comment by deleonio** [comment]
@mello-r, @Chrisdo82 - Style-Anpassungen erfolgen aktuell nur in v2 nicht in v1. Wie sieht das aktuell mit den unterschiedlichen Projekten aus?

**Comment by mello-r** [comment]
Ich bin mir nicht sicher, ob ich die Frage verstehe, wenn du nicht meintest, ob wir das umsetzten können. Wozu sollen wir Feedback geben? Wenn du meinst, ob wir schon komplett auf v2 migriert sind, da sind wir noch dran.

**Comment by Chrisdo82** [comment]
@deleonio 
- Uns ist nicht klar, ob wir hier Arbeitsaufwand haben oder ob ihr die Umstellung zu SCSS macht. 
- Des Weiteren wissen wir nicht, worauf wir hier Feedback geben sollen (siehe dein Kommentar ganz oben).

**Comment by deleonio** [comment]
Für `v1` werden wir die Umsetzung nicht machen, da perspektivisch alle DESYBRI-Projekte auf `v2` wechseln.
