### ISSUE TITLE
💡 Hinweis: Handout-Startseite bricht nicht um

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#6056]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**

Die Startseite des Handouts (handout > basic) bricht beim Browserzoom nicht um => Diskussionspunkt

![image](https://github.com/public-ui/kolibri/assets/6279703/982b82f1-1e9f-4caf-8d3d-4c238ea46764)

**Comment by deleonio** [comment]
- [ ] `packages/samples/react`: `pnpm i && pnpm build:deps`, `npm start`
- [ ] Handout-Component ist hier:  `packages/samples/react/src/components/handout/basic.tsx`
- [ ] Sample-Description hinzufügen: Die Handout-Seite ist speziell für einen Handout-Druck optimiert (A4).
- [ ] Responsives Layout: Mittels `tailwind`-Breakpoints das Layout geschickt umbrechen lassen (kleines Beispiel: https://stackblitz.com/edit/tailwind-sample?file=index.html)
  - [ ] Fullscreen: so wie es jetzt ist
  - [ ] Prüfen ab welchem Breakpoint es nicht mehr ok ist und dann direkt auf 1-spaltig layouten

**Comment by cbraehmig** [comment]
Nach Abstimmung mit Martin werden wir auch in der SampleApp das Responsive Design umsetzen.

**Comment by fohi17** [comment]
------------- **A11y-Test Erfolgreich für v1** -------------
