### ISSUE TITLE
💡 Hinweis: Custom-Spin sollte einen Beispiel-Hinweis kriegen

### ISSUE THREAD

**Issue by fohi17** [public-ui/kolibri#6059]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**

Das Beispiel, dass gerade in der Komponente "Spin Custom" gezeigt wird ist nicht so schön. Es soll wohl nur zeigen, dass custom Designs möglich sind. Das sollte als Text noch dazu, damit keiner denkt das wäre ein gutes Design für eine Ladeanzeige.

**Comment by sdvg** [comment]
Bestehende Beschreibung ergänzen: "Nicht zwingend barrierefrei."
