### ISSUE TITLE
🐞 Bug: create-kolibri Dependency issue

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6072]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

```
$ npm init kolibri@latest app

Installing dependencies using pnpm
> pnpm install --dir /Users/***/packages/app
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for nightwatch-axe-verbose@2.0.5

This error happened while installing a direct dependency of /Users/***/packages/app

The latest release of nightwatch-axe-verbose is "2.3.0".

If you need the full list of all 17 published versions run "$ pnpm view nightwatch-axe-verbose versions".
Progress: resolved 1, reused 0, downloaded 0, added 0
Failed to install dependencies: 1
```

**Comment by petereichinger** [comment]
Version 2.0.6 hat das Problem immer noch.
Ich hab bei mir die package.json angepasst und Version wie folgt gesetzt als kleiner workaround

		"nightwatch-axe-verbose": "^2.0.0",

**Comment by laske185** [comment]
Die Templates zum Erzeugen eines neuen Projektes wurde komplett neu erstellt. Sie sind in diesem Repo zu finden: https://github.com/public-ui/templates

Dort ist auch eine ausführliche Anleitung enthalten.
