### ISSUE TITLE
🛠️ Todo: Verwendung von CSS-Klasse `hidden` prüfen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6075]
Die CSS-Klasse `hidden` soll gegen das `hidden`-Attribut ersetzt und nur in einer `display: none`-Situation verwendet werden.

Ansonsten soll `visually-hidden` verwendet werden, damit das Element optisch nicht, aber semantisch sichtbar ist.

**Comment by laske185** [comment]
Beispiele?
