### ISSUE TITLE
🛹 Feature: Checkbox/Switch/ToggleButton - Option Label entweder links oder rechts

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6083]
- [x] Neue Property `_label-align` mit den Optionen `left` und `right`
- [x] `right` ist default
- [x] Im Basis-Style wird auf die Property reagiert.
- [x] Sample in der react sample app anlegen 
- [x] Muss in einem Screenshot-Test sichtbar sein

**Comment by laske185** [comment]
Themes müssen angepasst werden. Nachfolge-Ticket für die internen Themes muss angelegt werden.
