### ISSUE TITLE
🛠️ Todo: `@public-ui/core` wieder einführen - Abhängigkeit `register` von `Web Components` auflösen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6086]
`@public-ui/core` war doch sehr sinnvoll - die `register`-Methode ist nutzbar ohne die Components mitzuziehen

**Comment by laske185** [comment]
Der erwartete Konflikt bei der Kombination der Komponenten mit einer eigenen Lib an Komponenten trat nicht auf.
