### ISSUE TITLE
🐞 Bug: Input Error Message renders Alert Shadow DOM

### ISSUE THREAD

**Issue by chriskrj** [public-ui/kolibri#6099]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
![Bildschirmfoto 2024-02-20 um 16 18 22](https://github.com/public-ui/kolibri/assets/23551989/94d1a61f-3e69-441c-ae7e-5d53fe350e9d)

## Zusätzlicher Kontext
Es besteht keine Möglichkeit, die angezeigte Fehlermeldung individuell zu stylen. Siehe #5102  @deleonio

**Comment by deleonio** [comment]
Innerhalb von KoliBri-Komponenten werden keine erneuten Shadow-Roots verwendet, um die Gestaltbarkeit zu vereinfachen.

Hier müssen alle Inputs, Select und Textarea so refactored werden, dass sie statt der `kol-alert` direkt die `kol-alert-wc` verwenden.

- [ ] `kol-alert` gegen `kol-alert-wc` austauschen (`Input`s, `Select`, `Textarea`)
- [ ] Themes anpassen (`Mixins` nutzen)
