### ISSUE TITLE
🛠️ Todo: I18nService ohne I18next

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6127]
Damit die Initialisierung der Sprach-Ressourcen synchron geladen werden können, soll das i18next durch eine einfache Map ersetzt werden. Die einfache Map reicht aus, da wir die vielen Features wie Formatierungen oder auch zur Laufzeit ändernde Texte und wechselnde Sprachen nicht benötigt werden.

Hierdurch entfällt auch die Abhängigkeit zu i18next, wodurch Nebenwirkungen mit verwendenden Projekten nicht mehr auftreten können.

**Comment by deleonio** [comment]
@laske185: Wir müssen noch beachten, dass wir mit i18next Interpolierung haben. Wie bekommen wir das hin?

**Comment by laske185** [comment]
Duplicate of #6320
