### ISSUE TITLE
🛠️ Todo: `components.d.ts` auf aus Git entfernen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6128]
Die `components.d.ts` wird beim Bauen immer generiert. Daher muss sie auch nicht über Git-Versioniert werden. Aktuell sorgt sie eher für Verwirrung, wenn sie sich ändert, obwohl man selbst daran keine Aktien hat.

Es sollte auch funktionieren, wenn sie im Git auf ignorieren gestellt wird.

**Comment by deleonio** [comment]
Wurde nebenbei erledigt.
