### ISSUE TITLE
🐞 Bug: Verschiedene Eingabefelder können nicht mit Enter abgeschickt werden

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6135]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

Die Eingabefelder-Komponenten haben überwiegend ein Feature umgesetzt, das dafür sorgt, dass beim Drücken von `Enter` das umgebende Formular abgesendet wird.

Folgende Komponenten unterstützen dies noch nicht:
* select
* input-color
* input-file
* input-radio

Für die Komponenten sollte jeweils geprüft werden, wie das native Verhalten der Browser aussieht, wenn das jeweilige Eingabefeld fokussiert ist und Enter gedrückt wird.
Wichtig ist auch, dass das Formular nicht ungewollt, z.B. der Auswahl einer Select-Option, abgeschickt wird.

--- 

Zusätzlich in diesem Ticket:

Form associated elements werden für Radio-Elemente nicht korrekt gesetzt. Das Attribut `checked` fehlt.

**Comment by deleonio** [comment]
Hi @sdvg, das können wir gerne überprüfen. Das Absenden via Enter unterstützen nicht alle nativen Formularfelder, da das `Enter` zu Auswahlsteuerung gehört. Daher sind nicht alle Felder mit `Enter` absendbar.

- select - **`Enter` sendet Formular ab**
- input-color - `Enter` öffnet Farbauswahl
- input-file - `Enter` öffnet Dateiauswahl
- input-radio - **`Enter` sendet Formular ab**

👍 Das `radio` und das `select` lässt sich noch mit `Enter` absenden!

Link: https://stackblitzstartersw4glmy-vgiz--8080--c9a8a620.local-credentialless.webcontainer.io/

**Comment by deleonio** [comment]
Umsetzung in Anlehnung an: https://github.com/public-ui/kolibri/pull/6136/files

- [x] Das Absenden mittels `Enter` beim `radio` ergänzen.
- [x] Das Absenden mittels `Enter` beim `select` ergänzen.

**Comment by sdvg** [comment]
Für einen Lösungsansatz siehe: https://6626825ec5df6d0d22ca2afe--kolibri-public-ui.netlify.app/#/scenarios/static-form

Hier wurde _nur für das Select_ ein weiteres, verschachteltes Formular innerhalb des Shadow DOM umgesetzt. Das erlaubt uns zuverlässig, innerhalb der Komponente __implicit form submissions__ zu erkennen.

Die Verwendung von verschachtelten Formularen sollte aus Sicht der Barrierefreiheit getestet werden, bevor wir mit diesem Ansatz fortfahren.

<img width="960" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/b519f576-0ee4-4e99-a2f0-fc4eb949702d">
