### ISSUE TITLE
🐞 Bug: Input-Date akzeptiert kein Date-Objekt

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6137]
# Fehlermeldung

## Beschreibung des Fehlers
Wenn man dem Input-Date ein Date-Objekt als Wert zuweist, wird es nicht gesetzt.

## Reproduktion

- [Link zu StackBlitz](https://stackblitz.com/edit/vitejs-vite-x7lfeu?file=src%2FApp.tsx)

## Erwartetes Verhalten
Das Date sollte korrekt geparst und im input gesetzt werden.

## Screenshots

![image (1)](https://github.com/public-ui/kolibri-themes/assets/37439758/9ba747db-b073-4d5c-ada8-7a9683b46d93)

## Akzeptanzkriterien

- [ ] Neues Ticket für v3 anlegen, damit die Date-Logik komplett entfernt wird ( Die API erlaubt nur noch `Iso8601` als Value-Typ)
- [x] Die Logik zum Konvertieren des Date-Objects nach Iso8601 bleibt aus Kompatibilitätsgründen erhalten
- [ ] Konvertierungsfunktionen werden als deprecated markiert und in V3 entfernt.
- [ ] `Watcher` `Log.dep` Log-Message für Development-Mode, wenn ein Date als Prop-Value erkannt wurde.

**Comment by laske185** [comment]
Lösungsmöglichkeit: das DateInput akzeptiert als Wert kein Date-Objekt mehr. Damit wird die Asynchronität der Daten bei Value und onChange aufgehoben, da die Werte immer als String sind.

**Comment by chrisalat** [comment]
Wurde mit einer log deprecation message gelöst um Entwickler zu warnen, dass der Date type in der `v3` entfernt wird
