### ISSUE TITLE
Komponentenübersicht in der Dokumentation

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6140]
# Akzeptanzkriterien

- [x] Die [Komponenten-Oberseite](https://public-ui.github.io/docs/components) ist für eine Übersicht der Komponenten angelegt
- [x] Je Komponente gibt es eine Kachel, z. B. wie bei AntDesign: https://ant.design/components/overview
- [x] Jede Kachel enthält das Beispiel der Komponente aus der Readme
- [x] Das Beispiel ist kein Bild, sondern die gerenderte Komponente
- [x] Die Komponenten werden lazy geladen
- [x] Pointer-Events sind auf none gesetzt, damit die Funktionalität der Komponente nicht den Link beeinflusst.

Checkliste:
- [x] [Abbr](https://public-ui.github.io/docs/components/abbr)
- [x] [Accordion](https://public-ui.github.io/docs/components/accordion)
- [ ] [Alert](https://public-ui.github.io/docs/components/alert)
- [ ] [Avatar](https://public-ui.github.io/docs/components/avatar)
- [ ] [Badge](https://public-ui.github.io/docs/components/badge)
- [ ] [Breadcrumb](https://public-ui.github.io/docs/components/breadcrumb)
- [ ] [ButtonLink](https://public-ui.github.io/docs/components/button-link)
- [ ] [Button](https://public-ui.github.io/docs/components/button)
- [ ] [Card](https://public-ui.github.io/docs/components/card)
- [ ] [Details](https://public-ui.github.io/docs/components/details)
- [ ] [Dialog](https://public-ui.github.io/docs/components/dialog)
- [ ] [Form](https://public-ui.github.io/docs/components/form)
- [ ] [Heading](https://public-ui.github.io/docs/components/heading)
- [ ] [Icon](https://public-ui.github.io/docs/components/icon)
- [ ] [Image](https://public-ui.github.io/docs/components/image)
- [ ] [IndentedText](https://public-ui.github.io/docs/components/indented-text)
- [ ] [InputCheckbox](https://public-ui.github.io/docs/components/input-checkbox)
- [ ] [InputColor](https://public-ui.github.io/docs/components/input-color)
- [ ] [InputDate](https://public-ui.github.io/docs/components/input-date)
- [ ] [InputEmail](https://public-ui.github.io/docs/components/input-email)
- [ ] [InputFile](https://public-ui.github.io/docs/components/input-file)
- [ ] [InputNumber](https://public-ui.github.io/docs/components/input-number)
- [ ] [InputPassword](https://public-ui.github.io/docs/components/input-password)
- [ ] [InputRadioGroup](https://public-ui.github.io/docs/components/input-radio-group)
- [ ] [InputRadio](https://public-ui.github.io/docs/components/input-radio)
- [ ] [InputRange](https://public-ui.github.io/docs/components/input-range)
- [ ] [InputText](https://public-ui.github.io/docs/components/input-text)
- [ ] [LinkButton](https://public-ui.github.io/docs/components/link-button)
- [ ] [Link](https://public-ui.github.io/docs/components/link)
- [ ] [Modal](https://public-ui.github.io/docs/components/modal)
- [ ] [Nav](https://public-ui.github.io/docs/components/nav)
- [ ] [Pagination](https://public-ui.github.io/docs/components/pagination)
- [ ] [Popover](https://public-ui.github.io/docs/components/popover)
- [ ] [Progress](https://public-ui.github.io/docs/components/progress)
- [ ] [Quote](https://public-ui.github.io/docs/components/quote)
- [ ] [Select](https://public-ui.github.io/docs/components/select)
- [ ] [SkipNav](https://public-ui.github.io/docs/components/skip-nav)
- [ ] [Spin](https://public-ui.github.io/docs/components/spin)
- [ ] [Split-Button](https://public-ui.github.io/docs/components/split-button)
- [ ] [Table](https://public-ui.github.io/docs/components/table)
- [ ] [Tabs](https://public-ui.github.io/docs/components/tabs)
- [ ] [Textarea](https://public-ui.github.io/docs/components/textarea)
- [ ] Toast (Screenshot)
- [ ] [Tree](https://public-ui.github.io/docs/components/tree)

**Comment by deleonio** [comment]
- [x] Karten anklickbar machen
- [x] Beispiel mit `aria-label="..."`, `role="img"` und kol-* mit `aria-hidden="true"`
- [x] Screenshots von allen, wo keine Beispiele sind
- [x] beide Sprachen beachten i18n

```html
<a href="---">
  <kol-card aria-label="..." role="img">
    <kol-* aria-hidden="true" />
  </kol-card>
</a>
<a href="---">
  <kol-card>
    <img alt="..." />
  </kol-card>
</a>
```
