### ISSUE TITLE
Refactoring: Option Types und Validatoren optimieren

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6144]
Die möglichen Werte bei Optionsgruppen wie z.B. button `_variant` werden zur Zeit mehrfach definiert.

Ist:

```
export type ButtonVariantPropType = 'primary' | 'secondary' | 'normal' | 'tertiary' | 'danger' | 'ghost' | 'custom';

// ...

watchValidator(
		component,
		`_variant`,
		(value) => value === 'primary' || value === 'secondary' || value === 'normal' || value === 'danger' || value === 'ghost' || value === 'custom',
		new Set(['KoliBriButtonVariant {primary, secondary, normal, danger, ghost, custom}']),
// ...

```

Stattdessen sollen die möglichen Werte einmal in einem Array definiert werden, das dann zur Validierung sowie für die Type-Definition genutzt wird.

Soll:

```
const buttonVariants = ['primary', 'secondary', 'normal', 'tertiary', 'danger', 'ghost', 'custom'] as const;
export type ButtonVariantPropType = (typeof buttonVariants)[number];


watchValidator(
  component,
  `_variant`,
  value => buttonVariants.includes(value),
  new Set(['KoliBriButtonVariant {${buttonVariants.join(', ')}}']),
// ...
```

Dies wurde bereits an vielen Stellen nach dem Pattern umgesetzt. Siehe [PR](https://github.com/public-ui/kolibri/pull/5492/files). 
Es fehlt nur noch bei `AlternativeButtonLinkRolePropType`.

**Comment by laske185** [comment]
Bitte prüfen.

**Comment by sdvg** [comment]
Das Ticket ist im Prinzip ein Duplikat von: https://github.com/public-ui/kolibri/issues/5095
In diesem PR wurde auch bereits viel erledigt und es kann als Vorlage dienen: https://github.com/public-ui/kolibri/pull/5492/files

Trotzdem habe ich noch zwei Prop Types gefunden, die wir anpassen können:

- `AlternativeButtonLinkRolePropType`
- `LinkTargetPropType` - hier ist zu beachten, dass neben den verschiedenen als String-Literal definierten Optionen auch der `string`-Type eine mögliche Prop ist. Daher ist das Array-Muster hier vermutlich nicht anwendbar, das wäre zu prüfen.
