### ISSUE TITLE
Tree - Keyboard-Shortcuts

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6160]
- [x]  Fehlende Keyboard-Shortcuts implementieren:
    - [x]  home/end
    - [x]  a-z, A-Z
    - [x]  Arrow right auf offener Node: Fokus auf erstes Child
    - [x]  Arrow left: Fokus auf Parent Node (wenn nicht gerade auf geöffneter Node)

Genauere Beschreibung der Keyboard-Navigation ist hier zu finden: https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/

**Comment by AntnSaj** [comment]
Folgendes ist uns beim testen der Tree Komponente aufgefallen:
Beim fokussieren der tree Komponente wechselt der Screenreader nicht in den Formularmodus. Daher funktioniert die Navigation nur mit alt+Pfeiltasten. Beim navigieren mit alt+Pfeiltasten komme ich nicht an alle Elemente von der Tree Komponente und werde oft zurück an den Anfang gesetzt.

Weiterhin ist für den Screenreader Nutzenden nicht zu erkennen auf welcher Ebene sich dieser befindet und welcher Eintrag offen bzw. geschlossen ist.

**Comment by laske185** [comment]
Neues Ticket anlegen, um die oben genannten Punkte zu beheben.
