### ISSUE TITLE
Tree - Aria Attribute

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6164]
Hängt ab von: #6163 (sollte gemeinsam released werden)

links (`a` element) benötigen:
- [x]  role=treeitem
- [x]  aria-expanded
- [x]  aria-owns

(benötigt Anpassungen von link component oder direkte Nutzung von `a`-tag)

- [x] `kol-link` durch `kol-link-wc` ersetzen
- [x] `kol-link-wc` um neue Attribute/Props erweitern (Nicht die öffentliche Shadow Kol-Link!)

**Comment by laske185** [comment]
Es wird kol-link verwendet.

Optionen:
- kol-link erweitern, sodass die aria-Attribute übergeben werden können
- direkt a-Tag verwenden
