### ISSUE TITLE
🐞 Bug: In der Dokumentation ist das Syntax-Highlighting bei Diff unzureichend

### ISSUE THREAD

**Issue by reinerBa** [public-ui/kolibri#6175]
# Fehlermeldung

## In der Dokumentation ist das Syntax-Highlighting uneinheitlich
Siehe:
![image](https://github.com/public-ui/kolibri/assets/4329883/db71735f-9145-47e0-aa47-a948bdc2a166)
Im oberen Code-Beispiel wird zumindest noch etwas blaue Schrift verwendet aber unten gar nicht mehr. Selbst jene von Github erstellen Markdown-Code-Beispiele enthalten mehr Elemente zur Hervorhebung, wie zB. mehrere Schriftfarben 
![image](https://github.com/public-ui/kolibri/assets/4329883/5844bdf5-c57a-40d9-baa3-18bc76e07042)

Das Syntax-Highlighting der Website ist also schlechter als jenes in den Github-MD-Files.

Etwas weiter unten ist dann fast alles rot und zudem völlig anders als in vue-Komponenten 
![image](https://github.com/public-ui/kolibri/assets/4329883/caf55659-fd43-4b26-b65a-44563d526d30)

Deren Notation lauten würde:
``` html
<KolInputText v-model="text" @change="text = v"></KolInputText>
<KolButton :label="Text löschen" @click="text =''"></KolButton>
```
es gibt also gar keine vue-Komponenten sondern vue kann lediglich um die Kolibri-Komponenten herum verwendet werden. 

Dieser optionale Konfigurationsabschnitt müsste überhaupt nicht in der Doku stehen 
![image](https://github.com/public-ui/kolibri/assets/4329883/15ebade3-fc77-4eee-8eb2-f51604d715cb)

## Reproduktion

Die Doku-Website besuchen https://public-ui.github.io/en/docs/get-started/first-steps 

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Browser

**Comment by laske185** [comment]
Hier nur die Umsetzung des Code-Highlightings der diff-Codebeispiele.
