### ISSUE TITLE
🛹 Feature: ToasterService - einzelne Nachrichten schließen

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#6177]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Ich möchte in der Lage sein, über den ToasterService ein einzelnes Toast zu schließen. Dadurch würden sich doppelte "gleiche" Toasts vermeiden lassen. Bisher können nur alle Toasts auf einmal geschlossen werden. 

## Beschreiben Sie die gewünschte Lösung
- `enqueue` nimmt eine ID des Toasts entgegen: `function enqeue(toast: Toast & { id: string }): Promise<() => void>`
- Die ToasterService API um `function close(id: string): void` erweitern. 

So könnte das ganze dann aussehen:

```
toaster.enqeue(props)
toaster.close(id)
```

**Comment by laske185** [comment]
@Chrisdo82 : Die enqueue Funktion gibt einen Promise mit einer Funktion zurück. Diese ist die Close-Funktion zum Schließen des eingereihten Toasts. Über eine eigene Mapping-Funktion kann man gezielt die Toasts wieder schließen.
