### ISSUE TITLE
💡 Hinweis: Placeholder Text in Eingabfelder verschwindet erst bei Tippen

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#6186]
Laut Empfehlung der NNGroup sollte der Placeholder Text erst verschwinden wenn der Nutzer tippt, nicht wenn der Fokus reingesetzt wird. Der Placeholder Text sollte bei Klick und Fokus in das Eingabefeld erhalten bleiben und erst bei Tippen verschwinden.

**Comment by laske185** [comment]
Im nativen Input bleibt der Placeholder stehen: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

**Comment by deleonio** [comment]
Sowohl in `v1` als auch `v2` ist das Ticket nicht korrekt oder fehlerhaft umgesetzt.

- in `v1` ist unused code - https://github.com/public-ui/kolibri/actions/runs/9106581041 (rot)
- in `v2` ist die Implementierung m.E. falsch - https://github.com/public-ui/kolibri/pull/6442/files (?)
