### ISSUE TITLE
🐞 Bug: Designer Funktioniert nicht mehr

### ISSUE THREAD

**Issue by Imnir** [public-ui/kolibri#6198]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Rufe ich den koliBri Designer auf (https://public-ui.github.io/v2/designer/) ist kein Default Theme mehr vorhanden. Es gibt nur noch eine leere IDE Abbildung ohne Code und ich kann auch in der Vergangenheit erstellte Designs nicht mehr hochladen. In der Console lassen sich verschiedene Fehlermeldungen finden. Das Problem habe ich gestern Morgen (11.03 gegen 9 Uhr) das erste mal bemerkt.

## Reproduktion

Einfach den Designer aufrufen https://public-ui.github.io/v2/designer/. 

Es sind keine Inhalte erkennbar und es können auch keine Hochgeladen werden.

## Erwartetes Verhalten
Das Default CSS wird angezeigt und man kann eigene Datein hochladen und weiter bearbeiten.

## Screenshots
![image](https://github.com/public-ui/kolibri/assets/48272294/671719d3-e9f0-46d9-a524-79e2da270b15)

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows
- Browser: Edge
- Version: 118.0.2088.122

**Comment by deleonio** [comment]
Vielen Dank @Imnir,

das scheint mit der zentralen Umstellung des Theme-Registers zu tun zu haben: https://github.com/public-ui/kolibri/issues/6019

Wir schauen uns das an.

Falls Sie ein eigenes Theme verwalten, kann ich Ihnen das neue Theme-Template empfehlen: https://github.com/public-ui/templates/tree/main/kolibri/theme

**Comment by Imnir** [comment]
Vielen Dank für den Hinweis, ich schaue mir das neue Template an. 
Wir haben uns gestern noch gefragt, ob man den Designer irgendwie als lokale Anwendung betreiben kann, sodass wir von Änderungen oder Serverstabilität nicht abhängen würden. Gibt es da bereits eine Möglichkeit?

**Comment by deleonio** [comment]
Wir überlegen gerade, ob wir den Designer abkündigen - da wir einem smarteren Weg für die Pflege der Themes anbieten.

Quasi als separates Git Repo über die IDE mit SCSS-Dateien: https://github.com/public-ui/templates/tree/main/kolibri/theme

**Comment by deleonio** [comment]
See https://github.com/public-ui/kolibri/issues/6232

**Comment by deleonio** [comment]
In der Theming-Engine von `adopted-style-sheets` muss zunächst eine getMethode für das CSS-Auslesen integriert werden.
