### ISSUE TITLE
🐞 Bug: input-checkbox type button: Auswahl mit Leertaste nicht möglich

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6204]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Ist eine input-checkbox vom type button fokussiert, kann sie nur mit Enter aber nicht mit der Leertaste ausgewählt werden.
Beim Drücken der Leertaste wird sie kurz aktiviert und dann direkt wieder deaktiviert.

**Comment by laske185** [comment]
Aktuell geht SPACE, aber nicht ENTER.

**Comment by sdvg** [comment]
Dann passt aus meiner Sicht alles, Enter sollte nicht zum Aktivieren der Checkbox führen.
