### ISSUE TITLE
💡 Hinweis: Deprecation der KolLinkGroup Komponente

### ISSUE THREAD

**Issue by anicyne** [public-ui/kolibri#6210]
Die UI-Komponente KolLinkGroup wird als veraltet (deprecated) markiert und soll in Version 3 nicht mehr verwendet werden. Diese Entscheidung wurde getroffen, um die Wartbarkeit und Konsistenz des UI-Komponenten-Bibliotheks zu verbessern.

### Details

Die Komponente wird durch die Toolbar ersetzt, die eine verbesserte Funktionalität und Flexibilität bietet. Entwickler, die aktuell KolLinkGroup verwenden, sollten ihre Implementierungen entsprechend anpassen und auf die neue Komponente migrieren. Es wird empfohlen, bestehende Verwendungen von KolLinkGroup in den kommenden Versionen sukzessive zu ersetzen.

### ToDo

- [x] Im Code die Komponente als deprecated markieren.
- [x] Dokumentation aktualisieren, um die Deprecation zu reflektieren. (Vermutlich geschieht das automatisch durch stencil)

### Ziel

 Sicherstellung der kontinuierlichen Verbesserung und Vereinheitlichung der UI-Komponenten-Bibliothek.

**Comment by anicyne** [comment]
siehe Ticket [#5669](https://github.com/public-ui/kolibri/issues/5669)

**Comment by sdvg** [comment]
Todos sind alle erfüllt. Zusätzlich wurde die Komponente auch in der Sample App bereits als deprecated gekennzeichnet.
