### ISSUE TITLE
🐞 Toaster: Fehler im Code-Beispiel in der README.md

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6221]
<img width="803" alt="image" src="https://github.com/public-ui/kolibri/assets/6279703/87dc683b-b7bc-4935-b980-4e1dc8db3756">

Hier ist einer schließende geschweifte Klammer zu viel.

Link: https://public-ui.github.io/docs/components/toaster

**Comment by Schollkolade** [comment]
Kann Pull Requesst nicht verlinken. https://github.com/public-ui/public-ui.github.io/pull/208
