### ISSUE TITLE
🐞 Bug: Radiobutton checked im Hochkontrastmodus

### ISSUE THREAD

**Issue by cbraehmig** [public-ui/kolibri#6223]
# Fehlermeldung

## Beschreibung des Fehlers
Wenn ich im Firefox nutzerspezifische Einstellungen nutze, ist die Darstellung eines ausgewählten Radiobutton vom Kontrast nicht ausreichend.

![image](https://github.com/public-ui/kolibri/assets/93573283/060aa0f0-62b4-4136-a9b6-dd63724243da)

Todo:

- [ ] Es wird nur das Default-Theme korrigiert

**Comment by anicyne** [comment]
Ich habe die Änderungen direkt im Component-Style vorgenommen, da dort `!important` verwendet wurde. Diese Änderungen sind für alle Themen wirksam.

**Comment by AntnSaj** [comment]
Kontrast liegt jetzt im Default Theme weit über dem geforderten Mindestwert. A11y Test bestanden
