### ISSUE TITLE
🛠️ Todo: React Sample App Descriptions: Jeweilige Doku-Seite verlinken

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6258]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

## Beschreibung

<img width="1336" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/1eb29be1-a5cb-4e60-ba25-125a80362e27">

Hier einen neuen Link zu der jeweiligen Seite in den Docs hinzufügen.

Beispiel: `https://public-ui.github.io/v2/sample-react/#/abbr/basic` verlinkt auf `https://public-ui.github.io/docs/components/abbr`

**Comment by chrisalat** [comment]
Ich habe festgestellt das die `SampleDescription` in der `v1.7` nur in den Komponenten `InputTextHideErrors` und `TableWithPagination` existiert. Besteht der Task auch daraus die `SampleDescription` generell in jede Komponente einzubinden?
