### ISSUE TITLE
🐞 Bug: Toasts in React 18 werden im StrictMode nach einem Rerender nicht erneut angezeigt

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#6270]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In React 18 werden im StrictMode alle Componenten doppelt gerendert: https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development

Wenn Toasts nun im `useEffect` hook gerendert und mit dem cleanup callback aufgeräumt werden, dann führt dies dazu, dass Toasts beim 2. Render nicht mehr angezeigt werden:

```tsx
  useEffect(() => {
    const toaster = ToasterService.getInstance(document)
    async function createNotification() {
      await toaster.enqueue({ label: error.name, type: 'error', description: error.message })
    }
    void createNotification()

    return () => {
      toaster.closeAll()
    }
  }, [error.message, error.name])
```

## Reproduktion

Siehe StackBlitz. Der Toast ist für ca. 1ms sichtbar und verschwindet dann wieder. 

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-pbtjkp?file=src%2FApp.tsx

## Erwartetes Verhalten
Beim 2. Render wird der Toast ebenfalls wieder angezeigt.

**Comment by Chrisdo82** [comment]
Was auch nicht geht, ist wenn man die Toast Funktionen in dieser Reihenfolge aufruft:

1. `enqueue`
2. `closeAll`
3. `enqueue`

Ich würde erwarten, dass ich nur einen Toast sehe, dies ist aber nicht der Fall. Es werden für einen kurzen Augenblick mehrere Toasts gerendert.

**Comment by sdvg** [comment]
Ich habe die Lösung im PR kommentiert: https://github.com/public-ui/kolibri/pull/6522#issuecomment-2157741786
