### ISSUE TITLE
Split Button: Texte nicht lokalisiert

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6271]
- [x] Text für Dropdown öffnen und schließen in Ressourcen auslagern
- [x] Text: „Optionen anzeigen“ und „Optionen schließen“

**Comment by sdvg** [comment]
Ticket wird bearbeitet von @chrisalat.

Die `translate`-Methode ist hier zu finden: packages/components/src/core/i18n.ts
Implementierungsbeispiele gibt es einige, z.B. packages/components/src/components/avatar/component.tsx
Die Übersetzungen werden hier, für Deutsch und Englisch, eingepflegt:  packages/components/src/locales
