### ISSUE TITLE
📖 Help: Input - wie kann der Opacity Wert bei disabled Elementen überschrieben werden?

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#6281]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

Wir haben die Anforderung, dass der Value bei disabled Input Elementen komplett sichtbar ist, um eine farbliche Unterscheidung zwischen placeholder und value zu haben. Es ist derzeit aber nicht möglich die `opacity` die im Layer `kol-global` gesetzt wird, zu überschreiben, zumindest habe ich keine Möglichkeit gefunden dies zu tun. 

Alle diesbezüglichen Änderungen in der `global.scss` oder `input-text.scss` haben keine Auswirkungen.

<img width="1336" alt="Bildschirmfoto 2024-04-08 um 10 07 40" src="https://github.com/public-ui/kolibri/assets/6606913/51572965-c8df-4afb-88de-5b1433bfedb1">

**Comment by laske185** [comment]
Das Problem wird mit #6278 gelöst. Hier wird das `!important` aus den basisstyles entfernt und man kann die Opacity wieder überschreiben.

**Comment by Chrisdo82** [comment]
Top, danke!

**Comment by laske185** [comment]
Das Problem ist mit 2.1.0 behoben.
