### ISSUE TITLE
💡 Hinweis: Danger Button andere Farbe

### ISSUE THREAD

**Issue by StackOverflowIsBetterThanAnyAI** [public-ui/kolibri#6288]
> **Note**
> - [ X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**

> _Beschreiben Sie möglichst genau, was wir besser machen können._
Hey, ich habe mir eure Button-Komponente angesehen. Dabei ist mir aufgefallen, dass beim Danger-Button das Kontrastverhältnis 6,35:1 beträgt. Das reicht zur Erfüllung des Erfolgskriteriums 1.4.3. Um allerdings zusätzlich das Erfolgskriterium 1.4.6 zu erfüllen, muss das Kontrastverhältnis 7:1 betragen. 

Meines Erachtens nach fehlt dahin nicht allzu viel. Hat die spezifische rote Farbe dieses Danger-Buttons besondere Hintergründe oder wäre es eine Idee wert, einen barrierefreieren Rot-Ton zu wählen, um das Kontrastverhältnis 7:1 zu erreichen, um dadurch zusätzlich das Erfolgskriterium auf der Stufe AAA zu erfüllen.

Mit freundlichen Grüßen

Michael

**Comment by laske185** [comment]
Welches Theme wird verwendet?

**Comment by StackOverflowIsBetterThanAnyAI** [comment]
Ich habe das Default Theme verwendet, wobei die Ergebnisse bei den anderen Themes (bis auf ECL) ähnlich sind.

**Comment by laske185** [comment]
Im Default Theme diese Farbe für Danger setzen: #B4003C. Kontrast zu Weiß ist 7,1:1

Die Beispielthemes der ECL werden nicht angepasst, da wir diese aus dem Styleguide übernehmen und Umsetzungsbeispiele sind. Für eine Korrektur müsste eine Anpassung bei ECL erfolgen. Aktuell wird #DA2131 verwendet. Gibt einen Kontrast von 4,9:1 mit Weiß.

FYI: @emeryro
