### ISSUE TITLE
🛠️ Todo: Input `onInput` Event und Callback: Value übergeben

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6294]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Todo

* `onInput` soll analog zu `onChange` den Value als zweites Parameter übergeben bekommen.
* KolSelect-Optionen können zur Zeit nicht geändert werden. Das soll ebenfalls behoben werden.

**Comment by deleonio** [comment]
Hallo @sdvg, kannst Du das bitte noch für `v1` machen. Danke
