### ISSUE TITLE
🐞 Bug: Tabelle: Sortierte Spalte wird nicht mehr fett angezeigt

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6302]
# Fehlermeldung

Sortierbare Tabellenspalten wurde zuvor hervorgehoben (z.B. durch Fettschrift), wenn die Sortierung aktiv war. Dieses Verhalten soll wiederhergestellt werden.

Soll: 
<img width="687" alt="image" src="https://github.com/public-ui/kolibri/assets/971072/2d2e9849-3f1a-4d02-9b80-affc220a7db1">

Der Bug ist höchstwahrscheinlich in #5839 entstanden.

### To-do:

- [x] Sobald beim Header `aria-sorted` gesetzt ist, soll die `font-weight` auf `bold` gesetzt sein.

**Comment by deleonio** [comment]
@chrisalat 

@laske185 empfiehlt es nicht in das Basis-Styling zu integrieren, sondern nur im Default-Theme. So würden andere Theme bzgl. des Stylings nicht "bevomundet".
