### ISSUE TITLE
🛠️ Todo: Update Snapshot Branchauswahl vereinfachen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6341]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Todo

## Beschreibung

Die Auswahl des Branches beim Update-Snapshots-Script soll vereinfacht werden. Zur Auswahl des Zielbranches soll "Use Workflow from" verwendet werden. Dies erspart einen Skripte-Misch-Masch in den verschiedenen Branches.

Ursprung des Tickets ist dieser Kommentar im [PR 6337](https://github.com/public-ui/kolibri/pull/6337).
Hier hatte ich große Probleme in einem anderen Branch das Script durchlaufen zu lassen, da er immer die Scripte aus dem "Target Branch" Branch verwendet hat, obwohl ich "Use Workflow from" auf den Branch mit dem gefixten Script gesetzt hatte. Aber das "Use Workflow from" bezieht sich nur auf das workflow-File, nicht auf andere Scripte. 

Weiterer Nutzen ist, dass ich den Branch in der Dropdown suchen kann und nicht immer von einer anderen Stelle kopieren muss und evtl. mich vertippe.

## Referenzen

https://github.com/public-ui/kolibri/pull/6337#issuecomment-2072051359

![Image](https://github.com/user-attachments/assets/6669ffe5-bee1-4479-b772-ae9570ffd53b)

Todo:

- [x] Pipeline anpassen durch Ersetzen des 2. Parameter durch die Branchauswahl
- [ ] Dokumentation CONTRIBUTION aktualisieren

**Comment by sdvg** [comment]
Ticket wieder geöffnet, weil der zweite Punkt (Dokumentation aktualisieren) nicht erledigt ist. Der Workflow, wie er gerade beschrieben ist, funktioniert nicht mehr.
