### ISSUE TITLE
Modal: Stacking/Verschachtelung nicht möglich

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6360]
Das äußere Modal schließt sich, wenn ein inneres geöffnet werden soll. Anschließend ist kein Modal sichtbar.

Eine Verschachtelung von `<dialog>`-Elementen (geöffnet mit `showModal`) ist dagegen problemlos möglich, vielleicht reicht das als Alternative.

Todo: Prüfen, ob das Problem noch besteht.

**Comment by laske185** [comment]
Erster Schritt: Prüfen, ob das Problem besteht. Falls ja weitere Schritte besprechen.

**Comment by deleonio** [comment]
Das geht ... hier gibt es auch ein Code-Beispiel.

Muss ich raussuchen...
