### ISSUE TITLE
Vaadin-Adapter benutzen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6365]
Abhängig von: 
- https://github.com/public-ui/kolibri-vaadin/issues/1
- https://github.com/public-ui/kolibri-vaadin/issues/2

### Akteptanzkriterien

- [ ] App erweitern um KoliBri-Komponenten und dabei die Adapter nutzen

**Comment by sdvg** [comment]
@deleonio Status des Tickets: Wenn man `cd adapter && pnpm i && pnpm build` selber ausführt passt alles.

Ich bin gerade noch dabei, diesen Part mit Gradle zu integrieren und das funktioniert noch nicht so ganz. Ich werde meine aktuellen (kaputten) Stand trotzdem schon mal pushen.
