### ISSUE TITLE
💡 Hinweis: Anleitung für Oberflächentest schreiben

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6385]
Dokumentation (Konzept) zum Testen von Anwendungen mit KoliBri-Komponents.

- Referenzprojekt (sample-app)
- Verwendung von Playwright hervorheben

Vorher muss dieses Ticket umgesetzt sein: https://github.com/public-ui/kolibri/issues/6513

**Comment by sdvg** [comment]
Related: https://github.com/public-ui/kolibri/issues/6513

**Comment by laske185** [comment]
Was ist das Ziel?
Wer ist der Leser?

**Comment by laske185** [comment]
Test-Konfiguration in Sample-App ist vorhanden. Anleitung siehe Playwright Docs.
