### ISSUE TITLE
🛠️ Todo: Interne Kunden-Themes das Styling für die neuen Tabellen nachziehen (`>=2.0.15`)

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6386]
Nachdem die neuen Tabellen-Komponenten mit Version 2.0.15 bereitgestellt wurden, muss das Styling nachgezogen werden.

**Comment by deleonio** [comment]
Do not stale

**Comment by laske185** [comment]
Tabellen sind gestylt (2.1.7).
