### ISSUE TITLE
Selbstständige Initialisierung des I18nServices

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6391]
Es wurde gemeldet, dass seit der Version 2.0.9 eine interne Exception in i18n ausgelöst wird:

„In @public-ui/components/dist/kolibri (2.0.8) gibt es die Datei "i18n-8b7a6ddc.js", welche keinen Fehler verursacht.
Ab der Version 2.0.9 wurde diese geändert und aufgeteilt(?) zu "i18n-7a7ff96e.js" und "i18n-0c047df5.js"

index-59e9528b.js:4 Error: i18n not initialized yet
    at getI18nInstance (i18n-0c047df5.js:4:752)
    at translate (i18n-7a7ff96e.js:4:2936)

Diese Exception kommt bei praktisch allen KoliBri-Elementen, welche eigenen Text beinhalten ab 2.0.9ff.“

Ursache für das Verhalten ist, dass der I18nService vor der Nutzung durch eine Komponente initialisiert werden soll. Da die Texte statisch vorhanden sind, kann beim ersten Aufruf der Service sich auch initialisiert werden, wenn bisher nicht durch die registry-Funktion geschehen. Damit kommt es nicht mehr zur Exception.

**Comment by deleonio** [comment]
Ich finde, hier liegt eher eine Falschverwendung vor. Denn wer KoliBri nutzen möchte, muss auch die Register-Methode von KoliBri verwenden.

KoliBri verwendet das Theming System von A11y_ui und erweitert dieses.

Am Ende müssten wir das mit allen services so machen, die Frage, wozu dann eine eigene Register überhaupt?
