### ISSUE TITLE
🐞 Bug: TS-Fehler beim import von @public-ui/themes

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#6396]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Beim `import { BMF } from '@public-ui/themes'` kann TS die types nicht auflösen. Ich bekomme folgenden Fehler: 
```
Could not find a declaration file for module '@public-ui/themes'. 'stackblitz:/node_modules/@public-ui/themes/dist/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/public-ui__themes` if it exists or add a new declaration (.d.ts) file containing `declare module '@public-ui/themes';`
```

## Reproduktion

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-wp7fyh?file=package.json,src%2Freact.main.tsx

Schritte zum Reproduzieren des Verhaltens:
- Gehe zu `react.main.tsx`
- der Fehler ist beim Import sichtbar

## Erwartetes Verhalten
Es gibt keine Fehler beim Import.

**Comment by deleonio** [comment]
@Chrisdo82 Hallo Christian, Ihr könnt jetzt immer den Projekt Ticket Status sehen. Wir haben das Projektboard auch public gemacht.
