### ISSUE TITLE
🐞 Bug: Regression bei onChange-Listener der KolInputRadio-Komponente

### ISSUE THREAD

**Issue by oas** [public-ui/kolibri#6416]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
In unserer Anwendung werden KolInputRadio-Komponenten basierend auf vorherigen Eingaben ein- oder ausgeblendet. Es scheint so, als ob der onChange-Listener der KolInputRadio-Komponente in einigen Fällen nicht mehr korrekt ausgelöst wird. Es handelt sich dabei um eine Regression, in älteren Versionen (bspw. 2.0.9) funktionierte es noch wie erwartet.

## Reproduktion
- Link zu StackBlitz: https://stackblitz.com/edit/kolibri-bug-05-13?file=package.json

Schritte zum Reproduzieren des Verhaltens:
- "toggle"-Button auswählen, anschließend erscheint die KolInputRadio-Komponente
- wie erwartet wird der onChange-Listener bei Auswahl eines Elements korrekt ausgelöst
- "toggle"-Button zwei Mal auswählen, sodass die KolInputRadio-Komponente verschwindet und anschließend wieder auftaucht
- der onChange-Listener wird bei Auswahl eines Elements nicht mehr ausgelöst

## Erwartetes Verhalten
In der Konsole erscheint die Ausgabe "Selected value(s)" auch nach mehrmaliger Ein- / Ausblendung ohne Probleme.

## Screenshots
[Bildschirmaufnahme 2024-05-13 um 14.15.37.webm](https://github.com/public-ui/kolibri/assets/14850833/7ae2fc32-57a5-4341-8c89-8cedb3905cfe)

## Desktop:
- Betriebssystem: macOS
- Browser Chrome
- Version 124.0.6367.158

**Comment by sdvg** [comment]
Der Fehler ist in `develop` anscheinend schon behoben und sollte mit der nächsten KoliBri-Version dann nicht mehr auftauchen.
Ich werde das nach dem nächsten Release noch einmal prüfen und das Ticket dann ggf. schließen.

**Comment by deleonio** [comment]
> Der Fehler ist in `develop` anscheinend schon behoben und sollte mit der nächsten KoliBri-Version dann nicht mehr auftauchen. Ich werde das nach dem nächsten Release noch einmal prüfen und das Ticket dann ggf. schließen.

Prüfe bitte kurz folgende Änderung hinsichtlich dieses Tickets: https://github.com/public-ui/kolibri/commit/4ee20059beb51ca222829202398f3915026bf05a

**Comment by sdvg** [comment]
Ich habe es noch mal nachgestellt und kann bestätigen, dass der Bug auftritt, sobald man das beforePatch wieder herausnimmt 👍

**Comment by sdvg** [comment]
Das Problem ist in der neuesten KoliBri-Version wie erwartet behoben.

Hier ein aktualisierter StackBlitz, indem ich bloß die neuesten KoliBri-Pakete installiert habe: https://stackblitz.com/edit/kolibri-bug-05-13-tvmksd
