### ISSUE TITLE
🐞 Bug: Input File Event Values: String statt FileList

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6426]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Die Event-Callbacks `onInput` und `onChange` von KolInputFile werden zur Zeit beide mit dem Datei-Pfad statt einer FileList als Value-Parameter aufgerufen.

Ist: `'C:\\fakepath\\mein-dokument.pdf'`
Soll: `FileList`

## Reproduktion

- Link zu StackBlitz: https://stackblitz.com/edit/vitejs-vite-1cnydy?file=package.json,src%2FApp.tsx

**Comment by deleonio** [comment]
Hi @sdvg,

wir müssen den Fix auch noch für `v1` nachholen.
