### ISSUE TITLE
🛠️ Todo: Barrierefreiheit bei der Combobox herstellen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6430]
Initiale Implementierung wurde gemerged: https://github.com/public-ui/kolibri/pull/6354

Beim Navigieren der Trefferliste springt der Fokus beim betätigen von "Pfeiltaste nach unten" immer auf den dritten oder zweiten Eintrag in der Liste und beginnt nicht von Vorne (Siehe Screenshot). Fokus sollte von Vorne beginnen.
![image](https://github.com/public-ui/kolibri/assets/126143994/984622e0-4a53-4dd4-a80c-b27d7d4a2d5b)

Nach dem Auswählen von einem Element aus der Trefferliste wird manchmal das Label mit dem neuen Eintrag vorgelesen und manchmal der Dokumententitel. Das vorlesen des Dokumententitels ist hier falsch. Es scheint so, als wäre die Ausgabe beim ersten mal richtig und beim zweiten mal falsch.
Reproduzierbarkeit Ausgabe Titel: deu in das Input Feld eingeben --> Deutschland auswählen (Screenreader Ausgabe siehe nachfolgenden Screenshot)
![image](https://github.com/public-ui/kolibri/assets/126143994/4b6acf66-b383-4e1e-91ae-0aa1122de848)

**Comment by deleonio** [comment]
Dieses Ticket ist nach dem Nachtest nicht gelöst.

**Comment by AntnSaj** [comment]
Ticket wurde nachgetestet. Die beschriebenen Fehler sind Behoben
