### ISSUE TITLE
🐞 Bug: Pagination und Responsiveness verbessern

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6435]
![image](https://github.com/public-ui/kolibri/assets/6279703/0153c2a2-ac1d-4a20-bdcf-53c9475d3fff)

Die Elemente müssen in mehrere Zeilen umbrechen. Bei kleinem Display muss der Text "Einträge von ...", die Buttons und die Seitengrößenauswahl in eine eigene Zeile.

**Comment by laske185** [comment]
In Standard wird bereits vor und nach der Buttonreihe umgebrochen:


![Image](https://github.com/public-ui/kolibri/assets/37439758/d8fce197-c779-4e78-a245-1d637f95e280)

Nachstellen kann ich es nur im BMF Theme.

**Comment by laske185** [comment]
Darstellung ist in Ordnung. Fehler kommen wenn nur durch die Themes.
