### ISSUE TITLE
🛠️ Todo: Issue-Vorlagen überarbeiten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6436]
Zahlreiche Issues sind nicht konkret genug und wir sind gezwungen konkreter Abfragen vorzugeben.

Wir brauchen u.a. Version, Theme, Verwendungart usw.

Können wir hier ein Formular machen?! Oder nur ein md-Vorlage?!

https://github.com/public-ui/.github/tree/main/.github/ISSUE_TEMPLATE

**Comment by chrisalat** [comment]
Ich habe bei großen anderen bekannten repositories mal recherchieret und bin auf die folgenden Lösungsvorschläge gekommen.
Insgesamt sollte erstmal die ganze Sidebar der Issue reports für externe gesperrt werden, damit die CI später die Issues steuert. Außerdem müssen alle bestehenden Templates mit Formularen ersetzt werden.

**Template: KoliBri Bug (Alle relevanten bugs, z.B. fehlerhafte Stencil-Komponenten oder Beispiele)**
-------------------------------
Werden mit `Bug` gelabelt. Neue bzw. bestehende Felder in den Templates hinzufügen/ersetzen, welche größtenteils durch eine CI-Pipeline, automatisch als `Labels` an die Issues gesetzt werden:

**Code Reproduction Example**
Ein Plain-Text-Feld bzw. ein URL-Feld um einen Link zu einem Code-Beispiel einzufügen. Folgende Schritte sollten wir hierfür vornehmen:

1. Ein Code-Template basierend auf dem neusten Version-Branch auf Codesandbox erstellen.
2. Auf der anderen Seite sollte ein öffentlicher Branch von einem Beispiel auf GitHub möglich sein, welches der Author des Issues erstellt. Auch hier basierend auf einem letzten Version-Release.
3. (Optional) Die CI-Pipeline prüft diese Links und schließt das Issue mit einem `Label` -> `invalid link`, falls der Link nicht valide sein sollte. TODO: Recherche wie so eine Action aussehen könnte.

**Version überprüft?** (Pflichtfeld)
Checkbox mit `Ich habe mich vergewissert, dass das Problem in der neuesten KoliBri-Version besteht`. Nur um sicherzustellen, dass der Issue-Author erstmal seine Version prüft bevor dieser ein Issue erstellt.

**Version** (Pflichtfeld)
Ebenfalls ein Plain-Text-Feld für die genaue Versionsnummer. Diese wird vollständig im Issue und abgekürzt als Label in folgendem bestehenden Format `v1`, `v2`, `v3` von der CI gesetzt.

**Theme** (Pflichtfeld)
Ein Select-Feld mit den einzelnen Themes. Diese wird vollständig im Issue und abgekürzt als Label in folgendem Format `BMF`, `ITZ`, etc. von der CI gesetzt.

**Können Sie einordnen, wo der Fehler auftaucht? (Falls bekannt)** 
Eine Select-Komponente, `Nativ (im shadow)`, `React`, `Angular`, etc.

**Name der Komponente** (Pflichtfeld)
Ein Select-Feld mit den einzelnen Komponenten-Namen. Diese wird vollständig im Issue und als Label von der CI gesetzt.

**Welchen Browser bzw. Betriebsystem verwenden Sie? (Falls vorhanden)**
Text-Feld.  In der Beschreibung könnten ein paar Beispiele stehen, wie Firefox, Chrome, iOS 12.4, etc. und ein Link zu einer Dokumentation, wie ich diese bekomme.

**Wie können wir den Fehler reproduzieren?** (Pflichtfeld)
Plain-Textarea, wobei der Issue-Author nochmal im Detail beschreibt, wie dieser zu dem Fehler kam. Beispiel als Platzhalter:
1. Ich habe dies getan
2. Daraufhin folgte das
3. usw.

**Aktuelles vs. Erwartetes Verhalten** (Pflichtfeld)
Plain-Textarea, wobei der Issue-Author nochmal im Detail beschreibt, was derzeitig passiert und was eigentlich passieren sollte.

**Informationen zur Umgebung** (Pflichtfeld)
Eine tolle Idee wär noch unsere jetzige Shell-Scripte zu erweitern, um per Befehl, wie `kolibri info` das lokale Environment wiedergibt und in ein Textarea-Feld gespeichert wird, somit wüssten wir immer unter welchen System der Fehler aufgetreten ist. Das Script gibt z.B. die KoliBri-, Node.js-, pnpm-, npm-Version, etc. wieder. Somit bräuchten wir auch kein Versions-Feld oder andere wie die vorhin genannten nicht mehr.

**Template: KoliBri Docs Report (Fehler oder wünsche für die Dokumentation)**
-------------------------------
Werden mit `docs` gelabelt.

**Welche Aktualisierung würden Sie gerne sehen?** (Pflichtfeld)
Einfaches Textarea-Feld für eine Beschreibung.

**Gibt es irgendeinen Zusammenhang, der uns helfen könnte, es besser zu verstehen?** (Pflichtfeld)
Einfaches Textarea-Feld für eine Beschreibung.

**Gibt es die Doku-Seite bereits? Bitte verlinken Sie sie.**
Einfaches URL-/Text-Feld für eine Beschreibung.

**Template: KoliBri Feature Request**
-------------------------------
Sollte mit Redirect in GitHub-Discussions verschoben werden.

**Template: KoliBri Question**
-------------------------------
Sollte mit Redirect in GitHub-Discussions verschoben werden.

**Template: Hilfreicher Hinweis & Todo erstellen**
-------------------------------
Brauchen wir diese Templates wirklich? Können wahrscheinlich entfernt werden, da die oberen Bereiche bereits alles decken. Alles andere sollte über die Discussions laufen.

Zusätzliches:
-------------------------------
Wir sollten noch einen Schritt weiter gehen um im Zuge der oben genanten Vorschläge, auch die Templates für die Diskussionen überarbeiten. Das Endziel sollte sein, dass nur qualitative Bug-Reports von Anwendern und uns selbst in den Issues landen und wir auf Basis der Diskussionen neue Issues für Feature-Request direkt im Kanban-Board verwalten.

Generelles:
-------------------------------
- Vielleicht sollten wir für alle Templates Englisch als Default nutzen? Falls das problematisch ist, vielleicht Englisch und deutsche Übersetzungen? Wir schrenken die Reichweite mit Deutsch stark ein, da es inzwischen viele Unternehmen mit englisch sprachigen Entwicklungs-Teams gibt.
- Zu jedem Feld sollten Beispiele mit Platzhalter und Beschreibungen geschaffen werden, um das selbe Format sicherzustellen.
- Für das **KoliBri-Team** würde ich so etwas wie eine Whitelist vorschlagen, um die oberen CI-Validierungen zu umgehen. Ansonsten habe ich die Befürchtung das wir uns selber ausbremsen und nur mit Ausarbeitungen von Issues beschäftigt sind. Ein kurzes Meeting scheint mir hier der bessere Weg zu sein. Auch hier sollten alle Issues, welche vom **KoliBri-Team** erstellt werden ein Label mit `created-by: KoliBri-Team` erhalten.
- Zusätzlich sollten wir Templates anlegen, falls die Validierung der CI fehlschlägt. Die CI kommentiert dann automatisch in das Issue und nennt dem Author, worauf dieser achten soll.

**Comment by chrisalat** [comment]
Notiz:

- Validierungen von Feldern werden erstmal nicht umgesetzt
- Titel & Beschreibungen in Englisch und in Klammern Deutsch. Placeholder von Feldern auf Englisch.
