### ISSUE TITLE
🛹 Feature: HTML Template override

### ISSUE THREAD

**Issue by chriskrj** [public-ui/kolibri#6446]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

Wir sind gerade dabei, die Input File Komponente nach unserem Design und Funktionsgrundlage anzupassen. Dafür müssen wir aber das Template (HTML Struktur) der Komponente anpassen. Wir haben neue eigene Properties, die gerendert werden sollen und 1, 2 Darstellungsformen, die nicht mit der HTML-Struktur von euch kompatibel ist. Wie gehen wir am einfachsten / besten vor? Wir würden natürlich gerne die Grundfunktionalität der Kolibri Komponente behalten, ohne komplett eine neue Komponente zu erstellen. 

Wie gehen wir generell mit so einem Problem um? Wenn wir Komponenten von euch in dem Maße umbauen wollen?

**Comment by laske185** [comment]
Gleiches Thema ist bereits im Ticket #6362 adressiert.
