### ISSUE TITLE
🛹 Feature: CreateTheme mit eigenen Komponenten

### ISSUE THREAD

**Issue by chriskrj** [public-ui/kolibri#6447]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Featureanfrage

Wenn wir KERN eigene Komponenten stylen im Theme kommt es zu Kompilierungsfehler in der index.ts. Wie müsste hier die Grundstruktur im monorepo sein, damit das Styling nicht in der Komponente selber platziert werden müsste.

```ts
export const TEST = KoliBri.createTheme('test', {
	GLOBAL: globalCss,
	'KOL-ALERT': alertCss,
	'KERN-ALERT': alertCss
});
``` 

KERN-ALERT, wird natürlich nicht von createTheme aus dem schema erkannt. Wie müssten wir das hier anpassen.

**Comment by chriskrj** [comment]
Grundsätzlich ist es natürlich möglich, dass ich mit meinem eigenen Schema die createTheme Methode anstoße, aber ich wüsste nicht wie ich 2 Themes gleichzeitig aktiv haben kann. Bestenfalls müssten die irgendwie zusammengeführt werden. 

Denke ich zu kompliziert, oder gibt es hier eine Lösung für?

**Comment by laske185** [comment]
Gemäß [Architekturkonzept](https://public-ui.github.io/docs/concepts/architecture#erweitert) ist jede Library autark. D. h. jede Bibliothek hat auch ein eigenes Theme-Paket, welches von deren Schema abhängig ist.

Auf Anwendungsentwicklungsebene werden diese nach Kompositionspattern geladen. Dafür akzeptiert die `bootstrap`-Methode ein Array von Themes und Loader:
https://github.com/public-ui/kolibri/blob/fb79e17f893d38f93be0208d797b4dff87f99f53/packages/components/src/core/bootstrap.ts#L22
