### ISSUE TITLE
💡 Hinweis: migration zu  v.2.0 -> modal width prop

### ISSUE THREAD

**Issue by agnieszkaw61** [public-ui/kolibri#6454]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfreicher Hinweis**

> _Beschreiben Sie möglichst genau, was wir besser machen können._

Wir hatten einen Problem mit Modals nach migration zu v.2.0.14 von 1.7.4. Die Modals waren nicht zu sehen, weil jetzt 'width' prop dafuer noetig ist. Es waere gut es in Migration-Skript hinzuzufuegen.

**Comment by deleonio** [comment]
Bitte das Verhalten in v2 ohne `width` Nachtesten und ggf. Fehler identifizieren.

**Comment by laske185** [comment]
Funktioniert mittlerweile auch ohne Width. Sie ist bereits optional.
