### ISSUE TITLE
📖 Help: KolRadioButton hint

### ISSUE THREAD

**Issue by agnieszkaw61** [public-ui/kolibri#6455]
> **Note**
> - [ ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

> _Beschreiben Sie möglichst genau, wobei wir Ihnen helfen können._

RadioButton-Komponent bietet einen "_hint" Property, aber es erlaubt nur ein string und deshalb es ist dasselbe fur jede Option:

![image](https://github.com/public-ui/kolibri/assets/115545729/0f837804-5139-430d-9671-4a5774c241eb)

ist es moglich dass jede Optione andere hint hat?

**Comment by deleonio** [comment]
Soll:

- [x] Der Hint soll nicht an die Radio-Inputs weitergegeben werden, sondern nur einmal unterhalb der Fehlermeldung sein.
- [x] Einführen der `RadioOptions` mit neuem optionalen `description` diese soll dann als `_hint` an die `kol-input-wc` weitergeben werden.
- [x] Beispiel in der Sample-App dazu machen
- [x] Snapshots aktualisieren

![Image](https://github.com/user-attachments/assets/a2021d67-57d2-477a-8e32-ae98c4a2e8db)

```ts
type Option<T> = {
  label: "Deutschland",
  value:? T,
}

type RadioOption<T> = Option<T> & {
  description:?  string
}
```
