### ISSUE TITLE
🛠️ Todo: Upgrade Jest to latest version `v29`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6459]
We have a problem by using the stencil `v4.18.2` and we should take a look at our jest setup.

Link: https://github.com/ionic-team/stencil/issues/5766

First I tried to upgrade jest (by using stencil `v4.17.1`) to `v29`(breaks), `v28`(breaks) and `v27`(breaks).

FYI: @sdvg

**Comment by laske185** [comment]
stencil geht evtl. Richtung playwrite.
