### ISSUE TITLE
🛠️ Todo: Monorepo für PNPM 9 anpassen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6467]
**Beschreibung:**

Wir müssen unser Monorepo an PNPM 9 anpassen. Dafür müssen die Abhängigkeiten in allen `package.json`-Dateien so geändert werden, dass Abhängigkeiten innerhalb des Monorepos die Versionsspezifikation `"workspace:*"` verwenden.

**Aufgaben:**

1. **PNPM auf Version 9 aktualisieren:**
    - Stelle sicher, dass PNPM auf Version 9 im Repository aktualisiert wird. Das kann bedeuten, Konfigurationsdateien oder Skripte anzupassen, die die PNPM-Version festlegen.

2. **Anpassen der `package.json`-Dateien:**
    - Durchlaufe alle `package.json`-Dateien im Monorepo.
    - Ändere für jede Abhängigkeit, die ein anderes Paket innerhalb des Monorepos ist, die Version zu `"workspace:*"`.

3. **Abhängigkeitsreferenzen aktualisieren:**
    - Stelle sicher, dass alle internen Abhängigkeiten korrekt mit `"workspace:*"` referenziert werden.
    - Überprüfe, dass keine fehlenden oder falschen Abhängigkeitsversionen vorhanden sind.

4. **Setup testen:**
    - Führe `pnpm install` aus, um sicherzustellen, dass alle Abhängigkeiten korrekt verlinkt sind.
    - Führe die Testsuite aus, um sicherzustellen, dass die Änderungen keine bestehenden Funktionen beeinträchtigen.

**Schritte zur Reproduktion:**

1. **Repository klonen:**
    ```sh
    git clone <repository-url>
    cd <repository-name>
    ```

2. **PNPM aktualisieren:**
    ```sh
    pnpm install -g pnpm@9
    ```

3. **Dependencies in den `package.json`-Dateien aktualisieren:**
    - Öffne jede `package.json`-Datei im Monorepo und ändere die Version der internen Abhängigkeiten zu `"workspace:*"`.

4. **Abhängigkeiten installieren:**
    ```sh
    pnpm install
    ```

5. **Tests ausführen:**
    ```sh
    pnpm test
    ```

**Zusätzlicher Kontext:**

- Überprüfe eventuelle PNPM-spezifische Konfigurationen wie `pnpm-workspace.yaml` oder `.npmrc`-Dateien auf Kompatibilität mit PNPM 9.
- Lies die [PNPM 9 Release Notes](https://github.com/pnpm/pnpm/releases) für eventuelle Breaking Changes oder zusätzliche Konfigurationsanforderungen.

**Comment by deleonio** [comment]
Ist für `v1` schon erledigt.
