### ISSUE TITLE
🐞 Bug: KolForm rendert seinen Inhalt nicht richtig

### ISSUE THREAD

**Issue by mello-r** [public-ui/kolibri#6469]
> **Note**
> - [X] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Seit der Version `2.0.9` wird der Inhalt von `KolForm` nicht mehr richtig gerendert. Mit der Version `2.0.8` funktionierte es mit dem gleichen Code.

## Reproduktion

- https://stackblitz.com/edit/vitejs-vite-lcuzen?file=src%2FApp.tsx

## Erwartetes Verhalten
Input Felder innerhalb von `KolForm` sollten gerendert werden.

## Desktop:
- Betriebssystem: Windows
- Browser: Firefox
- Version: 126

**Comment by deleonio** [comment]
Geht leider auch nicht mehr mit `v2.1.1`

**Comment by deleonio** [comment]
Vielen Dank  @mello-r. Mit der Version `2.1.1` geht es wieder: https://stackblitz.com/edit/vitejs-vite-sqqt3b?file=package.json

Bei Gelegenheit, werden wir versuchen herauszufinden, wieso es zeitweise fehlerhaft war.
