### ISSUE TITLE
Toolbar auf Barrierefreiheit prüfen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6475]
Die Toolbar muss auf Barrierefreiheit getestet werden.

https://public-ui.github.io/v2/sample-react/#/toolbar/basic

Todo:

- [ ] Ergebnis des Barrierefreiheitstests hier zusammentragen

**Comment by fohi17** [comment]
Gibt es ein Konzept für starken Zoom? Im aktuellen Beispiel ist es ok. Ich kann mir aber vorstellen, dass das bei einer größeren Toolbar Probleme gibt, wenn sie in der Breite gestaucht wird bspw. bei 400% Zoom. Ich kenne es, dass die Elemente innerhalb der Toolbar dann umbrechen. 
Rest passt für mich, nichts zu meckern.

**Comment by deleonio** [comment]
> Gibt es ein Konzept für starken Zoom? Im aktuellen Beispiel ist es ok. Ich kann mir aber vorstellen, dass das bei einer größeren Toolbar Probleme gibt, wenn sie in der Breite gestaucht wird bspw. bei 400% Zoom. Ich kenne es, dass die Elemente innerhalb der Toolbar dann umbrechen. Rest passt für mich, nichts zu meckern.

Ticket: https://github.com/public-ui/kolibri/issues/6569
