### ISSUE TITLE
Bei allen Themes dürfen `textarea` nur vertikal vergrößerbar sein

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6476]
Die `textarea` soll nur vertikal skalierbar sein, nicht aber horizontal. Die Breite wird immer durch die Umgebung des KolTextarea vorgegeben.

Bitte die CSS Rule im Basis-Theme wiederherstellen.

![image](https://github.com/public-ui/kolibri/assets/6279703/8f0a230f-0844-4acc-9329-d2f24b31fec3)

**Comment by chrisalat** [comment]
- Horizontale und Vertikale Anpassung wird beibehalten
- Stattdessen müssen mehrere Stylings der Textarea angepasst werden um den Border, sowie Focus beizubehalten

**Comment by deleonio** [comment]
@chrisalat Aufgrund des Widerspruchs im Styling, würden wir doch alles beim Styling so belassen und stattdessen die Option für horizontales Skalieren abschalten.

Todos:
- Neues Ticket für v3 anlegen, dass wir da dann ausbauen 
- Warning (Die Option wird in v3 nur noch vertical skalieren (`none | vertical`)) in Watcher für die Option einbauen (`both`, `horizontal`)
- Das Property wird von Enum auf Boolean geändert (Was besagt, dass vertikale Skalieren an oder aus)
- Hinweis in der Dokumentation einbauen (Readme.md)
- `_icon` Prop wie bei anderen nachziehen

FYI: @Chrisdo82, @mello-r. @laske185

**Comment by deleonio** [comment]
Umsetzung hat sich fachlich geändert. Das Ticket ist daher obsolet.
