### ISSUE TITLE
`onChange` in Kombination mit `_value` setzen bei Inputs fehlerhaft

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6481]
### Beschreibung

Beim Behandeln von `_value` und `onChange` kommt es einem Fehler. Wird der Wert eines Input-Feldes (`input-text`) von außen über die `_value`-Property geändert und anschließend vom Benutzer der vorherige Wert wieder hergestellt, kommt es nicht zum `onChange`-Ereignis.

### Reproduktion

https://stackblitz.com/edit/vitejs-vite-d5uyff?file=src%2FApp.tsx

Folgende Schritte sind auszuführen:

1. Eine Zahl im Input eingeben
2. Feld verlassen (Zustand wird korrekt aktualisiert)
3. „Klick“-Button anklicken
    - Zustand und Input werden korrekt auf ‚0‘ gesetzt
4. Zahl aus Schritt 1 eingeben
5. Feld verlassen
    - `onChange` wird nicht ausgeführt und Zustand bleibt bei ‚0‘
6. Sobald ich einen anderen Text eingebe, wird `onChange` wieder ausgeführt.

Problem tritt sowohl in 1.7.x als auch in 2.1.x auf

**Comment by deleonio** [comment]
@anicyne Hi Cyrine, machst Du das bitte auch für v1. Danke
