### ISSUE TITLE
Fehlendes Webpack

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6493]
Aktuell ist in der package json kein Webpack hinterlegt. Dadurch kann lokal nicht gebaut werden.

**Comment by deleonio** [comment]
@laske185 ich habe es unter Windows on scratch nachvollzogen und keine Probleme festgestellt.

```bash
git clone https://github.com/public-ui/kolibri
pnpm clean && pnpm i && pnpm -r build
cd packages/samples/react
pnpm start # works
```
