### ISSUE TITLE
📖 Help: Beispiel vitest mit react-testing-library mit KoliBri

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6510]
Hallo,

ich habe mich der Entwicklung mit Kolibri-Komponenten angeschlossen.
Wir haben bereits viele React-Forms entwickelt, die diese Komponenten verwenden.
Es ist sinnvoll, die Funktionalität der einzelnen React-Komponenten unabhängig voneinander zu testen.

Gibt es Empfehlungen, welche Libraries zum Testen von Forms mit Kolibri-Komponenten verwendet werden können? Das, was die Test-Frameworks aus Kolibri-Komponenten generieren, kann nicht vernünftig getestet werden.
Beispiel vitest mit react-testing-library zum Testen von React-Komponenten rendert solche Sachen wie
<kol-input-number
            _disabled="true"
            _error=""
            _id="verkaufspreisProEinheit_Id"
            _label="OVP Originalware pro Einheit/Euro"
            _min="0"
            _name="verkaufspreisProEinheit"
            _placeholder="Betrag in Euro"
            _required="true"
            _step="0.01"
            _touched="true"
            class="mt-6 md:w-full md:ml-3"
          />
Die so gerenderten Komponenten haben keine Funktionalität und können nicht vernünftig getestet werden.

Es wäre gut, wenn es ein Tutorial geben würde.

**Comment by laske185** [comment]
Teams sollten sich primär auf E2E Tests konzentrieren. Daher sollten wir keine vitest-Beispiele anbieten.
