### ISSUE TITLE
🛠️ Todo: Beispiel mit Schrift-Icons in der Tabelle

### ISSUE THREAD

**Issue by cbraehmig** [public-ui/kolibri#6514]
# Todo

Wir benötigen ein Beispiel einer Tabelle mit Schrifticons, um z. B. die korrekte Invertierung der Icons beim Fokus/Hover zu testen bzw. zu zeigen.

## Beschreibung

Styling bei Hover für Zellen-Komponenten entsprechend "invers" stylen.

![Image](https://github.com/user-attachments/assets/88086ad9-b6f1-4380-800a-5ee47092b067)

![Image](https://github.com/user-attachments/assets/5b8b37ac-13d6-40f2-bbbf-21cc5328eba2)

Mit Icon
![Image](https://github.com/user-attachments/assets/defbebc5-0c00-4371-ae1a-41bc8ca0f65d)

## Todos

- [ ] erweitern wir das Beispiel um Icons an den Schaltern innerhalb der Tabellenzelle rechts
- [ ] eine kurze Beschreibung erstellen, die beschreibt, wie man mittels CSS-Props den Button-Style beeinflussen kann (Readme von TableStateless)

**Comment by deleonio** [comment]
Eine mögliche Lösung hier für ist die Nutzung von `CSS-Properties`. Hierbei wird die Schriftfarbe bspw. eines KolLinks durch eine Property gesteuert und im Fallback ist es die Standardschriftfarbe. Wir das Property beim Hover in der Tabellenzeile aber auf eine andere Farbe gesetzt, dann bekommt der Link "plötzlich" eine andere Schriftfarbe.

**Comment by Makko74** [comment]
Wäre dies die Lösung?

wobei container-area ein beispiel für die Table wäre und die input-test irgendeine row


```html
<section>
  <style>
      :root {
          --color-gray: #333;
          --color-white: white;
      }
  </style>
  <div>
      <p style="background-color: var(--background-color); color: var(--foreground-color);">Hello, <span>Friend</span>!</p>                            
  </div>
  <container-area  >
      <template shadowroot="open">
          <style>
               input-test:hover {
                  --foreground-color: var(--color-white);
                  --background-color: var(--color-gray);
              }
          </style>
          <input-test >
              <template shadowroot="open">
                  <div style="background-color: var(--background-color, --color-white); color: var(--foreground-color, --color-gray);"><slot ></slot></div>
              </template>
              <h1>Greetings 1</h1>
          </input-test>
      </template>
  </container-area>
</section>
```
