### ISSUE TITLE
Formik Vorlage um Validierung erweitern

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6529]
Benötigt: https://github.com/public-ui/kolibri/issues/6528

- [x] Eine Feldvalidierung (on-blur) soll mit `yup`, `zod` oder `valibot` erstellt werden 
- [x] Frameworks vergleichen und kommunizieren
    - Anlaufpunkt: https://npmtrends.com/yup-vs-zod
    - zod scheint populärer zu sein
- [x] Eine Form-Validierung (on-submit)
    - Es reicht, wenn nur einige Felder (3-5) validiert werden.

**Comment by sdvg** [comment]
https://npmtrends.com/valibot-vs-yup-vs-zod

* Zod und Yup sind sehr viel populärer als Valibot.
* Die Bundle-Größen unterscheiden sich (in absoluten Zahlen) eher geringfügig. Durch den modularen Aufbau von Valibot könnte hier aber mehr eingespart werden.
* [Yup kann mit Formik](https://formik.org/docs/guides/validation) direkt genutzt werden, Zod benötigt zusätzlich einen [Adapter](https://github.com/robertLichtnow/zod-formik-adapter) ([3K](https://bundlephobia.com/package/zod-formik-adapter@1.3.0)).
* Valibot lässt sich mit Formik sicherlich nutzen, allerdings habe ich hier keine Beispiele oder fertige Adapter auf das Formik [validationSchema](https://formik.org/docs/api/formik#validationschema-schema----schema) gefunden.

Ergebnis: Yup ist wohl am einfachsten mit Formik zu verwenden, da kein Adapter notwendig ist. Zod ist eine gute Alternative, die sich ebenfalls leicht integrieren lässt. Wenn die Bundle-Size sehr wichtig ist oder ein modularerer Ansatz gewünscht ist sollte man sich Valibot näher anschauen.
