### ISSUE TITLE
Doc: Synonyme für die Komponenten mit in die Readme's aufnehmen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6539]
Hier kann man abschauen: https://open-ui.org/research/component-matrix/

- Komponentenübersicht: Badges mit den Synonymen
- In der Readme ganz am Anfang als Einzeiler einfügen.

**Comment by sdvg** [comment]
Wieder geöffnet für zweites PR: https://github.com/public-ui/public-ui.github.io/pull/220
