### ISSUE TITLE
🐞 Bug: Error: `Toaster: Call KoliBri bootstrap/register method first.`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6545]
### Can you categorise where the error occurs?
React

### How to reproduce issue?
1.

### Current vs. Expected:
Ich habe auch gerade Schwierigkeiten mit dem Tag Transform. Alles funktioniert, wenn ich sowohl die Frontend-Lib Lokal teste als auch lokal eingebaut in einem Microfrontend. Sobald ich aber das Microfrontend übers Portal lade und das Microfrontend geladen wird, welches wiederum ja selbst eine WebComponent ist, bekomme ich diesen Fehler: „Error: Toaster: Call KoliBri bootstrap/register method first.“. Habt ihr eine Idee, woran das liegen könnte? (siehe Screenshot)

![image](https://github.com/public-ui/kolibri/assets/6279703/85b1bcde-e70f-470d-9f80-aef7eb8b90e7)

### Environment informations:
```bash ? ```

**Comment by Chrisdo82** [comment]
Hier ist ein Reproduktionsbeispiel: https://github.com/Chrisdo82/lab-micro-frontends/tree/buggy-with-toasts

**Comment by sdvg** [comment]
Hallo @Chrisdo82!

Danke für das Reproduktionsbeispiel.

Das Problem ist, dass `module-v2` nicht die richtige KoliBri bzw. ToastService Instanz (die von `kolibri-v2-provider`) verwendet. Stattdessen wurde KoliBri ein weiteres mal mit gebundelt.

Ich habe das hier einmal behoben: https://github.com/Chrisdo82/lab-micro-frontends/pull/1/files
Bei dieser Lösung exportiert `kolibri-v2-provider` seine KoliBri-Instanz, so dass die Module sie (z.B. für den ToastService) verwenden können, wo notwendig, ohne KoliBri ein weiteres Mal installieren zu müssen.

**Comment by Chrisdo82** [comment]
Hi @sdvg, das Beispiel war wann leider doch nicht ganz so repräsentativ, bzw. gab es doch einige Unterschiede zu dem was wir machen. Wir haben jetzt aber festgestellt, dass wir diesen Fehler nur erhalten, wenn wir das Bundle als IIFE erstellen. Mit ESM sind die Probleme verschwunden.

Eine Sache ist uns dann aber doch noch aufgefallen. Wir bekommen initial beim Laden von KoliBri, bzw. vielmehr beim Laden des ToastService dieses Toast angezeigt, welches definitiv nicht auf unserer Seite gesetzt wird:

![Bildschirmfoto 2024-06-24 um 09 38 03](https://github.com/public-ui/kolibri/assets/6606913/9b7ceeb9-762e-4e79-b6a6-f8b900392f89)

**Comment by sdvg** [comment]
> Eine Sache ist uns dann aber doch noch aufgefallen. Wir bekommen initial beim Laden von KoliBri, bzw. vielmehr beim Laden des ToastService dieses Toast angezeigt, welches definitiv nicht auf unserer Seite gesetzt wird:

Das kann ich so (zum Glück) nicht nachvollziehen. Wir haben diese Test-Message an zwei Stellen definiert: In der Stencil-Testumgebung und in der React Sample App. Könnte es sein, dass ihr eines von beiden versehentlich importiert habt? Könntest du vielleicht einmal (z.B. mit einem Debugger) genauer nachschauen, woher die Meldung bei euch kommt?

https://github.com/search?q=repo%3Apublic-ui%2Fkolibri+Toasty&type=code

**Comment by Chrisdo82** [comment]
Also wir haben überall nur imports von `@public-ui/react` oder `@public-ui/components` verwendet. Was ich aber festgestellt habe, ist dass der betreffende Code mit in den node_modules landet:

![Bildschirmfoto 2024-06-24 um 10 16 12](https://github.com/public-ui/kolibri/assets/6606913/4ee03c26-987f-4d88-aba6-fb18f0c47de9)

Warum dies am Ende bei uns mit im Bundle landet, versuche ich noch rauszufinden

**Comment by Chrisdo82** [comment]
Noch eine Anmerkung zu meinem vorherigen Kommentar, ist es sinnvoll dass der Testcode von euch mit im Bundle landet? Das hat da doch eigentlich gar nichts zu suchen.

**Comment by sdvg** [comment]
> Noch eine Anmerkung zu meinem vorherigen Kommentar, ist es sinnvoll dass der Testcode von euch mit im Bundle landet? Das hat da doch eigentlich gar nichts zu suchen.

Das hängt ein bisschen damit zusammen, wie Stencil arbeitet bzw. wie wir die integrierte Entwicklungsumgebung früher genutzt haben.
Ist aber völlig richtig und eigentlich brauchen wir diesen Test-Code auch nicht mehr. Wird gelöscht 👍

**Comment by sdvg** [comment]
@Chrisdo82 
In der neuesten Version ([2.1.3](https://github.com/public-ui/kolibri/releases/tag/2.1.3)) ist der Code jetzt ganz entfernt, sollte also keine Probleme mehr machen.

**Comment by Chrisdo82** [comment]
Hat funktioniert, danke @sdvg . Ticket kann geschlossen werden
