### ISSUE TITLE
🐞 Bug: `_error` und `_msg` funktioniert an allen Formularfelder nicht wie gewünscht

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6552]
### Link to the code that reproduces this issue:
https://stackblitz.com/edit/vitejs-vite-ymqgk6?file=src%2FApp.tsx

### Can you categorise where the error occurs?
Web Components

### Which browser or operating system do you used to test KoliBri?
Chrome

### How to reproduce issue?
See sample on Stackblitz.

### Current vs. Expected:
Error is displayed as soon as _error, _msg is set. On the other hand, errors should only be displayed as soon as the field is exited or `_touched` is set. It is currently not possible to reset error messages.

### Environment informations:
```bash - ```

**Comment by laske185** [comment]
Todo:

- Verhalten für `_error` wiederherstellen (bleibt deprecated)
- `_touched` wird deprecated und in v3 entfernt (Hinweis geben: Umstellung auf `_msg`)

**Comment by sdvg** [comment]
@deleonio Angepasster Stackblitz, bei dem onChange nicht das State-Update von onInput überschreibt: https://stackblitz.com/edit/vitejs-vite-ndcdbq?file=src%2FApp.tsx

**Comment by deleonio** [comment]
Danke @sdvg - https://stackblitz.com/edit/vitejs-vite-kj1f1l?file=src%2FApp.tsx - mein Fehler waren die fehlenden `_` bei den Properties für `_msg`.
