### ISSUE TITLE
🐞 Bug: Combobox: Fehlerhafte Events

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6565]
* Der `change`-Callback wird nur aufgerufen, wenn eine freie Eingabe erfolgt ist, nicht wenn einer der Vorschläge ausgewählt wurde.
* Das `input`-Event fehlt. Es sollte ausgeführt werden:
  * Wenn eine Eingabe im Eingabefeld erfolgt (analog KolInputTextarea bzw. dem nativen `input`-Event auf dem `<input>`.
  * Wenn ein Vorschlag ausgewählt wurde (_vor_ dem change-Event).
* Zwecks Testbarkeit sollte die Combobox in den Beispiel-Scenarios `inputs-get-value` und `static-form` hinzugefügt werden.

**Comment by chrisalat** [comment]
Zusätzlich wurde noch ein Fix eingefügt, damit die Combobox bei ENTER-Press das Dropdown wieder schließt.
Soll das Dropdown immer geschlossen werden, wenn das Feld (inkl. Dropdown) den Fokus verliert?
