### ISSUE TITLE
Investigation/Todo: Release-Pipeline umsetzen/optimieren

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6566]
Aktuell wird die Versionsnummer manuell gesetzt und anschließend auf den Release-Branches die [Public-Pipeline](https://github.com/public-ui/kolibri/actions/workflows/publish.yml) ausgeführt.

- Für alle Versionen nutzbar (durch Auswahl des `release`-Branch)
- Versionsnummer vergeben (patch, minor, major), Versionsnummer in ganzen Projekt entsprechend anpassen, auch Texte
- Label vergeben (dev, next, latest)
- Die Pipeline liegt in jedem `release`-Branch und commited die Versionsnummer nach dem Durchlauf zurück.
- Publish ausführen

**Comment by deleonio** [comment]
Wir müssen noch die Branch-Protection überwinden: https://github.com/public-ui/kolibri/actions/runs/9950836221/job/27489410405

**Comment by sdvg** [comment]
Mögliche Lösung, ohne das wir den Workflow auf PRs umstellen müssen: https://stackoverflow.com/a/72515781

Hierfür benötigen wir unsere GitHub App, die in [#5993](https://github.com/public-ui/kolibri/issues/5993) erstellt wird.
