### ISSUE TITLE
Checkbox-Auswahl bei Tabellen mit Pfeiltasten Fokus wechseln/verschieben

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6567]
Die Steuerung mit Pfeiltasten oben/unten darf nur gehen, wenn der Fokus genau auf der internen Checkboxen/Radio-Buttons steht. Dann wechselte der Fokus zur/m vorhergehenden oder nächsten Checkbox/Radio-Button.

Zusatz: Wenn die erste Checkbox fokussiert ist und die Pfeiltaste nach oben gedrückt wird, dann wird die letzte Checkbox fokussiert. Und umgekehrt.

Input: https://github.com/public-ui/kolibri/issues/6431#issuecomment-2146878246

---

### Ergänzung

Wir möchten sicherstellen, dass die Pfeiltasten-Navigation in einer Tabelle nur zwischen Checkboxen funktioniert, wenn sich der Fokus bereits auf einer Checkbox befindet. Dazu soll ein weiteres interaktives Element (z.B. ein Button oder ein Textfeld) in den Tabellenzeilen hinzugefügt werden, um zu überprüfen, dass die Pfeiltasten-Navigation nur bei den Checkboxen greift und nicht bei anderen interaktiven Elementen.

Anforderung:

- Bei allen Beispielen: z.B. https://66e025f9fd50be009788ebdd--kolibri-public-ui.netlify.app/#/table/stateful-with-selection
- Ein weiteres interaktives Element in den Tabellenzeilen einfügen.
- Die Pfeiltasten-Navigation soll nur funktionieren, wenn der Fokus auf einer Checkbox liegt.
- Bei allen anderen interaktiven Elementen (z.B. dem neuen Element) darf die Pfeiltasten-Navigation nicht zu den Checkboxen führen.

**Comment by anicyne** [comment]
Bitte warten, bis [#6617](https://github.com/public-ui/kolibri/issues/6617) abgeschlossen ist.

**Comment by deleonio** [comment]
@anicyne Danke ich habe das ausprobiert und es funktioniert wunderbar. Kannst du bitte noch bei den Beispielen ein in jeder Zeile ein Link oder ein Button einfügen. Mehr Details siehe Ticketbeschreibung oben "Ergänzung"
