### ISSUE TITLE
Fehlermeldungen lassen sich nicht zurücksetzen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6579]
Reproduzierbar in unserer Sample-App - AppountmentForm Adresseeingabe: https://public-ui.github.io/v2/sample-react/#/scenarios/appointment-form

Fixed vielleicht auch das: https://public-ui.github.io/v2/sample-react/#/scenarios/appointment-form

**Comment by sdvg** [comment]
Duplikat von #6580
