### ISSUE TITLE
Feature für Pagination `_label` für eindeutige Bezeichnung einer Nav-Struktur

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6584]
Wenn ich mehrere Paginationen auf einer Seite habe, dann möchte ich diese unterschiedlich benennen können. Hier könnte man auch, wie bei der Nav, Breadcrump, eine übergreifende unique Liste führen.

- [ ] Sicherstellen, dass jede Nav auf der Seite ein anderes Label hat
- [ ] Warnung ausgeben, wenn ein Label doppelt benutzt wurde

*Umsetzunghinweis*: Bei der Nav wurde dies bereits mit einem Service realisiert.

**Comment by laske185** [comment]
Bereits umgesetzt.
