### ISSUE TITLE
🐞 Bug: Textarea not scrollable

### ISSUE THREAD

**Issue by pbedat** [public-ui/kolibri#6592]
### Link to the code that reproduces this issue:
https://stackblitz.com/edit/vitejs-vite-jlc15j?file=src%2FApp.tsx

### Can you categorise where the error occurs?
React

### Which browser or operating system do you used to test KoliBri?
Firefox

### How to reproduce issue?
Resize the textarea to the point where the content overflows vertically: ![image](https://github.com/public-ui/kolibri/assets/1275613/970987d4-e749-4295-984e-2b79267fbd06)

### Current vs. Expected:
The Textarea is not scrollable, but it should be. See https://github.com/public-ui/kolibri/blob/916381c8534163208a11aa9551ac2f72dd98ac66/packages/components/src/components/textarea/shadow.tsx#L33

### Environment informations:
```bash {
 "Operating System": {
 "platform": "linux",
 "arch": "x64",
 "version": "5.0 (X11)"
 },
 "Binaries": {
 "node": "v18.20.3",
 "npm": "10.2.3",
 "pnpm": "8.15.6",
 "yarn": "1.22.19"
 },
 "Relevant Packages": {
 "@public-ui/components": "^2",
 "@public-ui/react": "^2",
 "@public-ui/theme-default": "^2",
 "react": "^18",
 "react-dom": "^18",
 "typescript": "^5"
 }
 } ```

**Comment by deleonio** [comment]
@anicyne Bitte Ticket raussuchen, wo wir das von ein paar Sprint gemacht hatten und kommentieren, dass es in der aktuellen Version funktioniert in 1 und 2.

**Comment by anicyne** [comment]
Bug wird im #6147 behoben. Es Funktioniert jetzt in der neuen Version.
