### ISSUE TITLE
🐞 Bug: AssociatedInputController funktioniert nicht mit Combobox

### ISSUE THREAD

**Issue by chrisalat** [public-ui/kolibri#6600]
### Can you categorise where the error occurs?
Native

### How to reproduce issue?
1. Gehe zum Scenario `static-form` in den samples
 2. Wähle in der `Combobox` eine Option aus
 3. Sende das Formular ab

### Current vs. Expected:
Derzeitig wird kein Query-Paramater für die `Combobox` gesetzt. Normalerweise sollte jetzt ein Query Paramater gesetzt und der Wert unter **"Submitted data"** aufgelistet werden.

**Comment by sdvg** [comment]
Bereits gelöst in: https://github.com/public-ui/kolibri/pull/6621/files
