### ISSUE TITLE
Im Produktionsmodus sollen nur Fehler-Ausgaben ausgegeben werden

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6609]
Die log.error Ausgaben sollen weiterhin auch im Prod ausgegeben werden. Alles kleiner gleich Warning soll nicht ausgegeben werden.

Konfiguration über die `bootstrap` Funktion. Die Options werden erweitert um Environment mit den möglichen Werten `DEV` und `PROD`. Default ist `PROD`. 

Wenn das Environment auf `PROD` gesetzt ist, werden die beschriebenen Logausgaben abgeschaltet.

**Comment by chrisalat** [comment]
@deleonio du hast gemeint, das wir hierfür bereits eine Funktion besitzen oder?
