### ISSUE TITLE
KoliBriTableSelection: Das Feld keyPropertyName auch für Datenattribute konfigurierbar machen, die nicht im Tabellenkopf stehen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6613]
Discussed in https://github.com/public-ui/kolibri/discussions/6610
Originally posted by ChrPtt July 9, 2024

### Goals
Derzeit können nur Datenattribute, die auch im Tabellenkopf verwendet werden, für das Feld keyPropertyName in der Konfiguration des Selection-Modus verwendet werden.
Dies sollte auf alle Attribute der Tabellendaten ausgeweitet werden.

```ts
const selection: KoliBriTableSelection = {
	/* ... */
	/* Hier funktionieren nur Keys die auch im Header verwendet werden. */
	keyPropertyName: 'id',
};

```

### Background
Oft gibt es eine technische ID, die eine Zeile als eindeutig identifiziert, aber dem Benutzer nicht angezeigt wird. Daher ist es notwendig, Attribute der Tabellendaten, die nicht im Tabellenkopf enthalten sind, als keyPropertyName Eigenschaft auswählbar zu machen, auf die sich die selectedKeys beziehen.

### Proposal
keyPropertyName auf alle Attribute der Tabellendaten erweitern.

**Comment by deleonio** [comment]
Duplikat: https://github.com/public-ui/kolibri/issues/6682
