### ISSUE TITLE
Tabellen-Spalte mit Icons und Komponenten in Zelle bei dunklem Hover

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6616]
Wenn der Hover-Effekt in der Tabelle der Zeile einen dunklen Hintergund setzt, muss der Inhalt der Zelle farblich invertiert werden. Beispielweise muss der Text, Icons oder der Rahmen eines Textfeldes weiß werden.

JIRA 552

Hinweis: Konzept mit CSS-Properties berücksichtigen - für Hover und Styling von Sub-Components: #6514

Es soll für folgende Komponenten umgesetzt werden:
- KolButton
- KolButtonLink
- KolLink
- KolLinkButton

Festlegung: Weitere Komponenten werden erst bei Bedarf umgesetzt. Hierfür werden dann neue Issues erstellt.

### Beispiel

So kann die Farbe an den Komponenten manipuliert werden: CSS-Variablen mit Fallback.

```html
<section>
  <style>
      :root {
          --color-gray: #333;
          --color-white: white;
      }
  </style>
  <div>
      <p style="background-color: var(--background-color); color: var(--foreground-color);">Hello, <span>Friend</span>!</p>                            
  </div>
  <container-area  >
      <template shadowroot="open">
          <style>
               input-test:hover {
                  --foreground-color: var(--color-white);
                  --background-color: var(--color-gray);
              }
          </style>
          <input-test >
              <template shadowroot="open">
                  <div style="background-color: var(--background-color, --color-white); color: var(--foreground-color, --color-gray);"><slot ></slot></div>
              </template>
              <h1>Greetings 1</h1>
          </input-test>
      </template>
  </container-area>
</section>
```

**Comment by laske185** [comment]
Die aktuelle Änderung beinhaltet ein Beispiel.
Muss am Theme selbst noch umgesetzt werden.

**Comment by sdvg** [comment]
Die Vorbreitung ([neues Sample](https://develop--kolibri-public-ui.netlify.app/#/table/interactive-child-elements)) ist erledigt. Die Änderung am internen Theme steht noch aus.

**Comment by laske185** [comment]
Bitte auch im Hochkontrastmodus prüfen.

**Comment by laske185** [comment]
Benötigt #6923
