### ISSUE TITLE
Tabelle mit Selektion von nur einer Zeile

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6617]
- Selektion von Tabelle-Zeilen soll entweder einfach oder mehrfach (`multiple`-Option) möglich sein (`render`-Funktion)
- Auswahl-Schalter (Checkbox oder Radio-Button) nativen `input`-Tag (`name`-Attribute, `type`) + `kol-tooltip` umgesetzt
- `kol-input-checkbox` wird ersetzt
- Handling der Auswahl in ein Array von 0, 1 oder n-vielen Items
- `ReturnType getSelection`: `null | Item | Item[]`

```js
function getSelection() {
  if(radio) {
    return selection[0] | null
  ...

```

**Comment by deleonio** [comment]
@anicyne, @chrisalat ... sprecht mal, ob nicht Chris das Ticket machen sollte. Er hat ja gerade eben die Selektion mit Checkboxen gemacht.
