### ISSUE TITLE
abbr - Langform in Klammern hinter Abkürzung

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6627]
Akzeptanzkriterien:

- Tooltip wird entfernt
- Label wird optional
- Label wird in Klammer hinter das abbr-Tag geschrieben
- Umsetzung analog https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

---

### Link to the code that reproduces this issue:
Kolibri Version 2.1.3

### Which browser or operating system do you used to test KoliBri?
Firefox, Chrome

### How to reproduce issue?
Auslesen des aria-labels der Abkürzungs-Bedienelemente

### Current vs. Expected:
Aktuelles Verhalten: Der zugängliche Name "zum Beispiel" enthält nicht den sichtbaren Text "z.B". Das kann für Menschen, die Spracheingabe verwenden zu Schwierigkeiten führen, da sie das Element ohne Kenntnis der ausgeschriebenen Form nicht direkt ansteuern können. Erwartetes Verhalten: Es reicht aus, wenn der sichtbare Text Bestandteil des zugänglichen Namens ist, also beispielsweise "z.B. zum Beispiel". natürlich sollte im Anschluss die Sprachausgabe mit dem Screenreader nochmal getestet werden.

### Environment informations:
```bash Kolibri Version 2.1.3
 Build: f30a4d4
 at 2024-06-28T04:09:59.035Z Windows 10, Firefox, Chrome ```

**Comment by laske185** [comment]
Akzeptanzkriterien:
 
- Tooltip wird entfernt
- Label wird optional
- Label wird in Klammer hinter das `abbr`-Tag geschrieben

Umsetzung analog https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
