### ISSUE TITLE
🐞 Bug: 11.7 - accordion: Überlappungen bei benutzerdefinierter Schriftart / Schriftgröße

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6629]
### Link to the code that reproduces this issue:
Kolibri Version 2.1.3

### Which browser or operating system do you used to test KoliBri?
Firefox, Chrome

### How to reproduce issue?
Chrome: 
 ![image](https://github.com/user-attachments/assets/e9326b00-d803-46ce-a255-74bcca41d8b6) 
Firefox: 
 ![image](https://github.com/user-attachments/assets/fd5a2404-f43a-46e8-aeae-ab24d0b17493)

### Current vs. Expected:
Firefox: 
 ![image](https://github.com/user-attachments/assets/e8d8b83f-0e8e-4a38-9687-727df52e55d3) 
Chrome (nur im Handout): 
 ![image](https://github.com/user-attachments/assets/dc80bcb1-8472-4422-af9d-c67bebc4b07d)
 Erwartetes Ergebnisse: Die Inhalte sollten ohne Überlappungen umbrechen!

### Environment informations:
```bash Kolibri Version 2.1.3
 Build: f30a4d4
 at 2024-06-28T04:09:59.035Z Windows 10
 Firefox: 
 Chrome: 126.0.6478.57 (Offizieller Build) (64-Bit)
 115.12.0esr (64-Bit) ```

**Comment by laske185** [comment]
Todo:

- Prüfen und gegebenenfalls Anpassungen vornehmen
- Auf A11y-Test stellen

**Comment by Makko74** [comment]
Überlappungen wurde mit #6838  bereits behoben

**Comment by AntnSaj** [comment]
Überlappung in Firefox wurde Behoben. Überlappung in Chrome wurde nicht behoben (Siehe Screenshot).
![Image](https://github.com/user-attachments/assets/0bb24e29-c33c-4881-8a1b-a78a5b99ef25)

**Comment by Roman-Use** [comment]
Das Problem wurde behoben. Good job! 
So sieht es nun korrekt aus:
![accordion_headlines_11_7](https://github.com/user-attachments/assets/aeef73cd-2279-468d-bb74-0f8747494325)
![accordion_basic_11_7](https://github.com/user-attachments/assets/e37d425f-eef7-4b32-810d-19e4c0291c2a)
