### ISSUE TITLE
🐞 Bug: 9.1.1.1 - alert: Inkonsistentes Verhalten der Alternativtexte der Benachrichtigungssymbole

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6631]
### Verify current release

- [X] I verified that the issue exists in the latest KoliBri v1 or v2 release

### Link to the code that reproduces this issue

Kolibri Version 2.1.3

### Which theme(s) are affected?

Default

### Which browser or operating system do you used to test KoliBri? (If available)

Firefox, Chrome

### Which component/area(s) are affected? (Select all that apply)

Alert

### To Reproduce

Alerts durch den Screenreader wiedergeben lassen. 
Betrifft Basic, card-msg und html.

### Current vs. Expected behavior

Das Verhalten von Meldungen mit Überschrift und ohne Überschrift ist unterschiedlich. Bei Meldungen ohne Überschrift wird das Symbol mit einem Alternativtext versehen (Nachricht, Hinweis, Erfolg, Fehler, Warnung) Mit Überschrift ist das Element vor dem Screenreader versteckt. Das Verhalten sollte konsistent sein. 

![image](https://github.com/user-attachments/assets/f4cc318f-1f77-4027-bfe0-155d4bbd4d65)
![image](https://github.com/user-attachments/assets/5ceec180-a574-40b7-a0f9-5b24f5bb2f41)

Empfehlung: Das Icon immer mit einem Alternativtext versehen, dann muss man nicht sicherstellen, dass die Nachrichtenart (Hinweis, Warnung, Erfolg, Fehler, etc)  im Nachrichtentext benannt wird. 

### Provide environment information

```bash
Kolibri Version 2.1.3
Build: f30a4d4 at 2024-06-28T04:09:59.035Z Windows 10
Firefox: 115.12.0esr (64-Bit)
Chrome: 126.0.6478.57 (Offizieller Build) (64-Bit)
```

**Comment by laske185** [comment]
Das Icon soll immer vorgelesen werden.

Es muss in der Doku darauf hingewiesen werden, dass das Icon mit "Fehler", "Warnung", ... auch vorgelesen wird. Der Titel des Alerts sollte also nicht mit dem Alerttyp beginnen. Dies würde zu einem doppelten Vorlesen des Alert-Typs führen.

Richtig: Label = "Füllen SIe das Feld aus" -> Ausgabe: Fehler - Füllen SIe das Feld aus
Falsch: Label = "Fehler: Füllen Sie das Feld aus." -> Ausgabe: Fehler - Fehler: Füllen SIe das Feld aus

Muss im Changelog ersichtlich sein -> PR muss entsprechend betitelt sein!

**Comment by sdvg** [comment]
Branch ist bereits gemerged, kann also direkt auf dem `develop`-Deployment getestet werden: https://develop--kolibri-public-ui.netlify.app/

**Comment by Roman-Use** [comment]
Wurde auf der verlinkten dev-Umgebung getestet und korrekt umgesetzt.

**Comment by sdvg** [comment]
@Roman-Use Danke!
