### ISSUE TITLE
📖 Docs: 9.1.3.1a - alert: Optimierung der Überschriftenstruktur im Beispiel

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6637]
### What is the update you wish to see?

Kolibri Version 2.1.3
Aktuell sind alle Nachrichten H1, alle Fehler H2, alle Hinweise H3, alle Erfolge H4 und alle Warnungen H5. Das ist sicher nur zur Demonstatrion was möglich ist, sollte aber entsprechend erklärt werden, damit es nicht kopiert wird. 

![image](https://github.com/user-attachments/assets/bb245ee6-7902-4547-80e1-d9df041995d1)

### Is there any context that might help us understand?

Man könnte die Überschriftenstruktur in den Überschriften darstellen "Das ist die Überschrift Ebene X des Alert".

**Comment by laske185** [comment]
Beschreibung der beiden Alert-Szenarien (card und msg) ergänzen: Das ist repräsentatives Beispiel zur Demonstration der Überschriften-Ebenen in den Alerts.

Überschrift wie Empfohlen anpassen in: "Das ist die Überschrift Ebene X des Alert".


Auf englisch, da die Beispiele bereits übersetzt wurden.
