### ISSUE TITLE
🐞 Bug: Bug: 11.7 - Breadcrumb: Inhalte überlappen bei benutzerdefinierter Schriftart und Schriftgröße im Firefox

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6640]
### Link to the code that reproduces this issue:
2.1.3

### Which browser or operating system do you used to test KoliBri?
Firefox

### How to reproduce issue?
Fehler tritt nur im Firefox auf!
 Einstellungen: 
 ![image](https://github.com/user-attachments/assets/8407a019-6849-41b8-ab09-5a1fc7a703c7)

### Current vs. Expected:
Aktuell: 
 ![image](https://github.com/user-attachments/assets/a38eb397-959b-44a1-8bb3-71ee875011cf) Erwartet: Inhalte sollten umbrechen ohne zu überlappen (wie aktuell im Chrome):
![image](https://github.com/user-attachments/assets/465e62ae-cc61-4ca4-841f-98847eb5f62c)

### Environment informations:
```bash Kolibri Version 2.1.3
 Build: f30a4d4 at 2024-06-28T04:09:59.035Z Windows 10
 Firefox:115.12.0esr (64-Bit) ```

**Comment by laske185** [comment]
Todo: 

- Im Basis-Style die Line-Height auf 1.2 setzen
- Danach Retest

**Comment by laske185** [comment]
Die Line-Height wird in diesem Ticket https://github.com/public-ui/kolibri/issues/6835 global angepasst. Hier werden die Themes explizit mit geprüft.

**Comment by Roman-Use** [comment]
Das Problem wurde behoben. So sieht es nun korrekt aus:
![Breadcrumb_11_7](https://github.com/user-attachments/assets/727bb075-41e2-43f0-8580-3159338b497a)
