### ISSUE TITLE
🐞 Bug: 11.7 - button group: Bei individueller Schriftart und Schriftgröße überlappen die Icons mit der Schrift. (nur Firefox)

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6641]
### Verify current release

- [X] I verified that the issue exists in the latest KoliBri v1 or v2 release

### Link to the code that reproduces this issue

Kolibri Version 2.1.3

### Which theme(s) are affected?

Default

### Which browser or operating system do you used to test KoliBri? (If available)

Firefox

### Which component/area(s) are affected? (Select all that apply)

Button-Group

### To Reproduce

Folgende Einstellungen: 
![image](https://github.com/user-attachments/assets/c166734d-a557-4408-a493-d77552fe0c1e)

### Current vs. Expected behavior

Aktuell: Inhalte überlappen teilweise: 
![image](https://github.com/user-attachments/assets/9065735e-bb83-4929-a880-bc14548e3ad5)

Erwartet: Keine Überlappungen, auch bei benutzerdefinierten Einstellungen

### Provide environment information

```bash
Kolibri Version 2.1.3
Build: f30a4d4 at 2024-06-28T04:09:59.035Z Windows 10
Firefox:115.12.0esr (64-Bit)
```

**Comment by laske185** [comment]
Komponente ist abgekündigt. Der Fehler wird im Button behoben.
