### ISSUE TITLE
🐞 Bug: 11.7 - button-link - icon: Bei individueller Schriftart und Schriftgröße überlappen die Icons mit der Schrift. (nur Firefox)

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6643]
### Verify current release

- [X] I verified that the issue exists in the latest KoliBri v1 or v2 release

### Link to the code that reproduces this issue

2.1.3

### Which theme(s) are affected?

Default

### Which browser or operating system do you used to test KoliBri? (If available)

Firefox

### Which component/area(s) are affected? (Select all that apply)

Button-Link

### To Reproduce

Tritt nur im Firefox auf
Folgende Einstellungen: 
![image](https://github.com/user-attachments/assets/cb659ed8-7b54-478c-ab94-a44dec49dc6c)

### Current vs. Expected behavior

aktuell überlappt der Text das Icon, wenn das Icon links vom Text dargestellt wird. 
![image](https://github.com/user-attachments/assets/5d045d0c-f0fe-4663-a3d9-e9524ba70436)

### Provide environment information

```bash
Kolibri Version 2.1.3
Build: f30a4d4 at 2024-06-28T04:09:59.035Z Windows 10
Firefox:115.12.0esr (64-Bit)
```

**Comment by laske185** [comment]
Bitte hier testen: https://develop--kolibri-public-ui.netlify.app/

**Comment by AntnSaj** [comment]
Fehler wurde behoben.
![Image](https://github.com/user-attachments/assets/f24c3889-c671-4275-b4d2-a8b1e1d40236)
