### ISSUE TITLE
📖 Docs: Inkosistentes Verhalten der Buttons im Beispiel-HTML (entweder keine Reaktion, oder Alert als Popup) 

### ISSUE THREAD

**Issue by Sommerli2** [public-ui/kolibri#6646]
### What is the update you wish to see?

Grundsätzlich ist mir aufgefallen, dass manche der Buttons auf Klick mit einem alert als Popup und manche nicht. Das sollte  vereinheitlicht werden. 

### Is there any context that might help us understand?

Wäre auch gut zum Prüfen der "access keys": https://public-ui.github.io/v2/sample-react/#/button/access-key letzer Button geht kein Toast auf.

**Comment by laske185** [comment]
Beim Klick auf Buttons in der React-Sample-App (nur die Button-Samples) soll ein Toast mit einer kleinen Meldung "Hello" aufgehen.

**Comment by deleonio** [comment]
Der Button im access-key sample, geht noch nicht.

**Comment by deleonio** [comment]
Is also fixed with `release/2` to `develop` merge: https://github.com/public-ui/kolibri/pull/7100/files
