### ISSUE TITLE
Project: Release-Branches in `release/v1` und `release/v2` umbenennen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6653]
Für die Pflege brauchen wir einheitliche Release-Branches. Zudem werden keine Minor-Level im Branch-Namen benötigt.

- `release/1.7` in `release/1` umbenennen
- `release/2` von `develop` erstellen
- alle anderen `release/*`-Branches löschen

**Comment by sdvg** [comment]
Zu beachten, folgendes muss ebenfalls angepasst werden:

- [x] GitHub protected Branches (durch @deleonio).
- [x] GitHub Workflows
- [x] CONTRIBUTING.md
- [x] Netlify - URL für v2

**Comment by laske185** [comment]
Ticket darf erst umgesetzt werden, wenn  es Unterschiede zwischen Version 2 und 3 gibt.

**Comment by deleonio** [comment]
Es gibt jetzt Änderungen zwischen den Branches. Version 2.2 ist Released und die package.jsons weichen jetzt ab.

**Comment by sdvg** [comment]
Hier war nicht mehr viel zu tun. Ich habe nur die CONTRIBUTING.md für V2 und V3 angepasst. V1 hatte die relevante Dokumentation noch nicht, da gab es nichts anzupassen.
