### ISSUE TITLE
DokuSeite: Homepage link zu Kompionenten direkt auf die comp-Übersicht

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6657]
- Badges sollte nicht die beispiele überdecken
- https://public-ui.github.io/ soll der Komponenten-Link auf https://public-ui.github.io/docs/components verlinken. Bitte alle Varianten (en, de und versionen >= 1.7 beachten)

> Hint: genau die Zeile muss angepasst werden: https://github.com/public-ui/public-ui.github.io/blob/86b1e20dade8bc42006cea14c544ff9601fed20c/dev/src/components/HomepageFeatures.tsx#L73 ;-)

**Comment by sdvg** [comment]
Bitte Badges noch fixen und Sprachen/Version überprüfen

**Comment by sdvg** [comment]
Noch eine Ergänzung, können wir ebenfalls in diesem Ticket erledigen:

Auf schmalen Breakpoints (mobile) sollten die Komponenten-Kacheln in eine Spalte (statt zwei) umbrechen.

| Ist | Soll |
|--------|--------|
| ![screenshot 2024-07-29-10 14 21@2x](https://github.com/user-attachments/assets/c838db67-8448-426f-b3dd-39ee966457ca) | ![screenshot 2024-07-29-10 13 50@2x](https://github.com/user-attachments/assets/076c9d61-1bcf-4029-9408-8de0dcf19535) |
