### ISSUE TITLE
🐞 Bug: Keine Screen Reader Ausgabe von Fehlermeldungen an Input-Feldern bei Pfeiltastennavigation

### ISSUE THREAD

**Issue by mweiershaeuser** [public-ui/kolibri#6660]
### Link to the code that reproduces this issue:
https://stackblitz.com/edit/vitejs-vite-5zkosk?file=src%2FApp.tsx

### Can you categorise where the error occurs?
React

### Which browser or operating system do you used to test KoliBri?
Chrome, Windows (Stackblitz)

### How to reproduce issue?
Hallo zusammen,
 uns ist aufgefallen, dass Fehlermeldungen, die an Input-Feldern dargestellt werden, zwar beim Fokus auf das Input selbst durch das gesetzte aria-describedby vom Screen Reader vorgelesen werden. Beim Vorlesen der Seite via Pfeiltastennavigation werden die Meldungen jedoch, obwohl sie visuell dargestellt sind, nicht ausgegeben. **Schritte**
 1. Code-Beispiel öffnen (mit aktivem Screen Reader)
 2. Mit Pfeiltasten hoch und runter die Seite lesen.

### Current vs. Expected:
Expected: Die visuell dargestellten Fehlermeldungen werden vorgelesen.
Current: Die Fehlermeldungen werden nicht vorgelesen.

### Environment informations:
Stackblitz in Chrome auf Windows mit NVDA Screen Reader

**Comment by AntnSaj** [comment]
Die Fehlermeldung wird nicht vorgelesen, weil das kol-alert ein aira-hidden="true" hat.

**Comment by sdvg** [comment]
Zum Erarbeiten der Lösung bitte das A11y-Team kontaktieren und zusammenarbeiten.

**Comment by AntnSaj** [comment]
Die Fehlermeldung wird mit JAWS und NVDA in den Browsern Firefox und Chrome beim navigieren im Lesemodus nicht vorgelesen. Vermutlich liegt es daran, dass ein aira-hidden="true" verwendet wurde.

**Comment by deleonio** [comment]
StackBlitz-Links:

- https://stackblitz.com/edit/vitejs-vite-hbvdcnvw
- https://stackblitz.com/edit/vitejs-vite-c22rjpqg

**Comment by deleonio** [comment]
-[ ] Wir nehmen das `aria-hidden` bei der Fehlermeldung raus.
-[x] ~~Wir wollen, dass Fehlermeldungen beim Verlassen des Feldes vorgelesen (alert oder aria-live) werden.~~
