### ISSUE TITLE
🐞 Bug: Init command `npm init kolibri@latest my-kolibri-app` does not work

### ISSUE THREAD

**Issue by borgfriend** [public-ui/kolibri#6672]
### Can you categorise where the error occurs?
Node v22.5.0

### Which browser or operating system do you used to test KoliBri?
Windows 11

### How to reproduce issue?
1. Run the command `npm init kolibri@latest my-kolibri-app`

### Current vs. Expected:
Command fails, as 'create-kolibri' is not a command. ![image](https://github.com/user-attachments/assets/4871b04b-c24c-4a70-ae5d-855475de3c6c)

### Environment informations:
```bash Windows 11, Commandline, Node v22.5.0 ```

**Comment by deleonio** [comment]
Hi @sdvg,

bitte schau mal, wieso das `create-kolibri` nicht mehr funktioniert. `create`-NPM-Pakete funktionieren doch alle so. Was ist passiert?

**Comment by deleonio** [comment]
Sobald die Ausführung wieder funktioniert und wir das Paket einmal korrekt gepublished haben, wird dieses Paket aus dem Publish-Build rausgenommen.

**Comment by sdvg** [comment]
Wieder geöffnet für: 

> Sobald die Ausführung wieder funktioniert und wir das Paket einmal korrekt gepublished haben, wird dieses Paket aus dem Publish-Build rausgenommen.

Müssen wir machen, nachdem V1 und V2 das nächste mal gepublished wurden.

**Comment by sdvg** [comment]
```
npm create kolibri@latest
npm create kolibri@1
```

Funktionieren jetzt beide korrekt und zeigen die Banner-Message an:
![screenshot 2024-08-08-09 44 13@2x](https://github.com/user-attachments/assets/9c7dd847-fc56-486d-8a81-9b86a61c72de)
