### ISSUE TITLE
Sample App mit abweichender root font-size

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6674]
Wir verwenden die hier beschriebene Methode, um unsere Font-Sizes mit `rem` zu definieren und gleichzeitig für verschiedene Root Font-Sizes variabel zu gestalten: https://github.com/public-ui/kolibri/wiki/Code-Style-and-Conventions

Leider ist es leicht zu vergessen, Font-Sizes immer mit der `rem`-Sass-Funktion zu definieren. Dies ist in den Basis-Styles und den Themes wichtig.

Lösungsvorschlag: Anpassung der Root-Font-Size in der Sample App auf einen sehr hohen Wert (z.B. `100px` bzw. `655%`). So springen falsch definierte Font-Sizes direkt ins Auge und sind auch den visuellen Tests sichtbar.

**Comment by sdvg** [comment]
Ticket wieder geöffnet, weil diese Änderung nicht persistiert wurde, bzw. nicht Teil vom PR war:

> Anpassung der Root-Font-Size in der Sample App auf einen sehr hohen Wert (z.B. 100px bzw. 655%). So springen falsch definierte Font-Sizes direkt ins Auge und sind auch den visuellen Tests sichtbar.

Todo:

- [ ] Sample App hat dauerhaft eine Root-Font-Size von `655%` definiert.

**Comment by laske185** [comment]
Darüber müssen wir noch mal reden. Ich fände es falsch, alle Beispiele mit einer so riesigen Schriftgröße umzusetzen.

**Comment by deleonio** [comment]
@Makko74,

darum geht es hier garnicht.

Die Root-Font-Size soll ja nur so groß eingestellt werden, damit wir erkennen, wo sie das Komponent-Styling beeinflusst.

Damit wir das zukünftig dauerhaft sehen, soll das so eingestellt werden.

Idealerweise ist nach dieser Aufgabe die Font-Size groß aber alles Style sehen weiterhin korrekt aus.

**Comment by laske185** [comment]
Die Themes sollen bei einer riesigen Font-Size trotzdem „normal“ aussehen.

Elemente aus der Sample-App (nicht-KoliBri-Komponenten) müssen entsprechend wieder kleiner gestellt werden.
