### ISSUE TITLE
🙏 Help: InputDate im Voice Over Screen Reader

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6680]
Der Fehler tritt auch bei den nativen input-Elementen ohne Initialwert auf. Es soll recherchiert werden, warum das so ist. Der Bug ist in den known-Issues aufzunehmen (falls ermittelt mit der Begründung).

---

- [x] ~~Die Selektionsfarbe soll im Basis-Theme bei allen Komponenten in ein dunkleres Blau so geändert werden, dass der Kontrast zu Weiß 7:1 beträgt.~~ (In diesem Ticket geht es um das Voice Over. Die Kontraste sind Systemeinstellung. Hier sollten wir nichts machen.)

---

### Discussed in https://github.com/public-ui/kolibri/discussions/6644

<div type='discussions-op-text'>

<sup>Originally posted by **agnieszkaw61** July 18, 2024</sup>
### Summary

Halo,
Wenn wir das Eingabedatum in Google Chrome mit dem VoiceOver-Screenreader auf dem Mac verwenden, erhalte ich so etwas:
![image](https://github.com/user-attachments/assets/75078254-5030-41c5-a707-0e8bf011823c)
Ich habe Information uber Tag / Monat, und Labelname aber warum sind diese Prozente auch gelesen? Ist das ein Bug bei dir? Im Windows Narrator gibt es nichts Vergleichbares.
</div>

**Comment by laske185** [comment]
Die Selektionsfarbe soll in ein dunkleres Blau so geändert werden, dass der Kontrast zu Weiß 7:1 beträgt.
