### ISSUE TITLE
🚀 Feature: aria-describedby Attribut bei Button

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6681]
### Discussed in https://github.com/public-ui/kolibri/discussions/6612

![image](https://github.com/public-ui/kolibri/assets/3471658/4f1132db-7f2b-4f85-a986-071698cc9263)

Wir wollen die Komponenten `KolButton`, `KolButtonLink`, `KolLink` und `KolLinkButton` um das neues Property für eine zusätzliche Beschreibung des Schalters erweitern.

1. [ ] Prüfen, ob ein `aria-describedby`-Verweis nach "außen" (aus dem Shadow-Root) auf einen Text mittels ID verweisen kann.

Danach mit PO absprechen.

3. Wenn ja, das Property als `aria-describedby` umsetzen: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby
4. Wenn nicht, das Property als `aria-description` umsetzen: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-descriptionription (Property-Name: `_ariaDescription`, Implementierung als `aria-describedby` mit einer ID auf einen span mit CSS-Klasse `visually-hidden`)

![image](https://github.com/user-attachments/assets/44251b8a-ac91-41fa-8a01-edc85a53abcc)

**Comment by deleonio** [comment]
Hallo,

das Ticket muss erst noch refined werden.

**Comment by deleonio** [comment]
Es würde ausschließlich den Screenreader-Nutzenden zugutekommen.

![image](https://github.com/user-attachments/assets/44251b8a-ac91-41fa-8a01-edc85a53abcc)

**Comment by sdvg** [comment]
Ticket wird von @Makko74 bearbeitet (kann noch nicht zugewiesen werden)

**Comment by Makko74** [comment]
Ergebnis der Überprüfung, ob ein aria-describedby-Verweis nach "außen" (aus dem Shadow-Root) auf einen Text mittels ID verweisen kann:

`<section>
        <simple-greeter name="Inside">
            <template shadowroot="open">
                <slot ></slot>
                <p>Hello, <span>Inside</span>!</p>
                <button aria-describedby="inside">click me!</button>
                <div id="inside">Describe Test Inside</div>
            </template>
            <h1>Inside</h1>
        </simple-greeter>     
    </section> `

Die Inside aria-describedby Variante hat mit VoiceOver wie erwartet funktioniert

`<section>
        <simple-greeter name="outside">
            <template shadowroot="open">
                <slot ></slot>
                <p>Hello, <span>Outside</span>!</p>
                <button aria-describedby="outside">click me!</button>   
            </template>
            <h1>Outisde</h1>
        </simple-greeter>  
        <div id="outside"> Describe Test Outisde</div>   
    </section>`

Die Outside aria-describedby Variante hat mit VoiceOver nicht funktioniert, der DescribedBy-Block wurde nicht vorgelesen
