### ISSUE TITLE
🚀 Feature: KoliBriTableSelection -> Das Feld keyPropertyName auch für Datenattribute konfigurierbar machen, die nicht im Tabellenkopf stehen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6682]
### Discussed in https://github.com/public-ui/kolibri/discussions/6610

<div type='discussions-op-text'>

<sup>Originally posted by **ChrPtt** July  9, 2024</sup>
### Goals

Derzeit können nur Datenattribute, die auch im Tabellenkopf verwendet werden, für das Feld `keyPropertyName` in der Konfiguration des Selection-Modus verwendet werden.
Dies sollte auf alle Attribute der Tabellendaten ausgeweitet werden.

```
const selection: KoliBriTableSelection = {
	/* ... */
	/* Hier funktionieren nur Keys die auch im Header verwendet werden. */
	keyPropertyName: 'id',
};
```

### Background

Oft gibt es eine technische ID, die eine Zeile als eindeutig identifiziert, aber dem Benutzer nicht angezeigt wird. Daher ist es notwendig, Attribute der Tabellendaten, die nicht im Tabellenkopf enthalten sind, als `keyPropertyName` Eigenschaft auswählbar zu machen, auf die sich die `selectedKeys` beziehen.

### Proposal

`keyPropertyName` auf alle Attribute der Tabellendaten erweitern.</div>

### Code-Stelle

https://github.com/public-ui/kolibri/blob/develop/packages/components/src/components/table-stateless/component.tsx

```ts
const keyPropertyName = selection.keyPropertyName ?? 'id';
const keyCell = row.find((cell) => cell.key === keyPropertyName);
if (!keyCell) return '';
const isMultiple = selection.multiple || selection.multiple === undefined;
const keyProperty = (keyCell?.data as KoliBriTableDataType)[keyPropertyName] as string;
const selected = selection?.selectedKeys?.includes(keyProperty);
```

Daten, die nicht angezeigt werden, müssen trotzdem noch zuordenbar bleiben.

![Image](https://github.com/user-attachments/assets/361e755c-ca7d-463e-ad5c-d0786525457b)

**Comment by sdvg** [comment]
Wir haben bereits einen Lösungsansatz in diesem Commit: https://github.com/public-ui/kolibri/pull/6665/commits/ce5136fe999cdddfc19f6f93282e5f4bc8612944

Idealerweise sollte der Bug aber gefixt werden, ohne eine Änderung der Datenstruktur bzw. API erforderlich zu machen. Die Ermöglichung von verschiedene Selection-Keys _pro Zeile_ sind nicht notwendig.
