### ISSUE TITLE
🚀 Feature: Standalone-Link zu Alert hinzufügen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6683]
### Discussed in https://github.com/public-ui/kolibri/discussions/6611

<div type='discussions-op-text'>

<sup>Originally posted by **gretaneumannn** July  9, 2024</sup>
### Goals

1. Es soll ein Link mit Höhe von 44px unterhalb des Alert Textes zur Verfügung gestellt werden.
2. Der Link ist optional.

### Non-Goals

1. 
2.
3.

### Background

Für Duplikats-Fehlemeldungen in Formularen, möchten wir innerhalb des Alerts dem Nutzenden einen Link anbieten, damit er direkt zum anderen Datensatz abspringen kann. 

Beispiel:

![image](https://github.com/public-ui/kolibri/assets/118734593/005d9242-6f44-4551-a680-3612bbad239b)

### Proposal

Hierzu bitte bei Fragen auf @Chrisdo82 zugehen.</div>

**Comment by deleonio** [comment]
Hey @gretaneumannn,

wir sollen "einfach" einen Link in den Inputs vorsehen?!

**Comment by gretaneumannn** [comment]
Hi @deleonio! 
Korrekt, es soll ein Link innerhalb der Alerts hinzugefügt werden.

**Comment by laske185** [comment]
Die Featureanfrage muss erst noch diskutiert werden.
