### ISSUE TITLE
🐞 Bug: InputDate-Feld hat einen Fehler wenn ein nicht vorhandenes Datum eingegeben wird

### ISSUE THREAD

**Issue by jgldstr** [public-ui/kolibri#6684]
### Link to the code that reproduces this issue:
https://stackblitz.com/edit/vitejs-vite-bzcakl?file=package.json,src%2FApp.tsx

### Can you categorise where the error occurs?
React

### How to reproduce issue?
1. InputDate-Feld händisch füllen (Nicht über den Date-Picker)
 2. Ungültigen Wert eintragen (bspw. 31.02.2024)
 3. Feld verlassen
 4. Reset-Button betätigen

### Current vs. Expected:
Beim füllen des Feldes wird das Datum in der Konsole ausgegeben. Sobald jedoch ein ungültiges Datum eingetragen ist (bspw. 31.02.2024) erfolgt die Ausgabe nicht mehr. Ab hier ist es auch nicht mehr möglich den Wert über den Button "Reset" zurückzusetzen.

### Environment informations:
```bash {
 "Operating System": {
 "platform": "linux",
 "arch": "x64",
 "version": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
 },
 "Binaries": {
 "node": "v18.20.3",
 "npm": "10.2.3",
 "pnpm": "8.15.6",
 "yarn": "1.22.19"
 },
 "Relevant Packages": {
 "@public-ui/components": "2.1.5",
 "@public-ui/react": "2.1.5",
 "@public-ui/themes": "2.1.5",
 "react": "^18.2.0",
 "react-dom": "^18.2.0",
 "typescript": "^5.0.2"
 }
 }
```

### Todo

- [ ] Fehler beheben
- [ ] E2E-Test anlegen

**Comment by jgldstr** [comment]
Mir ist gerade noch aufgefallen, dass der Fehler auch auftritt, wenn das Datum z.B. so gefüllt wird: "12.MM.1999". In dem Fall  wurde bei der Eingabe des Datums der Monat mit Tab übersprungen. Analog trifft das Verhalten auch auf das Weglassen von Jahr oder Tag zu.

**Comment by sdvg** [comment]
Ich habe hier keine zufriedenstellende Lösung gefunden, um das Problem direkt zu beheben. Der Grund:

Das native input[type=date] bildet einen ungültigen Wert als leeren String ab. Man hat gar keine Möglichkeit, auf einen ungültigen Wert wie z.B. `2024-02-31` zuzugreifen.

Dadurch verbleibt auch der interne Component-State bei einer ungültigen Eingabe bei einem leeren String, und nur die native Komponente hält den ungültigen (bzw. unvollständigen) Wert. Wenn wir jetzt versuchen, den Component-Wert von außen auf `null` oder `""` zu ändern, löst dies keine Änderung im State aus und entsprechend wird auch nicht neu gerendert.
Wenn wir versuchen, eine State-Änderungung zu forcieren oder direkt über die Element-Referenz die DOM-Property `value` auf `""` zu ändern, können wir nicht sicherstellen, dass man nicht in einer laufenden, noch ungültigen Eingabe, unterbrochen wird.

Mein Vorschlag ist daher, eine explizite `reset`-Methode auf KolInputDate für speziell diesen Zweck bereitzustellen, die sowohl den internen State, als auch den nativen input-Value auf einen leeren Wert zurücksetzt.
