### ISSUE TITLE
🐞 Bug: In einigen Komponenten sind focus und KolFocus verpflichtend

### ISSUE THREAD

**Issue by jschendzielorz** [public-ui/kolibri#6728]
### Can you categorise where the error occurs?
React

### How to reproduce issue?
* @public-ui/components v2.1.6 installieren
* Fehler erscheinen in VSC, dass sowohl focus und KolFocus mandatory an den Komponenten sind

### Current vs. Expected:
Ich habe nicht erwartet, dass dieser Fehler auftaucht. Man möchte ja nicht an jedem Element explizit den Focus steuern.

### Environment informations:
```bash {
 "Operating System": {
 "platform": "win32",
 "arch": "x64",
 "version": "10.0.17763"
 },
 "Binaries": {
 "node": "v20.13.1",
 "npm": "10.5.2",
 "pnpm": "N/A",
 "yarn": "N/A"
 },
 "Relevant Packages": {
 "@public-ui/components": "2.1.6",
 "@public-ui/react": "2.1.6",
 "@public-ui/schema": "2.0.15",
 "react": "18.3.1",
 "react-dom": "18.3.1",
 "typescript": "5.5.4"
 }
 } ```

**Comment by deleonio** [comment]
@Makko74, bitte ein Reproduktionsbeispiel auf Stackblitz aufbauen.

Link: https://stackblitz.com/edit/vitejs-vite-kkfhk5

**Comment by Makko74** [comment]
Link: https://stackblitz.com/edit/vitejs-vite-tj47uz?file=index.html,src%2FApp.tsx

**Comment by deleonio** [comment]
@Makko74 hat keine Auffälligkeiten festgestellt.

**Comment by jschendzielorz** [comment]
@deleonio @Makko74 habe hier mal einen Fork von eurem gemacht und mit einer Beispielkomponente von mir etwas gebaut https://stackblitz.com/edit/vitejs-vite-dmmbfb?file=src%2FApp.tsx,src%2Fcomponents%2FFormikInputNumber.tsx

Keine Ahnung, warum das nicht rendert, der Fehler, den ich meine, kommt erscheint aber im Editor.

**Comment by deleonio** [comment]
Hier ist das Problem gut zu sehen: https://stackblitz.com/edit/vitejs-vite-9yqkfc?file=src%2Fcomponents%2FFormikInputNumber.tsx

**Comment by deleonio** [comment]
@jschendzielorz Eine Anpassung in KoliBri ist nicht möglich, da dies sogenannte Methoden sind, die nicht als optional umformuliert werden können.

- [ ] Wir werden bei Stencil ein Ticket suchen oder aufmachen, dass Methoden nicht mit in die API als Property übernommen werden, falls dort nichts dagegen spricht.

Hier ein Workaround:

```ts
type InputNumber = Components.KolInputNumber &
  React.HTMLAttributes<HTMLKolInputNumberElement>;
export type FormikInputNumberProps = Omit<
  InputNumber & { _name: string },
  'focus' | 'getValue' | 'kolFocus'
>;
```

Hier der Fix: https://stackblitz.com/edit/vitejs-vite-gdysgu?file=src%2FApp.tsx,src%2Fcomponents%2FFormikInputNumber.tsx
