### ISSUE TITLE
Entscheidungsvorlage für CSS-Pattern vorbereiten -  `BEM`, `data` oder `sx`

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6762]
Das Team soll bitte einmal Argumente für die CSS-Pattern BEM, data oder sx zusammentragen und eine Empfehlung geben.

Wir möchten uns einheitlich für ein CSS-Pattern entscheiden.

**Comment by laske185** [comment]
Festlegung auf BEM. Dies ist zu dokumentieren und auch entsprechend zu begründen, um zukünftige Diskussionen abzuwenden.

**Comment by deleonio** [comment]
Wir haben uns für das BEM-Konzept entschieden.
