### ISSUE TITLE
BundesSans kann aus unserem Repo entfernt werden

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6763]
**Als** Entwickler/Administrator,

**möchte ich** die Schriftart "BundesSans" aus dem System entfernen,

**damit** das System schlanker und wartungsfreundlicher wird, da kein Theme mehr auf diese Schriftart zurückgreift.

Betrift sowohl BundesSans als auch BundesSerif.

#### Akzeptanzkriterien:
1. "BundesSans" ist vollständig aus dem System entfernt, inklusive aller Referenzen in den Codebasen und Konfigurationsdateien.
2. Alle Themes und Stylesheets funktionieren weiterhin einwandfrei ohne die "BundesSans"-Schriftart.
3. Es gibt keine Abhängigkeiten oder Fehler aufgrund des Entfernens der Schriftart.
4. Das System wird nach der Entfernung getestet, um sicherzustellen, dass die User Experience und das Design nicht beeinträchtigt sind.
5. Falls BundesSans verwendet wird, soll auf Verdana gewechselt werden. Weitere Fallbacks sind: Arial, Calibri, Helvetica
6. BundesSerif wird mit Times New Roman ersetzt.

#### Technische Hinweise:
- Überprüfung der verwendeten Schriftarten in allen Themes und Stylesheets.
- Bereinigung von CSS-Dateien, um eventuelle Verweise auf "BundesSans" zu entfernen.
- Testen der Benutzeroberfläche nach der Entfernung, um sicherzustellen, dass keine visuellen Probleme auftreten.

**Comment by Chrisdo82** [comment]
Im BMF Theme wird die BundesSans genutzt, wenn ihr diese entfernt, dann wird nur noch der Fallback greifen. Bitte daher erst entfernen, sobald wir das Theme zu uns rübergeholt haben.

**Comment by deleonio** [comment]
@Chrisdo82 bitte priorisiert den Umzug, damit wir das Thema nicht zu weit hinausschieben müssen. Danke!

**Comment by Chrisdo82** [comment]
@deleonio wird gemacht. Nochmal fürs Verständnis. Folgende Schritte müssen auf unserer Seite dazu getan werden:

1. https://github.com/public-ui/kolibri-theme-bwst kopieren
2. alles unter src mit den Daten unseres Themes austauschen
3. bswt durch unseren Theme Namen ersetzen
4. Anweisungen in der Readme befolgen
5. deployment in die Registry

So in etwa korrekt?

**Comment by Chrisdo82** [comment]
@deleonio der Umzug ist erledigt. Ihr könnt sowohl das Theme, als auch die Schrift entfernen

**Comment by deleonio** [comment]
Hi @Chrisdo82,

können wir das BMF Theme von Euch installieren?

**Comment by Chrisdo82** [comment]
@deleonio 

Nein, soweit sind wir noch nicht. Wir haben es weder als eigenes Package aufgebaut noch es frei verfügbar gemacht. Es ist jetzt Teil unserer internen Lib.

**Comment by laske185** [comment]
Welche alternative Schriftart soll verwendet werden?

**Comment by Supportic** [comment]
Schriftart aus "Erste Schritte" docs entfernen: https://public-ui.github.io/docs/get-started/first-steps#einbinden-von-schriftarten
`<link rel="stylesheet" href="assets/bundes/style.css" />`
