### ISSUE TITLE
Tab-Komponente ohne Button-Group

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6767]
### Beschreibung

**Ziel:** Die `Tab`-Komponente soll umgebaut werden, sodass sie die `ButtonGroup`-Komponente nicht mehr verwendet, da diese als deprecated markiert ist.

**Aktuelle Situation:** 
Die `Tab`-Komponente nutzt derzeit die `ButtonGroup`, um die Tabs als Gruppe von Buttons darzustellen. Da die `ButtonGroup`-Komponente jedoch deprecated ist, sollte die `Tab`-Komponente überarbeitet werden, um die Abhängigkeit zu dieser veralteten Komponente zu entfernen.

**Anforderungen:**
- [ ] Entfernen der Abhängigkeit zur `ButtonGroup`-Komponente in der `Tab`-Komponente.
- [ ] Implementierung einer alternativen Lösung für die Darstellung und Funktionalität der Tabs, die die gleiche oder eine verbesserte Benutzererfahrung bietet.
- [ ] Sicherstellen, dass das Styling und die Benutzerfreundlichkeit der `Tab`-Komponente beibehalten oder verbessert werden.

**Zusätzliche Informationen:**
Bitte darauf achten, dass die Änderungen rückwärtskompatibel sind, oder wenn dies nicht möglich ist, die entsprechenden Breaking Changes klar dokumentiert werden.

**Comment by AlexanderSchmidtCE** [comment]
@laske185 
Guten Tag,

Ich habe eine Fragen, wie ich das Projekt zum Laufen bringe. Die Doku dazu scheint nicht aktuell zu sein.
Ich beziehe mich auf https://github.com/public-ui/kolibri/blob/develop/CONTRIBUTING.md

Unter **Developing** steht folgendes als Schritt 11:
_When you want to start the project navigate to packages/components/ and run pnpm start_

Problem hierbei ist, dass es das script _pnpm  start_ nicht gibt. ich vermute hierbei ist dann _pnpm dev_ gemeint?
Wobei hier der Server nicht gestartet wird.

Unter Punkt 6 in der https://github.com/public-ui/kolibri/blob/develop/docs/tutorials/NEW_COMPONENT.md wird die **/packages/components/src/index.html** erwähnt. Diese finde ich auch nicht.

Möglicherweise übersehe ich etwas oder bin an komplett falscher Stelle.
Könnte ich eine kurze Erklärung bekommen, wie der vorgesehene Weg das Projekt zum Laufen bekomme ist?

_Update:_
Ist die _packages/sample_ dafür vorgesehen, den Server zu starten? 

Viele Grüße
Alexander Schmidt

**Comment by deleonio** [comment]
Guten Morgen @AlexanderSchmidtCE,

vielen Dank für das Feedback. Wir schauen uns die Dokumentation an und nehmen kurzfristig die notwendigen Korrekturen vor.

Was ist denn der konkrete Fehler, beim fehlerhaften Start?

**Comment by AlexanderSchmidtCE** [comment]
Hey @deleonio,
ich hab inzwischen alles zum laufen bekommen. Beim Starten habe ich keine Fehler.

**Comment by AlexanderSchmidtCE** [comment]
Interne Themes anpassen.
