### ISSUE TITLE
Horizontales Scrollen bei leerer Kol-Table sicherstellen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6772]
**Als** Nutzer der Applikation,  
**möchte ich** auch bei einer leeren Kol-Table die Möglichkeit haben, horizontal zu scrollen,  
**damit** ich die Spaltenüberschriften vollständig lesen kann, insbesondere bei starker Vergrößerung (400% Zoom).

---

**Akzeptanzkriterien:**

1. **Scrollbalken bei leerer Tabelle:**
   - Ein horizontaler Scrollbalken muss auch dann sichtbar sein, wenn die Kol-Table keine Daten enthält, um sicherzustellen, dass alle Spaltenüberschriften bei starkem Zoom (400%) lesbar sind.

2. **Verhalten der Tabelle:**
   - Die Kol-Table soll unabhängig von der Befüllung (mit oder ohne Daten) konsistent bleiben, insbesondere bezüglich des Scrollverhaltens.
   - Die Breite der Spaltenüberschriften sollte auch in einer leeren Tabelle berücksichtigt werden, um das Scrollen zu ermöglichen.

3. **Lösungsvorschlag:**
   - Falls notwendig, kann eine leere Zeile mit Dummy-Daten hinzugefügt werden, um das Layout der Spalten aufrechtzuerhalten und das horizontale Scrollen zu ermöglichen.
   - Alternativ könnte geprüft werden, ob die "Es sind keine Einträge vorhanden"-Zeile so gestaltet werden kann, dass die Spaltenüberschriften trotzdem vollständig sichtbar bleiben.

4. **Barrierefreiheit:**
   - Das Barrierefreiheits-Team muss bestätigen, dass die Lösung den Anforderungen entspricht und das Lesen der Spaltenüberschriften auch bei leerer Tabelle und starker Vergrößerung ermöglicht.

5. **Beispiel:**
   - Ein Beispiel mit leerer Tabelle wird in der Sample-App bei dem Beispiel für horizonales Scrollen der Tabelle hinzugefügt.

---

**Beschreibung:**

Auf der aktuellen Seite zeigt sich ein Problem beim horizontalen Scrollen der Kol-Table. Während das Scrollen bei einer gefüllten Tabelle auch bei 400% Zoom einwandfrei funktioniert, fehlt der horizontale Scrollbalken, wenn die Tabelle leer ist. Dies führt dazu, dass nicht alle Spaltenüberschriften sichtbar sind und somit nicht gelesen werden können. Dieses Verhalten wurde vom Barrierefreiheits-Team als nicht akzeptabel eingestuft. 

Ziel dieses Tickets ist es, eine Lösung zu finden, die sicherstellt, dass der horizontale Scrollbalken unabhängig von der Datenbefüllung der Tabelle vorhanden ist. Dies könnte durch die Einführung einer Dummy-Zeile oder durch Anpassungen der aktuellen Tabellen-Definition erreicht werden.

**Comment by laske185** [comment]
Wir benötigen ein Repoduktionsbeispiel.

**Comment by deleonio** [comment]
> Wir benötigen ein Repoduktionsbeispiel.

Das müssen wir selbst leisten.

**Comment by AlexanderSchmidtCE** [comment]
[Aktuelles Beispiel einer leere Tabelle](https://stackblitz.com/edit/vitejs-vite-pbk6ps?file=src%2FApp.tsx)
die `_minWidth` ist hier entscheidend. Wenn eine `_minWidth` gesetzt wird, ist der Scrollbalken vorhanden. Wenn keine gesetzt wird, oder `auto` genutzt wird, passt sich die Tabelle an die Breite an, ohne dass ein Scrollbalken benutzt wird. Dadurch werden die einzelnen Spalten enger.

**Comment by Makko74** [comment]
_ninWidth sollte aber hier nicht die richtige Lösung sein. Es sollte automatisch ermittelt werden.

Variante 1:
im th style statt width auf min und max width umstellen

Variante 2:
alle gesetzten Spalten Breiten zusammen addieren und auf table style width setzen

**Comment by AlexanderSchmidtCE** [comment]
Beim Einbinden eines Samples ist aufgefallen, dass das Verhalten identisch mit dem einer ausgefüllten Tabelle ist.
