### ISSUE TITLE
🐛 Bug Report: `KolInputDate` akzeptiert kein JS-`Date`-Objekt

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6781]
### Beschreibung
Die `KolInputDate`-Komponente scheint generell keine JavaScript-`Date`-Objekte mehr als `_value` zu akzeptieren. Dies betrifft alle unterstützten Input-Typen (`date`, `datetime-local` etc.). Wenn ein JS-`Date`-Objekt übergeben wird, wird der Wert nicht im Input-Feld angezeigt. Wird hingegen ein String im entsprechenden Format übergeben, funktioniert die Anzeige wie erwartet.

### Reproduktionsschritte
Beispiel auf [Stackblitz](https://stackblitz.com/edit/vitejs-vite-d6xeay?file=src%2FApp.tsx).

1. Erstelle ein mehrere `KolInputDate`-Instanzen:
    - Eine mit einem JS-`Date`-Objekt als `value` und dem Typ `datetime-local`.
    - Eine mit einem JS-`Date`-Objekt als `value` und dem Typ `date`.
    - Eine mit einem String als `value` und dem Typ `datetime-local`.
    - Eine mit einem String als `value` und dem Typ `date`.
2. Beachte, dass die Inputs mit einem JS-`Date`-Objekt keinen Wert anzeigen, während die Inputs mit einem String korrekt funktionieren.

### Erwartetes Verhalten
Die Komponente sollte JS-`Date`-Objekte korrekt parsen und den entsprechenden Wert im gewünschten Format (`YYYY-MM-DD` oder `YYYY-MM-DDTHH:mm`) in das Input-Feld eintragen, unabhängig vom Typ (`date` oder `datetime-local`).

### Tatsächliches Verhalten
- **JS-`Date`-Objekte**: Der Wert wird nicht angezeigt.
- **String-Werte**: Der Wert wird korrekt im Input-Feld dargestellt.

![Image](https://github.com/user-attachments/assets/d53614b2-a961-49ae-85b1-fbe96edd62ba)

### Beispielcode
```tsx
<fieldset>
  <legend>Date</legend>
  <KolInputDate
    _type="datetime-local"
    _value={new Date()}
    _label="Datetime local"
  />
  <KolInputDate 
    _type="date" 
    _value={new Date()} 
    _label="Date" 
  />
</fieldset>
<fieldset>
  <legend>String</legend>
  <KolInputDate
    _type="datetime-local"
    _value={'2024-09-05T12:34'}
    _label="Datetime local"
  />
  <KolInputDate 
    _type="date" 
    _value={'2024-09-05'} 
    _label="Date" 
  />
</fieldset>
```

### Mögliche Ursache
Es scheint, dass die Komponente aktuell keine automatische Konvertierung von JS-`Date`-Objekten in das erforderliche String-Format (`YYYY-MM-DD` für `date` oder `YYYY-MM-DDTHH:mm` für `datetime-local`) durchführt. Dadurch wird der Wert nicht korrekt im Input-Feld angezeigt.

### Erwartetes Verhalten bei Korrektur
Die Komponente sollte in der Lage sein, sowohl JS-`Date`-Objekte als auch Strings als `value` zu akzeptieren und den entsprechenden Wert korrekt im Input-Feld anzeigen.

### Akzeptanzkriterien

- [x] Fehler behoben
- [x] E2E-Test für die Date und String Varianten für alle `types` geschrieben

**Comment by laske185** [comment]
Offen ist: wie geht man mit dem Change-Callbacks um. Dort wird aktuell auf jeden Fall die String-Repräsentation übergeben, welche aus dem nativen `input` kommt.

**Comment by sdvg** [comment]
Verwandtes Issue: https://github.com/public-ui/kolibri/issues/6137
Hier wurde beschlossen, die Möglichkeit Date-Objekte zu verwenden, in V3 ganz zu entfernen.
