### ISSUE TITLE
Screenshot-Tests für Modal und Toast

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6815]
**Beschreibung:**
Wir möchten Screenshot-Tests für unsere Modal- und Toast-Komponenten einführen. Dabei sollen die Toast-Komponente mit verschiedenen Typen (`success`, `error`, etc.) und Varianten (`msg`, `card`) getestet werden.

**Akzeptanzkriterien:**
- Playwright-Tests werden implementiert, um Modals und Toasts vor dem Screenshot zu öffnen und korrekt anzuzeigen.
- Ein geöffnetes Modal soll angezeigt werden.
- Toasts sollen mit allen Typen (`success`, `error` usw.) sowie den Varianten `msg` und `card` angezeigt werden.
- Nach dem Einblenden des Modals oder Toasts wird ein Screenshot erstellt.

**Comment by laske185** [comment]
Beim Drawer wird per Query-Parameter in der URL mitgegeben, dass der Drawer gelich geöffnet werden soll. Dies wäre für Modal und Toast genauso umsetzbar und einfacher.

**Comment by sdvg** [comment]
Zurück auf "In progress" geschoben, da die Tests fehlschlagen.
