### ISSUE TITLE
9.2.4.7 - input-checkbox: Aktuelle Position des Fokus deutlich

### ISSUE THREAD

**Issue by Roman-Use** [public-ui/kolibri#6824]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Über die Elemente mit der Tastatur navigieren.

**Current vs. Expected:**
Aktuelles Verhalten: Der Tastaturfokus ist auf den meisten Elementen nicht sichtbar. Lediglich das Element mit Fehlermeldung besitzt einen sichtbaren Tastaturfokus. Die Elemente mit verstecktem Label können nur durch das Einblenden des Labels wahrgenommen werden.
Erwartetes Verhalten: Der Tastaturfokus sollte auf den interaktiven Elementen deutlich sichtbar sein. Zum Beispiel durch einen Rahmen.

**Comment by deleonio** [comment]
@Roman-Use Der Fehler nach nicht reproduziert werden: https://67224b3fdcdf3921a52ad10c--kolibri-public-ui.netlify.app/#/handout/basic

**Comment by Roman-Use** [comment]
@deleonio Ich habe es ausprobiert und das Problem mit dem fehlenden Fokus ist weiterhin vorhanden. Ich hätte noch hinzuschreiben sollen, dass es bei input-checkbox -> switch auftritt: https://67224b3fdcdf3921a52ad10c--kolibri-public-ui.netlify.app/#/input-checkbox/switch

**Comment by deleonio** [comment]
@Roman-Use in der neusten Version geht es, wir haben es nachgetestet: https://public-ui.github.io/v2/sample-react//#/input-checkbox/switch

**Comment by deleonio** [comment]
@Roman-Use bitte noch einmal nachtesten und bestätigen.

**Comment by Roman-Use** [comment]
Wurde nachgetestet und Fokus ist jetzt gut erkennbar.
