### ISSUE TITLE
📖 Docs: "Theming" Toter link

### ISSUE THREAD

**Issue by fschoenfeldt** [public-ui/kolibri#6828]
### What is the update you wish to see?

Der Link zur "Modularisierung" auf [dieser Seite](https://public-ui.github.io/docs/concepts/styling/theming#:~:text=Dark%2DMode-,KoliBri%2DFactory,-Eigene%20spezifische%20Komponenten) ist tot.

### Is there any context that might help us understand?

s.o.

### Does the docs page already exist? Please link to it.

https://public-ui.github.io/docs/concepts/styling/theming#:~:text=Dark%2DMode-,KoliBri%2DFactory,-Eigene%20spezifische%20Komponenten

**Comment by AlexanderSchmidtCE** [comment]
PR: https://github.com/public-ui/public-ui.github.io/pull/240
