### ISSUE TITLE
9.3.3.1 - combobox: Fehlererkennung

### ISSUE THREAD

**Issue by luze8** [public-ui/kolibri#6833]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Linear lesend mit dem Screenreader über die Fehlermeldungen navigieren. 

**Current vs. Expected:**
Aktuelles Verhalten: Beim linearen Lesen werden die Fehlermeldungen vom Screenreader nicht ausgegeben. 
Erwartetes Verhalten: Die Fehlermeldung sollte nicht vor dem Screenreader versteckt werden und von diesem auch beim linearen Lesen ausgegeben werden können.

**Comment by deleonio** [comment]
Duplicate #6660
