### ISSUE TITLE
`_min` und `_max` werden beim `InputDate` nicht korrekt gesetzt

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6849]
### Beschreibung:
Wird bei der `InputDate`-Component ein JavaScript `Date`-Objekt an die `_min` und `_max` Properties übergeben (like `_value`), werden die Werte nicht korrekt gesetzt – entweder werden sie gar nicht übernommen oder falsch geparst. Dies führt dazu, dass die erwarteten Eingabebeschränkungen (min/max) im UI nicht greifen.

### Aufgaben:
1. **Untersuchung des Problems:**
   - Überprüfen, warum die `_min` und `_max` Properties beim `InputDate` nicht korrekt geparst oder übernommen werden.
   - Sicherstellen, dass sowohl JS-`Date`-Objekte als auch Strings in verschiedenen `type`-Variationen (z.B. `date`, `datetime-local`, `month`, etc.) unterstützt und korrekt behandelt werden.

2. **Beispiel in der Sample-App:**
   - Ein Beispiel in der Sample-App integrieren, das die Nutzung von `_min` und `_max` mit einem JavaScript-`Date`-Objekt und Strings demonstriert.
   - Das Beispiel sollte verschiedene `type`-Varianten (z.B. `date`, `datetime-local`) beinhalten, um die Funktionalität vollständig abzudecken.

3. **Tests schreiben:**
   - Einen Test implementieren, der das Verhalten der `_min` und `_max` Properties mit folgenden Szenarien abtestet:
     - JS-`Date`-Objekte.
     - String-Repräsentationen von Daten.
   - Die Tests sollten für alle unterstützten `_type`-Variationen durchgeführt werden (z.B. `date`, `datetime-local`, `month`).

### Akzeptanzkriterien:
- Das `InputDate`-Component setzt korrekt die min/max Grenzen basierend auf JS-`Date`-Objekten und Strings.
- Ein Beispiel in der Sample-App zeigt die Funktionalität von min/max für verschiedene `type`-Varianten.
- Unit-Tests decken alle Kombinationen von `_min`/`_max` Werten und `type`-Variationen ab.

**Comment by AlexanderSchmidtCE** [comment]
Zu Punkt 1:
Ich habe die Komponente mit jedem Type mit Date und Iso8601 getestet. Das Ergebnis ist folgendes:

time - Wird bei beidem korrekt gemappt

date - Wird bei beidem korrekt gemappt

datetime-local - Min wird bei beidem korrekt gemappt, Max wird nicht korrekt gemappt ( erhällt ein default wert)
week - Iso wird korrekt gemappt. Date wird nicht korrekt gemapt. Es wird ein Error geworfen: `Error: Auto convert to week is not supported!`

month - Min wird bei beidem korrekt gemappt, Max wird nicht korrekt gemappt ( erhällt ein default wert)
