### ISSUE TITLE
Style-Optimierung am Link und Button-Link

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6875]
@Makko74 hat einige Optimierungen an den öffentlichen Stylings vorgenommen, die erst abgeschlossen werden sollten. Marko gibt dann ein Signal, wann wir dieses Ticket starten können.

KOLIBRI-571

**Comment by Makko74** [comment]
kann gestartet werden

**Comment by anicyne** [comment]
Warten auf neues Release, um interne Änderungen zu testen

**Comment by deleonio** [comment]
Hi @anicyne,

ich glaube, das passt leider noch nicht ganz:

1. Die Icons am Link sollen auf Schrifthöhe sein. Aktuell sind sie zu hoch.
2. Zwischen Icons und Text soll ein Abstand von 0,5 sein.
