### ISSUE TITLE
Refactoring: EC & EU - "sauber" in separater Unterverzeichnise auftrennen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6881]
![image](https://github.com/user-attachments/assets/34726294-84f1-42eb-b671-f862c1310941)

- [ ] Themes sind in getrennten Verzeichnise
- [ ] Keine Änderungen nach "äußer" außen / Sichtbares / Snapshots identisch

**Comment by Makko74** [comment]
mit dem line-height Task bereits erledigt #6835

**Comment by sdvg** [comment]
Reviewed, sieht gut aus!
