### ISSUE TITLE
Prüfen, welche Komponenten noch nicht in der Übersicht sind

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6887]
https://public-ui.github.io/docs/2.0/components

Abgleich mit unseren Repository: https://github.com/public-ui/kolibri/tree/develop/packages/components/src/components

-[ ] Fehlende dokumentierten.

**Comment by AlexanderSchmidtCE** [comment]
Folgende Komponente fehlen:
Combobox
Drawer
SingleSelect
Symbol
Table Stateful (Table ist in den Docs als Deprecated markiert und verlinkt zu Table Stateful Readme auf Github)
Table Stateless
Toolbar
