### ISSUE TITLE
9.1.4.3 - pagination: Kontraste von Texten ausreichend

### ISSUE THREAD

**Issue by Roman-Use** [public-ui/kolibri#6888]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Das Kontrastverhältnis des Buttons der aktuellen Seite auf der man sich befindet beispielsweise mit Colour Contrast Analyser messen.

**Current vs. Expected:**
Aktuelles Verhalten: Der Button der aktuellen Seite auf der man sich befindet besitzt ein Kontrastverhältnis von ca. 2:1.
Erwartetes Verhalten: Der Button der aktuellen Seite auf der man sich befindet besitzt ein Kontrastverhältnis von mind. 4,5:1.

**Comment by laske185** [comment]
Todo:
 
- Style vom primary-Button nehmen: Blauer Hintergrund und weißer Text

**Comment by Makko74** [comment]
Sollte der Kontrast noch nicht ausreichen, so müsste der  Selected Button gegen ein normale Text Element ausgetauscht werden, da der Button als disabled dargestellt wird und damit die Farbe blasser ist

**Comment by Roman-Use** [comment]
> Sollte der Kontrast noch nicht ausreichen, so müsste der Selected Button gegen ein normale Text Element ausgetauscht werden, da der Button als disabled dargestellt wird und damit die Farbe blasser ist

Das Konstrastverhältnis ist mit 2,7:1 weiterhin nicht ausreichend.
![9 1 4 3_pagination_Kontraste von Texten ausreichend](https://github.com/user-attachments/assets/b36f9eaa-0e74-4eb3-843b-fa679e2bffc5)

**Comment by deleonio** [comment]
Retest from a11y

**Comment by Roman-Use** [comment]
Wurde getestet und es entspricht nun den Anforderungen für das Kontrastverhältnis
