### ISSUE TITLE
9.1.3.1e - table (stateless): Datentabelle richtig aufgebaut

### ISSUE THREAD

**Issue by Roman-Use** [public-ui/kolibri#6890]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Mit Hilfe des im Browser befindende Funktion "Untersuchen" (zu finden im Kontextmenü) lässt sich der Quellcode der Tabelle einsehen und dort auch wieviele Tabellenspalten jede Tabellenzeile besitzt. 

**Current vs. Expected:**
Aktuelles Verhalten: Unregelmäßige Anzahl an Spalten in der Tabelle Die zweite Tabellenzeile hat 5 Tabellenspalten/zellen statt wie die erste Headerzeile 4 Tabellenspalten/zellen. Des weiteren haben die Tabellenspalten/zeilen 3, 4 und 5 der Tabelle ebenfalls nur eine Tabellenspalte/zelle.
Erwartetes Verhalten: Alle Tabellenzeilen sollten die gleiche Anzahl an Tabellenspalten haben.
![image](https://github.com/user-attachments/assets/1a71f4a4-11ae-404e-a1aa-c385bc642569)

**Comment by laske185** [comment]
Sample: https://public-ui.github.io/v2/sample-react/#/table/stateless

**Comment by deleonio** [comment]
ist jetzt auch in `v3`

**Comment by Roman-Use** [comment]
Ich habe es auch noch getestet und es sieht aus Barrierefreiheitssicht gut aus.
