### ISSUE TITLE
9.2.4.7 - table (horizontal-scrollbar): Aktuelle Position des Fokus deutlich

### ISSUE THREAD

**Issue by Roman-Use** [public-ui/kolibri#6897]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Über die Elemente mit der Tastatur navigieren.

**Current vs. Expected:**
Aktuelles Verhalten: Der Tastaturfokus des Toggle-Buttons ist nicht erkennbar.
![image](https://github.com/user-attachments/assets/37b57d9f-4ddf-4595-b152-5006f89583ba)

Erwartetes Verhalten: Der Tastaturfokus des Toggle-Buttons sollte deutlich sichtbar sein. Zum Beispiel durch einen Rahmen.

**Comment by laske185** [comment]
- Der Fokus des Switches ist generell nicht sichtbar. 
- Er soll analog zur Checkbox werden. 
- Fokus-mixin verwenden.
- Themes: default und BMF

**Comment by Roman-Use** [comment]
Änderungen wurden getestet und korrekt umgesetzt.
