### ISSUE TITLE
9.1.1.1 c - Form error-list: Leere Alt-Attribute für Layoutgrafiken

### ISSUE THREAD

**Issue by luze8** [public-ui/kolibri#6901]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Mit dem Screereader linear lesend über die Komponente navigieren.

**Current vs. Expected:**
**Aktuelles Verhalten:** 
Die Grafik zum Markieren des Fehlers oberhalb des Formulars wird vom Screenreader linear lesend ausgegeben. Das ist unnötig. Zusätzlich wirkt die Grafik falsch platziert.
![image](https://github.com/user-attachments/assets/f6508db1-4c4a-48ad-bc02-b70c92c3527d)

**Erwartetes Verhalten:** 
- Das Icon sollte vom Screenreader nicht ausgegeben werden, indem es vorm Screenreader versteckt wird. 
- Die Positionierung des Icons sollte überprüft werden.

**Comment by deleonio** [comment]
Könnte schon gefixed sein.

**Comment by laske185** [comment]
Icon wird jetzt vorgelesen: https://github.com/public-ui/kolibri/issues/6631

Das Icon ist vertikal zentriert. Ob es oben platziert werden soll wäre eine Design-Entscheidung im Default-Theme und somit ein neues Ticket.

**Comment by deleonio** [comment]
Für die Alerts wurde gefordert, dass diese Icons immer ein aria-label haben. Das wurde auch so konsistent umgesetzt und somit wird hier auch "Fehler" vorgelesen.

**Comment by cbraehmig** [comment]
Abstimmung im BF-Team erfolgt. Verhalten bleibt wie umgesetzt. So wird sichergestellt, dass die Meldung als Fehler dargestellt wird. Im Zweifelsfall wird das Wort "Fehler" doppelt ausgegeben.

**Comment by cbraehmig** [comment]
Ergänzung: Hinweis in Dokumentation

https://github.com/public-ui/kolibri/issues/7081

**Comment by deleonio** [comment]
Das Ticket können wir schließen, weil das Label am Icon bleibt und das Design der Fehlerliste mittlerweile eine Card ist.
