### ISSUE TITLE
9.1.4.4 - image: Text auf 200% vergrößerbar

### ISSUE THREAD

**Issue by luze8** [public-ui/kolibri#6902]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Komponente auf 200 % vergrößern

**Current vs. Expected:**
**Aktuelles Verhalten:** Bei 200 % Zoom passt sich das Bild nicht an, sondern bleibt in seiner Originalgröße.

**Erwartetes Verhalten:** Das Bild sollte zoombar sein.

**Comment by laske185** [comment]
Die Größe des Bildes wird vom Layout der Sample App festgelegt. Das Image selbst skaliert (bei <100% sieht man es). Sample überdenken!

**Comment by laske185** [comment]
Todo: Größe von relativ (aktuell 80%) auf absolut ändern: `width: 500px`.

**Comment by deleonio** [comment]
@anicyne, kannst du für `v3` die Änderung einfach via Cherry-Picking reinholen und dann ein PR für `develop` aufmachen. Dadurch weiß `release/2` und `develop`, dass es genau die gleiche Änderung ist.

```bash
git checkout develop
git pull
git reset --hard
git checkout -b branch für v3
git cherry-pick 2dd1554db45394c7b68c5123676fd86aa505522c
```
