### ISSUE TITLE
9.4.1.2 - indented Text: Name, Rolle, Wert verfügbar

### ISSUE THREAD

**Issue by luze8** [public-ui/kolibri#6903]
**Link to the code that reproduces this issue:**
Kolibri Version 2.1.5

**Which browser or operating system do you used to test KoliBri?**
Firefox, Chrome

**How to reproduce issue?**
Mit dem Screenreader linear Lesend über die Komponente navigieren.

**Current vs. Expected:**
**Aktuelles Verhalten:** 
Der Screenreader gibt den visuellen Einschub des Textes nicht aus. 

**Erwartetes Verhalten:** Für Screenreadernutzende sollte die Hervorhebung des Textes erkennbar sein, z.B. durch Verwendung von `<blockquote>`.

**Comment by laske185** [comment]
Komponente ist abgekündigt und wird zur V3 entfernt. Trotzdem für die V2 fixen?

**Comment by laske185** [comment]
Die Komponente hat nur eine visuelle Funktion und wird in Version 3 nicht mehr enthalten sein.
