### ISSUE TITLE
🐞 Bug: Counter für Anzahl der Zeichen in Text-Feld wird initial nicht korrekt geladen

### ISSUE THREAD

**Issue by weingardt** [public-ui/kolibri#693]
# Fehlermeldung

## Beschreibung des Fehlers
Wenn bei der Anzeige von Zeichen (hasCounter) in einem Text-Feld (KolTextarea) ein Wert/Text initial geladen, wird trotzdem "0/xxx" angezeigt. Also steht im Counter initial immer eine Null, auch wenn bereits Text (mit einer Zeichenanzahl > 0) vorliegt.
Erst mit Bearbeiten des Textes wird die richtige Anzahl von Zeichen angezeigt, d.h. wir müssen in das Textfeld klicken und eine Taste drücken, damit der Counter sich aktualisiert.

## Reproduktion
            <LeanInputAdapter _control={textCtrl}>
              <KolTextarea
                _id="text"
                _name="text"
                _placeholder="max. 4000 Zeichen"
                _rows={8}
                _maxLength={4000}
                _hasCounter={mode !== Mode.READONLY}
                _readOnly={
                  mode === Mode.READONLY ||
                  textbaustein.status !== Status.IN_BEARBEITUNG
                }
                _touched={touched}
              >
                Text
              </KolTextarea>
            </LeanInputAdapter>

## Erwartetes Verhalten
Wir würden erwarten, dass sich der Counter auch schon beim initialen Laden/Anzeigen bereits auf den aktuellen Wert (Anzahl der Zeichen) setzt.

## Screenshots
Habe einen Screenshot angehangen, wie der Counter initial aussieht:
![TB_Textarea_Counter_Null](https://user-images.githubusercontent.com/118521078/202670071-799987b2-322d-458d-9653-534d8a5c1f76.PNG)
Und ein Screenshot, wenn man im Textfeld ein Zeichen hinzugefügt hat:
![TB_Textarea_Counter_Aktualisiert](https://user-images.githubusercontent.com/118521078/202670230-53693307-2e9e-4617-9f12-85fbd051d01b.PNG)

## Zusätzlicher Kontext
Aktuell verwenden wir KoliBri Version 1.1.10 - in älteren Versionen war es aber auch schon so.

**Comment by deleonio** [comment]
Wird mit dem Zwischenrelease 1.1.12 adressiert. RC's sind schon unterwegs.

**Comment by deleonio** [comment]
https://codesandbox.io/s/peaceful-sun-wz954l works with 1.1.12-rc.0
