### ISSUE TITLE
BMF-Theme entfernen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#6939]
Siehe: https://github.com/public-ui/kolibri/issues/6763

**Comment by deleonio** [comment]
Es wäre schön, wenn Ihr weiterhin das Theme für BMF separat anbietet, da uns sonst ein wichtiges Theme für die Öffentlichkeit fehlt.

Software-mäßig wäre es nur ein kleiner Mehraufwand, es zu bundeln und selbst als Paket zu konsumieren.

@Chrisdo82, @laske185

**Comment by Chrisdo82** [comment]
@deleonio 
Wie im anderen Ticket bereits erwähnt, ist weder die Lib öffentlich erreichbar noch als eigenes Package aufgebaut. Beide Schritte werden auch nicht zeitnah fertig sein.

Alternativ sehe ich derzeit nur, dass ihr es nicht löschen könnt und es bis dahin weiterhin pflegen müsst.

**Comment by sdvg** [comment]
Muss noch für V2 erledigt werden.

**Comment by deleonio** [comment]
ist jetzt auch in `v3`

**Comment by sdvg** [comment]
Noch mal geöffnet für `V2`

**Comment by deleonio** [comment]
Das DESYBRI-Theme ist jetzt separiert: https://github.com/public-ui/kolibri-theme-bmf-starter
