### ISSUE TITLE
🐞 Bug: render-Callback bei vertikalen Tabellen-Headern

### ISSUE THREAD

**Issue by webbird** [public-ui/kolibri#6952]
### Can you categorise where the error occurs?
Statisches HTML

### Which browser or operating system do you used to test KoliBri?
Chrome

### How to reproduce issue?
When adding a render callback to a vertical table header, it seems not to be executed. I use v2.1.8 with static HTML. Example: 

    horizontal: [
         [{
             label: "horLabel",
             key: "horlabel",
             render: (el, cell, tupel) => { console.log("horizontaljupp") }
         },{...}]
     ],
     vertical: [
         [{
             label: "myLabel",
             key: "mylabel",
             render: (el, cell, tupel) => { console.log("verticaljupp") }
         },{...}]
     ] 

Works with horizontal headers. I am going to add a working example later.

### Current vs. Expected:
I think the render callback should work on both heading directions.

### Environment informations:
```bash Sorry, not available. ```

**Comment by deleonio** [comment]
Vielen Dank für das Ticket.

**Comment by sdvg** [comment]
Ich sehe das Ticket aktuell blockiert von: https://github.com/public-ui/kolibri/issues/6949

Erste Analyse: Render-Funktionen auf vertikalen Headern funktionieren korrekt, wenn sie die einzigen Header sind (keine horizontalen Header).

Wenn horizontale _und_ vertikale Header definiert sind, werden wohl die Render-Funktionen bei den horizontalen Headern erwartet.
Hier stellen sich für mich bei einer möglichen Änderung auch die Fragen, ob das nicht ausreicht und wie man damit umgeht wenn Render-Funktionen doppelt definiert sind, also beim horizontalen und vertikalen Header.

**Comment by webbird** [comment]
Vielen Dank für die Analyse! Das erklärt, dass es bei mir nicht funktioniert, ich habe sowohl horizontale als auch vertikale Header. Ich könnte auch mit der Begründung leben. Dann müßte es nur in die Doku aufgenommen werden.

**Comment by deleonio** [comment]
- Dokumentieren
- Neues Bug-Ticket mit kleiner Prio
