### ISSUE TITLE
Abhängigkeitsbaum über alle Komponenten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6958]
Mittels einer Else-Komponente bauen wir eine Stencil-Komponent aus allen KoliBri-Komponenten ohne tieferen Sinn.

Das hilft uns aber mittels Stencil einen vollen Abhängigkeitsgrafen im Markdown zu bekommen,

https://github.com/public-ui/kolibri/tree/develop/packages/components/src/components/%40else/all

Damit die All-Komponente generiert wird, muss man einmal lokal diese aus der Blocklist nehmen: https://github.com/public-ui/kolibri/blob/aa1d128b7f36916a3860a22b601bb3c1c6e0a865/packages/components/stencil.config.ts#L69

Hier bitte alle fehlenden Komponenten integrieren und einmal der Graph aus der Readme extrahieren.

**Comment by laske185** [comment]
Aufwand zu hoch, um es neu generieren zu können.
