### ISSUE TITLE
Alle Jest-Mocks durch Jest-Snapshot-Tests ablösen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6963]
Dieses Ticket soll erst nach folgendem Ticket begonnen werden: https://github.com/public-ui/kolibri/issues/6964

Die HTM-Mock tests werden durch Snapshot tests abgelöst.

Beispiel:
```ts
executeSnapshotTests<AvatarProps>(
	KolAvatarTag,
	[KolAvatar, KolAvatarWc],
	[
		{ _label: 'Erika Maria Mustermann', _src: undefined },
		{ _label: 'Erika', _src: undefined },
		{ _label: 'Erika', _src: '/image.webp' },
	],
```

Im ersten Schritt sollen hier nur die Tests mit einfaches Use-Cases umgestellt werden. Für konkrete Test-Cases werden neue Issue erstellt.

**Comment by sdvg** [comment]
Wieder geöffnet für https://github.com/public-ui/kolibri/pull/7060
