### ISSUE TITLE
Überprüfen, ob wir das hidden Input für die Wertsynchronisierung noch brauchen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6965]
Guten Morgen,
aus einem BITV-Test wurde uns gemeldet, dass die folgenden Elemente einen Syntax-Fehler darstellen:
Das Element ist eine KolInputCheckbox, ich konnte diese versteckten Elemente auch in allen anderen Eingabe-Komponenten wiederfinden. Wenn ich den SourceCode richtig interpretiere kommt es aus dem Associated Controller, allerdings bin ich mir der Funktion ungewiss. Gibt es eine Möglichkeit dieses versteckte Feld zu entfernen? Oder zumindest das aria-hidden="true"welches auf einem Input vom Typ "hidden" als Fehler ausgezeichnet wird?

![image](https://github.com/user-attachments/assets/7c7cd76f-3102-4c4b-8959-da6513baec41)

![image](https://github.com/user-attachments/assets/d72b8e96-888d-4be9-b478-6f26b12544cd)

Aufgabe ist, dass `aria-hidden` zu entfernen.

**Comment by deleonio** [comment]
Meiner Meinung nach ja, da wir für JSF so das Werte-Handling sicherstellen.

Für normale statische Formular würden wir es nicht mehr benötigen, da Web Components mittlerweile Associated Form Fields unterstützen.

**Comment by petrakow** [comment]
Hi,
wenn es für Werte Handling genutzt wird, braucht es ggf. auch das aria-hidden nicht? Würde den Fehler auch beheben.
(Danke fürs Ticket!)

**Comment by sdvg** [comment]
Für die aktuelle Implementierung dürfte es noch gebraucht werden.

Eine einfache Lösung könnte hier sein, dass `aria-hidden` zu entfernen? Ein Input vom Type hidden dürfte ja sowieso nicht vorgelesen werden (getestet in VO).

**Comment by sdvg** [comment]
Der Vollständigkeit halber:

Der AssociatedInputController arbeitet nicht nur mit inputs vom type hidden, sondern auch mit anderen input types, `select` und `textarea`.
Gemeinsam haben allen diese Elemente jedoch das Attribut `hidden`, das fix gesetzt wird. Dadurch wird sichergestellt, dass die Element mit CSS vollständig versteckt werden (`display: none`), was ein aria-hidden eigentlich in jedem Fall überflüssig machen sollte.

**Comment by deleonio** [comment]
Einfach nur aus dem Hidden-Inputs, -Select und -Textarea `aria-hidden` entfernen.

**Comment by petrakow** [comment]
Anm.: bei den Select Elementen ist uns aufgefallen, das dort Option-Elemente ohne Text-Node ausgegeben werden. Das wird wohl auch als Fehler angemerkt. Ist aber ein anderer Fehler, lediglich aus dem gleichen Kontext.

**Comment by sdvg** [comment]
~~reopen für V2~~
