### ISSUE TITLE
🐞 Bug: KolInputDate Fehlermeldung wird nicht zurückgesetzt

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#6977]
### Link to the code that reproduces this issue:
https://stackblitz.com/edit/vitejs-vite-qrazuc?file=src%2FApp.tsx

### Can you categorise where the error occurs?
React

### How to reproduce issue?
1. Öffne https://stackblitz.com/edit/vitejs-vite-qrazuc?file=src%2FApp.tsx
 2. Klicke auf den "Toggle Error" Button
 3. Fehlermeldung wird angezeigt
 4. Klicke erneut auf den "Toggle Error" Button
 5. Fehlermeldung wird weiterhin angezeigt <img width="1489" alt="Bildschirmfoto 2024-10-28 um 10 11 26" src="https://github.com/user-attachments/assets/ab15a467-732d-4061-98b4-a407ce50c827">

### Current vs. Expected:
Die Fehlermeldung sollte verschwinden, wenn `_msg` nicht definiert ist. Das tut sie derzeit jedoch nicht.

### Environment informations:
```bash {
 "Operating System": {
 "platform": "darwin",
 "arch": "arm64",
 "version": "23.6.0"
 },
 "Binaries": {
 "node": "v20.17.0",
 "npm": "10.8.2",
 "pnpm": "8.12.1",
 "yarn": "N/A"
 },
 "Relevant Packages": {
 "@public-ui/components": "2.1.8",
 "@public-ui/react": "2.1.8",
 "react": "^18.3.1",
 "react-dom": "^18.3.1",
 "typescript": "5.5.4"
 }
 } ```

**Comment by Chrisdo82** [comment]
Betrifft vermutlich auch andere Inputfelder, ich konnte das gleiche Verhalten auch beim `KolInputCheckbox` nachstellen.

**Comment by Chrisdo82** [comment]
@deleonio habt ihr euch das bereits anschauen können?

**Comment by deleonio** [comment]
@Chrisdo82 noch nicht, ich habe es jetzt schon einmal geplant.

**Comment by deleonio** [comment]
@laske185 dafür gibt es doch jetzt die `reset()`-Methode?

**Comment by laske185** [comment]
Übergibt man `null` statt `undefined` wird die Meldung ausgeblendet, da `undefined` von Stencil ignoriert wird.

Bei der Property `_error` funktioniert es auch mit `undefined`: https://stackblitz.com/edit/vitejs-vite-7f2uql?file=src%2FApp.tsx

**Todo**: 
- Das Handling bei `_msg` muss analog zu `_error` auch mit `undefined` umgehen können. (Betrifft alle Inputs)
- E2E-Test

**Comment by deleonio** [comment]
Should be works with the fix: https://stackblitz.com/edit/vitejs-vite-bserke?file=package.json,src%2FApp.tsx

**Comment by deleonio** [comment]
ist jetzt auch in `v3`
