### ISSUE TITLE
Komponentenbeschreibung in Dokumentation umziehen (damit `readme.md`s aus Git entfernen)

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6978]
Ist es möglich die `readme.md`'s nicht mehr einchecken zu müssen?

1. Alle deutschen Beschreibung aus den `readme`'s der Komponenten in die `mdx`-Dateinen zu den Komponenten in der Dokumentation (https://github.com/public-ui/public-ui.github.io) verschieben.
2. Anschließend können alle Komponente-ReadMes aus Komponenten aus Git gelöscht werden.
3. Abschließend die Komponente-ReadMes in gitignore eintagen. (`/packages/components/src/components/*/ReadMe.md`)
  - die ReadMe im components-Ordner kann auch entfernt werden.

Package: `/packages/components/src/components/**`

Bspw. muss die Beschreibung von Abbr aus der Readme von Abbr hier in Zeile 15 verschoben werden: https://github.com/public-ui/public-ui.github.io/blob/084dacd4862e2961c46babc57772b0ddd5d24f63/docs/30-components/abbr.mdx?plain=1#L15

Hinweise: 
- bei Dokuänderungen gibt es dann zwei PRs: im kolibri- und in den docs-Repo. 
- Die Generierung sollte aus dem "Standard"-Build entfernt werden und nur beim erstellen der Doku aktiviert sein

**Comment by sdvg** [comment]
Related (könnte dann geschlossen werden): https://github.com/public-ui/kolibri/issues/6928

**Comment by AlexanderSchmidtCE** [comment]
Mir sind einige Punkte zu Dokumentationen aufgefallen.

- Die Dialog-Komponente existiert nicht in der Component-Library, aber es gibt innerhalb der Dokumentation  eine Abschnitt dafür. Der bindet jedoch die Modal-ReadMe ein. Wie soll damit umgegangen werden?
- TableStateless und TableStateful existieren nicht in der Dokumentation. Dazu existiert eine Story (https://github.com/public-ui/public-ui.github.io/issues/242) mit dem PullRequest (https://github.com/public-ui/public-ui.github.io/pull/250), der vermutlich untergegangen ist.
-  Die Symbol-Komponente existiert in der Library, aber nicht in den Dokumentationen. Soll sie noch hinzugefügt werden?

**Comment by sdvg** [comment]
* Dialog würde ich entfernen.
* Docs für TableStateful/Stateless würde ich zuerst fertigstellen, das entsprechende Ticket ist wieder geöffnet.
* Symbol: Würde ich erst einmal weglassen. Hier bräuchten wir idealerweise eine Entscheidung, ob die Komponente in V3 bleiben soll oder nicht.

cc @deleonio - passt das soweit?

**Comment by sdvg** [comment]
@AlexanderSchmidtCE o.g. Punkte sind so auch mit Martin besprochen, das passt alles.

**Comment by AlexanderSchmidtCE** [comment]
Der Umzug für die Tables wird bereits in [#242](https://github.com/public-ui/public-ui.github.io/issues/242) durchgezogen.
