### ISSUE TITLE
Gibt es keine Snapshots beim Tree? Das Label ist aktuell zentriert?!

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6981]
- Gibt es keine Snapshots beim Tree?
- Das Label ist aktuell zentriert?!

Link: https://develop--kolibri-public-ui.netlify.app/#/handout/basic

<img width="903" alt="image" src="https://github.com/user-attachments/assets/945fc754-d2d6-424f-98a2-66af246324c9">

**Comment by sdvg** [comment]
@deleonio 

Snapshot Tests für Tree gibt es, allerdings tritt der Fehler nicht im Firefox auf.

Ich glaube nicht, dass wir hier aktiv etwas kaputt gemacht haben, sondern der Bug durch die neue Unterstützung von `justify-content` auf Block-Elementen zustande kam [Citation needed].

**Comment by deleonio** [comment]
Ist jetzt im Backlog für Sprint 12.

**Comment by deleonio** [comment]
@sdvg Danke!
