### ISSUE TITLE
Input-Passwort zeigt nicht den Anzeigen-Button

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#7045]
https://public-ui.github.io/v2/sample-react/#/input-password/show-password
![Image](https://github.com/user-attachments/assets/dd1f2b08-3b7b-4d42-baf8-a0c00050de93)

Das Input-Passwort Feld zeigt aktuell den Button zum Anzeigen des aktuell eingegebenen Passworts erst an, wenn das Feld nicht mehr leer ist.

### Todo:

- [x] Button ist immer sichtbar
- [x] Sample erweitern:
  - Leeres Textfeld
  - Mit bereits eingegebenen "Passwort"
- [x] E2E-Test schreiben

**Comment by deleonio** [comment]
Is also fixed with `release/2` to `develop` merge: https://github.com/public-ui/kolibri/pull/7100/files
