### ISSUE TITLE
Ursache für `style`-Tags in unseren Komponenten im Shadow-Root ermitteln

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#7056]
Bei uns ist z.B. beim `KolButton`, aber nicht beim `KolAlert`, ein `style`-Tag im DOM. Bei KERN generell nicht.

<img width="662" alt="image" src="https://github.com/user-attachments/assets/20ec4cdd-c261-4c42-8f47-4d88d95c1c36">

KoliBri: https://github.com/public-ui/kolibri/tree/develop/packages/samples/react
KERN-Repo: https://gitlab.opencode.de/kern-ux/pattern-library/-/tree/chore/multi-theming/packages/sample-app

**Comment by deleonio** [comment]
Hi @christian-bromann,

weißt Du vielleicht, warum `style`-Tags im Shadow-Root auftauchen?

Vielen Dank

**Comment by christian-bromann** [comment]
Styles, die im `@Component` decorator registriert werden, z.B. durch `styleUrl: 'my-component.css'` werden im Shadow Root angehangen. Das ist nicht neu und soweit ich weiß schon immer so gewesen.

**Comment by deleonio** [comment]
Vielen Dank @christian-bromann.

Ich habe ein Update für das Paket `adopted-style-sheets` gebracht, dass die Style-Tags besser handled.

Die Theming-Engine sieht wieder gut aus ... ich musste allerdings was wichtiges fixen.

Hint: Alle SCSS files müssen immer die `style.scss` importieren. Dadurch erkennt die Engine, was der Base-Style ist.

```scss
@import '../@shared/mixins';
@import '../style';
...
```


Viele Grüße

**Comment by deleonio** [comment]
Es ist so weit alles ok damit. Die Style-Tags am Ende der Web Component kommen von der Internal Component und nicht von der Shadow-Komponent. Ein paar Optimierungen waren aber trotzdem dabei.
