### ISSUE TITLE
Bug: aria-selected in Combobox und Single-select ist unvollständig gesetzt

### ISSUE THREAD

**Issue by anicyne** [public-ui/kolibri#7059]
Das aria-selected Attribut sollte für das ausgewählte Item als  `aria-selected="true"` angezeigt werden. Aktuell wird das Attribut ohne Wert angezeigt und erscheint nur als `aria-selected`.

**Comment by sdvg** [comment]
Ist durch #7100 mittlerweile auch in `develop`.
