### ISSUE TITLE
🐞 Bug: Alternativtexte von "Fehler-Icons" werden im Firefox nicht vorgelesen/erkannt.

### ISSUE THREAD

**Issue by AntnSaj** [public-ui/kolibri#7076]
### Which browser or operating system do you used to test KoliBri?
Firefox 128.3.1esr (64-Bit) ChromeVersion 130.0.6723.59 (Offizieller Build) (64-Bit)

### How to reproduce issue?
Mit einem Screenreader im Formularmodus zu den Eingabefeldern navigieren, die eine Fehlermeldung haben

### Current vs. Expected:
Im Chrome wird anstelle des "Fehlericons" (Großes X in einem Kreis) das Wort "Error" ausgegeben, wie im nachfolgenden Screenshot zu erkennen ist.
 ![2024-11-18_10h14_41](https://github.com/user-attachments/assets/8adb3995-95b7-4005-8cce-fcf92081b411) Bei Betrachtung im Firefox wird dieser Text nicht ausgegeben (Siehe nachfolgender Screenshot).
 ![2024-11-18_10h15_25](https://github.com/user-attachments/assets/871a4211-b79c-477a-b9fc-f74af568c3b6) Dieses Verhalten Tritt sowohl mit Jaws als auch NVDA auf.

### Environment informations:
https://public-ui.github.io/v2/sample-react/#/input-number/basic

**Comment by deleonio** [comment]
@AntnSaj: Wenn es in einem Browser geht, dann ist die Wahrscheinlichkeit, dass die Implementierung korrekt ist, hoch. Hier handelt es sich offensichtlich um eine Browser-spezifische Schwäche, bei der Weitergabe des Accessibility-Trees.

![image](https://github.com/user-attachments/assets/6ede5ee0-432a-42b8-ab81-71583175b08b)

**Comment by deleonio** [comment]
### Statement: Firefox liest `aria-label` nicht vor

Firefox hat derzeit bekannte Einschränkungen bei der Unterstützung von `aria-label` in bestimmten Kontexten. Im vorliegenden Beispiel wird das `aria-label` für das Icon (`<i aria-label="Error">`) nicht korrekt vorgelesen. Dies kann daran liegen, dass Firefox für SVG- oder dekorative Icons in Kombination mit ARIA-Attributen nicht konsistent arbeitet.

#### Hintergrund:
- **Technische Ursache:** Firefox setzt in einigen Fällen den Fokus nicht korrekt auf Elemente mit `aria-label`, insbesondere wenn diese als `role="img"` oder in verschachtelten Strukturen eingebettet sind. 
- **Workaround:** Alternativ könnten andere ARIA-Attribute, wie `aria-labelledby` oder eine explizitere Fokushandhabung, ausprobiert werden. Auch die Verwendung eines visually hidden Textes direkt in der Nähe des interaktiven Elements könnte die Barrierefreiheit erhöhen.

#### Empfehlung:
- **Überprüfung auf anderen Browsern:** Testen Sie das Verhalten in Chrome, Edge oder Safari, um sicherzustellen, dass das Problem spezifisch für Firefox ist.
- **Zusätzliche Tests mit Screenreadern:** Verifizieren Sie das Verhalten mit JAWS, NVDA oder VoiceOver, um die Auswirkungen auf Benutzer zu verstehen.
- **Fallbacks:** Erwägen Sie die Verwendung eines textuellen Feedbacks oder alternativer ARIA-Strategien, um die Barrierefreiheit zu gewährleisten.

Dieses Problem sollte weiter evaluiert und ggf. als Bug an Mozilla gemeldet werden.

**Comment by deleonio** [comment]
`aria-labelled-by` ist leider auch keine Lösung

![image](https://github.com/user-attachments/assets/f78373b3-a7c9-4856-bcfa-39b6cb846d1b)

**Comment by deleonio** [comment]
`aria-label` am `kol-icon`

![image](https://github.com/user-attachments/assets/eccd1639-d3a0-4c62-8661-49e45f0ab940)

**Comment by deleonio** [comment]
Im Code auf Known-Issue verlinken.

Wir könnten folgende Ansätze versuchen:

A. `aria-labelledby="icon-label"` + Label-Text in Span mit der ID `icon-label` und `.visually-hidden`
B. `aria-hidden="true"` + Label-Text in Span mit `.visually-hidden`

Retest required.
