### ISSUE TITLE
Fehler und Debug-Ausgaben aus Sample App Console entfernen

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#7077]
Öffnet man auf der Sample App die Konsole, sieht man zur Zeit mehrere ablenkende Log-Meldungen, die zum Teil auch auf Probleme hinweisen:

![screenshot 2024-11-18-11 46 35@2x](https://github.com/user-attachments/assets/5ee4657f-6e22-4617-8a9b-3ece79509ffa)

1) 404-Request für `assets/bundes/style.css`: Link kann entfernt werden.
2) ROUTE_LIST - Debug Ausgabe: Kann entfernt werden.
3) Mehrere Debug-Ausgaben zum Initialisierungsstatus: Können entfernt werden.
4) ~~Warnungen aus dem Theming: Sollten analysiert und das Problem behoben werden.~~ Wird von @deleonio erledigt.
5) `navigator.vibrate` wird ohne Interaktion aufgerufen: Undokumentiertes Feature der Alert-Komponente. Klären, ob das Feature überhaupt funktioniert und ob es benötigt wird. Ursache der Warnung analysieren und das Problem beheben. + Ein Ticket anlegen, wo wir `vibrate` - zurückverfolgen, ob das alles logisch (https://github.com/public-ui/kolibri/issues/7138)
6) Wiederholung von (1)

**Comment by deleonio** [comment]
🤦🏼‍♂️ Bzgl. der 5 gelben müssen wir in der Theming-Engine schauen.

ROUTE und bootstrap ist in der Sample-App.

Die 404 / roten Logs ... weiß ich nicht.

**Comment by deleonio** [comment]
Theme in der Theming-Engine sind mit "adopted-style-sheets": "1.1.7-rc.0" optimiert.

**Comment by sdvg** [comment]
@deleonio Wir haben hier auch mit adopted-style-sheets 1.1.7 weiterhin die folgende Warnung, die ich nicht so recht nachvollziehen kann:

> [Theming] The presetting of theme options is only relevant by using 'fixed' detection mode.

**Comment by sdvg** [comment]
Das Thema `navigator.vibrate` würde ich aufgrund seiner Tiefe gerne ins dedizierte Ticket verschieben: https://github.com/public-ui/kolibri/issues/7191

Für den Moment habe ich eine Prüfung auf `navigator.userActivation.hasBeenActive` hinzugefügt, das fängt den Fehler erst mal ab. Ich kann nicht garantieren, dass das Vibrationsfeature damit weiterhin funktioniert, bin aber optimistisch.
