### ISSUE TITLE
Implementierung des `_spellcheck` Attributs für alle Text-Eingabekomponenten

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#7102]
### Beschreibung:
Um die Benutzerfreundlichkeit und Textgenauigkeit in den Text-Eingabekomponenten der Anwendung zu verbessern, soll das HTML-Attribut `spellcheck` in allen relevanten Komponenten implementiert werden. Dieses Feature ermöglicht es, die Rechtschreibprüfung für Benutzer zu aktivieren oder zu deaktivieren, je nach Anwendungskontext.

---

### Anforderungen:
1. **Einführung eines neuen Properties `_spellcheck`**
   Das neue Property `_spellcheck` hat den Typ `boolean`, ist nicht Pflicht und ist standardmäßig `undefined`.
2. **Aktivierung der Rechtschreibprüfung**
   Das `spellcheck`-Attribut sollte standardmäßig auf `true` gesetzt sein, um die Rechtschreibprüfung in Eingabefeldern zu aktivieren.

3. **Flexibilität für spezifische Komponenten** 
   In Fällen, in denen die Rechtschreibprüfung nicht erforderlich oder unerwünscht ist (z. B. bei technischen Eingaben, Passwörtern oder bestimmten Codefeldern), sollte es einfach sein, `spellcheck` gezielt auf `false` zu setzen.

4. **Abdeckung aller relevanten Komponenten** 
   - `input`-Felder (z. B. Typ `text`, `search`).
   - `textarea`-Felder.
   - Sonstige benutzerdefinierte Komponenten, die Text-Eingaben unterstützen.

5. **Dokumentation**  
   - Update der Komponentendokumentation, um die Verwendung des `spellcheck`-Attributs klar zu beschreiben.
   - Hinweis, wie dieses Attribut konfiguriert werden kann.

6. **Tests**  
   - Sicherstellen, dass die Implementierung in verschiedenen Browsern korrekt funktioniert.
   - Unit- und Integrationstests, um sicherzustellen, dass das Attribut korrekt angewendet wird.

---

### Technische Hinweise:
- Das `spellcheck`-Attribut ist ein globales Attribut, das für alle HTML-Eingabekomponenten verwendet werden kann. [[MDN Dokumentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck)](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck)
- Beispielimplementierung:
  ```html
  <input type="text" spellcheck="true" />
  <textarea spellcheck="true"></textarea>
  ```

---

### Akzeptanzkriterien:
- [ ] Alle `spellcheck=` in den Komponenten durchsehen und nur noch bei relevanten Feldern verwenden
  - Es schein nur `type=text` und `textarea` zu betreffen.
- [ ] Alle relevanten Text-Eingabekomponenten enthalten das `spellcheck`-Attribut.
- [ ] Standardverhalten: `spellcheck="true"`, außer wenn explizit deaktiviert.
- [ ] Dokumentation und Tests sind aktualisiert und vollständig.

---

### Priorität:
Mittel - Verbesserung der Benutzerfreundlichkeit und Genauigkeit, besonders bei längeren Texteingaben.

---

Bitte bei Rückfragen oder Vorschlägen zur Implementierung kommentieren!

**Comment by xp0-1nt** [comment]
Ich hinterfrage ob bei allen Typen der Input-Komponente ein spellcheck sinnvoll ist. Bei den Typen password, date, email und number halte ich es nicht für sinnvoll, weil dort entweder bewusst nicht orthografisch richtig geschrieben wurde oder es sich um Zahlenfolgen handelt. Daher wäre für ein zusätzliches Akzeptanzkriterium:  die Dokumentation der Input-Komponente für den Fall der Typen password, date, email, number muss um die Empfehlung spellcheck=false erweitert werden.

**Comment by deleonio** [comment]
Hi @xp0-1nt, nur bei den laut w3c spezifizierten.

Danke für's Nachhaken:

![image](https://github.com/user-attachments/assets/b3f98a89-bdef-45b1-8cbe-91d929108337)

Das hat sich tatsächlich stur durchgezogen. Ich würde das direkt beheben lassen.

**Comment by deleonio** [comment]
@laske185, @sdvg 

Nach hinreichender Überlegung werden wir das Property `_spellCheck` einführen, um es bei Bedarf aktivieren zu können. Hierbei ist Spellcheck nur bei Text-Input type=text und Textarea sinnvoll.

Da aktuell überall `spellcheck=false` ist, ist aktuell der Issue-Grund nicht erfüllt. Aber bietet uns die Möglichkeit es ohne Breaking Change einzuführen.

- [ ] neues optionales Property `_spellcheck: boolean`, default `undefined`, entspricht Browser default.

**Comment by deleonio** [comment]
ist jetzt auch in `v3`
