### ISSUE TITLE
🐞 Bug: Checkbox-Input Lesereihenfolge

### ISSUE THREAD

**Issue by mweiershaeuser** [public-ui/kolibri#7104]
### Link to the code that reproduces this issue:
https://stackblitz.com/edit/vitejs-vite-p3eaey?file=src%2FApp.tsx

### Can you categorise where the error occurs?
React

### Which browser or operating system do you used to test KoliBri?
Chrome

### How to reproduce issue?
1. Reproduktionsbeispiel öffnen und Screen Reader starten (NVDA)
 2. Seite mit Pfeiltastennavigation vorlesen lassen (Lesemodus)
 3. Anschließend über Felder mit Tab navigieren

### Current vs. Expected:
**Current**
 Visuell ist sowohl bei der KoliBri-Checkbox als auch bei der HTML-Checkbox das Input-Feld links neben dem Label positioniert. Bei Navigation via Tab lesen sowohl die KoliBri-Checkbox als auch die HTML-Checkbox erst das Label und dann das Input-Feld vor. Bei Navigation mit Pfeiltasten wird bei der KoliBri-Checkbox zuerst das Label vorgelesen und dann das Input-Feld, bei der HTML-Checkbox hingegen erst das Input-Feld und dann das Label. **Expected**
 Die Lesereihenfolge bei Pfeiltastennavigation (Lesemodus) entspricht der visuellen Darstellung. Ist das Label rechts neben der Checkbox, sollte erst das Input-Feld und dann das Label vorgelesen werden, wie es beim HTML-Beispiel der Fall ist.

### Environment informations:
Stackblitz, Chrome, Windows
 NVDA Screen Reader

**Comment by deleonio** [comment]
**Hallo @mweiershaeuser,**  

vielen Dank für deinen Hinweis und das Aufwerfen dieses wichtigen Themas.  

Das **SOLL** ist, dass das Markup der visuellen Darstellung entspricht. Meines Wissens liegt der Fokus darauf, sicherzustellen, dass CSS nicht verwendet wird, um die Reihenfolge der Inhalte so zu verändern, dass diese nicht mehr in der logischen Abfolge (z. B. von links oben nach rechts unten) für Screenreader wahrnehmbar sind.  

Ein Eingabefeld besteht aus Sicht der Barrierefreiheit jedoch immer aus einem Label, einem Input-Feld und ggf. weiteren Elementen. Diese sollten als Einheit betrachtet werden. Ob innerhalb der Komponente das Label vor oder nach dem Input-Feld gelesen wird, sollte der Barrierefreiheit keinen Abbruch tun, solange die logische Verbindung gegeben ist.  

Ein Fehler wäre es allerdings, die Inputs beispielsweise am Ende des Dokuments zu platzieren und sie nur visuell als Suchfeld oben anzuzeigen.  

Die von KoliBri entwickelten Elemente sind in sich vollständig und barrierefrei gestaltet. An der Stelle, wo sie verwendet werden, sind sie semantisch korrekt und für sich barrierefrei. Eine kleine Abweichung im Detail sollte daher immer in Relation betrachtet und bewertet werden.  

**@Chrisdo82, @AntnSaj:** Ich würde euch bitten, hier ebenfalls eine Stellungnahme abzugeben. Hinterfragt auch gerne meinen Ansatz und zieht, falls möglich, Rückmeldungen von Screenreader-Nutzenden hinzu.

**Comment by deleonio** [comment]
Was wir machen können:

- [ ] für Checkbox, machen wir das Label bei `_alignLabel=left` vor und bei `_alignLabel=right` nach dem Input?!

FYI @Makko74 könntest Du sowas beim Refactoring der Input-Komponent berücksichtigen?

**Comment by mweiershaeuser** [comment]
![grafik](https://github.com/user-attachments/assets/dca4e3d2-8d9e-4050-87b0-f8631d3d5537)

**Comment by mweiershaeuser** [comment]
Im gemeinsamen Gespräch ist aufgefallen, dass das Label und das Input-Feld im Lesemodus separat ausgegeben werden (zweimal Pfeiltaste drücken) während es bei der Verbindung des reinen HTML-Labels mit -Input zusammen vorgelesen wird.

**Comment by deleonio** [comment]
Wir müssen schauen, wieso bei uns Label und Input beim Lesemodus getrennt vorgelesen wird. Im reinen HTML wird es immer im Zusammenhang vorgelesen.

**Comment by laske185** [comment]
Ist es für einen blinden Menschen nicht egal, ob die Checkbox visuell links oder rechts ist?

**Comment by deleonio** [comment]
@laske185 Das ist gar das kleiner Problem. Wir haben am Freitag festgestellt, dass bei uns Label und Checkbox im Lesemodus getrennt und im Native immer zusammen vorgelesen wird. Das ist am Ende das ernstere Problem.

**Comment by deleonio** [comment]
![Image](https://github.com/user-attachments/assets/1c7b37df-825a-4402-ad99-0a5af4dbcf79)
.
Im Native wird Label und Input immer einmal und gemeinsam vorgelesen

![Image](https://github.com/user-attachments/assets/967cb0ef-27d6-40c5-bccb-6b5a5e07a2da)

Bei KoliBri wird alles einzeln und getrennt vorgelesen.

Ursache unbekannt.

- [ ] Kurz mal die anderen Inputs nachprüfen, wenn Lösung umgesetzt.
