### ISSUE TITLE
9.3.3.1 - input-email: Fehlererkennung

### ISSUE THREAD

**Issue by Roman-Use** [public-ui/kolibri#7167]
Link to the code that reproduces this issue:
Kolibri Version 2.1.5

Which browser or operating system do you used to test KoliBri?
Chrome und Firefox

How to reproduce issue?
Mit eingeschaltetem Screenreader (NVDA) im Lesemodus (Pfeiltasten runter + hoch) durch die Seite navigieren. 

Current vs. Expected:
Aktuelles Verhalten: Das Label "E-Mail (list)" und auch das Kombinationsfeld mit dem placeholder "elke@mustermann.de" wird vorgelesen. Die Fehlermeldung "I am an error message!" jedoch nicht.
Erwartetes Verhalten: Zusätzlich zu den Informationen die zuvor erwähnt wurden, soll auch die Fehlermeldung ausgegeben werden.

Dies trifft für alle Fehlermeldungen der Seite auf.

![2024-12-06_15h53_35](https://github.com/user-attachments/assets/08305ed3-36db-40a1-8539-3d4dd256b8f6)

**Comment by deleonio** [comment]
Achtung, dass ist wahrscheinlich ein Dublikat ... Verlinken und dann schließen.

**Comment by deleonio** [comment]
Duplicate #6660
