### ISSUE TITLE
9.3.3.1 - input-color: Fehlererkennung

### ISSUE THREAD

**Issue by Roman-Use** [public-ui/kolibri#7168]
**Link to the code that reproduces this issue:**
Kolibri Version 2.2.1

**Which browser or operating system do you used to test KoliBri?**
Chrome und Firefox

**How to reproduce issue?**
Mit eingeschaltetem Screenreader (NVDA) im Lesemodus (Pfeiltasten runter + hoch) und auch im Fokus Modus (Tab-Taste) durch die Seite navigieren.

**Current vs. Expected:**
**Aktuelles Verhalten:** Das Label und auch der Farbcode der ausgewählten Farbe wird vorgelesen. Die Fehlermeldung "I am an error message!" wird im Chrome weder im Lesemodus, noch im linearen Modus vorgelesen. Im Firefox wird die Fehlermeldung lediglich im Fokus Modus (Tab-Taste) vorgelesen, jedoch nicht im Lesemodus (Pfeiltasten runter + hoch).
**Erwartetes Verhalten:** Zusätzlich zu den Informationen die zuvor erwähnt und korrekt vorgelesen wurden, sollen auch die Fehlermeldungen sowohl im Fokus Modus (Tab-Taste), als auch im Lesemodus (Pfeiltasten runter + hoch) auf dem Firefox- und Chrome-Browser durch den Screenreader (NVDA) ausgegeben werden. 

Dies trifft für alle Fehlermeldungen dieser Seite auf.

**Comment by deleonio** [comment]
Duplicate #6660
