### ISSUE TITLE
💡 Hinweis: Alert Icon mittig platziert

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#765]
Das Icon ist aktuell mittig platziert. Es sollte oben links ausgerichtet sein, sodass das Icon immer neben der Überschrift oder dem Text steht.

**Comment by deleonio** [comment]
@gretaneumannn / @Chrisdo82 

Das könnt Ihr über den Theme-Designer lösen: https://public-ui.github.io/designer/

**Comment by gretaneumannn** [comment]
@Chrisdo82: Umsetzung im Labor.

**Comment by deleonio** [comment]
@Chrisdo82 - könnte Ihr bitte Feedback.

**Comment by Chrisdo82** [comment]
@deleonio die Styles gehe ich alle gesammelt an. Ich warte momentan aber noch auf den Wrapper in #770
