### ISSUE TITLE
🛹 Feature: Alert "Close"-Funktion hinzufügen

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#766]
Aktuell lässt sich das Alert nicht schließen. Bitte "Close"-Funktion hinzufügen. Siehe: 

![image](https://user-images.githubusercontent.com/118734593/203042383-2b77fd03-b0df-4fdc-8bb4-c092aa091654.png)

**Comment by gretaneumannn** [comment]
Umgesetzt, Beispiele in Storybook fehlen. 
@Chrisdo82: prüft ob im Labor zur Verfügung steht

**Comment by gretaneumannn** [comment]
Closer steht im Labor zur Verfügung.

**Comment by deleonio** [comment]
Insgesamt müssten die Storybook-Beispiele aktualisiert und erweitert werden:

- Alert
- Button
- ButtonLink
- Pagination
- Table
- Toast

**Comment by deleonio** [comment]
@Chrisdo82 - könnte Ihr bitte Feedback.

**Comment by Chrisdo82** [comment]
@deleonio auf welches Feedback wartest du von mir? @gretaneumannn hatte dazu doch schon was geschrieben
