### ISSUE TITLE
💡 Hinweis: Ghost-Button hat keinen transparenten Hintergrund

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#767]
Aktuell hat der Ghost-Button einen weißen Hintergrund. Besser wäre ein transparenter, damit dieser auch auf farbigem Hintergrund Verwendung finden kann.

**Comment by gretaneumannn** [comment]
@Chrisdo82: Im Labor umsetzen, eigener Ghost-Button erstellen für Tabelle (in 2 Varianten für weißen und grauen HG).

**Comment by Chrisdo82** [comment]
Ticket kann geschlossen werden @deleonio
