### ISSUE TITLE
🛹 Feature: Textarea und Text-Input Angabe von Zeichenanzahl

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#768]
Die Zeichenanzahl bei der Textarea und Text-Input Komponente wird nicht mehr angezeigt. Wunsch: 

Neben dem Label auf der rechten Seite:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/118734593/203045042-fb3b876b-510e-4764-87c5-e9572ada6faa.png">

Anzeige erst nach Klick in das Feld:
<img width="833" alt="image" src="https://user-images.githubusercontent.com/118734593/203046223-83948485-fc8a-44b1-a2ed-9863d92612d8.png">

**Comment by deleonio** [comment]
Related: https://github.com/public-ui/kolibri/issues/28

**Comment by deleonio** [comment]
Bei alle Text-basierten Eingabefeldern ergänzen. In der Textarea haben wir das schon umgesetzt.

- [x] Zähler umsetzen
- [x] Ausrichten via CSS später
