### ISSUE TITLE
🛹 Feature: Filter Badges

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#770]
Funktion: Anzeige des gesetzten Filters + Aktion "Entfernen"

Fokusrahmen innerhalb der Klickfläche von 44px:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/118734593/205637558-089f84ea-6965-4404-8855-283f32a5f219.png">

Fokusrahmen außerhalb der Klickfläche von 44px: 
<img width="573" alt="image" src="https://user-images.githubusercontent.com/118734593/205637828-30949a3a-72ca-4983-a7b8-f1d284ed7163.png">

**Anzeige Filterung:** 
height: 32px;
width: 99px;
left: 0px;
top: 0px;
padding: 4px 8px 4px 12px;
border-radius: 5px 0px 0px 5px;

**"Close"-Button:** 
height: 32px;
width: 32px;
left: 26px;
top: 33.242919921875px;
padding: 4px;
border-radius: 0px 5px 5px 0px;

Sichtbare Klickfläche bei 32x32px, tatsächliche Klickfläche muss bei 44x44px sein.

**Comment by gretaneumannn** [comment]
Kann der Fokusrahmen für diese Komponente angepasst werden, sodass der Rahmen nicht außerhalb, wie bei den anderen Komponenten, sondern innerhalb der Klickfläche ist? In diesem Fall würde es bedeuten, dass der Rahmen innerhalb der 44px liegt und sich der Abstand von Element zu Fokusrahmen von 6px auf 3px reduziert? (Fokusrahmen=3px).

**Comment by gretaneumannn** [comment]
Bevorzugt Fokusrahmen innerhalb der Klickfläche von 44px (obere Variante)

**Comment by Chrisdo82** [comment]
@deleonio gibt es dazu schon ein Beispiel im Theme Designer? Ich wüsste jetzt auf Anhieb nicht welche Komponente das jetzt löst. 

Vielleicht wäre es sinnvoll, wenn ihr PRs auch mit den Issues verknüpft? Dann hätte man wenigstens eine ungefähre Idee ;-)

**Comment by Chrisdo82** [comment]
@deleonio ich gehe mal davon aus, dass das `smartButton` property beim Badge das lösen soll. Ein zusätzlicher div-Wrapper um das `kol-span-wc` und `kol-button-wc` wäre jedoch noch notwendig, damit beide Elemente auch nebeneinander dargestellt werden können. Kannst du das Ticket wieder aufmachen oder muss ich dafür jetzt ein neues erstellen?

**Comment by deleonio** [comment]
Wir werden Beispiele im Designer aufnehmen.

**Comment by deleonio** [comment]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/6279703/212645915-6bccef83-1a57-4871-972c-a822e37b9e7d.png">

Ist jetzt im Designer.

möglichst viel mit `>` - der Button beinhaltet auch `kol-span-wc`
```tsx
:host {
  display: inline-block;
}

:host > span {
  border-radius: 0.3125rem;
  display: inline-flex;
  font-size: 0.875em;
  font-style: normal;
  font-weight: 700;
  line-height: 1rem;
}

:host > span kol-button-wc {
  border-left: 1px solid rgba(0, 0, 0, 0.25);
}

:host > span kol-span-wc {
  padding: 0.25rem 0.5rem;
}

:host > span > kol-span-wc {
  align-items: center;
  font-style: normal;
  gap: 0.5rem;
}

:host > span > kol-span-wc > span {
  display: flex;
  gap: 0.25rem;
}
```

![image](https://user-images.githubusercontent.com/6279703/212667702-ec563d16-0493-49bc-9ffc-44655d3dcfce.png)
