### ISSUE TITLE
🐞 Bug: create-kolibri Angular Template ohne Logo und Zone.js

### ISSUE THREAD

**Issue by BenRichter** [public-ui/kolibri#772]
# Fehlermeldung

## Beschreibung des Fehlers
Nachdem via `npm init kolibri@latest my-kolibri-app` eine Angular erstellt wurde, startet diese nicht.
- Es fehlt die Datei "logo.angular.png"
-"zone.js": "^0.12.0" muss als Dependency in der package.json hinterlegt werden

## Erwartetes Verhalten
Die App startet nach der Grundeinrichtung

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Windows 11
-  Chrome

**Comment by deleonio** [comment]
👍 Danke

**Comment by deleonio** [comment]
Wird mit dem Zwischenrelease 1.1.12 adressiert. RC's sind schon unterwegs.

**Comment by deleonio** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/6279703/203258736-aba9f24a-6b21-47f8-82ff-089a7b7ce941.png">

1.1.12-rc.0

**Comment by deleonio** [comment]
@BenRichter it's done.

Thx 🤝
