### ISSUE TITLE
💡 Evaluation ob der HTML-Tag dialog die Komponente Modal mittelfristig ablösen kann

### ISSUE THREAD

**Issue by ElVariablo** [public-ui/kolibri#796]
Seit dem letzten Firefox update ist es bei unserem Arbeitgeber möglich, das HTML5 Element <dialog> zu nutzen. Dieses könnte eure selbst geschriebene Komponente ablösen, da diese von haus aus alles mitbringt. 

Anbei noch ein Link zur Erklärung des Tags und eine Übersicht der Browserverfügbarkeit 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog?retiredLocale=de
https://caniuse.com/dialog

**Comment by deleonio** [comment]
Lösungsweg:

- neue Komponente `Dialog`
- Komponente `Modal` bleibt solange `Dialog` sie nicht 1 zu 1 ersetzt

**Comment by deleonio** [comment]
Sprint 23/1: Klarheit über die Fähigkeit des `dialog`-Tags. Auch Modal und nicht Modal betrachten.

**Comment by ElVariablo** [comment]
https://wiki.selfhtml.org/wiki/HTML/Tutorials/dialog
 - In HTML5 wurde dafür das [dialog](https://wiki.selfhtml.org/wiki/HTML/Elemente/dialog)-Element eingeführt, das seit März 2022 von allen Browsern unterstützt wird. Für ältere Versionen kann ein [polyfill](https://wiki.selfhtml.org/wiki/Polyfill) eingebunden werden.
 
Verfügbarkeit:
https://caniuse.com/dialog

**Comment by deleonio** [comment]
@Chrisdo82 Ich denke, diese Konstruktion lässt sich ganz einfach mit zwei `div`s lösen.

Würde das Ticket dann schließen?!

**Comment by Chrisdo82** [comment]
@deleonio ich verstehe deinen Kommentar nicht so ganz? Bezieht sich die Antwort evtl. auf ein anderes Ticket???

**Comment by deleonio** [comment]
Der dialog-Tag kann die aktuelle Modal-Komponente ersetzen.
