### ISSUE TITLE
Positionierung in scroll-zone muss optimieren

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#826]
Es geht darum, dass Tooltips in einer Scroll-Zone um den Scroll-Offset versetzt - falsch angezeigt werden. Im Desinger -> Buttons -> runterscrollen -> Icon-Only-Button.

**Comment by deleonio** [comment]
![image](https://user-images.githubusercontent.com/6279703/203546322-356a334a-3550-4946-aef5-8b809b8932d4.png)

**Comment by laske185** [comment]
Minimales Reproduktionsbeispiel:

```html
<body>
	<div style="height: 300px; overflow-y: scroll">
		<div style="height: 200px"></div>
		<kol-button _icon="arrow-up" _icon-only _tooltip-align="right" _label="Tooltip text"></kol-button>
		<div style="height: 200px"></div>
	</div>
</body>
```

**Comment by laske185** [comment]
Umfassender Test, der auch die horizontale Verschiebung innerhalb eines relativ positionierten Divs prüft:
[CodeSandbox](https://codesandbox.io/s/dank-star-howd72?file=/src/App.tsx)

**Comment by laske185** [comment]
https://codesandbox.io/s/dank-star-howd72?file=/src/App.tsx

**Comment by deleonio** [comment]
Supi https://codesandbox.io/s/hardcore-turing-fctxk6?file=/public/index.html
