### ISSUE TITLE
Component: Dialog als Alternative für Modal aufbauen (parallel)

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#827]
Siehe: https://github.com/public-ui/kolibri/issues/796

**Comment by deleonio** [comment]
Related #796

**Comment by Wolfram-Zell** [comment]
remove:
_on
_width
closeButton

**Comment by Wolfram-Zell** [comment]
Änderung der Fragestellung:
Ist das native <dialog> Element barrierefrei, oder benötigen wir hier einen Wrapper um die Barrierefreiheit sicher zu stellen?

https://wiki.selfhtml.org/wiki/HTML/Elemente/dialog
https://www.w3.org/TR/2013/CR-html5-20130806/interactive-elements.html
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/

**Comment by Wolfram-Zell** [comment]
`<dialog>` ist barrierefrei.

-  Dialog nicht implementieren
-  in Dokumentation auf natives Element verweisen
-  Modal deprecated
-  in Version 2 entfernen
- -> entsprechende Tickets erstellen
