### ISSUE TITLE
🐞 Bug: Table - Data-Handling / Async / Refill

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#832]
> **Note**
> - [ ] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Daten werden bei Wiederholten Befüllen in die Table nicht übernommen.

## Reproduktion

[Nutzen Sie die [CodeSandbox](https://codesandbox.io/s/inspiring-firefly-teqjmn), um ein reproduzierbares Beispiel zu erstellen.

- Link zu CodeSandbox: https://codesandbox.io/s/vibrant-sun-t4lykc

@hansellkopp

**Comment by deleonio** [comment]
@HansellKopp

Hast Du `_data` wie folgt gesetzt? / Immutable

```tsx
<KolTable
    _data={[...newData]}
/>
```

**Comment by HansellKopp** [comment]
Ich habe auf die Version 1.1.12 aktualisiert und das Problem ist verschwunden. Ich vermute, dass das Problem an wie ich  den Daten aktualisiere lag, und nicht an der Table.
