### ISSUE TITLE
🐞 Bug: [1.1.12] Sortier-Button Icons werden nur initial angezeigt 

### ISSUE THREAD

**Issue by eugen-cc** [public-ui/kolibri#893]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

# Fehlermeldung
Bei einer sortierbaren Spalte, ist der Sortier-Button lediglich initial sichtbar. 

## Beschreibung des Fehlers
Initial sieht man die Sortierbuttons im Tabellen-Header. Klickt man auf den Sortier-Button, so ist das zugehörige Icon nicht mehr sichtbar. Der Button ist nach wie vor da und die Sortierung funktioniert weiterhin. 

## Screenshot
![sortierung_initial](https://user-images.githubusercontent.com/14055972/203954881-5acaaf95-a329-4106-8cf3-abb131def268.PNG)
![sortierung_aktiv](https://user-images.githubusercontent.com/14055972/203954870-905ffdc0-7cbb-4315-b0b5-28037f88353e.PNG)

**Comment by deleonio** [comment]
Sollte mit 1.1.13 gelöst sein.
