### ISSUE TITLE
📖 Help: Wie geht das MDX2 Setup?!

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#947]
Hallo @Chrisdo82,

kannst Du uns das zeigen?

https://github.com/public-ui/kolibri/blob/main/packages/storybook/.storybook/main.js

**Comment by Chrisdo82** [comment]
Hi, ich habe lediglich die Schritte aus der Doku dazu befolgt: https://storybook.js.org/docs/react/writing-docs/mdx#mdx-2

**Comment by deleonio** [comment]
Eingerichtet und baut nicht fehlerfrei.

Das Storybook-Plugin ist in einer sehr frühen Entwicklung: https://github.com/storybookjs/mdx2-csf

Bei uns funktioniert aktuell alles wie gewünscht mit MDX1

**Comment by deleonio** [comment]
obsolete
