### ISSUE TITLE
🐞 Hint: ThemeDesigner - patchTheme wählt nicht das korrekte Theme aus

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#959]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers

Wenn im Theme Designer z.B. das Theme "bmf" ausgewählt wird und man anschließend versucht dieses in seiner Anwendung zu patchen, dann erscheint folgende Fehlermeldung: "The theme process is locked. This means that the theme "bmf" should not be patched."

Gelöst werden kann das nur, indem man den Namen des Themes großschreibt.

falsch: `KoliBriDevHelper.patchTheme("bmf", {`

richtig: `KoliBriDevHelper.patchTheme("BMF", {`

## Reproduktion

1. Öffne den Theme Designer
2. Wähle als Theme "bmf" aus
3. Klicke auf Theme erstellen
4. Kopiere den Code in deine Anwendung

## Erwartetes Verhalten
Der Code sollte out-of-the box in meiner Anwendung funktionieren und außerdem sollte die Fehlermeldung darauf hinweisen, dass das Theme so nicht existiert.

**Comment by deleonio** [comment]
Hallo @Chrisdo82,

die Theme-Kennungen werden kleingeschrieben. Wir können jedoch bei der patch-Methode eine zusätzliche Validierung hinzufügen.

Wird ein Theme über die register-Methode registriert, dann erfolgt das ja über eine importierte Konstante (groß geschrieben). Die Theme-Kennung dahinter ist aber immer klein geschrieben (intern).

Siehe https://github.com/public-ui/kolibri/blob/eb28a45def776b275600b4b884e70fc82ebec811/packages/themes/src/themes/bmf.ts#L5

Danke für den Hinweis und den Impuls zur Optimierung.

**Comment by Chrisdo82** [comment]
Ok, dann scheint es da gerade ein anderes Problem zu geben. Siehe die Fehlermeldung die ich erhalte, wenn ich versuche das Theme zu patchen. Bin auf der neusten rc Version.

Als ich das Theme grossgeschrieben hatte, ging es auf einmal. Jetzt aber nicht mehr, merkwürdig
