### ISSUE TITLE
🛹 Feature: reCaptcha-Component

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#961]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Featureanfrage

Ich denke so ziemlich jede Webpage stolpert über die Problematik eines notwendigen Captchas für den Schutz gegen missbräuchliche Nutzung von Formularen. Habt Ihr vielleicht bereits eine Entwicklung dazu in Planung? Es wäre schön, wenn sich hier eine zentrale Lösung finden würde.

Wikipedia: https://de.wikipedia.org/wiki/ReCAPTCHA

## Beschreiben Sie die gewünschte Lösung
...

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
...

## Zusätzlicher Kontext
...

**Comment by deleonio** [comment]
Klärungspunkte:
- Wie ist die Sicht der Barrierefreiheit zu einem reCAPTCHA.
- Wird ein Backend benötigt?

**Comment by ElVariablo** [comment]
Aus Sicht der Barrierefreiheit sollte auf die Verwendung aller Formen von CAPTCHAs verzichtet werden, da sie für Menschen mit Seh- und Lesebehinderungen aber auch für Menschen mit kognitiven Behinderungen eine zusätzliche Barriere darstellen. Aus diesem Grund sollten alternative Sicherheitskonzepte wie z.B. Honeypots oder effektive Spamfilter verwendet werden.

Gegen CAPTCHAs spricht außerdem, dass die meisten Spam Bots mittlerweile so leistungsstark sind, dass diese kein Problem haben diese zu lösen. Darauf weißt unter anderem auch die W3C in Ihrem Artikel zu CAPTCHAs hin.

Nützliche Links:

- https://www.w3.org/TR/turingtest/
- https://www.netz-barrierefrei.de/wordpress/captchas-und-barrierefreiheit-warum-es-keine-barrierefreien-bild-codes-gibt/
- https://barrierefreies.design/blog/captchas-schliessen-nicht-nur-maschinen-aus#barrierefreie-losungen
- https://www.einfach-fuer-alle.de/artikel/captcha/
- https://de.wikipedia.org/wiki/Captcha

**Comment by deleonio** [comment]
Bitte hier beantworten: https://github.com/public-ui/kolibri/discussions/1020

@ElVariablo bitte öffentliche Quellen ergänzen.
