### ISSUE TITLE
🐞 Bug: Angular Adapter schlägt fehl ab Version 1.1.12

### ISSUE THREAD

**Issue by AndreasZimnas** [public-ui/kolibri#999]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Fehlermeldung

## Beschreibung des Fehlers
Nach update zu Version 1.1.12 von kolibri und des Angular kolibri Adapters schlägt die Anwendung fehl sobald sie gestartet wird.
Log als Anhang. 
[error.log](https://github.com/public-ui/kolibri/files/10132333/error.log)
## Reproduktion

Schritte zum Reproduzieren des Verhaltens:
- npm update ausführen
- Angular Anwendung mittels npm run start starten
- Siehe Fehler

## Erwartetes Verhalten
Nach update zu Version 1.1.12 funktioniert die Anwendung wie bevor.

## Desktop (bitte vervollständigen Sie die folgenden Informationen):
- Betriebssystem: Windows 10

**Comment by deleonio** [comment]
🌟 Angular: Versionsspezifische Adapter notwendig (wir unterstützen v11, v12, v13, v14 und v15)
@public-ui/angular-v11
@public-ui/angular-v12
@public-ui/angular-v13
@public-ui/angular-v14
@public-ui/angular-v15
@public-ui/angular (@deprecated)
